libs/data-mapper/src/lib/components/inputDropdown/InputDropdown.tsx, libs/data-mapper/src/lib/components/propertiesPane/tabs/FunctionNodePropertiesTab.tsx, libs/data-mapper/src/lib/utils/Function.Utils.ts
=> [DM | InputDropdown / PropPane Function properties] Touch up input and output values

libs/data-mapper/src/lib/components/inputDropdown/InputDropdown.tsx, libs/data-mapper/src/lib/components/nodeCard/SchemaCard.tsx, libs/data-mapper/src/lib/components/propertiesPane/tabs/FunctionNodePropertiesTab.tsx, libs/data-mapper/src/lib/components/propertiesPane/tabs/SchemaNodePropertiesTab.tsx, libs/data-mapper/src/lib/components/tree/SchemaTreeItem.tsx, libs/data-mapper/src/lib/utils/Icon.Utils.tsx
=> [DM | PropPane | InputDropdown] Show data type icons

libs/designer/src/lib/core/parsers/restructuringHelpers.ts
=> Fixed run-after bug with deleting nodes that have multiple siblings

libs/designer-ui/src/lib/createConnection/createAuthorizedConnection.stories.tsx, libs/designer-ui/src/lib/createConnection/createMultiAuthConnection.stories.tsx, libs/designer-ui/src/lib/createConnection/createSimpleConnection.stories.tsx, libs/designer-ui/src/lib/createConnection/createSingleAuthConnection.stories.tsx, libs/designer-ui/src/lib/createConnection/index.tsx, libs/designer/src/lib/core/actions/bjsworkflow/connections.ts, libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts, libs/designer/src/lib/ui/panel/panelTabs/createConnectionTab.tsx, libs/services/designer-client-services/src/lib/standard/search.ts
Issue - The create connection component was incorrectly checking if it requires OAuth, so fixed that method.
=> Fixing multi auth connection creation for azure connectors

libs/data-mapper/src/lib/components/mapOverview/MapOverview.stories.tsx, libs/data-mapper/src/lib/components/nodeCard/SchemaCard.stories.tsx, libs/data-mapper/src/lib/components/nodeCard/SchemaCard.tsx, libs/data-mapper/src/lib/components/propertiesPane/tabs/SchemaNodePropertiesTab.tsx, libs/data-mapper/src/lib/components/tree/SchemaTreeItem.tsx, libs/data-mapper/src/lib/core/state/DataMapSlice.ts, libs/data-mapper/src/lib/models/Schema.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts, libs/data-mapper/src/lib/utils/Icon.Utils.tsx, libs/data-mapper/src/lib/utils/Schema.Utils.ts, libs/data-mapper/src/lib/utils/__test__/ConnectionUtils.spec.ts, libs/data-mapper/src/lib/utils/__test__/SchemaUtils.spec.ts, package-lock.json
Backend properties is coming to us in a comma separated string. We need to deserialize that manually
=> [Data Mapper] Add nodeProperties field

libs/designer/src/lib/ui/panel/panelTabs/parametersTab/index.tsx, libs/designer/src/lib/ui/panel/panelroot.tsx
- Hiding loading state for branching subgraph nodes
- Switch case parameter is now shown correctly
- Fixes #1227
=> Hide loading state for branching subgraph nodes

libs/data-mapper/src/lib/components/breadcrumb/EditorBreadcrumb.tsx, libs/data-mapper/src/lib/components/nodeCard/FunctionCard.tsx, libs/data-mapper/src/lib/components/nodeCard/HandleWrapper.tsx, libs/data-mapper/src/lib/components/nodeCard/SchemaCard.tsx, libs/data-mapper/src/lib/ui/ReactFlowStyleOverrides.css
-Also fixes a little lineHeight bug with the Breadcrumb overview text
=> [DM | Node handles] Default/Validation/Positional/Etc styles

libs/data-mapper/src/lib/__mocks__/FunctionMock.ts, libs/data-mapper/src/lib/__test__/MapDefinition.spec.ts, libs/data-mapper/src/lib/models/Function.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts
=> [Data Mapper] Conditionals passthrough

libs/data-mapper/src/lib/core/state/DataMapSlice.ts
=> [DM | Notifications] Fix one being wrongly shown

libs/data-mapper/src/lib/components/propertiesPane/tabs/FunctionNodePropertiesTab.tsx
=> [DM | PropPane] Styles update for unbounded Function inputs

libs/data-mapper/src/lib/__test__/MapDefinition.spec.ts, libs/data-mapper/src/lib/core/state/DataMapSlice.ts
* Also fix for dupes when swapping levels
=> [Data Mapper] Conditional Looping confirmed

libs/designer-ui/src/lib/authentication/MSIAuth/MSIAuth.tsx, libs/designer-ui/src/lib/authentication/util.ts, libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx, libs/designer/src/lib/core/utils/parameters/helper.ts, libs/services/designer-client-services/src/lib/workflow.ts
=> Fixing the MSI auth in authentication editor

libs/data-mapper/src/lib/__test__/MapDefinition.spec.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts, libs/data-mapper/src/lib/utils/Function.Utils.ts, libs/data-mapper/src/lib/utils/__mocks__/HeavyRepeatingMockSchema.json, libs/data-mapper/src/lib/utils/__mocks__/index.ts, libs/data-mapper/src/lib/utils/__test__/FunctionUtils.spec.ts
This just introduces the dynamic variable. Next PR will confirm that nested loops generate correctly
=> [Data Mapper] Dynamic index values

libs/designer/src/lib/ui/Minimap.tsx, package-lock.json, package.json
https://user-images.githubusercontent.com/13208452/200439890-574cd410-a26c-472c-8709-24f1326403cc.mp4
=> feat: Add support for interaction with the mini map

libs/data-mapper/src/lib/components/canvasToolbox/CanvasToolbox.tsx, libs/data-mapper/src/lib/components/functionList/FunctionList.tsx, libs/data-mapper/src/lib/components/targetSchemaPane/TargetSchemaPane.tsx, libs/data-mapper/src/lib/utils/Schema.Utils.ts
Searches the schema tree while maintaining its structure (i.e. if the search term matches a leaf node, that node's hierarchy will still be maintained to show its place in the schema)
=> [DM | Schema trees] Search

__mocks__/schemas/SimpleInputOrderSchema.json, __mocks__/schemas/SimpleOutputOrderSchema.json, libs/data-mapper/src/lib/components/floatingPanel/FloatingPanel.tsx, libs/data-mapper/src/lib/components/tree/SourceSchemaTreeItem.tsx, libs/data-mapper/src/lib/components/tree/TargetSchemaTreeItem.tsx, libs/data-mapper/src/lib/components/tree/TreeHeader.tsx
Not pixel perfect, but far more to spec, light/dark friendly, etc
=> [DM | Schema trees] Copy/style update

libs/data-mapper/src/lib/components/buttonContainer/ButtonContainer.tsx, libs/data-mapper/src/lib/components/schemaSelection/SourceSchemaPlaceholder.tsx, libs/data-mapper/src/lib/ui/DataMapperDesigner.tsx
=> [Data Mapper] Style minimap, and fix one or two other small style things

libs/designer/src/lib/core/actions/bjsworkflow/add.ts, libs/designer/src/lib/core/actions/bjsworkflow/delete.ts, libs/designer/src/lib/core/parsers/addNodeToWorkflow.ts, libs/designer/src/lib/core/parsers/deleteNodeFromWorkflow.ts, libs/designer/src/lib/core/state/workflow/workflowSlice.ts, libs/designer/src/lib/core/utils/graph.ts, libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx, libs/designer/src/lib/ui/connections/dropzone.tsx, libs/designer/src/lib/ui/panel/panelroot.tsx, libs/designer/src/lib/ui/panel/recommendation/operationGroupDetailView.tsx, libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
Fixes #1272 
Now triggers can be deleted and placeholder node shows up to add new trigger.
=> lafix: Allow trigger deletion and replacing them

libs/data-mapper/src/lib/__test__/MapDefinition.spec.ts, libs/data-mapper/src/lib/core/state/DataMapSlice.ts, libs/data-mapper/src/lib/utils/Array.Utils.ts
Also start on layered loop test, but that test is skipped for now on needing to fix the yml generation logic
=> [Data Mapper] Fix for parent connection bug 

apps/data-mapper-standalone/src/app/DataMapperStandaloneDesigner.tsx, apps/vs-code-data-mapper-react/src/app/app.tsx, libs/data-mapper/src/lib/components/mapOverview/MapOverview.tsx, libs/data-mapper/src/lib/components/schemaSelection/SelectSchemaCard.tsx, libs/data-mapper/src/lib/components/schemaSelection/card_onHover_dark.svg, libs/data-mapper/src/lib/components/schemaSelection/card_onRest_dark.svg, libs/data-mapper/src/lib/core/DataMapDataProvider.tsx, libs/data-mapper/src/lib/core/DataMapperDesignerProvider.tsx, libs/data-mapper/src/lib/core/state/AppSlice.ts, libs/data-mapper/src/lib/core/state/Store.ts
*Going to go ahead and update overview background to a token right after putting this up too
Edit: Here's the result:
=> [DM | Schema selection card] Use separate dark-theme SVGs

libs/data-mapper/src/lib/components/propertiesPane/tabs/SchemaNodePropertiesTab.tsx
=> [DM | PropPane] Use Label component for schema node field labels

apps/vs-code-data-mapper-react/src/app/app.tsx, apps/vs-code-data-mapper/src/DataMapperExt.ts, apps/vs-code-data-mapper/src/commands/commands.ts, apps/vs-code-data-mapper/src/extensionConfig.ts, libs/data-mapper/src/lib/components/configPanel/ConfigPanel.tsx, libs/data-mapper/src/lib/core/services/dataMapperApiService/DataMapperApiService.ts
=> [Data Mapper] Primarily VSIX QoL changes/fixes

libs/data-mapper/src/lib/components/targetSchemaPane/TargetSchemaPane.tsx, libs/data-mapper/src/lib/components/tree/SourceSchemaTreeItem.tsx, libs/data-mapper/src/lib/components/tree/TargetSchemaTreeItem.tsx, libs/data-mapper/src/lib/components/tree/Tree.tsx, libs/data-mapper/src/lib/components/tree/TreeBranch.tsx
=> [DM | Tree] Fix chevron color/filled styles + move indicator management to Tree

libs/data-mapper/src/lib/components/edge/ConnectionEdge.tsx
=> [DM | Edges] Fix add function button positioning

libs/data-mapper/src/lib/components/nodeCard/FunctionCard.tsx, libs/data-mapper/src/lib/components/nodeCard/SchemaCard.tsx
=> [DM | Canvas] Don't allow panning on nodes 

libs/data-mapper/src/lib/components/propertiesPane/tabs/FunctionNodePropertiesTab.tsx
=> [Data Mapper] Display index value in the prop pane

libs/data-mapper/src/lib/utils/Connection.Utils.ts
=> [Data Mapper] Stopped duplicate loop parents being added to the canvas

libs/data-mapper/src/lib/core/DataMapperDesignerProvider.tsx
=> [Data Mapper] Dark theme code view

__mocks__/schemas/LayeredLoopSourceSchema.json, libs/data-mapper/src/lib/components/functionList/FunctionList.tsx, libs/data-mapper/src/lib/core/state/DataMapSlice.ts, libs/data-mapper/src/lib/utils/__test__/DataMapUtils.spec.ts
1. Fixed issue where initial connection is left if function is inserted in repeated connection: https://msazure.visualstudio.com/DefaultCollection/One/_workitems/edit/16309159
2. Fixed logic that causes "parent connection added" message when not needed https://msazure.visualstudio.com/DefaultCollection/One/_workitems/edit/16322647
=> fixed 2 connections on instert bug

libs/data-mapper/src/lib/constants/MapDefinitionConstants.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts
Change how we read in custom values to support numbers and special values
=> [Data Mapper] Change custom values

libs/data-mapper/src/lib/components/inputDropdown/InputDropdown.tsx, libs/data-mapper/src/lib/components/propertiesPane/tabs/FunctionNodePropertiesTab.tsx
=> [Data Mapper] Fix prop pane showing quotes all the time

libs/data-mapper/src/lib/components/functionList/FunctionList.tsx, libs/data-mapper/src/lib/components/nodeCard/FunctionCard.tsx, libs/data-mapper/src/lib/core/queries/functions.ts, libs/data-mapper/src/lib/utils/ReactFlow.Util.ts
Fixes AB#16415720
Fixes AB#16378044
=> [Data Mapper] Sort functions and remove pseudo from manifest

libs/data-mapper/src/lib/components/inputDropdown/InputDropdown.tsx, libs/data-mapper/src/lib/components/propertiesPane/tabs/FunctionNodePropertiesTab.tsx
-Add type icon to output value (Expression)
-Fix functionName display
-Fix array-type icons showing incorrectly by passing along nodeProperties to InputDropdown options
=> [DM | PropPane] Icons + other fixes

libs/data-mapper/src/lib/components/canvasToolbox/CanvasToolbox.tsx, libs/data-mapper/src/lib/components/floatingPanel/FloatingPanel.tsx, libs/data-mapper/src/lib/components/mapOverview/MapOverview.tsx, libs/data-mapper/src/lib/components/targetSchemaPane/TargetSchemaPane.tsx, libs/data-mapper/src/lib/components/tree/TreeHeader.tsx, libs/data-mapper/src/lib/core/state/DataMapSlice.ts
-Includes bugfix for node statuses not updating when edges deleted
=> [DM | Tree] Fix statuses + sticky tree header (searchbar)

libs/data-mapper/src/lib/components/configPanel/ConfigPanel.tsx, libs/data-mapper/src/lib/components/testMapPanel/TestMapPanel.tsx
=> [DM] Use dark-themed Panel overlay when in dark mode

libs/data-mapper/src/lib/__test__/MapDefinition.spec.ts, libs/data-mapper/src/lib/utils/Connection.Utils.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts, libs/data-mapper/src/lib/utils/__test__/ConnectionUtils.spec.ts
Needs some more in the prop pane to render all the different functions correctly, will come in a different PR to keep this one focused
=> [Data Mapper] Conditionals and index on the same connection

libs/data-mapper/src/lib/components/inputDropdown/InputDropdown.tsx, libs/data-mapper/src/lib/utils/Function.Utils.ts
=> [Data Mapper] Shows indices in the prop pane

.github/workflows/temp-build.yml
-Should be a nice, quick, far-less-messy way to get a build of everything (primarily VSIX) when needed in-case-of-emergency or otherwise
=> [Workflow] Manually-triggered build workflow

libs/data-mapper/src/lib/__test__/MapDefinition.spec.ts, libs/data-mapper/src/lib/components/inputDropdown/InputDropdown.tsx, libs/data-mapper/src/lib/components/propertiesPane/tabs/FunctionNodePropertiesTab.tsx, libs/data-mapper/src/lib/models/Function.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts, libs/data-mapper/src/lib/utils/Function.Utils.ts
Does not include deserialization work yet. That will come in the next PR
=> [Data Mapper] Direct Index Access

apps/vs-code-data-mapper/src/DataMapperExt.ts, apps/vs-code-data-mapper/src/DataMapperPanel.ts
-Not shown in gif (I think), but trying to open a map with the same name while a panel is already open for it will show a notification to the user and then just re-show/focus that panel
=> [DM | VSIX] Allow multiple webview panels (for different data maps)

apps/vs-code-data-mapper/src/commands/commands.ts, apps/vs-code-data-mapper/src/package.json, package-lock.json
-loadDataMap command can now be used outside of context menu (Command Palette, or newly added button under 'Create new data map' button)
=> [DM | VSIX] Add FilePicker support to loadDataMap command

libs/data-mapper/src/lib/core/state/DataMapSlice.ts
=> [DM | BUGFIX] Fix source schema node deletion being affected by or affecting different canvas layers

libs/data-mapper/src/lib/components/propertiesPane/tabs/FunctionNodePropertiesTab.tsx
=> [DM | PropPane | Fn Properties] Update 'Add field' button styles

libs/data-mapper/src/lib/components/canvasControls/CanvasControls.tsx, libs/data-mapper/src/lib/components/mapOverview/MapOverview.tsx, libs/data-mapper/src/lib/constants/ReactFlowConstants.ts, libs/data-mapper/src/lib/ui/ReactFlowWrapper.tsx
-Fixes fitView'ing from Canvas Controls not accounting for the hidden source schema placeholder node
=> [DM | Canvas] Use fitViewOptions in Canvas Controls fitView call

Localize/loc/it/strings.json.lcl
LEGO: Pull request from loc/juno/hb_2c680428-7b9c-4a23-8be5-3edfbaebf5fb_20221203180442002 to main with localized lcls
=> LEGO: Pull request from loc/juno/hb_2c680428-7b9c-4a23-8be5-3edfbaebf5fb_20221203180442002 to main

libs/data-mapper/src/lib/__test__/MapDefinition.spec.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts
* Indices now get added in correct order
* Adding either the index or the source node to an $if will generate properly
* Using an index will have proper local loop values
=> [Data Mapper] Fixes for layered loops

apps/data-mapper-standalone/src/app/DataMapperStandaloneDesigner.tsx, apps/vs-code-data-mapper-react/src/app/app.tsx, apps/vs-code-data-mapper/src/commands/commands.ts, libs/data-mapper/src/lib/components/inputDropdown/InputDropdown.tsx, libs/data-mapper/src/lib/components/propertiesPane/tabs/FunctionNodePropertiesTab.tsx, libs/data-mapper/src/lib/components/testMapPanel/TestMapPanel.tsx, libs/data-mapper/src/lib/core/queries/functions.ts, libs/data-mapper/src/lib/index.ts, libs/data-mapper/src/lib/ui/DataMapperDesigner.tsx, libs/data-mapper/src/lib/utils/DataMap.Utils.ts, libs/data-mapper/src/lib/utils/Edge.Utils.ts, libs/data-mapper/src/lib/utils/Function.Utils.ts, libs/data-mapper/src/lib/utils/Icon.Utils.tsx, libs/data-mapper/src/lib/utils/Logging.Utils.ts, libs/data-mapper/src/lib/utils/ReactFlow.Util.ts, package-lock.json
Created a log utility class that will allow us to both log to the console as well to the app insights.
=> [Data Mapper] Logging helper

libs/services/designer-client-services/src/lib/standard/manifests/request.ts
=> lafix: Fix issue where relative path parameters were inserted wrong

libs/data-mapper/src/lib/components/functionList/FunctionListItem.tsx, libs/data-mapper/src/lib/components/nodeCard/FunctionCard.tsx, libs/data-mapper/src/lib/components/propertiesPane/tabs/FunctionNodePropertiesTab.tsx, libs/data-mapper/src/lib/models/Function.ts, libs/data-mapper/src/lib/utils/Icon.Utils.tsx, libs/data-mapper/src/lib/utils/ReactFlow.Util.ts, libs/data-mapper/src/lib/utils/__test__/IconUtils.spec.ts
Icons now uploaded to PROD CDN. 
Note:
- used Fluent V8 because it has a fallback option, in case the icon cannot be found
- Utility is used if the icon does not load
=> [DM] Adding icons to prod CDN

apps/vs-code-designer/src/app/commands/deleteNode.ts, apps/vs-code-designer/src/app/commands/registerCommands.ts, apps/vs-code-designer/src/constants.ts, apps/vs-code-designer/src/package.json
- Add delete node logic.
- Add delete logic app command.
- Delete logic app through the azure context tab.
- Delete logic app through the command palette.
- Checked that logic app status of deleted matches in portal.
https://user-images.githubusercontent.com/102700317/210855745-275e0b57-a31c-40f0-979f-d248ff0f0ec3.mov
=> Add Delete Command

libs/data-mapper/src/lib/mapDefinitions/MapDefinitionDeserializer.ts, libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionDeserializer.spec.ts
NOTE: May already work mostly/completely with in-loop DA's as well, but that'll be verified in its separate task
AB#16746415
=> [DM | Deserialization] Direct Access support (non-loop)

libs/data-mapper/src/lib/components/propertiesPane/tabs/FunctionNodePropertiesTab.tsx, libs/data-mapper/src/lib/core/state/DataMapSlice.ts
* Deleting a connection between 2 functions not connected to anything throws error
* Swapping between functions too fast would cause FunctionNodePropertiesTab.tsx to try and render with new connection and old function data
=> [Data Mapper] Minor bugfixes

libs/data-mapper/src/lib/mapDefinitions/MapDefinitionDeserializer.ts, libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionDeserializer.spec.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts, libs/data-mapper/src/lib/utils/__test__/DataMapUtils.spec.ts
* Also fixes a bug with loops and custom values
=> [Data Mapper] Looping conditionals

apps/vs-code-designer/src/app/commands/browseWebsite.ts, apps/vs-code-designer/src/app/commands/registerCommands.ts, apps/vs-code-designer/src/app/utils/dotnet/parseDotnetTemplates.ts, apps/vs-code-designer/src/constants.ts, apps/vs-code-designer/src/package.json
- Add command in package.json
- Add logic to open the website
- Open logic app website through azure item context menu
- Open slot instance website through azure item context menu
https://user-images.githubusercontent.com/102700317/213535261-89c95838-7022-4a54-b705-b4b6496f2268.mov
=> Add browse website command

.github/workflows/nightly-release.yml, .vscode/launch.json, apps/vs-code-designer/project.json, apps/vs-code-designer/src/package.json
- Add step to set App Insights key to designer extension package.json
- Add step to build project and pack extension
- Add step to attach designer extension vsix to release
- Add LICENSE.md to assets list when building project
- Add vscode-extension library to bump version step
- Adding `"DEBUGTELEMETRY": "v"` environment variable to `launch.json` when debugging extension in order to see it in debug console and not send that telemetry to production
=> VSFeat: Update nightly-release for vscode designer extension

libs/data-mapper/src/lib/components/functionList/FunctionListHeader.tsx, libs/data-mapper/src/lib/constants/FunctionConstants.tsx
=> [DM | Function List] Use category branding (displayName) instead of enum value

apps/vs-code-designer/src/app/commands/registerCommands.ts, apps/vs-code-designer/src/app/commands/workflows/reviewValidation.ts, apps/vs-code-designer/src/constants.ts, apps/vs-code-designer/src/package.json
Added Review Validation command
=> VSFeat: Review validation

apps/vs-code-designer/src/app/commands/registerCommands.ts, apps/vs-code-designer/src/app/commands/workflows/switchDebugMode/StatelessWorkflowsListStep.ts, apps/vs-code-designer/src/app/commands/workflows/switchDebugMode/UpdateDebugModeStep.ts, apps/vs-code-designer/src/app/commands/workflows/switchDebugMode/switchDebugMode.ts, apps/vs-code-designer/src/constants.ts, apps/vs-code-designer/src/package.json, libs/vscode-extension/src/lib/models/context.ts
- Add switch debug mode command for stateless workflow
- Add list stateless workflows step
- Add update debug mode in local.setting.json step
https://user-images.githubusercontent.com/102700317/214361977-7d431c5d-feb0-4715-bc77-de6f28ab9184.mov
=> VSFeat: Add switch debug mode command

apps/vs-code-designer/src/app/commands/registerCommands.ts, apps/vs-code-designer/src/app/commands/workflows/configureWebhookRedirectEndpoint/ConfigureRedirectEndpointStep.ts, apps/vs-code-designer/src/app/commands/workflows/configureWebhookRedirectEndpoint/SaveWebhookContextStep.ts, apps/vs-code-designer/src/app/commands/workflows/configureWebhookRedirectEndpoint/configureWebhookRedirectEndpoint.ts, apps/vs-code-designer/src/app/commands/workflows/configureWebhookRedirectEndpoint/webhookWizard.ts, apps/vs-code-designer/src/app/commands/workflows/exportLogicApp.ts, apps/vs-code-designer/src/constants.ts, apps/vs-code-designer/src/package.json
- Add logic to configure webhook endpoint
- Add configure redirect endpoint step
- Add save webhook context step
- Update HTTP methods in export to constants
https://user-images.githubusercontent.com/102700317/214402928-902bea6a-05d8-41a0-a162-c4f97d328630.mov
=> VSFeat: Add configure web hook for connections command

apps/vs-code-designer/src/app/commands/registerCommands.ts, apps/vs-code-designer/src/app/commands/workflows/enableAzureConnectors.ts, apps/vs-code-designer/src/constants.ts, apps/vs-code-designer/src/package.json
- Add logic to enable to azure connector through explorer context menu
https://user-images.githubusercontent.com/102700317/214420562-427b3f11-d9bf-461c-a233-21e0047f2e00.mov
=> VSFeat: Enable azure connector command

apps/vs-code-designer/src/app/commands/deployments/connectToGitHub.ts, apps/vs-code-designer/src/app/commands/deployments/disconnectRepo.ts, apps/vs-code-designer/src/app/commands/deployments/viewCommitInGitHub.ts, apps/vs-code-designer/src/app/commands/registerCommands.ts, apps/vs-code-designer/src/app/tree/slotsTree/SlotTreeItem.ts, apps/vs-code-designer/src/constants.ts, apps/vs-code-designer/src/package.json
- Add command to connect to Github Repo
- Add command to view commits in Github
- Add command to disconnect from repo
- Connect to Github repo through command palette
- Connect to Github repo through inline command in azure tab
- View commit in Github repo through azure context menu
- Disconnect from repo through azure context menu
https://user-images.githubusercontent.com/102700317/214609568-09eebd18-7fd2-4b2a-9988-e4137e1ad9b2.mov
=> VSFeat: Add connect to Github, view commit in Github and disconnect from repo commands

apps/vs-code-designer/src/app/commands/registerCommands.ts, apps/vs-code-designer/src/app/commands/remoteDebug/getRemoteDebugLanguage.ts, apps/vs-code-designer/src/app/commands/remoteDebug/startRemoteDebug.ts, apps/vs-code-designer/src/constants.ts, apps/vs-code-designer/src/package.json
- Add start remote debug command for linux remote logic apps
=> VSFeat: Add start remote debug command

libs/data-mapper/src/lib/components/breadcrumb/EditorBreadcrumb.tsx
=> [Data Mapper] Add custom breadcrumb divider

__mocks__/mapDefinitions/FullTranscriptMapDefinition.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts
Deserialized nested-direct-access from Transcript map definition now reserializes w/ proper formatting (seen below)
=> [DM | Serialization] Check for and format nested direct access functions

libs/data-mapper/src/lib/components/functionList/FunctionListItem.tsx, libs/data-mapper/src/lib/components/nodeCard/functionCard/ExpandedFunctionCard.tsx, libs/data-mapper/src/lib/components/nodeCard/functionCard/SimpleFunctionCard.tsx, libs/data-mapper/src/lib/components/propertiesPane/tabs/FunctionNodePropertiesTab.tsx, libs/data-mapper/src/lib/utils/Icon.Utils.tsx
=> [Data mapper] FnF Expanded cards first pass

__mocks__/schemas/ComprehensiveSourceSchema.json, __mocks__/schemas/ComprehensiveTargetSchema.json, __mocks__/schemas/LayeredLoopSourceSchema.json, __mocks__/schemas/LayeredLoopTargetSchema.json, __mocks__/schemas/SimpleInputOrderSchema.json, __mocks__/schemas/SimpleLoopSource.json, __mocks__/schemas/SimpleLoopTarget.json, __mocks__/schemas/SimpleOutputOrderSchema.json, __mocks__/schemas/SourceSchema.json, __mocks__/schemas/TargetSchema.json, libs/data-mapper/src/lib/mapDefinitions/MapDefinitionSerializer.ts
Fixes #16943896
-Also updates mocks (corrects Bool normalizedDataTypes, and removes remaining schemaNodeDataType properties)
=> [DM | Serialization] Handle function relative path values within nested loops

libs/data-mapper/src/lib/components/nodeCard/NodeCard.tsx, libs/data-mapper/src/lib/components/nodeCard/SchemaCard.tsx, libs/data-mapper/src/lib/components/nodeCard/functionCard/ExpandedFunctionCard.tsx, libs/data-mapper/src/lib/components/nodeCard/functionCard/FunctionCard.ts, libs/data-mapper/src/lib/components/nodeCard/functionCard/SimpleFunctionCard.tsx
=> [Data Mapper] Updated error states for function cards

__mocks__/mapDefinitions/ComprehensiveMapDefinition.ts, __mocks__/schemas/ComprehensiveTargetSchema.json, libs/data-mapper/src/lib/components/propertiesPane/PropertiesPane.tsx, libs/data-mapper/src/lib/core/state/DataMapSlice.ts, libs/data-mapper/src/lib/mapDefinitions/MapDefinitionDeserializer.ts, libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionDeserializer.spec.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts, libs/data-mapper/src/lib/utils/__test__/DataMapUtils.spec.ts
=> [DM | Deserialization] Many-to-Many loop support

libs/data-mapper/src/lib/components/functionIcon/FunctionIcon.tsx, libs/data-mapper/src/lib/components/functionList/FunctionListItem.tsx, libs/data-mapper/src/lib/components/nodeCard/functionCard/ExpandedFunctionCard.tsx, libs/data-mapper/src/lib/components/nodeCard/functionCard/SimpleFunctionCard.tsx, libs/data-mapper/src/lib/components/propertiesPane/tabs/FunctionNodePropertiesTab.tsx, libs/data-mapper/src/lib/models/Function.ts, libs/data-mapper/src/lib/utils/Icon.Utils.tsx, libs/data-mapper/src/lib/utils/Logging.Utils.ts, libs/data-mapper/src/lib/utils/__test__/IconUtils.spec.ts
Adding in a FunctionIcon component so that we can de-couple the icon from the internet if need by (aka the customer can run the data mapper completely offline using the fallback icons)
=> [Data Mapper] Add FunctionIcon component

__mocks__/mapDefinitions/ComprehensiveMapDefinition.ts, __mocks__/mapDefinitions/FullTranscriptMapDefinition.ts, __mocks__/schemas/ComprehensiveSourceSchema.json, __mocks__/schemas/ComprehensiveTargetSchema.json
-Figure out conditionals within loops are a little wonky (logging and taking a look separately!)
-Add all looping w/ index scenarios
-TODO remaining loop stuff for visibility
-Fix CustomValues keys
-Some fixes/updates to the Transcript map definition (confirmed necessary by recreating scenarios and observing/verifying serialization)
=> [DM | Mocks] More comprehensive updates

libs/data-mapper/src/lib/mapDefinitions/MapDefinitionSerializer.ts
=> [DM | Serialization] Handle relative paths within conditionals within nested loops

libs/data-mapper/src/lib/components/mapChecker/MapCheckerItem.tsx
=> [Data Mapper] Highlight selected nodes in the Map Checker

libs/data-mapper/src/lib/components/mapChecker/MapCheckerPane.tsx, libs/data-mapper/src/lib/components/nodeCard/SchemaCard.tsx, libs/data-mapper/src/lib/components/nodeCard/functionCard/FunctionCard.ts, libs/data-mapper/src/lib/utils/MapChecker.Utils.ts
* Move required to warnings
* Click on function error, navigates to error
=> [Data Mapper] Check for mismatched input types

libs/data-mapper/src/lib/components/canvasToolbox/CanvasToolbox.tsx, libs/data-mapper/src/lib/components/targetSchemaPane/TargetSchemaPane.tsx, libs/data-mapper/src/lib/utils/Schema.Utils.ts
=> [DM | Schema trees] Implement fuse.js fuzzy search into schema tree searching

apps/data-mapper-standalone/src/components/DevApiTester.tsx, apps/data-mapper-standalone/src/components/DevSerializationTester.tsx
=> [DM | Standalone] Quick style update to DevToolbox items

Localize/loc/es/strings.json.lcl
LEGO: Pull request from loc/juno/hb_2c680428-7b9c-4a23-8be5-3edfbaebf5fb_20230214180727541 to main with localized lcls
=> LEGO: Pull request from loc/juno/hb_2c680428-7b9c-4a23-8be5-3edfbaebf5fb_20230214180727541 to main

libs/data-mapper/src/lib/__mocks__/FunctionMock.ts, libs/data-mapper/src/lib/components/functionList/FunctionList.tsx, libs/data-mapper/src/lib/models/Function.ts, libs/data-mapper/src/lib/utils/__mocks__/indexedConnections.ts, libs/data-mapper/src/lib/utils/__test__/ConnectionUtils.spec.ts, libs/data-mapper/src/lib/utils/__test__/DataMapUtils.spec.ts, libs/data-mapper/src/lib/utils/__test__/TypeCheckUtils.spec.ts
=> [DM | Function list] Search by category name + enumerate FunctionData.type

libs/data-mapper/src/lib/components/nodeCard/SchemaCard.tsx
=> [Data Mapper]Minor tweaks to schema cards

libs/data-mapper/src/lib/core/state/DataMapSlice.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts
=> [DM] Refactor performance-heavy JSON.stringify's

libs/parsers/src/lib/swagger/__test__/swagger.spec.ts, libs/parsers/src/lib/swagger/parameterprocessor.ts, package-lock.json, package.json
Changes to support callback Url in Header 
Related PR :- 
https://msazure.visualstudio.com/One/_git/AzureUX-BPMUX/pullrequest/7337645
https://msazure.visualstudio.com/One/_git/AzureUX-BPMUX/pullrequest/7631719
AB#17263113
=> Callback Url Support in Header

libs/data-mapper/src/lib/components/functionList/FunctionListItem.tsx, libs/data-mapper/src/lib/components/nodeCard/functionCard/ExpandedFunctionCard.tsx, libs/data-mapper/src/lib/components/nodeCard/functionCard/SimpleFunctionCard.tsx, libs/data-mapper/src/lib/components/propertiesPane/tabs/FunctionNodePropertiesTab.tsx
=> [Data Mapper] Invert function icons color

libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionE2e.spec.ts, libs/data-mapper/src/lib/models/Schema.ts, libs/data-mapper/src/lib/utils/Icon.Utils.tsx
Also add in commented comprehensive test
=> [Data Mapper][JSON] Fix icon for new JSON types

libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionDeserializer.spec.ts
Skip the first commit. It still adds in a new layer to the tests and copies all the existing one to the JSON section. No functional changes
=> [Data Mapper][JSON] Simple deserialization cases

libs/data-mapper/src/lib/mapDefinitions/MapDefinitionDeserializer.ts, libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionDeserializer.spec.ts, libs/data-mapper/src/lib/utils/Schema.Utils.ts
Ignoring multiple arrayitems in one array for now
=> [Data Mapper][JSON] Basic loop deserialization

apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForAzureResource.ts, apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts, apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForAzureResource.ts, apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForLocal.ts, libs/vscode-extension/src/lib/models/workflow.ts
- Remove script path from panel metadata
- Add information message for loading designer when opening remote monitoring view
=> [VSFeat] Update panel metadata for designer

libs/designer/src/lib/ui/settings/sections/runafterconfiguration/runafteractiondetails.tsx
fixes #1738
https://user-images.githubusercontent.com/13208452/226148007-0165b42d-a015-4d10-b551-de5a461efe99.mp4
=> Add support for keyboard control on runafter control

apps/vs-code-designer/src/CHANGELOG.md, apps/vs-code-designer/src/app/commands/deploy/verifyAppSettings.ts, apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts, libs/vscode-extension/src/lib/models/language.ts
- Changes from following PR's
-Update dotnet-isolated to designtime functions worker runtime([#394](https://github.com/microsoft/vscode-azurefunctions-clone/pull/394))
-Update changelog ([#393](https://github.com/microsoft/vscode-azurefunctions-clone/pull/393))
=> [VSFeat] Update new extension with latest old repo changese

libs/designer/src/lib/core/state/operation/operationSelector.ts, libs/designer/src/lib/core/state/workflow/workflowInterfaces.ts, libs/designer/src/lib/core/state/workflow/workflowSelectors.ts, libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx, libs/designer/src/lib/ui/connections/dropzone.tsx, package-lock.json
Operations must be in a path under their dependencies and they must be within the same scope to be drag & dropped
https://user-images.githubusercontent.com/13208452/227002413-84c3fe1c-11d4-47d6-a8ad-03c90ab873ba.mp4
=> Add better detection for operation drag drop allowability

apps/designer-standalone/src/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx, libs/designer-ui/src/lib/workflowparameters/workflowparameters.less
Note: Will also be making a change in portal code to reflect this as well
Before:
https://user-images.githubusercontent.com/13208452/227998453-31171724-09f8-4eef-ac47-aa0731d287f7.mp4
After:
https://user-images.githubusercontent.com/13208452/227997432-9e0a483d-6425-4e4a-a3ef-c20d66aaea7f.mp4
=> add better visual for workflow parameter errors and block save

libs/data-mapper/src/lib/constants/MapDefinitionConstants.ts, libs/data-mapper/src/lib/mapDefinitions/MapDefinitionDeserializer.ts, libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionDeserializer.spec.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts, libs/data-mapper/src/lib/utils/Function.Utils.ts
=> [Data Mapper][JSON] Handle index used a source value

apps/vs-code-designer-react/src/app/DesignerCommandBar/index.tsx, apps/vs-code-designer-react/src/app/app.tsx, apps/vs-code-designer/src/app/commands/workflows/exportLogicApp.ts, apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForAzureResource.ts, apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts, apps/vs-code-designer/src/assets/dark/workflow.svg, apps/vs-code-designer/src/assets/light/workflow.svg
- Disable save when workflow or parameters have error
- Add spinner when workflow is being saved
- Add workflows icon to designer panel tab
https://user-images.githubusercontent.com/102700317/228326428-026a29e6-e9b5-4d3f-bedf-1cf439f8fe4e.mov
Closes #1819
=> [VSFeat] Add better visual for workflow parameter errors

libs/services/designer-client-services/src/lib/standard/run.ts
- If raw data from api call is string, converts the string in a dictionary schema
Closes #1848
=> Add validation for string raw data in monitoring view

apps/vs-code-designer-react/src/app/servicesHelper.ts
- Add BaseFunctionService
Fixes #1849 
https://user-images.githubusercontent.com/102700317/228644890-3439d311-3d2b-463a-9a33-b8ba32c0838e.mov
=> [VSBug] Add BaseFunctionService to services helper

apps/vs-code-designer/src/app/tree/subscriptionTree/SubscriptionTreeItem.ts
- Add logic to generate a valid name to storage account when deploying to a new logic app
Closes #1846 
Based  on https://github.com/microsoft/vscode-azuretools/pull/1225/files
Logic app name is test-StorageName-deploy
Storage account name changes to teststoragenamedeploy
https://user-images.githubusercontent.com/102700317/228687960-fcd52d1e-9012-4111-a347-457ff6e42481.mp4
=> Add validation to storage account name

__mocks__/workflows/Panel.json, libs/designer/src/lib/common/constants.ts, libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts, libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts, libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts, libs/designer/src/lib/core/utils/parameters/helper.ts, libs/designer/src/lib/core/utils/swagger/operation.ts
operation.runConfiguration.staticResult was saving as operation.runConfiguration.staticResults, causing an error when saving
=> LaFix: Static Result Fix

libs/designer/src/lib/ui/Designer.tsx, libs/designer/src/lib/ui/panel/panelroot.tsx
Allow Designer panel customization by allowing panelLocation parameter
=> Allow passing panel location to the Designer

libs/designer/src/lib/core/state/connection/connectionSelector.ts, libs/designer/src/lib/core/state/selectors/actionMetadataSelector.ts, libs/designer/src/lib/ui/Designer.tsx, libs/parsers/src/lib/common/__test__/schemaprocessor.spec.ts
fixes: #1861
Before:
https://user-images.githubusercontent.com/13208452/229270112-7d481ffe-112e-4a7d-a883-dfb085f63c35.mp4
After:
https://user-images.githubusercontent.com/13208452/229270118-d0d0be74-cfc1-4002-9de1-368251d4470b.mp4
=> lafix: Remove erroring requests happening from manifest based operations

apps/vs-code-designer/src/package.json
- Update regex in package.json
Closes #1899 
https://user-images.githubusercontent.com/102700317/229590212-585bd286-7355-4075-88db-99be2fcb2a8b.mov
=> Update regex for review validation command

apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesigner.tsx, libs/designer/src/lib/ui/settings/settingsection.tsx
Fixes #1912 
https://user-images.githubusercontent.com/13208452/229906547-e8471a4c-6185-4164-9eba-1532cf633503.mp4
=> lafix: Disable remove button and add parameters in readOnly mode

libs/data-mapper/src/lib/components/sidePane/SidePane.tsx
=> [Data Mapper] Fix close code view button half unselectable

apps/data-mapper-standalone/src/components/DevSerializationTester.tsx, libs/data-mapper/src/lib/components/propertiesPane/tabs/CodeTab.tsx, libs/data-mapper/src/lib/core/state/DataMapSlice.ts, libs/data-mapper/src/lib/mapDefinitions/MapDefinitionSerializer.ts, libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionE2e.spec.ts, libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionSerializer.spec.ts, libs/data-mapper/src/lib/ui/DataMapperDesigner.tsx
=> [Data Mapper] Sort the connections based on the target schema

__mocks__/workflows/Conditionals.json, libs/designer-ui/src/lib/editor/base/index.tsx, libs/designer-ui/src/lib/editor/base/utils/parsesegments.ts, libs/designer-ui/src/lib/editor/base/utils/tokenTypeaheadMatcher.tsx, libs/designer-ui/src/lib/tokenpicker/index.tsx, libs/designer-ui/src/lib/tokenpicker/plugins/TokenPickerHandler.tsx, libs/designer/src/lib/core/utils/parameters/helper.ts, libs/designer/src/lib/core/utils/validation.ts
Fixes 
- #1917 
- #1918 
Fixed a bug where we would could have multiple token picker skittles visible at once
Fixed a bug where clicking on an expression token on initialization(instead of on add) would not render the expression in the token picker
=> LAFix: Conditional Bugs/ Other Bugs

libs/designer/src/lib/core/utils/graph.ts
=> lafix: Add validation for node metadata

libs/designer-ui/src/lib/arrayeditor/arrayeditor.less, libs/designer-ui/src/lib/authentication/authentication.less, libs/designer-ui/src/lib/dictionary/dictionaryeditor.less, libs/designer-ui/src/lib/editor/base/editor.less, libs/designer-ui/src/lib/html/htmleditor.less, libs/designer-ui/src/lib/querybuilder/querybuilder.less, libs/designer-ui/src/lib/settings/settings.less
https://user-images.githubusercontent.com/13208452/230646927-df20f5ab-6aa5-44df-81a9-7eddc9b7cc4e.mp4
=> lafix: Make the caret in editors have consistent color with a11y contrast

libs/data-mapper/src/lib/components/codeView/CodeView.tsx, libs/data-mapper/src/lib/ui/DataMapperDesigner.tsx
=> [Data Mapper] Resize code panel

apps/vs-code-designer-react/src/state/DesignerSlice.ts, apps/vs-code-designer-react/src/webviewCommunication.tsx, apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts, libs/vscode-extension/src/lib/models/extensioncommand.ts
- Add onDidChangeViewState to handle updates of connections, parameters and setting when user gets back to designer.
Closes #1963 
https://user-images.githubusercontent.com/102700317/230996873-bf26e827-f477-4863-97a4-093d5a9ad701.mov
=> VSBug: Adding on change view to update configurations

apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForAzureResource.ts, apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts, apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForAzureResource.ts, apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForLocal.ts
- Assign schema and map artifacts to panel metadata to send it to designer
- Reason of issue was that we weren't assigning them at the right time
- Closes #1993 
https://user-images.githubusercontent.com/102700317/231619686-5d982716-b2e9-45b1-a634-b79afd9d2a58.mov
=> fix(vscode): Assign maps and schema artifacts to panel metadata

apps/data-mapper-e2e/src/general/GeneralTranscript.e2e.spec.ts, libs/data-mapper/src/lib/components/edge/ConnectionEdge.tsx, libs/data-mapper/src/lib/components/nodeCard/SchemaCard.tsx, libs/data-mapper/src/lib/components/nodeCard/functionCard/ExpandedFunctionCard.tsx, libs/data-mapper/src/lib/components/nodeCard/functionCard/SimpleFunctionCard.tsx, libs/data-mapper/src/lib/core/state/DataMapSlice.ts, libs/data-mapper/src/lib/utils/ReactFlow.Util.ts
* Also disabled flaky e2e test while it is investigated
=> fix(Data Mapper): Fix connected highlighting to not over highlight

libs/designer-ui/src/lib/editor/base/plugins/TokenTypeahead.tsx, libs/designer-ui/src/lib/editor/base/tokenpickerbutton.less, libs/designer/src/lib/ui/panel/panelTabs/parametersTab/index.tsx
- Fixed token display issue in dictionary editors
- Fixes #1764 
- Cleaned up some of the token picker hotkey styling
---
=> fix(designer): Fixed token display issue in dictionary editors

libs/designer-ui/src/lib/combobox/index.tsx, libs/designer/src/lib/core/actions/bjsworkflow/delete.ts, libs/designer/src/lib/core/state/staticresultschema/staticresultsSlice.ts, libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts, libs/designer/src/lib/core/utils/parameters/helper.ts, libs/designer/src/lib/ui/panel/panelTabs/testingTab/index.tsx
=> fix(designer): Delete StaticResults when node is deleted/ Support Combobox for enums

libs/designer/src/lib/core/utils/loops.ts, libs/designer/src/lib/core/utils/outputs.ts, libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts, libs/designer/src/lib/core/utils/parameters/helper.ts, libs/designer/src/lib/core/utils/tokens.ts
=> fix(designer): Output token expressions generated incorrectly for swagger based operations

libs/data-mapper/src/lib/components/propertiesPane/tabs/CodeTab.tsx, libs/data-mapper/src/lib/mapDefinitions/MapDefinitionSerializer.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts
=> fix(Data Mapper): Fix source schema attributes and functions

apps/vs-code-react/src/app/export/export.tsx, apps/vs-code-react/src/app/export/instanceSelection/instanceSelection.tsx, apps/vs-code-react/src/app/export/summary/helper.ts, apps/vs-code-react/src/app/export/summary/summary.tsx, apps/vs-code-react/src/app/export/validation/validation.tsx, apps/vs-code-react/src/app/overview/app.tsx, apps/vs-code-react/src/run-service/export/index.ts
- Set refetchOnMount to true for export and overview QueryClient
- Fix empty subscription api call when selecting region/ISE in first page
- Add MessageBar to review validation
Closes #2078 
- Export error message with tracking id. User shouldn't be able to go next
- Fix of stale dialogs when going back
https://user-images.githubusercontent.com/102700317/234130427-a00f4b0a-ea10-49cd-8715-0759f5cc5f2c.mov
=> fix(vscode): Export url fail error

libs/services/designer-client-services/src/lib/standard/connection.ts
=> feat(designer): Add parameterSet name for multi auth connections in service providers

Localize/lang/strings.cs.json, Localize/lang/strings.de.json, Localize/lang/strings.es.json, Localize/lang/strings.fr.json, Localize/lang/strings.hu.json, Localize/lang/strings.id.json, Localize/lang/strings.it.json, Localize/lang/strings.ja.json, Localize/lang/strings.ko.json, Localize/lang/strings.nl.json, Localize/lang/strings.pl.json, Localize/lang/strings.pt-BR.json, Localize/lang/strings.pt-PT.json, Localize/lang/strings.ru.json, Localize/lang/strings.sv.json, Localize/lang/strings.tr.json, Localize/lang/strings.zh-Hans.json, Localize/lang/strings.zh-Hant.json
This is the pull request automatically created by the OneLocBuild task in the build process to check-in localized files generated based upon translation source files (.lcl files) handed-back from the downstream localization pipeline. If there are issues in translations, visit https://aka.ms/icxLocBug and log bugs for fixes. The OneLocBuild wiki is https://aka.ms/onelocbuild and the localization process in general is documented at https://aka.ms/AllAboutLoc.
=> Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 525

libs/designer-ui/src/lib/editor/base/utils/tokenTypeaheadMatcher.tsx
=> fix(designer): Token Picker / Hide

libs/services/designer-client-services/src/lib/base/manifests/terminate.ts
=> fix(designer): Code & Message should be shown conditionally for Terminate action

libs/designer/src/lib/ui/panel/panelTabs/parametersTab/index.tsx
Accidentally checked in something from a previous PR, so reverting it.
Fixes #2215
=> fix(designer): reverting a change to variable change

libs/designer/src/lib/core/index.ts, libs/designer/src/lib/core/state/global.ts, libs/designer/src/lib/core/state/workflowparameters/workflowparametersSlice.ts, libs/designer/src/lib/core/state/workflowparameters/workflowparametersselector.ts, libs/designer/src/lib/ui/panel/panelroot.tsx
- Added workflow parameters dirty state
- Combined workflow and workflow parameters dirty state to a single selector and reset action
=> feat(designer): Workflow Parameters - Dirty State

apps/designer-standalone/src/app/AzureLogicAppsDesigner/Services/HttpClient.ts, libs/designer/src/lib/common/constants.ts, libs/vscode-extension/src/lib/services/httpClient.ts
=> fix(vscode): Adding extra headers for user agent in all http calls

libs/designer/src/lib/core/parsers/ParseReduxAction.ts, libs/designer/src/lib/core/parsers/__test__/respectExistingWorkflowDimensions.spec.ts
Adding unit tests for respecting workflow dimensions
=> fix(designer): adding unit tests for respecting workflow dimensions logic

libs/services/designer-client-services/src/lib/base/manifests/request.ts
=> fix(designer): Fixing request trigger settings for supress workflow headers

apps/data-mapper-standalone/src/components/DevToolbox.tsx, libs/data-mapper/src/lib/core/services/dataMapperApiService/DataMapperApiService.ts
=> fix(Data Mapper): Fix schemas with . in the file name

Localize/lang/strings.cs.json, Localize/lang/strings.de.json, Localize/lang/strings.es.json, Localize/lang/strings.fr.json, Localize/lang/strings.hu.json, Localize/lang/strings.id.json, Localize/lang/strings.it.json, Localize/lang/strings.ja.json, Localize/lang/strings.ko.json, Localize/lang/strings.nl.json, Localize/lang/strings.pl.json, Localize/lang/strings.pt-BR.json, Localize/lang/strings.pt-PT.json, Localize/lang/strings.ru.json, Localize/lang/strings.sv.json, Localize/lang/strings.tr.json, Localize/lang/strings.zh-Hans.json, Localize/lang/strings.zh-Hant.json
This is the pull request automatically created by the OneLocBuild task in the build process to check-in localized files generated based upon translation source files (.lcl files) handed-back from the downstream localization pipeline. If there are issues in translations, visit https://aka.ms/icxLocBug and log bugs for fixes. The OneLocBuild wiki is https://aka.ms/onelocbuild and the localization process in general is documented at https://aka.ms/AllAboutLoc.
=> Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 533

libs/data-mapper/src/lib/components/testMapPanel/TestMapPanel.tsx
=> fix(Data Mapper): Allow events to pass through on the panel

libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts, libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
=> fix(designer): Fixing the title prefix for dynamic inputs in manifest based operations

libs/designer-ui/src/lib/index.ts, libs/designer-ui/src/lib/querybuilder/HybridQueryBuilder.tsx, libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx, libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts, libs/designer/src/lib/core/utils/parameters/helper.ts
Adding HybridQueryBuilder editor and functionality to enable it only when isHybridEditor is set to true.
=> fix(designer): Add HybridQueryBuilder and isHybridEditor flag

libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts, libs/designer/src/lib/core/utils/parameters/helper.ts
https://github.com/Azure/LogicAppsUX/pull/2409
=> fix(designer): Special case array actions being converted to Object on initializing, then breaking Runtime on Save

libs/parsers/src/lib/common/schemaprocessor.ts
https://github.com/Azure/LogicAppsUX/pull/2438
=> fix(designer): Fixing the output names when they have encoded properties

libs/data-mapper/src/lib/mapDefinitions/MapDefinitionSerializer.ts
=> fix(Data Mapper): Stop refs for identical items

libs/designer/src/lib/core/utils/parameters/helper.ts, libs/designer/src/lib/ui/panel/panelTabs/parametersTab/index.tsx
https://github.com/Azure/LogicAppsUX/pull/2454
=> fix(designer): Workflow crashing when getting outputs of schema with multiple types

libs/designer/src/lib/core/actions/bjsworkflow/add.ts, libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts, libs/designer/src/lib/core/actions/bjsworkflow/settings.ts, libs/designer/src/lib/core/utils/loops.ts, libs/designer/src/lib/core/utils/outputs.ts, libs/designer/src/lib/core/utils/parameters/helper.ts, libs/designer/src/lib/ui/settings/sections/general.tsx
=> fix(designer): SplitOn setting not showing up settings even on enabled

libs/designer/src/lib/core/utils/tokens.ts, libs/designer/src/lib/ui/panel/panelTabs/parametersTab/index.tsx
=> fix(designer): Updating latest token action name for code editors

libs/designer-ui/src/lib/card/subgraphCard/index.tsx
Before:
https://github.com/Azure/LogicAppsUX/assets/13208452/ad693321-3fc6-4aa8-9091-87646ffcf7f6
After:
https://github.com/Azure/LogicAppsUX/assets/13208452/dae52a27-49d4-4738-91bf-1da4cc96507d
=> fix(designer): Fix issue where expanding or collapsing conditions would open panel

libs/designer-ui/src/lib/arrayeditor/util/util.ts
=> fix(designer): Instead of converting casted segments to literal, use segments intead

libs/data-mapper/src/lib/mapDefinitions/MapDefinitionSerializer.ts, libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionSerializer.spec.ts
=> feat(Data Mapper): Brute force order some of the map definition

libs/designer-ui/src/lib/createConnection/universalConnectionParameter.tsx
ssh key requires multiline editor
fixes #2511
=> fix(designer): support multiline for connection creation

libs/designer-ui/src/lib/createConnection/universalConnectionParameter.tsx
https://github.com/Azure/LogicAppsUX/pull/2513
=> fix(designer): multiline support for ssh

apps/vs-code-designer-react/src/app/servicesHelper.ts
- Removing stringifying the workflow details object
Closes #2426
=> fix(vscode): Invoke workflow showing the input parameter fields

libs/services/designer-client-services/src/lib/standard/run.ts
- Add catch clause when getting the inputs/outputs
- Implementation in portal side of the updateCors function
=> fix(designer): Catch exception for when cors is not established for monitoring view

libs/services/designer-client-services/src/lib/base/appService.ts, libs/services/designer-client-services/src/lib/base/function.ts, libs/services/designer-client-services/src/lib/helpers.ts
=> fix(designer): Fix filtering of function apps which have more than one type of kind

libs/designer/src/lib/core/utils/parameters/helper.ts
=> fix(designer): make it so we split on outer most comma in simple query builder

libs/services/designer-client-services/src/lib/standard/run.ts
Making this change as this is a regression I didn't notice.
=> fix(designer): Add parse inputs and outputs in monitoring view

libs/designer-ui/src/lib/staticResult/staticResultProperty.tsx
=> fix(designer): added support for objects in static results

libs/designer-ui/src/lib/querybuilder/SimpleQueryBuilder.tsx
=> fix(designer): SimpleQueryBuilder editor not updating on deserialization

apps/vs-code-data-mapper/src/DataMapperExt.ts, apps/vs-code-data-mapper/src/DataMapperPanel.ts, apps/vs-code-data-mapper/src/commands/commands.ts
=> fix(Data Mapper): Fall back to base file if the draft is invalid

Localize/lang/strings.cs.json, Localize/lang/strings.de.json, Localize/lang/strings.es.json, Localize/lang/strings.fr.json, Localize/lang/strings.hu.json, Localize/lang/strings.id.json, Localize/lang/strings.it.json, Localize/lang/strings.ja.json, Localize/lang/strings.ko.json, Localize/lang/strings.nl.json, Localize/lang/strings.pl.json, Localize/lang/strings.pt-BR.json, Localize/lang/strings.pt-PT.json, Localize/lang/strings.ru.json, Localize/lang/strings.sv.json, Localize/lang/strings.tr.json, Localize/lang/strings.zh-Hans.json, Localize/lang/strings.zh-Hant.json
This is the pull request automatically created by the OneLocBuild task in the build process to check-in localized files generated based upon translation source files (.lcl files) handed-back from the downstream localization pipeline. If there are issues in translations, visit https://aka.ms/icxLocBug and log bugs for fixes. The OneLocBuild wiki is https://aka.ms/onelocbuild and the localization process in general is documented at https://aka.ms/AllAboutLoc.
=> Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 545

libs/designer-ui/src/lib/picker/filepickereditor.tsx, libs/designer/src/lib/ui/panel/panelTabs/parametersTab/index.tsx
https://github.com/Azure/LogicAppsUX/pull/2603
=> fix(designer): Issue where Filepicker was not showing subfolders 

libs/designer-ui/src/lib/settings/settingsection/settingreactiveinput.tsx, libs/designer/src/lib/ui/settings/index.tsx, libs/designer/src/lib/ui/settings/sections/networking.tsx
=> fix(designer): Persist pagination toggle setting info in store

libs/designer/src/lib/ui/panel/panelroot.tsx
Cherry pick of fix(vscode): Copy/Paste commands in vscode for Mac [(#2653)](https://github.com/Azure/LogicAppsUX/pull/2653)
=> fix(vscode): Copy/Paste commands in vscode for Mac (#2653)

libs/designer/src/lib/core/utils/parameters/dynamicdata.ts, libs/designer/src/lib/core/utils/parameters/helper.ts
Bug fix
Fixes #2332 
Internal parameters in dynamic parameters will show up in serialization and fixed case insensitive check for parameters visibility
No
=> fix(designer): Fixing the visibility of internal and important parameters

.github/workflows/codeql-analysis.yml, .github/workflows/package-lock-version-test.yml, .github/workflows/test.yml
Update continuous integration configuration by adding dev/* branches to actions trigger
- Github actions only trigger in PR's to main branch
- Trigger github actions in dev/* branches
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?) 
No
=> chore(ci): Trigger github actions in dev/* and hotfix/* branches

apps/logic-apps-ux-docs/docs/tsg.mdx
Added TSG instruction on how to get the browser version for Edge, Chrome, Firefox, and Safari
=> chore: TSG - Added browser version section

libs/designer-ui/src/lib/workflow/schema/generator.ts, libs/designer/src/lib/core/utils/outputs.ts
bugfix
no error message is shown and is defaulted to {}
error message is shown, value is not changed
no
=> fix(designer): Show error message when using invalid payload in schema editor

apps/vs-code-designer-react/src/app/app.tsx, apps/vs-code-designer-react/src/app/servicesHelper.ts
Cherry pick of fix(vscode): Create an OAuth connection to Key vault https://github.com/Azure/LogicAppsUX/pull/2657
=> fix(vscode): Create an OAuth connection to Key vault 

.vscode/launch.json, apps/logic-apps-ux-docs/docs/vscode.md, package.json
* **What kind of change does this PR introduce?** 
- Infra improvement
* Unable to set breakpoints in vs-code-data-mapper
* able to set breakpoints in vs-code-data-mapper
N/A
=> fix(Data Mapper): breakpoints work for vs-code-data-mapper

apps/designer-standalone/src/app/AzureLogicAppsDesigner/azureContextSettings.tsx, apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesigner.tsx, apps/designer-standalone/src/app/LocalDesigner/contextSettings.tsx, apps/designer-standalone/src/app/LocalDesigner/localDesigner.tsx, apps/designer-standalone/src/state/workflowLoadingSlice.ts, libs/chatbot/.babelrc, libs/chatbot/.eslintrc.json, libs/chatbot/README.md, libs/chatbot/jest.config.ts, libs/chatbot/jest.setup.js, libs/chatbot/package.json, libs/chatbot/project.json, libs/chatbot/src/index.ts, libs/chatbot/src/lib/index.tsx, libs/chatbot/src/lib/ui/chatbot.tsx, libs/chatbot/tsconfig.json, libs/chatbot/tsconfig.lib.json, libs/chatbot/tsconfig.spec.json, package.json, tsconfig.base.json, workspace.json
Setup work for the chatbot
No chatbot
opens a panel with the chat bot
does not affect any of our production designers, just introduces it in standalone
=> feat(designer): Initial setup work of the chatbot

libs/data-mapper/src/lib/core/state/DataMapSlice.ts, libs/data-mapper/src/lib/core/state/__test__/DataMapSlice.spec.ts
Bug fix
Undoing a delete on a function won't restore the connections. It'll lead to a dead object. Fixes #2090
Undoing a delete works correctly now
No
=> fix(Data Mapper): Fix undo and function deletion

libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts, libs/designer/src/lib/core/utils/swagger/inputsbuilder.ts, libs/designer/src/lib/core/utils/swagger/operation.ts
=> fix(designer): Parameter location should be read only from top level in property

apps/data-mapper-standalone/src/app/DataMapperStandaloneDesigner.tsx, apps/vs-code-data-mapper-react/src/app/app.tsx, libs/data-mapper/src/lib/mapDefinitions/MapMetadataSerializer.ts, libs/data-mapper/src/lib/ui/DataMapperDesigner.tsx
Feature
N/A
Starting the work on generating the metadata that will be persisted on the file system for saving the position of nodes
No
=> feat(Data Mapper): Start the map metadata generation

apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesigner.tsx, apps/designer-standalone/src/app/LocalDesigner/localDesigner.tsx, apps/designer-standalone/src/components/LocalizationSettings.tsx, apps/designer-standalone/src/components/settings_box.tsx, apps/designer-standalone/src/state/workflowLoadingSlice.ts
https://github.com/Azure/LogicAppsUX/assets/13208452/05d950f7-af80-4c43-a06e-d68d7ee3b7d8
=> test(designer): Add Language option for loc to designer-standalone

libs/data-mapper/src/lib/__mocks__/FunctionMock.ts, libs/data-mapper/src/lib/mapDefinitions/MapDefinitionSerializer.ts, libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionSerializer.spec.ts, libs/data-mapper/src/lib/models/Function.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts, libs/data-mapper/src/lib/utils/Function.Utils.ts
Feature
N/A
Serialization work for sequence functions for XML, JSON and deserialization will come later
No
=> feat(Data Mapper): XML sequence serialization

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230614000552662 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230614000552662 to main

apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/NewCodeProjectTypeStep.ts, apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/setNamepSpace.ts, apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/ScriptProjectCreateStep.ts, apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/initLogicAppCodeProjectVScode/InitCodeProject.ts, apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/initLogicAppCodeProjectVScode/ScriptInit.ts, apps/vs-code-designer/src/app/commands/createNewCodeProject/createNewCodeProject.ts, apps/vs-code-designer/src/package.json
- Removed deployment sub path from logic app to enhance portal deployment experience 
- Added additional UX enhancements based on feedback
=> fix(vscode): fix deployment subpath in logic app workspace 

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230615000530333 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230615000530333 to main

libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionSerializer.spec.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts
Feature
N/A
N/A, just testing for this use case
N/A
=> feat(Data Mapper): JSON Sequence serialization

apps/vs-code-designer/src/assets/FunctionProjectTemplate/FunctionsProj
Added line in build step to delete unnecessary assembly files coming from Nuget package before files are copied to lib/custom
[Azure Board Work Item](https://msazure.visualstudio.com/One/_workitems/edit/24285993)
AB#24286064
=> fix(vscode): Fix function project file 

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230616000546607 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230616000546607 to main

libs/designer/src/lib/core/utils/parameters/dynamicdata.ts, libs/services/designer-client-services/src/lib/base/operationmanifest.ts, libs/services/designer-client-services/src/lib/consumption/manifests/invokeWorkflow.ts, libs/services/designer-client-services/src/lib/consumption/operationmanifest.ts, libs/services/designer-client-services/src/lib/consumption/operations/invokeWorkflow.ts
Bug fix
Child workflow trigger schema was not loaded previously
All trigger schema parameters will show up correctly in the UI
No
=> fix(designer): Consumption - Fixing dynamic content in child workflow manifest and loading in designer

Localize/loc/de/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230619000545643 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230619000545643 to main

libs/designer/src/lib/core/graphlayout/elklayout.ts
Added workflow graph to logged elk errors for debugging purposes
=> chore: More verbose ELK graph errors

libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts, libs/designer/src/lib/core/graphlayout/elklayout.ts, libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
Added catch for no-trigger workflows to prevent deserialization errors that adds the placeholder trigger
Added extra elk error logging
This was cherry picked from some main branch prs
=> chore: Hotfixing v2.28 release with no-trigger fixes

libs/designer/src/lib/core/DesignerProvider.tsx
Cherry picking commit 495cca41765b5d61fc2a20205c73f907a2b92eca
=> chore: Cherry picking commit 495cca41765b5d61fc2a20205c73f907a2b92eca

libs/designer/src/lib/core/actions/bjsworkflow/add.ts
bug fix
When adding a new node with a  switch case that has the same name, the designer crashes:
https://github.com/Azure/LogicAppsUX/issues/2770
Designer no longer crashes
no
before:
after:
=> fix(designer): Checks all nodes (including switch cases) for nodeIds when adding a new node

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230622000726531 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230622000726531 to main

apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/ScriptProjectCreateStep.ts, apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/workflowDesigner/DesignerConfig.ts, libs/vscode-extension/src/lib/models/host.ts
Add the feature flag to host.json files to support 'Invoke Function' connector in logic app workspace
=> fix(vscode): Modify Workspace to enable 'Invoke Function' flag 

apps/vs-code-designer/src/app/tree/LogicAppResourceTree.ts
- Fixes #2504 
When deploying the logic app couldn't create access policy for connection as the resolution service was taking the app settings from the remote LA instead of the local one.
Takes app settings from the local.settings.json instead of the remote one.
No
=> fix(vscode): Resolution of local settings when creating access policy for connection

Localize/loc/cs/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230623000753039 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230623000753039 to main

libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- The log level "Trace" is not present in portal
- I am replacing our one instance with "Verbose" to fix
=> fix(Designer): Fixed breaking log in Portal

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230624000632851 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230624000632851 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230625000743473 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230625000743473 to main

apps/vs-code-designer/src/app/commands/dotNetSDK/installDotNetSDK.ts, apps/vs-code-designer/src/app/commands/dotNetSDK/updateDotNetSDK.ts
MAC
Add donet@6 to PATH and .bash_profile after brew install
=> fix(vscode): brew install dotnet@6

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230629000516009 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230629000516009 to main

apps/designer-standalone/src/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx, apps/designer-standalone/src/app/AzureLogicAppsDesigner/Services/ConsumptionSerializationHelpers.ts, apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx, package-lock.json
** These changes are in standalone only on this PR, but they are mirrored near exactly in my Portal PR **
https://msazure.visualstudio.com/One/_git/AzureUX-LogicAppsPortal/pullrequest/8356337
There was a regression somewhere that made connections references in consumption not serialize properly, this has been fixed.
This PR also fixes an issue where connections would not serialize properly inside of nested scopes, our serialization logic now traverses the graph for all spots that need serialization.
Fixes:
- https://github.com/Azure/LogicAppsUX/issues/2837
- https://github.com/Azure/LogicAppsUX/issues/2861
=> fix(Designer): Fixed consumption standalone connection serialization

libs/designer-ui/src/lib/dropdown/index.tsx
Fixes dropdown options state issue that was only present in portal.
Changed an invalid useState to a useMemo hook
Fixes https://github.com/Azure/LogicAppsUX/issues/2858
=> fix(Designer): Fixed dropdown options state bug

libs/data-mapper/src/lib/core/DataMapperDesignerProvider.tsx
- fixes app crashing because of change in library being consumed
- please see this PR https://github.com/Azure/LogicAppsUX/pull/2806/files#diff-2330a0606b6b9745a00ef06f831f90a3907604876406f2533bf91b816f40ac2c
- app is crashing on load
- fix
- no
NA
=> fix(Data Mapper): Added React Query to DM lib to fix app crash

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230630001441930 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230630001441930 to main

libs/designer/src/lib/core/utils/parameters/casting.ts, package-lock.json
bugfix 
https://github.com/Azure/LogicAppsUX/issues/2886
now should serialize all tokens
no
=> fix(designer): Serialization of expressions within casted parameters failing validation

libs/services/designer-client-services/src/lib/base/operationmanifest.ts
=> feat(designer): Add support for x12 and edifact connector

Localize/loc/cs/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230701001043727 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230701001043727 to main

.github/ISSUE_TEMPLATE/bug_report.yml
bugfix
My last PR may have broken something in filing a github issue
Reverting the conditional, and just using a simple old designer/new designer
=> fix(designer): revert designer type dropdown

.github/ISSUE_TEMPLATE/data_mapper.yml
=> chore: Update data_mapper.yml to add danielle as assignee

libs/designer-ui/src/lib/arrayeditor/expandedsimplearray.tsx, libs/designer-ui/src/lib/arrayeditor/index.tsx, libs/designer-ui/src/lib/arrayeditor/util/serializecollapsedarray.ts, libs/designer-ui/src/lib/token/token.less, libs/designer/src/lib/core/utils/validation.ts, libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/scratchTab.tsx
Bug fix
We did not support enums
We should now support enums
no
AB#24459512
=> fix(designer): Added support for enums in simple array editor

apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts, apps/vs-code-designer/src/app/utils/codeless/__test__/parameterizer.test.ts, apps/vs-code-designer/src/app/utils/codeless/common.ts, apps/vs-code-designer/src/app/utils/codeless/connection.ts, apps/vs-code-designer/src/app/utils/codeless/parameter.ts, apps/vs-code-designer/src/app/utils/codeless/parameterizer.ts, libs/vscode-extension/src/lib/models/connection.ts, package-lock.json
- **What kind of change does this PR introduce?** feature
- **What is the current behavior?** when creating managed, function, and API connections, resource ID values are hardcoded in connections.json
- **What is the new behavior (if this is a feature change)?** when creating managed, function, and API connections, resource ID values are parameterized in connections.json, references appsettings and parameters
- **Does this PR introduce a breaking change?** no
AB#24354456
=> feat(vscode): externalize connection parameterization

apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
=> fix(vscode): Update services API  version  (#2957)

Localize/loc/de/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230715000529403 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230715000529403 to main

apps/vs-code-designer-react/src/app/servicesHelper.ts, apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
=> fix(vscode): Api version in api hub service

apps/vs-code-designer-react/src/app/servicesHelper.ts
Update api version and update apihub service details props
=> fix(vscode): Api version in api hub service (#2974)

apps/vs-code-designer/src/package.json
- Adding microsoft csharp extension as dependency for when debugging app
=> feat(vscode): Add microsoft csharp extension as dependency

libs/services/designer-client-services/src/lib/base/operationmanifest.ts
=> fix(designer): Update operations connector id for x12 and edifact

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230719000632125 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230719000632125 to main

libs/designer/src/lib/core/actions/bjsworkflow/runafter.ts, libs/designer/src/lib/ui/settings/sections/runafter.tsx, libs/designer/src/lib/ui/settings/sections/runafterconfiguration/runafterActionSelector.tsx
bug fix
https://github.com/Azure/LogicAppsUX/issues/2987
fixed so we update upstream nodes on each run after edge change
no
=> fix(designer): Update upstream nodes when updating run after

libs/designer-ui/src/lib/editor/monaco/monaco.less, libs/designer-ui/src/lib/expressioneditor/index.tsx, libs/designer-ui/src/lib/tokenpicker/index.tsx, libs/designer-ui/src/lib/tokenpicker/tokenpicker.less, libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickersection.tsx, package-lock.json
Bug Fix
https://github.com/Azure/LogicAppsUX/issues/3009
we should now be able to add expressions on small screens
no
=> fix(designer): token picker support for small screens 

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230723000709559 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230723000709559 to main

Localize/loc/de/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230724000805138 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230724000805138 to main

libs/designer-ui/src/lib/searchabledropdownWithAddAll/index.tsx
- Fixes a small type import bug that would have prevented build
=> fix(Designer): Fixed small type import build issue

Localize/loc/ja/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230725000517228 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230725000517228 to main

libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts, libs/services/designer-client-services/src/lib/workflow.ts
Add dynamic inputs for serialized workflow
cherry-pick https://github.com/Azure/LogicAppsUX/pull/3000
=> fix(designer): Add dynamic inputs for serialized workflow (#3000)

libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx, libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx, libs/designer/src/lib/ui/common/LoopsPager/LoopsPager.tsx
* Update repetition index according to scope id
* Update useEffect array to trigger when repetition name updates
* Update loops pager component
* Remove dependency
=> fix(designer): Nested loops actions update in monitoring view (#3050)

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230728000649015 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230728000649015 to main

libs/services/designer-client-services/src/lib/standard/artifact.ts
=> feat(ia): Support Premium IA in artifact service

Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230803000637332 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230803000637332 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230804000921597 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230804000921597 to main

apps/vs-code-designer-react/src/app/constants.ts, apps/vs-code-designer-react/src/app/servicesHelper.ts
* Add swagger operations functions and add connector/id to supported operations
=> fix(vscode): Add swagger to supported operations list (#3076)

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230811000507696 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230811000507696 to main

Localize/loc/es/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230812000421509 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230812000421509 to main

apps/designer-standalone/src/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx, apps/vs-code-designer-react/src/app/DesignerCommandBar/index.tsx
https://github.com/Azure/LogicAppsUX/pull/3129
=> fix(designer): Ignore validation on parameterGroups without parameters

apps/vs-code-designer/src/package.json
This adds the icon into the create menu like the Functions Apps here:
See https://github.com/microsoft/vscode-azureresourcegroups/pull/735 for details.
=> feat(vscode): Add icon to create command

Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230819001053065 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230819001053065 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230820000623474 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230820000623474 to main

Localize/loc/nl/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230821000546854 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230821000546854 to main

libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts, libs/designer/src/lib/core/index.ts, libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts, libs/designer/src/lib/core/parsers/ParseReduxAction.ts, libs/designer/src/lib/core/utils/tokens.ts, libs/services/designer-client-services/src/lib/base/index.ts
This reverts commit e5a6ddef79a2e50cdf7c9a3ceacd28c80eb2ae63.
=> fix(designer): Revert export function for deserialization of tokens

package-lock.json, package.json
Horizontal scrolling with shift + mouse wheel did not work previously due to a bug with react-flow.
This bug has now been fixed and I've updated react-flow.
Fixes https://github.com/Azure/LogicAppsUX/issues/2491
=> fix(Designer): Fixed broken horizontal scrolling with shift + mouse wheel

Localize/loc/ja/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230822000653402 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230822000653402 to main

libs/designer/src/lib/core/state/workflow/workflowSlice.ts
Quick PR to enable save button when optional parameter is removed
=> fix(designer): Enable isDirty When removing Optional Parameter

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230825000652875 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230825000652875 to main

libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts, libs/designer/src/lib/core/parsers/ParseReduxAction.ts, libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
* fix settings regression
* remove console logs
* remove use of workflowKind when operation definition is provided
Fixes #3199
=> fix(designer): Settings not Deserializing (#3143)

libs/designer-ui/src/lib/panel/panelUtil.ts, libs/designer/src/lib/ui/Designer.tsx, libs/designer/src/lib/ui/panel/panelRoot.tsx
=> feat: adding custom panel location capability

libs/data-mapper/src/lib/components/configPanel/AddOrUpdateSchemaView.tsx
bug fix
unable to add new schemas
no
=> Fix(data mapper): able to add new schemas

Localize/loc/hu/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230826000558431 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230826000558431 to main

Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230830001010264 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230830001010264 to main

libs/designer-ui/src/lib/token/inputToken.tsx
Fixes https://github.com/Azure/LogicAppsUX/issues/3209
=> fix(designer): Fix issue where deleting a token without focusing the editor would not update the property value

Localize/loc/cs/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/pl/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230831000550179 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230831000550179 to main

libs/services/designer-client-services/src/lib/standard/run.ts
Add property check for content in inputs/outputs object
=> fix(designer): Add property check for content in inputs/outputs object

libs/designer-ui/src/lib/querybuilder/HybridQueryBuilder.tsx, libs/designer-ui/src/lib/querybuilder/Row.tsx, libs/designer-ui/src/lib/querybuilder/SimpleQueryBuilder.tsx, libs/designer-ui/src/lib/querybuilder/helper.ts, libs/designer-ui/src/lib/querybuilder/index.tsx, libs/utils/src/lib/helpers/functions.ts
https://github.com/Azure/LogicAppsUX/pull/3232
=> fix(designer): SimpleQueryBuilder Negatory Operators Serialization/Deserializing Properly

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230901001550781 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230901001550781 to main

__mocks__/workflows/Panel.json, libs/designer/src/lib/core/utils/parameters/helper.ts
=> fix(designer): SimpleQueryBuilder Negatory Operators Deserializing Properly

libs/designer-ui/src/lib/arrayeditor/util/serializecollapsedarray.ts, libs/designer-ui/src/lib/arrayeditor/util/util.ts
Made Expanded/Collapsed Array more readable
=> fix(Designer): Add spaces in simple array editor to make more readable

Localize/loc/cs/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230902000556720 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230902000556720 to main

libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx, libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx, libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/monitoringTab/propertiesPanel.tsx
* Add check for skipped parents
* Add skipped for scope
=> fix(designer): Show skipped status for actions inside skipped scopes

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230910000617657 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230910000617657 to main

Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230911000555361 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230911000555361 to main

Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230912000503444 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230912000503444 to main

libs/data-mapper/src/lib/components/commandBar/EditorCommandBar.tsx
bug fix
toolbar is divided into different lines
changes formatting to have toolbar all on one line
no
=> fix(Data Mapper):  formatting fix for tool bar

apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionConfigFile.ts, apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/ScriptProjectCreateStep.ts, apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/workflowDesigner/DesignerConfig.ts, apps/vs-code-designer/src/assets/FunctionProjectTemplate/FunctionsProj
This reverts commit d2501fb720cc61de534c799e364c517872e705b4.
=> fix(vscode): Revert feat(vscode): Logic App Workspace Local Settings Updates.  (#3087)

apps/logic-apps-ux-docs/docs/intro.md
=> docs: Update intro.md

libs/designer/src/lib/ui/panel/recommendation/browseView.tsx, libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
* bind the search operations methods
* fix typo
=> fix(designer): bind the search operations methods (#3285)

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230916000606646 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230916000606646 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230917000618488 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230917000618488 to main

Localize/loc/es/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230918000527439 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230918000527439 to main

libs/data-mapper/src/lib/components/testMapPanel/TestMapPanel.tsx, package-lock.json
Bug fix 
User has to type something in the test panel, close it, then reopen it to be able to click on the test button
https://github.com/Azure/LogicAppsUX/issues/3046
As soon as user types something in the test panel, the test button gets enabled
no
NA
=> fix(Data Mapper): test button is disabled until you close and come back to test

libs/data-mapper/src/lib/utils/Function.Utils.ts
Bug fix
Data mapper crashes when user tries to remove functions
https://github.com/Azure/LogicAppsUX/issues/3284
Data mapper does not crash anymore on deleting functions
no
NA
=> fix(Data Mapper): Clicking on action (and deleting it) will cause data mapper to crash

libs/data-mapper/src/lib/components/inputTypes/InputDropdown.tsx
bug fix
app crashes when trying to assess the type for unbounded inputs
app no longer crashes, and display
- no
NA
=> fix(Data Mapper): unlimited inputs now show data type

Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230920165508298 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230920165508298 to main

libs/data-mapper/src/lib/utils/DataMap.Utils.ts, libs/data-mapper/src/lib/utils/__test__/DataMapUtils.spec.ts
Bug fix
When user selects some map definitions (yaml files), it would crash half way.
https://github.com/Azure/LogicAppsUX/issues/2932
Reported map crash instance has been fixed and loads map properly.
no
NA
=> fix(Data Mapper): map not loading on some instances

libs/designer/src/lib/core/DesignerProvider.tsx
Bugfix.
LoggingService throws because it has not been initialized.
Removed usage of LoggingService so code doesn't throw.
No.
Sample of logging in console after this change:
AB#25238017
=> fix(designer): Fix exception due to usage of LoggingService in DesignerProvider

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230926000748469 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230926000748469 to main

apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts, apps/vs-code-designer/src/app/utils/codeless/__test__/parameterizer.test.ts, apps/vs-code-designer/src/app/utils/codeless/common.ts, apps/vs-code-designer/src/app/utils/codeless/connection.ts, apps/vs-code-designer/src/app/utils/codeless/parameter.ts, apps/vs-code-designer/src/app/utils/codeless/parameterizer.ts, libs/vscode-extension/src/lib/models/connection.ts
cherry-picked connection parameterization
=> feat(vscode): externalize connection parameterization (#2830)

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230928001738154 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230928001738154 to main

apps/designer-standalone/src/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
bug fix
bug #3324 
fixes #3324
No
=> fix(designer): Fixing standalone test page to save workflow.json correctly

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230930000521787 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230930000521787 to main

apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForAzureResource.ts, apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts, apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForAzureResource.ts, apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForLocal.ts, apps/vs-code-designer/src/app/commands/workflows/openOverview.ts, apps/vs-code-designer/src/app/utils/codeless/common.ts, package-lock.json
Bug fix
#3314 
fixes #3314 
No
=> fix(vscode): Removing storing parameters inside definition in standard app

libs/designer-ui/src/lib/modaldialog/index.tsx
Fixes #3400 
https://github.com/Azure/LogicAppsUX/assets/102700317/9110e4f6-e2a5-4c2d-a97a-a9e0ad4750a5
=> fix(designer): Allow event bubbling in json modal

libs/designer-ui/src/lib/modaldialog/index.tsx, libs/designer/src/lib/core/utils/parameters/helper.ts, libs/designer/src/lib/ui/settings/sections/runafterconfiguration/index.tsx, libs/designer/src/lib/ui/settings/sections/runafterconfiguration/runafterActionSelector.tsx
-Fixes https://github.com/Azure/LogicAppsUX/issues/3414
small other changes
removing deprecated title attribute to fluent UI Dialog
Add readonly prop to ActionMenuItem to prevent it from changing the workflow in monitoring
=> fix(Designer): simple query builder not parsing correct data

libs/data-mapper/src/lib/mapDefinitions/MapDefinitionSerializer.ts, libs/data-mapper/src/lib/utils/DataMap.Utils.ts, libs/data-mapper/src/lib/utils/__test__/DataMapUtils.spec.ts
Bug fix
YML code cannot be generated when there is a function node that is not connected.
YML code is successfully generated when the function node is added (not connected to source or target) and shows on the Code view.
no
=> fix(Data Mapper): Cannot generate YML code with two unconnected functions

Localize/lang/strings.cs.json, Localize/lang/strings.de.json, Localize/lang/strings.es.json, Localize/lang/strings.fr.json, Localize/lang/strings.hu.json, Localize/lang/strings.id.json, Localize/lang/strings.it.json, Localize/lang/strings.ja.json, Localize/lang/strings.ko.json, Localize/lang/strings.nl.json, Localize/lang/strings.pl.json, Localize/lang/strings.pt-BR.json, Localize/lang/strings.pt-PT.json, Localize/lang/strings.ru.json, Localize/lang/strings.sv.json, Localize/lang/strings.tr.json, Localize/lang/strings.zh-Hans.json, Localize/lang/strings.zh-Hant.json
This is the pull request automatically created by the OneLocBuild task in the build process to check-in localized files generated based upon translation source files (.lcl files) handed-back from the downstream localization pipeline. If there are issues in translations, visit https://aka.ms/icxLocBug and log bugs for fixes. The OneLocBuild wiki is https://aka.ms/onelocbuild and the localization process in general is documented at https://aka.ms/AllAboutLoc.
=> Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 644

__mocks__/mapDefinitions/FullTranscriptMapDefinition.ts, apps/data-mapper-standalone/src/state/DataMapDataLoader.ts, libs/data-mapper/src/lib/core/state/DataMapSlice.ts, libs/data-mapper/src/lib/mapDefinitions/MapMetadataSerializer.ts, libs/data-mapper/src/lib/mapDefinitions/__test__/MapMetadataSerializer.spec.ts, libs/data-mapper/src/lib/models/MapMetadata.ts
feature
unable to load function positions
- creates a unique ID based on the outgoing connections and their order to the target node
- saves that ID to metadata
- matches to functions from YML by running identical ID generation code on that function
- none
- https://github.com/Azure/LogicAppsUX/assets/99753874/1c0a4bfe-8df …
=> feat(data-mapper): create unique ID for function and load position

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231014000741003 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231014000741003 to main

Localize/loc/es/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231015000425257 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231015000425257 to main

Localize/loc/nl/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231016000548523 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231016000548523 to main

apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/CodelessFunctionWorkflow.ts, apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/ScriptProjectCreateStep.ts, apps/vs-code-designer/src/assets/FunctionProjectTemplate/FunctionsFile, apps/vs-code-designer/src/assets/FunctionProjectTemplate/FunctionsProj
* logger function project updates
* updates to functions project dependencies
* changed temperatureScale from Celcius to Celsius
=> feat(vscode): Add Logger Configuration and Package Version Updates (#3444)

apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesigner.tsx, apps/designer-standalone/src/environments/environment.ts, libs/chatbot/jest.config.ts, libs/chatbot/src/lib/ui/chatbot.tsx, libs/designer-ui/jest.config.ts, libs/designer-ui/src/lib/chatbot/components/assistantError.tsx, libs/designer-ui/src/lib/chatbot/components/chatBubble.tsx, libs/designer-ui/src/lib/chatbot/components/connectionsSetupMessage.tsx, libs/designer-ui/src/lib/chatbot/components/conversationMessage.tsx, libs/designer-ui/src/lib/chatbot/components/feedbackMessage.tsx, libs/designer/jest.config.ts
Fixes:
* Correct white space formatting for responses
* Use /query api endpoint rather than /queryWorkflow
* Tell app not to crash when sending query with invalid workflow
=> fix(copilot): Minor fixes to copilot UI including proper text formatting and correct api endpoint

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231019000521332 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231019000521332 to main

apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/CodelessFunctionWorkflow.ts, apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/ScriptProjectCreateStep.ts, apps/vs-code-designer/src/app/tree/subscriptionTree/SubscriptionTreeItem.ts, apps/vs-code-designer/src/assets/FunctionProjectTemplate/FunctionsFile, apps/vs-code-designer/src/assets/FunctionProjectTemplate/FunctionsProj
- Cherry picks for vscode extension release
=> fix(vscode): Add Logger Configuration and Package Version Updates & Update logic app list in tree view after creating logic app in azure

libs/designer-ui/src/lib/editor/base/editor.less, libs/designer-ui/src/lib/editor/base/index.tsx, libs/designer-ui/src/lib/editor/base/plugins/TokenTypeahead.tsx, libs/designer-ui/src/lib/editor/base/plugins/tokenpickerbutton/index.tsx
* Add props to allow/disallow expression in token picker
* Update position when single token picker option
* Update prop name
=> feat(designer): Add option to hide expression in token picker (#3473)

apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/CodelessFunctionWorkflow.ts, apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/ScriptProjectCreateStep.ts, apps/vs-code-designer/src/app/tree/subscriptionTree/SubscriptionTreeItem.ts, apps/vs-code-designer/src/assets/FunctionProjectTemplate/FunctionsFile, apps/vs-code-designer/src/assets/FunctionProjectTemplate/FunctionsProj
- Cherry picks for vscode extension release
=> fix(vscode): Add Logger Configuration and Package Version Updates & Update logic app list in tree view after creating logic app in azure #3477

libs/services/designer-client-services/src/lib/base/operationmanifest.ts
=> feat(designer): Add support for x12 and edifact batch encode opertation.

libs/designer-ui/src/lib/editor/base/plugins/tokenpickerbutton/index.tsx, libs/designer-ui/src/lib/tokenpicker/models/token.ts, libs/designer/src/lib/core/index.ts
=> feat(desinger): Export getTriggerNodeId and update outputToken schema

libs/designer/README.md
Fixed issue in `libs/designer` folder where README contained invalid command to run unit tests.
Docs Update
No
=> docs: Updated `libs/designer/README.md` with the correct command to run unit tests.

apps/vs-code-designer/src/README.md
=> feat(Data Mapper) Merged Readme files

apps/vs-code-data-mapper-react/project.json, apps/vs-code-designer/src/app/commands/dataMapper/DataMapperExt.ts, apps/vs-code-designer/src/app/commands/dataMapper/DataMapperPanel.ts, apps/vs-code-designer/src/app/commands/dataMapper/FxWorkflowRuntime.ts, apps/vs-code-designer/src/app/commands/dataMapper/dataMapper.ts, apps/vs-code-designer/src/app/commands/pickFuncProcess.ts, apps/vs-code-designer/src/app/utils/workspace.ts, apps/vs-code-designer/src/extensionVariables.ts, apps/vs-code-designer/tsconfig.json, libs/data-mapper/project.json, package.json
=> feat(Data Mapper): changed outputPaths to vs-code-designer/vs-code-data-mapper

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231026000652970 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231026000652970 to main

apps/vs-code-designer/src/app/utils/codeless/__test__/parameterizer.test.ts, apps/vs-code-designer/src/app/utils/codeless/connection.ts, apps/vs-code-designer/src/app/utils/codeless/parameterizer.ts, package-lock.json
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...) feature
- **What is the current behavior?** Managed connections are being parametrized, however, connection URL should be pull from local app settings.
- **What is the new behavior (if this is a feature change)?** Managed connections URL is being added to appsettings and pull via parameters.json
- **Does this PR introduce a breaking change?** NO
-
=> feat(vscode): Connection Parameterization add Connection URL appSettings

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231027000805976 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231027000805976 to main

Localize/loc/hu/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231028001008415 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231028001008415 to main

apps/vs-code-designer/.eslintrc.json, apps/vs-code-designer/src/app/commands/dotnet/validateDotNetIsLatest.ts, apps/vs-code-designer/src/app/commands/funcCoreTools/installFuncCoreTools.ts, apps/vs-code-designer/src/app/commands/funcCoreTools/uninstallFuncCoreTools.ts, apps/vs-code-designer/src/app/commands/funcCoreTools/updateFuncCoreTools.ts, apps/vs-code-designer/src/app/commands/funcCoreTools/validateFuncCoreToolsInstalled.ts, apps/vs-code-designer/src/app/commands/funcCoreTools/validateFuncCoreToolsIsLatest.ts, apps/vs-code-designer/src/app/commands/pickFuncProcess.ts, apps/vs-code-designer/src/app/commands/workflows/switchToDotnetProject.ts, apps/vs-code-designer/src/app/debug/validatePreDebug.ts, apps/vs-code-designer/src/app/utils/azurite/activateAzurite.ts, apps/vs-code-designer/src/app/utils/binaries.ts, apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts, apps/vs-code-designer/src/app/utils/dotnet/dotnet.ts, apps/vs-code-designer/src/app/utils/dotnet/executeDotnetTemplateCommand.ts, apps/vs-code-designer/src/app/utils/funcCoreTools/cpUtils.ts, apps/vs-code-designer/src/app/utils/funcCoreTools/funcVersion.ts, apps/vs-code-designer/src/app/utils/funcCoreTools/getBrewPackageName.ts, apps/vs-code-designer/src/app/utils/funcCoreTools/getFuncPackageManagers.ts, apps/vs-code-designer/src/app/utils/funcCoreTools/getNpmDistTag.ts, apps/vs-code-designer/src/app/utils/vsCodeConfig/settings.ts, apps/vs-code-designer/src/constants.ts, apps/vs-code-designer/src/main.ts, apps/vs-code-designer/src/onboarding.ts, apps/vs-code-designer/src/package.json
- Open the designer
- Debugging/attaching
- Actual breakpoint working
=> feat(vscode): Opt-in/opt-out for installation of binaries

apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/initLogicAppCodeProjectVScode/ScriptInit.ts, apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/initLogicAppCodeProjectVScode/WorkflowCode.ts, apps/vs-code-designer/src/app/commands/initProjectForVSCode/DotnetInitVSCodeStep.ts, apps/vs-code-designer/src/app/commands/initProjectForVSCode/ScriptInitVSCodeStep.ts, apps/vs-code-designer/src/app/commands/initProjectForVSCode/WorkflowInitVSCodeStep.ts, apps/vs-code-designer/src/onboarding.ts
- Add feature preview message when accepting the installation/validation of dependencies binaries
- Update tasks.json according if user uses binaries dependencies
=> fix(vscode): Update function core tools option when optout

apps/vs-code-designer/src/app/commands/dataMapper/DataMapperExt.ts, apps/vs-code-designer/src/app/commands/dataMapper/DataMapperPanel.ts, apps/vs-code-designer/src/app/commands/dataMapper/dataMapper.ts, apps/vs-code-designer/src/app/utils/vsCodeConfig/verifyVSCodeConfigOnActivate.ts, apps/vs-code-designer/src/extensionVariables.ts, apps/vs-code-designer/src/main.ts
=> fix(Data Mapper): Find LogicApp Root & Select as Workspace

apps/vs-code-designer/src/app/commands/dataMapper/extensionConfig.ts
* 
adding file extension to the supported list
no
=> fix(Data Mapper): Run XSLT function to recognize both .xslt and .xml

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231103001009595 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231103001009595 to main

apps/vs-code-designer/src/main.ts
feature
- issues command to VSCode to uninstall the old DM extension as soon as the new one is activated
- **official messaging to be provided in future PR**
no 
=> Feat(Data Mapper): uninstall legacy extension on activation of Designer extension

libs/designer/src/lib/core/utils/tokens.ts
- Add way to include tokens from current node for token selector
=> feat(designer): Add ability to get tokens from current node in token selector

libs/designer/src/lib/core/utils/tokens.ts
=> feat(designer): Add ability to get tokens from current node in token selector (#3598)

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231104001115207 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231104001115207 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231105001445258 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231105001445258 to main

Localize/loc/de/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231106010823573 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231106010823573 to main

Localize/loc/de/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/nl/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231107010858667 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231107010858667 to main

libs/designer/src/lib/ui/panel/recommendation/browseView.tsx, libs/services/designer-client-services/src/lib/search.ts, libs/utils/src/lib/models/connector.ts
Adding ability for the host to customize the sort of the connectors in the browse view
=> feat(designer): Adding ability for the host to customize the sort of the connectors in the browse view

Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231108010852242 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231108010852242 to main

libs/chatbot/src/lib/ui/chatbot.tsx, libs/chatbot/src/lib/ui/panelheader.tsx, libs/designer-ui/src/lib/chatbot/components/conversationItem.ts, libs/designer-ui/src/lib/chatbot/feedbackHelper.tsx
=> feat(copilot): Adding basic telemetry in copilot feedback

apps/vs-code-designer/src/app/commands/pickFuncProcess.ts, apps/vs-code-designer/src/app/utils/workspace.ts, libs/data-mapper/src/lib/mapDefinitions/MapDefinitionSerializer.ts
fixing build error caused by loadash
data mapper would not load
n/a
=> fix(Data Mapper): Fixed Data Mapper Build Error

libs/designer/src/lib/core/actions/bjsworkflow/copypaste.ts, libs/designer/src/lib/core/state/connection/connectionSlice.ts, libs/designer/src/lib/ui/connections/dropzone.tsx
fixes https://github.com/Azure/LogicAppsUX/issues/3621
https://github.com/Azure/LogicAppsUX/assets/95886809/c9b7c7ca-2cd8-40d9-998a-533552624ea6
=> fix(designer): Allow copy paste of a node's connection mapping

Localize/loc/cs/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231109010718011 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231109010718011 to main

apps/vs-code-designer/src/app/commands/dataMapper/FxWorkflowRuntime.ts, apps/vs-code-designer/src/app/commands/pickFuncProcess.ts, apps/vs-code-designer/src/app/utils/verifyIsProject.ts, apps/vs-code-designer/src/app/utils/workspace.ts, libs/data-mapper/src/lib/mapDefinitions/MapDefinitionSerializer.ts
=> fix(vscode): Fixes for ignite vsix

libs/chatbot/src/lib/images/Workflow.svg, libs/chatbot/src/lib/ui/panelheader.tsx
Changing the Icon in the header
Before:
After:
=> fix(copilot): Changing icon in header

libs/designer-ui/src/lib/chatbot/components/chatBubble.tsx, libs/designer-ui/src/lib/chatbot/components/conversationMessage.tsx
fixes https://github.com/Azure/LogicAppsUX/issues/3657
=> fix(copilot): Support for copilot copy in portal

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231110011022406 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231110011022406 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231111011029834 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231111011029834 to main

Localize/loc/de/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231112010647599 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231112010647599 to main

apps/vs-code-designer/src/app/utils/binaries.ts, apps/vs-code-designer/src/app/utils/vsCodeConfig/settings.ts
Cherry picks from 
1. https://github.com/Azure/LogicAppsUX/pull/3687
2. https://github.com/Azure/LogicAppsUX/pull/3690
=> fix(vscode): Add troubleshoot dependencies message

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231115010817696 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231115010817696 to main

libs/designer-ui/src/lib/editor/base/utils/parsesegments.ts
fix(designer): fix links in html editor when they have tokens
=> fix(designer): fix links in html editor when they have tokens

Localize/loc/id/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231116010825570 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231116010825570 to main

Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231118010730909 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231118010730909 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231119010955419 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231119010955419 to main

Localize/loc/hu/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231120010624085 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231120010624085 to main

Localize/loc/ja/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231121010605031 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231121010605031 to main

libs/designer/src/lib/core/utils/parameters/helper.ts, libs/parsers/src/lib/common/constants.ts
tokens with 'body/value' should use triggerBody rather than triggerOutput
=> fix(designer): tokens with 'body/value' should use triggerBody rather than triggerOutput

apps/vs-code-designer/src/app/commands/createCodeless/createCodeless.ts, apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts, apps/vs-code-designer/src/app/utils/dotnet/dotnet.ts
Cherry pick of following
- https://github.com/Azure/LogicAppsUX/pull/3779
- https://github.com/Azure/LogicAppsUX/pull/3813
- https://github.com/Azure/LogicAppsUX/pull/3816
=> fix(vscode): Codefixes for workspace file creation, dotnet installation and designer refresh

libs/designer-ui/src/lib/editor/base/plugins/Paste.tsx, libs/designer-ui/src/lib/editor/base/utils/editorToSegment.ts, libs/designer-ui/src/lib/editor/base/utils/parsesegments.ts, libs/designer-ui/src/lib/editor/monaco/index.tsx
Fixes https://github.com/Azure/LogicAppsUX/issues/3787
=> fix(designer): Fixes an issue where we weren't properly creating new lines in the editor

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231212010608499 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231212010608499 to main

apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
This pull request refactors the code in the `generateDeploymentScripts.ts` file in the `apps/vs-code-designer/src/app/commands/generateDeploymentScripts` directory. The code is updated to use the `axios` library instead of `request-promise` for making POST requests to the standard resources and managed connections APIs. The headers and response handling are also updated.
Main code changes:
* Refactored code to use the `axios` library for making POST requests to the standard resources and managed connections APIs. Updated headers and response handling.
=> fix(vscode):  Update requestP to axios

.github/ISSUE_TEMPLATE/data_mapper.yml
Added label so we know which issues need to be addressed!
=> Feat(Data Mapper): Update data_mapper.yml to include triage label

apps/vs-code-designer/src/app/commands/dataMapper/extensionConfig.ts
=> fix(vscode): Add workflow app kind to local.settings.json (#3841)

libs/designer-ui/src/lib/editor/base/editor.less, libs/designer-ui/src/lib/editor/base/plugins/tokenpickerbutton/index.tsx
Bug fix (UI only)
**1 -** If dynamic content pill is open and you hover over the expression button, the tooltip blocks the top button.
**2 -** If dynamic content pill is open and the token button is disabled, expression button has incorrect rounding.
**1:**
**2:**
No
See above.
=> fix(designer-ui): Fix pill tooltip UX and corner rounding

.vscode/settings.json
Git-Removed `.vscode/settings.json`
This was already added to the gitignore, but was not removed from the git cache
=> fix(Designer): Git-Removed the .vscode/settings.json file

apps/vs-code-designer/src/app/commands/binaries/validateAndInstallBinaries.ts, apps/vs-code-designer/src/app/utils/dotnet/dotnet.ts
=> fix(designer): Custom Code Workspace fix empty lib folder (#3769)

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231217010621979 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231217010621979 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231218010934150 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231218010934150 to main

apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
Fix project path in designtime folder
=> fix(vscode): Fix project path in workflow-designtime folder

Localize/loc/de/strings.json.lcl, Localize/loc/ja/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231219010733803 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231219010733803 to main

Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231220010702316 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231220010702316 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231221010700343 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231221010700343 to main

Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231222010640391 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231222010640391 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231228010654144 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20231228010654144 to main

apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx, libs/designer-ui/src/lib/azureResourcePicker/index.tsx, libs/designer-ui/src/lib/panel/recommendationpanel/operationGroupDetails/index.tsx, libs/designer/src/lib/ui/panel/recommendation/azureResourceSelection.tsx, libs/designer/src/lib/ui/settings/settingsection.tsx, libs/services/designer-client-services/src/lib/base/apimanagement.ts, libs/services/designer-client-services/src/lib/consumption/manifests/apiManagement.ts
Fixed some schema parameter parsing issues on the consumption APIM action.
- Parameters marked as required are now shown as required
- Parameters are now titled correctly (previously they had the string `Operation Parameters` prepended before each one)
- APIM action now works in standalone
Other small fixes
=> fix(Designer): Fixed APIM action schema parameter issues

apps/designer-standalone/src/app/AzureLogicAppsDesigner/Services/OAuthService.ts, apps/designer-standalone/src/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx, apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesigner.tsx, apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
OAuth flow now works in standalone
=> fix(Designer): OAuth in Standalone

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240107010800881 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240107010800881 to main

Localize/loc/es/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240108011759294 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240108011759294 to main

apps/vs-code-designer/src/app/commands/funcCoreTools/validateFuncCoreToolsIsLatest.ts
Add set func command right after installing an update
=> fix(vscode): Add set function core tools command right after installing an update

libs/data-mapper/src/lib/utils/Logging.Utils.ts
fix
added dm prefix to logs so that we can query for DM info
no
=> fix(Data Mapper): added prefix to dm logging

Localize/loc/ja/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240110010546210 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240110010546210 to main

apps/vs-code-designer/src/app/commands/dotnet/installDotNet.ts, apps/vs-code-designer/src/app/commands/funcCoreTools/installFuncCoreTools.ts, apps/vs-code-designer/src/app/commands/nodeJs/installNodeJs.ts, apps/vs-code-designer/src/app/utils/binaries.ts, apps/vs-code-designer/src/app/utils/bundleFeed.ts, apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts, apps/vs-code-designer/src/constants.ts, apps/vs-code-designer/src/onboarding.ts
Downloads the Microsoft.Azure.Functions.ExtensionBundle.Workflows on project activation.
=> feat(vscode): Microsoft.Azure.Functions.ExtensionBundle.Workflows download on project activate

libs/designer-ui/src/lib/arrayeditor/util/serializecollapsedarray.ts, libs/designer-ui/src/lib/arrayeditor/util/util.ts, libs/designer-ui/src/lib/code/index.tsx, libs/designer-ui/src/lib/code/util.ts, libs/designer-ui/src/lib/editor/base/utils/editorToSegment.ts, libs/designer-ui/src/lib/editor/base/utils/parsesegments.ts, libs/designer-ui/src/lib/schemaeditor/index.tsx, libs/utils/src/lib/helpers/stringFunctions.ts
=> fix(designer): Regression where array editor no longer serialized casted value

libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts, libs/designer/src/lib/core/utils/outputs.ts, libs/designer/src/lib/core/utils/parameters/helper.ts, libs/utils/src/lib/helpers/http.ts
Implemented an improved error parsing method to get errors from dynamic data requests, and properly display them to users.
Fixes https://github.com/Azure/LogicAppsUX/issues/3851
=> fix(Designer): Fixed dynamic data inputs/outputs error message propogation

libs/designer-ui/src/lib/editor/base/utils/parsesegments.ts
Fixing this bug.
https://github.com/Azure/LogicAppsUX/issues/3856
New behavior: 
https://github.com/Azure/LogicAppsUX/assets/135278983/177aae7f-bce5-41c6-903c-80a1059b98e3
=> fix(designer): Adding tokens outside of any HTML elements in raw HTML view causes a visual bug

libs/services/designer-client-services/src/lib/base/operationmanifest.ts
Added two new xml operation ids:
- `xmlcompose`
- `xmlparse`
=> feat(Designer): Added two xml operation ids

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240125010748984 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240125010748984 to main

libs/designer-ui/src/lib/card/__test__/__snapshots__/card.spec.tsx.snap, libs/designer-ui/src/lib/card/index.tsx
=> fix(designer): Fix tab order for cards

Localize/loc/cs/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240126010650345 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240126010650345 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240127010701741 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240127010701741 to main

Localize/loc/de/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240128023530939 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240128023530939 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240131020730728 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240131020730728 to main

Localize/loc/es/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/sv/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240201010937303 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240201010937303 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240202010732237 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240202010732237 to main

libs/designer-ui/src/lib/searchabledropdown/index.tsx, libs/designer-ui/src/lib/searchabledropdownWithAddAll/index.tsx
fix
see bug attached
fix- label is now set to the aria label for the dropdown
no
=> fix(Designer): added aria-labelledby for searchable dropdown

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240203010720236 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240203010720236 to main

apps/vs-code-designer/src/app/commands/dataMapper/FxWorkflowRuntime.ts, apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerBase.ts, apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
Cherry picks from:
https://github.com/Azure/LogicAppsUX/pull/4135
https://github.com/Azure/LogicAppsUX/pull/4096
=> fix(vscode): Update json file creation in workflow-designtime folder and parse interpolated connections data 

apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerBase.ts
Add validation for no connections
=> fix(vscode): Add validation for no connections (#4155)

libs/designer-ui/src/lib/editor/base/index.tsx, libs/designer-ui/src/lib/editor/base/plugins/InsertTokenNode.tsx, libs/designer-ui/src/lib/tokenpicker/index.tsx
fixes #4042 
in tokenpicker, moving by keyboard takes the focus away to somewhere irrelevant
in tokenpicker, moving by keyboard stays within tokenpicker unless esc is pressed
https://github.com/Azure/LogicAppsUX/assets/144840522/12390b19-7ff5-4794-924c-1e88a9f9ab4a
=> fix(Designer): Keyboard Focus Moves Out of TokenPicker Navigating Using Keyboard

apps/vs-code-designer/src/app/commands/binaries/resetValidateAndInstallBinaries.ts, apps/vs-code-designer/src/app/commands/registerCommands.ts, apps/vs-code-designer/src/app/utils/binaries.ts, apps/vs-code-designer/src/constants.ts, apps/vs-code-designer/src/onboarding.ts, apps/vs-code-designer/src/package.json
Cherry pick of these PR:
- https://github.com/Azure/LogicAppsUX/pull/4175
- https://github.com/Azure/LogicAppsUX/pull/4181
- https://github.com/Azure/LogicAppsUX/pull/4185
=> feat(vscode): Onboarding GA and slots deployment

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240216020928018 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240216020928018 to main

apps/vs-code-designer/src/app/commands/dataMapper/FxWorkflowRuntime.ts, apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts, apps/vs-code-designer/src/onboarding.ts
Cherry pick of these PR:
- https://github.com/Azure/LogicAppsUX/pull/4203
- https://github.com/Azure/LogicAppsUX/pull/4205
=> fix(vscode): Remove double binaries validation & overwriting of JSON files

Localize/loc/de/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240220060700708 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240220060700708 to main

libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
Bug fix
Dynamic inputs do not populate due to a regression in #4140. See #4227 for details of issue & fix.
Offending change being reverted:
Dynamic inputs work properly. Closes #4227.
No
=> fix(designer): Replace missing state reassignment

libs/designer-ui/src/lib/code/index.tsx, libs/designer-ui/src/lib/editor/monaco/index.tsx, libs/designer-ui/src/lib/expressioneditor/index.tsx, libs/designer-ui/src/lib/index.ts, libs/designer-ui/src/lib/peek/index.tsx, libs/designer-ui/src/lib/schemaeditor/index.tsx, libs/designer-ui/src/lib/staticResult/staticResult.less, libs/designer-ui/src/lib/tokenpicker/index.tsx, libs/designer-ui/src/lib/workflow/languageservice/workflowlanguageservice.ts, libs/designer/src/lib/core/state/designerOptions/designerOptionsInterfaces.ts, libs/designer/src/lib/core/utils/tokens.ts, libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
fixes https://github.com/Azure/LogicAppsUX/issues/4196
to remove utf expressions, please add `hideUTFExpressions: true` to host options
=> fix(desinger): made utfLength Expressions optional based on host options

Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240222010856468 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240222010856468 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240223010912811 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240223010912811 to main

apps/vs-code-react/src/app/export/workflowsSelection/helper.ts, apps/vs-code-react/src/app/export/workflowsSelection/workflowsSelection.tsx
* Fix useEffect on workflows success data
* Update useEffect
* Add separate functions to parse workflow selected lists
* Update decision
=> fix(vscode): Fix useEffect on workflows success data - export tool 

libs/services/designer-client-services/src/lib/consumption/manifests/as2.ts
=> feat(designer): Expose receiver URI on AS2 encode output

apps/vs-code-react/src/app/export/workflowsSelection/helper.ts, apps/vs-code-react/src/app/export/workflowsSelection/workflowsSelection.tsx, libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/_test__/createConnection.spec.tsx, libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx, libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnectionWrapper.tsx, libs/services/designer-client-services/src/lib/connection.ts, libs/services/designer-client-services/src/lib/standard/connection.ts
Cherry pick of the following PR:
- https://github.com/Azure/LogicAppsUX/pull/4249
- https://github.com/Azure/LogicAppsUX/pull/4265
=> fix(vscode): Fix useEffect on workflows success data & Revert - Adding hidden parameter field

libs/logic-apps-shared/src/utils/src/lib/helpers/connections.ts
This reverts commit 498fef92d9d7c8e7abddf7c6b4c4af93bf92ce15.
=> fix(designer): Revert - Update to make connections name case-insensitive

apps/vs-code-designer/src/app/commands/generateDeploymentScripts/azureScriptWizard.ts, apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts, apps/vs-code-designer/src/app/commands/initProjectForVSCode/initProjectForVSCode.ts, apps/vs-code-designer/src/app/commands/parameterizeConnections.ts, apps/vs-code-designer/src/app/commands/registerCommands.ts, apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerBase.ts, apps/vs-code-designer/src/app/utils/binaries.ts, apps/vs-code-designer/src/app/utils/codeless/parameter.ts, apps/vs-code-designer/src/app/utils/codeless/parameterizer.ts, apps/vs-code-designer/src/app/utils/vsCodeConfig/settings.ts, apps/vs-code-designer/src/constants.ts, apps/vs-code-designer/src/main.ts, apps/vs-code-designer/src/package.json, libs/vscode-extension/src/lib/models/workflow.ts
This pull request primarily focuses on adding functionality to parameterize connections in the VS Code extension for Azure Logic Apps. It introduces a new command to parameterize existing connections.
* A new file was added that defines the `promptParameterizeConnections` and `parameterizeConnections` functions, which handle the logic for parameterizing connections in the project.
* The `parameterizeConnections` command was registered.
* Added the `parameterizeConnections` and `parameterizeConnectionsInProjectLoadSetting` constants to manage the new functionality. 
* The `promptParameterizeConnections` function is now called during the extension activation process.
* Added the `parameterizeConnections` command to the package configuration and updated the settings schema to include the …
=> feat(vscode): Implement parameterize existing connections command

apps/vs-code-designer/src/app/commands/parameterizeConnections.ts
The changes mainly focus on error handling and improving the readability of the code.
The key changes include:
* The `connectionsJson` variable was renamed to `connectionsData` for clarity. Also, a check was added to return from the function if `connectionsJson` is an empty string. This is a preventative measure to avoid parsing an empty string with `JSON.parse`, which would throw an error.
* The error message in the `catch` block was corrected from 'exiting' to 'existing'. This improves the readability and understanding of the error message.
=> fix(vscode): Add test case for no connections when parameterize

apps/vs-code-designer/src/app/utils/bundleFeed.ts
Add validation for extension bundle workflows folder
=> fix(vscode): Add validation for extension bundle workflows folder

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240309032350381 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240309032350381 to main

Localize/loc/ko/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240309092235414 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240309092235414 to main

Localize/loc/fr/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240309152103384 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240309152103384 to main

Localize/loc/hu/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/sv/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240309210630424 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240309210630424 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240310032316943 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240310032316943 to main

Localize/loc/de/strings.json.lcl, Localize/loc/pl/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240310142227822 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240310142227822 to main

Localize/loc/ja/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240311142439458 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240311142439458 to main

Localize/loc/it/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240312022351870 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240312022351870 to main

libs/designer/src/lib/core/utils/parameters/helper.ts
Changing the check to see if the value is undefined more general and with cleaner code. 
Addressing the same change made in this PR: #4360
=> fix(Consumption): Changing 'undefined' check for value

libs/designer/src/lib/ui/Designer.tsx
Allow user to zoom out 10x more than before
=> feat(Designer): Allow user to zoom out 10x more than before

libs/data-mapper/src/lib/constants/FunctionConstants.tsx, libs/data-mapper/src/lib/utils/Function.Utils.ts, libs/data-mapper/src/lib/utils/Icon.Utils.tsx
* [ x ] The commit message follows our guidelines
Bug fix
Fixes #4381
=> fix(Data Mapper): Fixes custom functions category branding

libs/designer-ui/src/lib/tokenpicker/tokenpicker.less, libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickeroption.tsx
Bugfix
1. Token picker section header is not read by screen reader.
2. Tokens are not grouped into a list.
#4391 
Speech viewer text:
Variables  list  with 2 items  var1  button  
goalOwner  button  
var1  button  
goalOwner  button  
var1  button
=> fix(designer-ui): Convert tokenpickeroptions to ul

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240321022351261 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240321022351261 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240321082401302 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240321082401302 to main

Localize/loc/es/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240321142234652 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240321142234652 to main

Localize/loc/fr/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/sv/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240322030053807 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240322030053807 to main

Localize/loc/zh-Hans/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240322082538826 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240322082538826 to main

Localize/loc/id/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240322142357217 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240322142357217 to main

apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/LogicAppCreateStep.ts, apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/workflowDesigner/DesignerConfig.ts, apps/vs-code-designer/src/app/commands/dataMapper/DataMapperExt.ts, apps/vs-code-designer/src/app/commands/dataMapper/FxWorkflowRuntime.ts, apps/vs-code-designer/src/app/commands/dataMapper/dataMapper.ts, apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts, apps/vs-code-designer/src/constants.ts
Add app kind setting to workspace localsettings creation and update on design time api
=> fix(vscode): Add app kind setting to local settings creation and update on design time

.eslintrc.json, .husky/pre-commit, apps/vs-code-designer/src/app/utils/funcCoreTools/funcHostTask.ts, apps/vs-code-designer/src/package.json, biome.json, libs/data-mapper/src/lib/components/configPanel/SelectExistingSchema.tsx, libs/designer-ui/src/lib/card/images/dynamicsvgs/allowdroptarget.tsx, libs/designer-ui/src/lib/card/images/dynamicsvgs/blockdroptarget.tsx, libs/designer-ui/src/lib/card/images/dynamicsvgs/trafficlightsvgs.tsx, libs/designer-ui/src/lib/editor/monaco/index.tsx, libs/designer-ui/src/lib/floatingactionmenu/floatingactionmenuoutputs/index.tsx, libs/designer-ui/src/lib/monitoring/values/html.tsx, libs/designer-ui/src/lib/querybuilder/Group.tsx, libs/designer-ui/src/lib/querybuilder/Row.tsx, libs/designer-ui/src/lib/recommendation/documentationItem.tsx, libs/designer-ui/src/lib/settings/settingsection/__tests__/settingtoggle.spec.tsx, libs/designer-ui/src/lib/settings/settingsection/dictionary/simpledictionary.tsx, libs/designer-ui/src/lib/tip/index.tsx, libs/designer-ui/src/lib/tokenpicker/index.tsx, libs/designer-ui/src/lib/workflowparameters/__tests__/workflowparametersButtons.spec.tsx, libs/designer/src/lib/core/state/operation/operationSelector.ts, libs/designer/src/lib/ui/connections/dynamicsvgs/allowdroptarget.tsx, libs/designer/src/lib/ui/connections/dynamicsvgs/blockdroptarget.tsx, libs/designer/src/lib/ui/connections/dynamicsvgs/gripper.tsx, libs/designer/src/lib/ui/connections/dynamicsvgs/trafficlightsvgs.tsx, libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/connectorConnectionsCard.tsx, libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/functions.spec.ts, libs/logic-apps-shared/src/utils/src/lib/helpers/functions.ts, package.json
This pull request includes changes across multiple files, mainly focusing on code simplification, refactoring, and linting rule modifications. The most significant changes include the removal of unnecessary imports, the modification of linting rules, the simplification of array declarations, and the refactoring of function declarations.
Linting rules modification:
* [`.eslintrc.json`](diffhunk://#diff-6884918dc8291219be508e05e28965b958c734def85324f3b53858ea4702090fL88-R88): The `no-param-reassign` rule was turned off.
* [`biome.json`](diffhunk://#diff-2bc8a1f5e9380d5a187a4e90f11b4dd36c3abad6aea44c84be354a4f44cdec55L24-R52): The linter was enabled with a new set of rules.
Code simplification:
* [`apps/vs-code-designer/src/app/utils/funcCoreTools/funcHostTask.ts`](diffhunk://#diff-73ead3f0fb …
=> chore(all): Some general code clean up

apps/vs-code-designer/src/app/utils/parseJson.ts
This pull request includes a small change to the `parseJson` function in the `apps/vs-code-designer/src/app/utils/parseJson.ts` file. The change simplifies the code by eliminating the unnecessary `updateData` variable and directly manipulating the `data` parameter.
=> fix(vscode): Update data variable to fix BOM character

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240328022933807 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240328022933807 to main

Localize/loc/fr/strings.json.lcl, Localize/loc/id/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240328082323289 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240328082323289 to main

Localize/loc/es/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240328142143490 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240328142143490 to main

apps/vs-code-designer/src/app/commands/workflows/exportLogicApp.ts, apps/vs-code-designer/src/app/utils/parseJson.ts, apps/vs-code-designer/src/extensionVariables.ts, apps/vs-code-react/src/app/export/instanceSelection/instanceSelection.tsx, apps/vs-code-react/src/app/export/navigation/navigation.tsx, apps/vs-code-react/src/app/export/summary/managedConnections.tsx, apps/vs-code-react/src/app/export/summary/summary.tsx, apps/vs-code-react/src/app/export/validation/validation.tsx, apps/vs-code-react/src/app/export/workflowsSelection/workflowsSelection.tsx, apps/vs-code-react/src/run-service/export/index.ts, libs/designer/src/lib/ui/panel/recommendation/azureResourceSelection.tsx, libs/logic-apps-shared/src/designer-client-services/lib/base/connection.ts, libs/logic-apps-shared/src/utils/src/lib/models/connection.ts, libs/vscode-extension/src/lib/models/extensioncommand.ts
Cherry pick of the following PR's:
- https://github.com/Azure/LogicAppsUX/pull/4419
- https://github.com/Azure/LogicAppsUX/pull/4421
- https://github.com/Azure/LogicAppsUX/pull/4430
- https://github.com/Azure/LogicAppsUX/pull/4437
=> fix(vscode): Connections, azure resources and telemetry fixed

Localize/loc/de/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240329022413580 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240329022413580 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240329082104902 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240329082104902 to main

Localize/loc/hu/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/sv/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240329142110902 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240329142110902 to main

apps/designer-standalone/src/app/AzureLogicAppsDesigner/LogicAppSelectionSetting/AzureConsumptionLogicAppSelector.tsx, apps/designer-standalone/src/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx, apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
Implemented consumption monitoring view in standalone designer
Didn't realize we didn't already have this
=> chore(Designer): Added consumption monitoring view to standalone

apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerBase.ts, apps/vs-code-designer/src/app/utils/codeless/common.ts, apps/vs-code-designer/src/app/utils/codeless/connection.ts, apps/vs-code-designer/src/constants.ts
Cherry pick of the following PR: 
https://github.com/Azure/LogicAppsUX/pull/4519
=> fix(vscode): Implement management base URL to api hub base URL to support multiple clouds

Localize/loc/fr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240403082133507 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240403082133507 to main

Localize/loc/it/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240403203130221 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240403203130221 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/nl/strings.json.lcl, Localize/loc/pl/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/sv/strings.json.lcl, Localize/loc/tr/strings.json.lcl, Localize/loc/zh-Hans/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240404022633337 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240404022633337 to main

Localize/loc/nl/strings.json.lcl, Localize/loc/ru/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240404082325341 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240404082325341 to main

Localize/loc/pt-BR/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240404144446797 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240404144446797 to main

Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/sv/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240404202421213 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240404202421213 to main

libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
feature - to support new xml actions added in backend
=> feat(designer): Adding changes to support xml operations

Localize/loc/pl/strings.json.lcl, Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240405022131128 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240405022131128 to main

Localize/loc/cs/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/ko/strings.json.lcl, Localize/loc/ru/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240405082334584 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240405082334584 to main

Localize/loc/hu/strings.json.lcl, Localize/loc/id/strings.json.lcl, Localize/loc/ja/strings.json.lcl, Localize/loc/pt-PT/strings.json.lcl, Localize/loc/sv/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240405142446148 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240405142446148 to main

apps/Standalone/.eslintrc.cjs, apps/Standalone/package.json, apps/Standalone/src/desginer/app/AzureLogicAppsDesigner/laDesigner.tsx, apps/Standalone/src/desginer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx, apps/Standalone/src/desginer/app/LocalDesigner/customConnection/TargetPicker.tsx, apps/Standalone/src/desginer/app/LocalDesigner/customConnection/customConnectionParameterEditorService.tsx, apps/Standalone/src/desginer/app/LocalDesigner/localDesigner.tsx, apps/Standalone/tsconfig.json, apps/vs-code-designer/tsconfig.json, pnpm-lock.yaml
There were some erroring files in standalone, this should address them
=> fix(designer): Standalone Error Fixes

Localize/loc/de/strings.json.lcl, Localize/loc/es/strings.json.lcl, Localize/loc/fr/strings.json.lcl, Localize/loc/it/strings.json.lcl, Localize/loc/pt-BR/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240405202718292 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240405202718292 to main

Localize/loc/nl/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240406022415606 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240406022415606 to main

Localize/loc/zh-Hans/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240406090619913 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240406090619913 to main

Localize/loc/pl/strings.json.lcl, Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240406142830380 to main with localized lcls
=> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20240406142830380 to main

libs/designer/src/lib/core/state/selectors/actionMetadataSelector.ts
This fixes the playwright tests
=> fix(designer): Fix issue that was causing designer to crashw hen clicking on settings

.github/workflows/production-build.yml
Cherry pick of following PRs
- https://github.com/Azure/LogicAppsUX/pull/4604
- https://github.com/Azure/LogicAppsUX/pull/4603
=> meta(vscode): Fix prod build action

apps/vs-code-designer/src/README.md
Add note about automated deployment scripts being available on 4.4.2 - should go together with automated deployment script changes.
- **What kind of change does this PR introduce?** (docs update)
=> feat(vscode): Update README.md - Deployment Scripts
