- libs/data-mapper/src/lib/components/nodeCard/SchemaCard.tsx
- libs/data-mapper/src/lib/utils/Browser.Utils.ts
-Now show tooltip only over name text instead of entire card
-Only show tooltip if the name actually overflows/ellipsis's
> [DM | Schema node card] Name tooltip update

- libs/data-mapper/src/lib/core/state/DataMapSlice.ts
- libs/data-mapper/src/lib/ui/ReactFlowWrapper.tsx
- libs/data-mapper/src/lib/utils/ReactFlow.Util.ts
-Remove edge updating behavior (deprecated/removed from requirements)
-Use a hidden dummy placeholder node for ReactFlow so the initial fitView centers the entire diagram, not just the target schema (we've already been doing this with elk.js layouting with no issues, but many benefits!)
> [DM | ReactFlow] Better fitView + remove edge updating

- libs/data-mapper/src/lib/components/breadcrumb/EditorBreadcrumb.tsx
- libs/data-mapper/src/lib/components/canvasToolbox/CanvasToolbox.tsx
- libs/data-mapper/src/lib/components/targetSchemaPane/TargetSchemaPane.tsx
- libs/data-mapper/src/lib/core/state/DataMapSlice.ts
- libs/data-mapper/src/lib/ui/DataMapperDesigner.tsx
- libs/data-mapper/src/lib/utils/ReactFlow.Util.ts
It just makes sense, see the gif:
> [DM | Overview] Overview operates at "schema root" instead of schemaTreeRoot

- libs/data-mapper/src/lib/components/canvasToolbox/CanvasToolbox.tsx
- libs/data-mapper/src/lib/components/functionList/FunctionList.tsx
- libs/data-mapper/src/lib/components/functionList/FunctionListHeader.tsx
- libs/data-mapper/src/lib/components/functionList/FunctionListItem.tsx
- libs/data-mapper/src/lib/components/targetSchemaPane/TargetSchemaPane.tsx
- libs/data-mapper/src/lib/components/tree/SourceSchemaTreeItem.tsx
- libs/data-mapper/src/lib/components/tree/TargetSchemaTreeItem.tsx
- libs/data-mapper/src/lib/components/tree/Tree.tsx
- libs/data-mapper/src/lib/components/tree/TreeBranch.tsx
-This should help keep things pretty consistent and easy/quick to change - I was as careful as I could be to still keep the core Tree component pretty generic and reusable while still allowing it to be useful in both typical tree situations (such as the schema trees) and Function List type situations
-Part of this migration/swap was to move some generic, or tree-node-container scoped items, such as styles and the click handler, to the actual node container the Tree wraps the nodeComponent prop in
- @refortie You can now click the Function List header to expand it - you're welcome :)
Pics or it didn't happen (what's that - you can barely tell a difference from the way it was? That's mostly the point :P):
> [DM | Trees] Migrate Function List to Tree (from FluentV8 GroupedList)

- apps/data-mapper-standalone/src/app/DataMapperStandaloneDesigner.tsx
- apps/data-mapper-standalone/src/state/DataMapDataLoader.ts
- apps/vs-code-data-mapper-react/src/WebViewMsgHandler.tsx
- apps/vs-code-data-mapper-react/src/app/app.tsx
- apps/vs-code-data-mapper-react/src/main.tsx
- apps/vs-code-data-mapper-react/src/state/DataMapDataLoader.ts
- apps/vs-code-data-mapper/src/DataMapperExt.ts
- apps/vs-code-data-mapper/src/FxWorkflowRuntime.ts
- apps/vs-code-data-mapper/src/commands/commands.ts
- apps/vs-code-data-mapper/src/extensionConfig.ts
- apps/vs-code-data-mapper/tsconfig.json
- libs/data-mapper/src/lib/components/propertiesPane/tabs/SchemaNodePropertiesTab.tsx
- libs/data-mapper/src/lib/core/DataMapDataProvider.tsx
- libs/data-mapper/src/lib/core/index.ts
- libs/data-mapper/src/lib/core/queries/schema.ts
- libs/data-mapper/src/lib/core/services/dataMapperApiService/DataMapperApiService.ts
- libs/data-mapper/src/lib/core/services/dataMapperApiService/index.ts
- libs/data-mapper/src/lib/models/index.ts
DM VSIX now:
-Utilizes workflow-designtime API
-Deeply merges settings (no more overwriting specific local.settings.json Values{} properties configured by the user)
-Properly awaits a schema-file-not-found resolution when loading data maps (got broken by telemetry integration)
-Uses portfinder to find an open port instead of using our default of 7071 all the time
*This involved some shuffling around of where we init the DmApiService and thus make calls to GET schemaTree and GET functionManifest/List -> this probably actually did some good by eliminating some uncertainty around race conditions that previously existed in the realm of VSIX webview message-passing
**Standalone was updated to match this ^ (and was a lot less involved to do so based on how we do some things differently there …
> [DM | VSIX] Use workflow-designtime + other e2e refinements

- apps/vs-code-data-mapper-react/src/app/app.tsx
- libs/data-mapper/src/lib/components/canvasToolbox/CanvasToolbox.tsx
- libs/data-mapper/src/lib/components/functionList/FunctionList.tsx
- libs/data-mapper/src/lib/components/targetSchemaPane/TargetSchemaPane.tsx
- libs/data-mapper/src/lib/components/tree/SourceSchemaTreeItem.tsx
- libs/data-mapper/src/lib/components/tree/Tree.tsx
- libs/data-mapper/src/lib/components/tree/TreeBranch.tsx
- libs/data-mapper/src/lib/ui/DataMapperDesigner.tsx
- libs/data-mapper/src/lib/utils/Schema.Utils.ts
-Show different icon on source schema item on hover
-Auto-expand searched tree items
-Edit: Additionally, made better sense of Tree generic typings, and made some schema tree functionality changes based off new spec
-Unrelated: Swap center view height tracking to ResizeObserver API for more PropPane placement/height-ing consistency (and maybe performance/speed/snappy-ness if I'm not crazy or seeing things)
> [DM | Tree] Add isHovered render prop for nodeContent + isExpanded property on TreeNode for controlled expanded states

- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
> lafix: #1282 - Cloning action definition to avoid object mutation during deserialization

- apps/vs-code-data-mapper-react/src/app/app.tsx
- apps/vs-code-data-mapper/src/DataMapperExt.ts
- apps/vs-code-data-mapper/src/extensionConfig.ts
- libs/data-mapper/src/lib/ui/DataMapperDesigner.tsx
-Data map name is now shown in panel title (along with dirty state - filled dot text icon)
-Save a draft file of map definition (.yml) as changes are made, deleting this draft file in favor of the "actual" one once an actual save is initiated using the Save button
-Also tested MapDef draft functionality with 'Create new data map' - worked great
> [DM | VSIX | Map Definitions] Display dirty state + save drafts between actual saves

- libs/data-mapper/src/lib/__test__/MapDefinition.spec.ts
- libs/data-mapper/src/lib/utils/DataMap.Utils.ts
A current limitation is that we won't be able to support both index and conditionals on the same loop for the time being. Will be addressed later
> [Data Mapper] Move conditionals to be made on the object, not the property

- libs/data-mapper/src/lib/components/inputDropdown/InputDropdown.tsx
...by setting selectedKey to null when we change (or just start with) our controlled inputValue to/at undefined
> [DM | BUGFIX] Fix PropPane InputDropdown inner-Dropdown stale values

- libs/data-mapper/src/lib/components/schemaSelection/SelectSchemaCard.tsx
Tabbed to schema selection card:
Hitting ENTER:
Hovering the card w/ mouse (styles/look remain unaffected):
> [DM | Accessibility] Wrap SelectSchemaCards in button to get tabIndex/ENTER support

- libs/data-mapper/src/lib/ui/DataMapperDesigner.tsx
- libs/data-mapper/src/lib/ui/ReactFlowWrapper.tsx
- libs/data-mapper/src/lib/utils/ReactFlow.Util.ts
Totally not shamelessly piggybacking off @rllyy97 (Thank you! :^) )
*Tradeoff (as rllyy97 probably discovered as well) is moving the canvas' zoom to controlled state, but as the comment I left suggests, it's that, or useViewport which re-renders not only each time zoom changes, but on any sort of panning action == lag
-It does confirmed-ly adapt to the diagram as it expands (see the 5-10 ToStrings in the GIF)
-It will need to a little more fine-tuned once the Code View gets some love again (as this currently just uses the canvas width as if the CV was never open - not a huge deal though)
> [DM | Canvas] Restrict panning to certain bounds

- libs/designer/src/lib/core/parsers/addNodeToWorkflow.ts
- libs/designer/src/lib/core/parsers/restructuringHelpers.ts
- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
- Fixed a bug where the run-after setting for graph root nodes was configured incorrectly, preventing saving and returning a validation error
> labugfix: Root Node Run-After Bugfix

- libs/designer/src/lib/ui/Designer.tsx
this fixes #1378 
Keeping the behavior similar to old designer, this now shows nothing and a panel with nothing.
> labug: Empty workflow in readonly mode shows trigger addition

- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicApp.ts
- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/package.json
- Add command in package.json to be executed through command palette and azure tab context
- Register command 
- Create logic app advanced through azure tab.
- Create logic app advanced through the command palette.
- Create logic app advanced while deploying.
https://user-images.githubusercontent.com/102700317/210393206-0de89b91-73bb-4afe-a7d4-39a634c516b7.mp4
> Add Create Logic App in Advanced Mode

- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
First child of Until nodes would be disconnected if not first in the workflow.json file, root node is now order independent like the other scope nodes
---
Parameter order was reversed, now fixed to show optionals last
> laFix: Do-Until graph fix + Parameter sort fix

- libs/designer/src/lib/core/state/selectors/actionMetadataSelector.ts
Just a quick reversion of a change I made in my last operation manifest PR.
This line looked irrelevant with the checks inside the method to get the manifest, but it's actually a little different.
> laFix: Reverting an OperationManifest change

- apps/vs-code-designer/src/app/commands/deployments/redeployDeployment.ts
- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/package.json
- Add redeploy command for deployments in remote logic apps
- Couldn't use functions extension as they open a different URL
- Redeploy deployments through azure item context menu
> Add redeploy command

- libs/designer-ui/src/lib/workflow/schema/generator.ts
- Fixed an issue where operations with empty schema values would error out, now passing `{}` instead of empty string
- Fixes #1523
> laBugfix: Empty schema value catch found on `Filter Array`

- libs/designer/src/lib/core/parsers/deleteNodeFromWorkflow.ts
- libs/designer/src/lib/core/parsers/moveNodeInWorkflow.ts
Fixed an issue where deleting or moving the only child of an Until node caused nothing to happen. 
(Fixes #1520)
> laBugfix: Fixed Until only child move and delete bug

- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/app/commands/viewProperties.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/package.json
- Add command to package.json to be executed through azure item context menu
- Add logit to open the properties JSON
- Didn't use functions extension command as they have a different azure tree structure, therefore when trying to view properties it results in an error. 
- View production logic app properties through azure item context menu
- View production slot properties through azure item context menu
https://user-images.githubusercontent.com/102700317/213748532-98f219ff-8de7-4217-8e36-0e4550946676.mov
> VSFeat: Add view properties command

- apps/vs-code-designer/src/app/commands/createSlot.ts
- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/package.json
- Add delete and create command to be executed through azure item context menu
- Didn't use functions extension command as they use different approach
- Create slot through azure item context menu
- Delete slot through azure item context menu
https://user-images.githubusercontent.com/102700317/213760987-33d00b71-8986-4c59-a4d9-b0012f1a1539.mov
https://user-images.githubusercontent.com/102700317/213760952-67caeded-2655-446b-b15b-3e0d63f67a0d.mov
> VSFeat: Add create and delete slot command

- apps/vs-code-designer/src/app/commands/deployments/viewDeploymentLogs.ts
- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/package.json
- Add view deployment logs command to be executed through azure item context menu
- Didn't use functions extension command as they use different approach
- View deployment logs through azure item context menu for remote deployment
https://user-images.githubusercontent.com/102700317/213805255-35b0b0eb-f001-4a5b-8344-e133d5bc0b87.mov
> VSFeat: Add view deployments logs command

- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/app/commands/swapSlot.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/package.json
- Add swap slot command to be executed through azure item context menu
- Didn't use functions extension command as they use different approach
- Swap slot through azure item context menu for remote logic apps 
https://user-images.githubusercontent.com/102700317/214131894-2183dcc0-15c5-405f-9c73-c4a426a06a74.mp4
> VSFeat: Add swapslot command

- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/app/commands/workflows/useSQLStorage.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/package.json
- Add use sql storage command
- Use sql storage for logic app project through explorer context menu
https://user-images.githubusercontent.com/102700317/214369617-dbe9317b-3073-45a9-bf37-b24c6a794182.mov
> VSFeat: Add use sql storage command

- libs/services/designer-client-services/src/lib/base/operationmanifest.ts
The new designer is unable to load the card for the SWIFT MT Decode and Encode actions because these operations are not present in the list of supported manifests. Old designer recognizes these already and is able to display the cards.
AB#16907547
> Adding swift mt operations to list of supported manifests

- libs/designer/src/lib/core/parsers/addNodeToWorkflow.ts
- libs/designer/src/lib/core/parsers/moveNodeInWorkflow.ts
Fixes an issue where nodes placed after the workflow trigger will have incorrect run-after settings, preventing saving the workflow.
> laFix: Fixed run-after-trigger bug

- libs/data-mapper/src/lib/components/mapOverview/MapOverview.tsx
- libs/data-mapper/src/lib/components/nodeCard/SchemaCard.tsx
- libs/data-mapper/src/lib/components/schemaSelection/SchemaNameBadge.tsx
- libs/data-mapper/src/lib/ui/ReactFlowWrapper.tsx
Fixes #16943884
Also incidentally upgrades name badges to always be positioned based on source and target schemaTreeRoots on both the editing canvas and the overview
> [DM | Overview] Fix source schema name badge offset

- .versionrc
- libs/vscode-extension/package.json
The version for the vscode-extension was not getting bumped, so this just brings it up to match and adds it to the list of files to get version bumped.
> laFix: Fixed nightly release action

- .github/workflows/nightly-release.yml
Allow manual release for the nightly-builds from the actions page
> Allow manual nightly-release

- libs/data-mapper/src/lib/ui/ReactFlowWrapper.tsx
- libs/data-mapper/src/lib/utils/Layout.Utils.ts
- libs/data-mapper/src/lib/utils/ReactFlow.Util.ts
> [DM | Layouting] Stop expanded function card edges from routing past target schema nodes

- __mocks__/mapDefinitions/ComprehensiveMapDefinition.ts
- __mocks__/mapDefinitions/FullTranscriptMapDefinition.ts
- libs/data-mapper/src/lib/mapDefinitions/MapDefinitionDeserializer.ts
- libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionDeserializer.spec.ts
As a side consequence, fixes some of the (technically harmless) double generating that was going on for in-loop property conditionals
It is definitely not pretty, but it works (we can now fully deserialize both the Transcript and Comprehensive map definitions which encompass all of our currently supported scenarios). Prettification/refactoring can come later, but for this the main thing is to just have the dang thing working, so please have some mercy
> [DM | Deserialization] Support property conditionals within loops

- libs/data-mapper/src/lib/components/mapOverview/MapOverview.stories.tsx
- libs/data-mapper/src/lib/components/mapOverview/MapOverview.tsx
- libs/data-mapper/src/lib/components/nodeCard/SchemaCard.stories.tsx
- libs/data-mapper/src/lib/components/nodeCard/SchemaCard.tsx
- libs/data-mapper/src/lib/components/wholeView/WholeView.stories.tsx
- libs/data-mapper/src/lib/components/wholeView/WholeView.tsx
- libs/data-mapper/src/lib/constants/NodeConstants.ts
- libs/data-mapper/src/lib/models/Schema.ts
- libs/data-mapper/src/lib/ui/DataMapperDesigner.tsx
- libs/data-mapper/src/lib/ui/ReactFlowWrapper.tsx
- libs/data-mapper/src/lib/utils/ReactFlow.Util.ts
* Added WholeMapOverview - tentative name. No connections, no functions yet
* Reworked how widths are calculated, should hopefully be sturdier and simpler to follow
* Fixed bug in minimap node sizes
* Refactored react flow node creation to go back to using 1 method for both source and target
Before Overview:
After Overview (should be no difference):
Before Mapping:
After Mapping (should be no difference):
Whole map:
AB#17192386
> [Data Mapper] Major reworks to ReactFlow.utils.ts

- libs/designer/src/lib/core/utils/graph.ts
We were just missing a single optional, the rest of the logic was already in place to support serializing empty workflows.
Fixes #1185
> laFix: Fix for code view breaking on empty workflows

- libs/designer/src/lib/ui/connections/dropzone.tsx
Allow parallel node addition on all valid edge buttons, any edge with one parent node.
Fixes #1612
> laFix: Allow parallel node addition on all valid edge buttons

- libs/data-mapper/src/lib/components/tree/TreeBranch.tsx
- libs/data-mapper/src/lib/ui/ReactFlowWrapper.tsx
Tab nav for schema tree now works, as well as improvements in the tab nav for schema nodes. Tree nav might need to be revisited, to make sure that the interaction that we have is similar to other grouped list tab nav.
> [DM/Feature] Starting tab nav

- libs/data-mapper/src/lib/components/nodeCard/functionCard/ExpandedFunctionCard.tsx
- libs/data-mapper/src/lib/components/nodeCard/functionCard/FunctionCard.ts
- libs/data-mapper/src/lib/constants/NodeConstants.ts
- libs/data-mapper/src/lib/utils/Layout.Utils.ts
New const maxWidth for expanded function cards (should allow everything as long as ‘Direct Access’ and some to be one line still, ellipsis is just a failsafe in case we add a function out of nowhere with a ridiculously long name): *Should be no change here
Temporarily reduced width just for a screenshot to show the ellipsis:
> [DM | Expanded function cards] Set a maxWidth, and utilize in layouting

- libs/services/designer-client-services/src/lib/standard/operationmanifest.ts
Removed an unused / incorrect function call, custom connectors get their operation info from swagger, not an operation manifest service.
> laFix: Custom Connectors - Removed unused/incorrect code

- libs/designer/src/lib/core/utils/tokens.ts
- libs/designer/src/lib/ui/connections/dropzone.tsx
- Fixes #1686 
- Trigger can now be deleted and not crash when selecting a different Node
- Fixes a related issue where when the trigger is deleted all other edge buttons become hidden
- Fixes #1689 
- Callout now renders properly, was a regex issue with the edge button ID
> laFix: Trigger Deletion to Operation Selection bugfix

- libs/designer/src/lib/core/actions/bjsworkflow/connections.ts
- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
- libs/designer/src/lib/core/utils/openapi/inputsbuilder.ts
- libs/utils/src/lib/helpers/__test__/functions.spec.ts
- libs/utils/src/lib/helpers/functions.ts
Currently, loading OpenAPI actions results in a duplicated set of parameters (and the duplicates are the ones populated with any previously saved data):
This change adds proper handling for OpenAPI actions so that they are not duplicated:
- Due to an issue we had in the past, I've updated the logic from `equals()` to handle Greek and Latin letters as well
AB#17466033
> Add support for OpenAPI parameter types

- package.json
The `fuse.js` library is set as both a dependency and dev dependency, which causes Nx to get confused and not bundle it in `package.json`.
I made the change locally and did a full clean and rebuild before and after. Below is the `dist/libs/designer/package.json` content before and after.
AB#17490406
> Remove fuse.js as a dev dependency

- libs/designer/src/lib/core/utils/__test__/outputs.spec.ts
- libs/designer/src/lib/core/utils/outputs.ts
Currently, OpenAPI properties used as outputs on a trigger (which are split-on properties) are loaded with `x-ms-property-name-alias` as their leaf node name rather than their proper reference name. For example, `outputs.$.body.body/importance` is loaded as `importance` instead of `body/importance`. This means that there is a mismatch between the outputs in the schema and the tokens that are loaded into memory.
As a result, the current setup looks like this:
*(Note: The last item is an action output, not a trigger output.)*
With the fix, it looks like this:
> Fix rendering of OpenAPI token titles

- libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
Many connectors return an object matching the following shape:
```js
{
enum: {
// whole objects
{ displayName: 'Aa', value: 'a' },
{ displayName: 'Bb', value: 'b' },
},
schema: {
enum: { 'a', 'b' }, // values only
...,
},
...,
}
```
However, OpenAPI connectors return their data in the following shape instead:
```js
{
schema: {
enum: { 'a', 'b' }, // values only
'x-ms-enum-values': {
// whole objects
{ displayName: 'Aa', value: 'a' },
{ displayName: 'Bb', value: 'b' },
},
...,
},
...,
}
```
In the current implementation, these OpenAPI display name are ignored, resulting in the raw values being displayed. For example:
The changes in this pull request update the logic so that `x-ms-enum-values` is also accounted for.
The `helper.spec.ts` file has been updated with tests. These tests were …
> Fix display names of enums using 'x-ms-enum-values'

- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/services/designer-client-services/src/lib/base/index.ts
Passing operationKind in to isSupported in places where that was not done before and exporting supportedBaseManifestObjects to avoid duplicating operation manifests for shared builtins.
AB#17530575
> Minor updates to operationManifest isSupported and map export

- libs/designer/src/lib/ui/Designer.tsx
Currently, host layer has no access to the `<ReactFlow>` component to customize it. This PR adds the ability to customize the `<ReactFlow>` background via the `<Background>` component using an optional props bundle.
> Add props for host layer to add custom background

- libs/designer-ui/src/lib/editor/base/index.tsx
- libs/designer-ui/src/lib/token/inputToken.tsx
- libs/designer-ui/src/lib/tokenpicker/plugins/TokenPickerHandler.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickerheader.tsx
- libs/designer/src/lib/ui/panel/panelTabs/parametersTab/index.tsx
Bug happening because Code Editor still uses the legacy token picker button and requires a callback, forgot to include that callback with getting the tokenpicker in the parameters tab
Fixes #1767 
Also Fixes a bug that unintentionally opens the token picker on clicking a dynamic content token
> Designer Crashes when editing Javascript editor

- libs/designer/src/lib/core/index.ts
This PR exports `clearPanel` and `useSelectedNodeId` so that host services can consume them.
> Export some panel state functions

- libs/designer/src/lib/core/utils/openapi/__test__/schema.test.ts
- libs/designer/src/lib/core/utils/openapi/schema.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/validation.ts
Currently, OpenAPI parameters which do not validate (i.e., have error messages) show the incorrect display name for the parameter:
This PR updates the logic to check if there is a schema associated with the parameter first and, if so, use that schema's title or summary fields to fill in the display name. Otherwise, fall back to the current logic.
Result:
> Update parameter validation to use OpenAPI display names

- libs/services/designer-client-services/src/lib/appService.ts
- libs/services/designer-client-services/src/lib/base/connection.ts
- libs/services/designer-client-services/src/lib/connection.ts
- Fixed an issue with incorrect parameter name on interface method
- Removed an old unused `dispose` method
> laFix: Small service cleanup

- __mocks__/workflows/RunAfter.json
- libs/designer/src/lib/core/parsers/addNodeToWorkflow.ts
- libs/designer/src/lib/core/parsers/deleteNodeFromWorkflow.ts
- libs/designer/src/lib/core/parsers/moveNodeInWorkflow.ts
- libs/designer/src/lib/core/parsers/restructuringHelpers.ts
- libs/designer/src/lib/ui/settings/index.tsx
- libs/designer/src/lib/ui/settings/sections/runafter.tsx
- libs/designer/src/lib/ui/settings/sections/runafterconfiguration/runaftertrafficlights.tsx
Fixed multiple niche run-after bugs.
Should now have valid run-afters for every state of adding / moving / deleting nodes, specifically:
- Nodes that used to have no run-after settings (under a trigger or was the root of a subgraph)
- Parallel branch nodes work as expected
- Removing/Moving leaf nodes (this used to sometimes error out silently)
Should serialize exactly the same as is visible in the UX
- I think this was an issue with setting visibility, this has been adjusted
- Tested changing + saving as many configurations as I could (and verified the source issue was fixed)
- Fixes #1838
> laFix: Many RunAfter bug fixes

- libs/services/designer-client-services/src/lib/consumption/search.ts
- libs/services/designer-client-services/src/lib/standard/search.ts
- Operations are now searched one page at a time, we were not getting enough to warrant batching multiple pages at once
- This leads to much less waiting for doomed requests
- We were showing all custom connectors before, we now filter by location to show relevant connectors
> laFix: Custom Connectors - sped up operations, fixed too many connectors

- libs/designer/src/lib/core/index.ts
- package-lock.json
Currently, designer services are initialized once in BJSWorkflowProvider and stored globally. They are not re-initialized on re-mounting the component. Exporting the function for host services to re-initialize the designer services as per need.
> Export initializeServices for host services to update designer services

- __mocks__/workflows/Panel.json
- libs/designer-ui/src/lib/code/index.tsx
- libs/designer-ui/src/lib/editor/base/plugins/TokenPickerButton.tsx
- libs/designer-ui/src/lib/index.ts
- libs/designer-ui/src/lib/panel/panelcontainer.tsx
- libs/designer-ui/src/lib/panel/panelheader/panelheader.tsx
- libs/designer-ui/src/lib/panel/panelheader/panelheadertitle.tsx
- libs/designer-ui/src/lib/querybuilder/SimpleQueryBuilder.tsx
- libs/designer-ui/src/lib/querybuilder/querybuilder.less
- libs/designer-ui/src/lib/schemaeditor/index.tsx
- libs/designer-ui/src/lib/schemaeditor/schemaeditor.less
- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/ui/panel/panelTabs/parametersTab/index.tsx
- libs/designer/src/lib/ui/panel/panelTabs/scratchTab.tsx
Some Accessibility Changes Broke Code Editor, so this PR fixes it
Removed Variables/Workflow parameters from code editor #1769
There was a bug where if we rename a node from the middle of it, our cursor would move to the end of the Title, should now be fixed
The Simple Query Builder Editor (previously known as until editor) was initializing (serializing/deserializing) incorrectly, which now should be fixed
Also the query editor was supporting more than one expression token, which it shouldn't have
> LaFix: SimpleQueryBuilder Serialization + Code Editor Fixes

- libs/designer-ui/src/lib/createConnection/index.tsx
- libs/designer-ui/src/lib/createConnection/universalConnectionParameter.tsx
- libs/designer/src/lib/core/state/connection/connectionSelector.ts
- Azure Blob connection creation now displays all auth options correctly
- Fixes #1893 
- Connection dropdown parameters now start with first option selected
- Old designer required one of the options to be selected, this matches that design
> laFix: Azure Blob connector - Auth options fix

- apps/vs-code-designer-react/src/app/app.tsx
- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
- Change functions worker runtime by OS
> fix(vscode): Set functions worker runtime according to OS

- apps/vs-code-designer/src/app/commands/workflows/switchToDotnetProject.ts
- package-lock.json
Fixes #1969 
This change checks whether the target URL is provided ([when right-clicking in the folder view](https://learn.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#enable-built-in-connector-authoring)), and if not, it attempts to take the target from current workspace. Two error cases are handled - no open workspace and multiple workspaces open.
**EDIT:** I am not sure why version got bumped in package.json, but it seems like it is some sort of a commit action adding it automatically. If you want to revert the change, let me know.
> fix(vscode): Fix an issue with switching to NuGet-based project when executed from Command menu

- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
Trigger metadata was not getting deserialized properly, and saving erased that metadata.
> fix(Designer): Fixed trigger metadata serialization bug

- apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesigner.tsx
- apps/vs-code-designer-react/src/app/servicesHelper.ts
- libs/services/designer-client-services/src/lib/base/gateway.ts
- Base url is now applied to gateway requests, enabling it in VSCode and Standalone
- VSCode no longer strips gateway requests of auth
> fix(Services): Gateway service now works in VSCode/Standalone

- __mocks__/workflows/Panel.json
- libs/designer-ui/src/lib/editor/base/index.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/parameters/segment.ts
- libs/designer/src/lib/ui/panel/panelTabs/parametersTab/index.tsx
Reverted part of https://github.com/Azure/LogicAppsUX/pull/2027 because it would only work for Dictionary Editors, but cause other editorViewModel editors to crash. Should now be able to grab the token metadata before it populates the parameters
Before: 
After: 
Also Fixes #2012 
Also hiding the placeholder editor tooltip if text does not overflow
> Fix(Designer): Update Token metadata for editorviewmodel editors/ other bugs

- apps/vs-code-data-mapper/src/README.md
- apps/vs-code-designer/src/README.md
- package-lock.json
This is confusing when included in the marketplace readme. We have better and more up to date docs in our docs.
> docs(vscode): Remove development notes from readme

- libs/designer/src/lib/core/state/connection/connectionSelector.ts
Reintroducing logic that uses Operation Manifest connector data that was removed as part of https://github.com/Azure/LogicAppsUX/commit/22d6c30d7977a9fb7ef17e10095084bf9e77c1aa#diff-ea2d1be19c1bdc8a7105f83da7156578f002d4dd84fcf9cc702d6c925d280bf9. The main change is that useConnectorByNodeId will give priority to Connection Service and then fallback to Operation manifest to avoid reintroducing a regression.
> fix: add logic to fallback to connector data from Operation Manifest when Connection Service data is undefined

- libs/designer/src/lib/ui/common/LoopsPager/LoopsPager.tsx
- Add UseEffect for refetch
- Add scope and run ids for query id
- Able to display the previous/next error pager when loop scope has error
> fix(designer): Add refetch for failed iterations

- libs/designer/src/lib/core/queries/browse.ts
- libs/designer/src/lib/core/state/connection/connectionSelector.ts
- libs/designer/src/lib/ui/panel/recommendation/browseView.tsx
- libs/designer/src/lib/ui/panel/recommendation/recommendationPanelContext.tsx
When adding an action for first time all Operations and Connectors should be fetched, if there is another page to be fetched a subsequent call needs to be made to fetch that page and continue until there are no more pages to fetch.
After https://github.com/Azure/LogicAppsUX/pull/1983 this behavior regressed and only one page is fetched resulting in three network calls (1 for Azure, 1 for Custom and 1 for BuiltIn), and subsequent pages are not fetched even though there is a next link. This change fixes that regression.
Current behavior:
New behavior:
Fixes #2081
> fix(designer): ensure all operations and connectors pages are fetched on fisrt search

- libs/designer-ui/src/lib/panel/panelcontainer.tsx
- libs/designer/src/lib/core/utils/loops.ts
- libs/designer/src/lib/ui/panel/panelroot.tsx
* Validate parameters when the panel gets onBlur:
* This commit allows us to have an apply to each loop with an array token without adding a parent loop:
> fix(designer): Panel should validate params onBlur + Foreach shouldn't add another when selecting a token

- libs/designer/src/lib/core/utils/loops.ts
double array should add a nested for each by default now. However, both foreach loops use the same foreach parameter, which is not the proper behavior. The fix for that is out of scope of this revert.
> fix(designer): Revert my recent changes to `shouldAddForeach` due to double array regression

- libs/designer/src/lib/ui/Designer.tsx
- libs/designer/src/lib/ui/styles.less
fix: updating Panel z-Index so that it does not overlap external components
Panel continues to be on top of the Designer
Parameters tab:
Settings tab:
Code View tab:
Testing tab:
About tab:
Scratch tab
> fix: updating Panel z-Index so that it does not overlap external components

- libs/designer-ui/src/lib/tokenpicker/index.tsx
Need to distinguish the V3 token picker classname from V1 classname.
When we are support both V1 and V3, we are seeing [V1 styling](https://msazure.visualstudio.com/One/_git/AzureUX-BPMUX?path=/src/ui/tokenpicker/tokenpicker.less&version=GBmaster&line=55&lineEnd=58&lineStartColumn=1&lineEndColumn=32&lineStyle=plain&_a=contents) getting applied to V3 token picker.
> fix(designer): Change V3 token picker classname diff from V1

- libs/designer-ui/src/lib/dynamicallyaddedparameter/index.tsx
Bug: We were using a call to a guid() function to generate a key for the delete menu item. When the user mouses over the menu item, this causes a re-render which causes the guid() function to be called, and the menu item key to be changed -- this causes the menu to be collapsed.
Fix: This PR changes the menu item key to be a string constant. Also removes some dead code.
Before:
After:
> fix(powerautomate): Fix DynamicallyAddedParameter menu getting collapsed on mouseenter

- libs/designer-ui/src/lib/dynamicallyaddedparameter/helper.ts
- libs/designer-ui/src/lib/floatingactionmenu/index.tsx
Flow-RP expects there to be a schema object for the manual trigger when trying to save a flow. When there were no dynamic parameters added via manual trigger, this was causing flow save to fail.
This PR adds code to detect if the passed in valueSegment is empty, and creates and sets an empty schema object on it, if so.
Before:
After:
> fix(powerautomate): Return empty schema object when manual trigger editor is initially loaded

- libs/designer/src/lib/core/index.ts
Power Automate needs to use the validateParameter helper function to validate the parameters before save.
> feat(designer): Expose `validateParameter` helper function

- libs/designer-ui/src/lib/workflowparameters/workflowparametersField.tsx
- Remove `stringifyValue` function. It seems that the value is already a string, as a result JSON.stringify() was adding double quotation marks 
- Tried with all the data types
Closes #1892 
https://user-images.githubusercontent.com/102700317/235012103-d7bda150-d895-40cb-a4e9-688da258ad83.mov
> fix(designer): Remove double quotation marks in parameters panel

- libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchHeader/index.tsx
- Disable action type dropdown when is trigger node
- Show `Triggers` as placeholder for this scenario
- Remove unused lines of code
Closes #2101 
- Action type filter is disabled and with triggers option as placeholder
https://user-images.githubusercontent.com/102700317/235216055-67b06a97-2f2f-4bf5-85c7-9aadb27ca89b.mov
> fix(designer): Disable action type dropdown when is trigger node

- libs/designer-ui/src/lib/editor/base/plugins/tokenpickerbutton/index.tsx
Add Event Listener for scroll action on the side panel, so the token picker button will have updated location when the panel is scrolled.
Current behavior:
Behavior after fix;
> fix(designer): Update token picker location during scroll

- libs/designer-ui/src/lib/dynamicallyaddedparameter/helper.ts
- libs/designer-ui/src/lib/floatingactionmenu/index.tsx
Changes in this PR:
- Update serialization and deserialization of manual trigger parameters to match updated manifest (PR: https://msazure.visualstudio.com/One/_git/Flow-RP/pullrequest/8032179)
- Render parameters only if `x-ms-dynamically-added` is true -- this is set to true for all user-defined parameters (as opposed to static parameters from Flow-RP).
> fix(powerautomate): Update manual trigger serialization to match manifest and render only dynamically added parameters

- libs/designer-ui/src/lib/panel/panelheader/panelheadercomment.tsx
- Changed `createRef` implementation to `useRef` to not be updated every render. 
- `createRef` was updating/creating a new ref object every time the component was rendering. 
Close #2161 
- Focus on comment box when clickin in `Add a note`.
- Able to show tooltip when comment box is empty.
- Been able to navigate by keyboard to panel.
https://user-images.githubusercontent.com/102700317/235521326-956d1a25-a25c-4a50-86ba-dccec7fc1ce8.mov
- When changing to another node and going back to the node with a comment, comment box gets focused.
https://user-images.githubusercontent.com/102700317/235522260-9291fde8-5f89-43b6-bb61-8e4335d3cc7c.mov
- When collapse and expand panel, menu button gets focused and user is able to navigate to comment box. …
> fix(designer):  Fix focus on comment box when comment is empty

- libs/designer/src/lib/core/utils/outputs.ts
Dynamic tokens for trigger outputs have actionName in the outputInfo:
This causes the trigger outputs to get converted into @body('trigger_name') format which is invalid:
This PR fixes the issue by not setting actionName if the operation is a trigger. This makes the dynamic token show up as @triggerBody() instead:
> fix(designer): Fix expression for dynamic trigger output tokens

- libs/designer/src/lib/core/queries/connector.ts
- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
- libs/services/designer-client-services/src/lib/base/connector.ts
- libs/services/designer-client-services/src/lib/connector.ts
Removing explicit legacy dynamic call methods from connector service and having one single method since it only calls connector with connection details and parameters.
All the filtering and repsonse manipulation code is moved in the caller since it was caching incorrect data for same response but different response selectors.
> fix(designer): Dynamic content was incorrectly cached for swagger based operations

- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/utils/src/lib/models/logicAppsV2.ts
- libs/utils/src/lib/models/operationmanifest.ts
Adding new connection host type for hybrid triggers:
Connection host for hybrid triggers in existing v1:
> fix(designer): Add a new connection host enum type for hybrid trigger

- libs/designer-ui/src/lib/editor/models/parameter.ts
- libs/designer-ui/src/lib/tokenpicker/models/token.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
- libs/designer/src/lib/core/utils/loops.ts
- libs/designer/src/lib/core/utils/outputs.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/parameters/segment.ts
- libs/designer/src/lib/core/utils/parameters/tokensegment.ts
- libs/designer/src/lib/core/utils/tokens.ts
- libs/designer/src/lib/ui/panel/panelTabs/parametersTab/index.tsx
Changes -
1. On every token addition, now we correctly identify the repetition context and loopsource on the token is updated correctly.
2. We calculate repetition context for all nodes during deserialization and store it. And on every token addition we update the repetition context for that node in the store.
3. Updates made in deserialization to correctly update token metadata for item and items token based on repetition context.
> fix(designer): Adding support for items token and updating repetition context for token addition

- libs/designer-ui/src/lib/panel/panelcontainer.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/__test__/connections.spec.ts
- libs/designer/src/lib/core/actions/bjsworkflow/connections.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/state/connection/connectionSelector.ts
- libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
- libs/designer/src/lib/core/state/operation/operationSelector.ts
- libs/designer/src/lib/core/utils/swagger/operation.ts
- libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
- libs/designer/src/lib/ui/panel/panelTabs/parametersTab/index.tsx
- libs/designer/src/lib/ui/panel/panelroot.tsx
This also fixes the code paths which should not be called when operation was not loaded correctly.
fixes #2033
> fix(designer): Adding error details in panel and card when operation cannot be deserialized

- apps/vs-code-designer-react/src/app/DesignerCommandBar/index.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
Currently, skipValidation option is not used in serializer. We need a way to get the latest workflow from designer even when parameters might be empty (to undo to the previous state of workflow while user is editing). Not having skipValidation option throws an error and doesn't serialize the workflow when there are errors, eg. parameters are empty.
> fix(designer): Use skipValidation to skip throwing errors in serializeWorkflow

- libs/designer/src/lib/core/actions/bjsworkflow/__test__/initialize.mocks.ts
- libs/designer/src/lib/core/actions/bjsworkflow/__test__/initialize.spec.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
In #1721, we had prevented OpenAPI parameters from executing the code path which populated **all parameters** that had values in the step definition, even if they were dynamic. However, in #2184, this code path was reactivated.
Now, parameters with a dynamic schema that have an existing value are populated twice: once using the value, which has a complete reference key (e.g., `body/body/recipient/to`), and once from the manifest, which has a dynamic schema reference key (e.g., `body/body/recipient`). This results in two objects being shown in the parameter list.
This fix addresses the issue so that if a parameter has a dynamic schema, we do not statically populate it in the parameters list.
> fix(openapi): Fix dynamic schema params being duplicated

- apps/designer-standalone/src/app/LocalDesigner/pseudoCommandBar.tsx
- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
- libs/designer/src/lib/ui/panel/panelroot.tsx
More actions will now trigger dirty state, for allowing saving and discarding in Portal
- Updating settings
- Updating run after
- Updating action names
- Updating action comments
- Updating switch cases
- Updating static testing
Also added a pseudo save and discard button for testing dirty state in local standalone
Fixes #2248
> fix(designer): More user interactions now trigger dirty state

- libs/designer-ui/src/lib/dynamicallyaddedparameter/helper.ts
- libs/designer-ui/src/lib/floatingactionmenu/index.tsx
- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
The change is isolated to PAuto-specific editor. Adding static inputs that were added ad-hoc and dynamically in V1 to be available for use in token picker.
> fix(Power Automate): Add static inputs option to floatingactionmenu editor

- libs/designer/src/lib/core/parsers/ParseReduxAction.ts
workflow.graph is the previous graph state
deserializedWorkflow.graph is the current graph state
Passing the right parameters to the functions.
> fix(designer): pass the right parameters to respect node dimensions

- libs/designer-ui/src/lib/panel/panelheader/panelheader.tsx
> fix(designer): do not set Panel header horizontal padding when Panel is collapsed

- libs/services/designer-client-services/src/lib/standard/connection.ts
TestConnection error were not showing properly, saying 'undefined is not valid JSON', we now just pass the error object up
> fix(designer): TestConnection errors now show properly in panel

- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
Some of our built-in operations were missing icon uri's, this PR add the operation's connector icon as a fallback to catch this case.
(Azure operations are already using connector icons)
> fix(Designer): Added extra icon and brand color fallbacks

- libs/designer-ui/src/lib/monitoring/valuespanel/index.tsx
- libs/designer-ui/src/lib/monitoring/valuespanel/valuedownload.tsx
- libs/designer/src/lib/ui/panel/panelTabs/monitoringTab/inputsPanel.tsx
- libs/designer/src/lib/ui/panel/panelTabs/monitoringTab/outputsPanel.tsx
- libs/services/designer-client-services/src/lib/standard/run.ts
- Update ValuesPanel component to show the download hyperlink
- Update run service to return undefined when the size of the file is bigger than the max size of content
Closes #2323 
https://github.com/Azure/LogicAppsUX/assets/102700317/33f091a2-5910-4ccb-9dd5-6380be619da6
> fix(designer): When outputs are too large to show, monitoring view will show a download link to the file

- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
- libs/designer/src/lib/core/utils/card.ts
Recent changes to icon uri and brand color fallbacks assumed operation manifests had a connector property to read from.
Power Automate has operations without that property, this PR allows for this.
> fix(Designer): Fixed crash with manifest not having connector property 

- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
Small fix to make the setVariable use the same boolean dropdown as initialize variable
before
after
> fix(designer): Update setVariable Boolean dropdown

- libs/designer-ui/src/lib/card/card.less
- package-lock.json
Saw some dark mode styles were being overridden by their light mode counterparts.
Just had to move the dark mode styling to the bottom of the file.
> fix(designer): Small dark mode node error colors fix

- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
Unfortunately there are some scenarios where the workflowDefinition to be loaded can contain parameters that do not exist in the manifest (and should not exist).
We want to have a way for the workflowDefinition to indicate that we do not want to show these parameters or serialize them.
current behavior:
> feat(designer): Allow operations to specify unknown parameters to not be rendered or serialized

- libs/designer/src/lib/ui/panel/panelTabs/createConnectionTab.tsx
- libs/utils/src/lib/helpers/functions.ts
Our parameter "required" check for multi-auth connections was evaluating true on "false" strings, so we were getting undefined passed to the backend which was causing our connection creation errors
I made us a utils method that ensures the value be a boolean `true` or a "true" string
> fix(designer): Fixed connections passing empty non-required parameters

- libs/parsers/src/lib/common/schemaprocessor.ts
Issue was we were decoding the key when it was not encoded leading to NaN title names for something like [blah] since it was considered as index property.
> fix(designer): Fixing the output names when they have encoded properties

- .github/workflows/production-build.yml
Added branch and release type to run name for easier locating of specific runs
Ex. `Production Build - [hotfix/v2.15][patch]`
There isn't an easy way for us to get the specific version right now
// Do we have pr title tag that's not fix or feat?
> chore: Added branch and release_type to release action

- libs/designer/src/lib/core/utils/outputs.ts
Issue was the schema was incorrectly generated for relative path parameters to show other parameters in token picker.
> fix(designer): Generate relative path parameters properties correctly

- libs/designer-ui/src/lib/monitoring/requestpanel/securedatasection.tsx
- libs/designer-ui/src/lib/monitoring/valuespanel/index.tsx
Our hex parsing function was getting called directly instead of going through our safe-execution wrapper in a few places, this has been fixed to use in all instances
> fix(designer): Properly catching invalid brand color values

- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/utils/loops.ts
- libs/designer/src/lib/core/utils/setting.ts
- libs/designer/src/lib/core/utils/tokens.ts
Workflow was crashing when certain operations cannot be loaded (unresolved apiids), this was causing repetition info load failure because we always expect trigger to be loaded fine.
> fix(desinger): Fixing deserialiation when operation cannot be loaded for triggers

- libs/designer-ui/src/lib/editor/base/utils/parsesegments.ts
> fix(designer): segment values are not showing properly

- apps/vs-code-designer/src/app/commands/createNewProject/createProjectSteps/ScriptProjectCreateStep.ts
- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
- apps/vs-code-designer/src/constants.ts
- Add APP_KIND and ProjectDirectoryPath values to local.settings.json when creating a new project and when opening designer
-  Runtime local.settings.json
- Design time local.settings.json
> feat(vscode): Add APP_KIND and ProjectDirectoryPath values to settings file

- libs/designer/src/lib/core/utils/parameters/helper.ts
> fix(designer): Mark dependent parameters as valid for even output token references for dynamic call

- libs/designer-ui/src/lib/createConnection/index.tsx
Parameters with the `gateway` capability were only shown if they were optional before, on some connectors they are required and these were being filtered out.  They are now shown.
- Fixes https://github.com/Azure/LogicAppsUX/issues/2502
> fix(designer): Fixed connections with non-optional gateway parameters

- libs/designer/src/lib/common/constants.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
We will now load a normal editor if the recurrence contains any tokens, instead of showing the schedule editor.
If user has to move to older view they will have to save this value with constants and reload designer. We are not creating a hybrid schedule editor as of now.
this fixes #2531
> fix(designer): Render schedule editor only when recurrence values are literal segments

- libs/designer-ui/src/lib/token/inputToken.tsx
If we stop the propagation of the mouse click event when clicking the token delete button, this causes the click to stop at dispatching the node deletion without selecting the editor, which would made the node deletion to not actually take effect in the state of the editor until the editor is manually selected again. 
The code for stopping the propagation was to fix an old issue where the token expression would randomly show on the click of the delete button. The code has since been reworked with this is no longer needed. I tested the scenario in question, and it works without a problem.
> fix(designer): Don't stop propagation on click of the token segment delete button

- libs/designer-ui/src/lib/createConnection/index.tsx
This fixes issue with key vault connection creations
> fix(designer): Showing only multi auth connection parameters when both legacy and multi auth is present

- __mocks__/workflows/Switch.json
- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
Switch cases in legacy designer did not need to be unique before, importing one of these actions caused react flow to crash if it had a child with a duplicate name.
This change checks for duplicate names during deserialization and increments the switch case name if it detects a duplicate.
This _only_ occurs on switch cases, so there was no other work needed for tokens / run after / connection logic / etc.
On saving it will commit the unique name
> fix(designer): Preventing crash when switch cases have non-unique names

- libs/designer-ui/src/lib/createConnection/index.tsx
- libs/designer-ui/src/lib/selectConnection/index.tsx
- libs/designer/src/lib/core/queries/connections.ts
- libs/designer/src/lib/core/utils/connectors/connections.ts
fixes #2488 
The issue was user was using different resource group in their connection id that may have been created for connectors in different region. So while listing connections under that connector this valid connectionId would not be retrieved and user would see Invalid Connection issue.
We are now also trying to do a get on a connectionid, when it is not found on the list.
Two other minor fixes -
1. Do not show connection name on OAuth single auth connections
2. When connection was not found on the list while opening select connections it would automatically update to first connection, updating users action without their action.
> fix(designer): Load connection when not present in resource group

- libs/designer-ui/src/lib/createConnection/universalConnectionParameter.tsx
- libs/services/designer-client-services/src/lib/base/connection.ts
Some connections were being created with incorrect parameters because on dropdowns we were passing the `text` property of dropdown parameters instead of the `value` property.
This was brought up in an issue with the Salesforce OAuth connection creation but may have been impacting other connectors.
I also fixed the error catching messages on test connection.
> fix(designer): Fixed issue where some connection parameter dropdowns were passing name text as value

- libs/designer-ui/src/lib/editor/base/index.tsx
- libs/designer-ui/src/lib/editor/base/plugins/TokenTypeahead.tsx
fixed an issue when even when unfocusing an editor ending with '/' would still show the typeahead menu
before:
after:
> fix(designer): Unfocusing an Editor ending in '/' would still show the typeahead menu

- libs/designer-ui/src/lib/createConnection/index.tsx
- libs/utils/src/lib/helpers/functions.ts
- On the SAP connector there were connection parameters with constraints for the auth type parameter as a dependent parameter, but there was a key casing mismatch between the two
- Ex: `AuthenticationType` on the dependency definition vs `authenticationType` on the actual parameter key
- The in-app SAP connector was the only connector I've been able to see this issue on
- I just switched our dependency logic to be case-insensitive when checking for the dependent parameter
- Made this a helper function in our utils package for future use
Fixes https://github.com/Azure/LogicAppsUX/issues/2633
> fix(Designer): Fixed issue with case-insensitive dependency parameters

- libs/designer/src/lib/common/constants.ts
- libs/designer/src/lib/core/parsers/restructuringHelpers.ts
- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
- Add placeholder trigger id in constants
- Add exception for updating metadata `isRoot` property for placeholder trigger node
Fixes #2584 
After deleting the trigger and adding an action, the metadata of the placeholder trigger was set to not be a root, therefore the next added action was having the
"runAfter": {
"builtin:newWorkflowTrigger": ["SUCCEEDED"]
}
https://github.com/Azure/LogicAppsUX/assets/102700317/91e1cf48-bd06-4d12-8a50-bd0b1a3aff0f
https://github.com/Azure/LogicAppsUX/assets/102700317/cc97b458-0cde-4a35-ba64-b69eb0078578
> fix(designer): Add validation for isRoot placeholder trigger node

- libs/designer/src/lib/core/queries/browse.ts
- libs/designer/src/lib/ui/panel/recommendation/browseView.tsx
Added filtering to hide connectors in browse view that have no valid actions / triggers based on the current filtering.
Previously this was done by capability but a large amount of connectors do not have any capabilities set, so now we are determining it by if we have fetched any operations that match the connector.
You should no longer click on a browse tile and see no actions/triggers.
Fixes https://github.com/Azure/LogicAppsUX/issues/2632
> feat(Designer): Browse View - Hiding connectors with no valid actions/triggers

- libs/designer/src/lib/ui/panel/panelroot.tsx
- Add `eventBubblingEnabled` in layerProps for Panel component
Closes #2326
Tested in
- vscode for Mac
- vscode for windows
- standalone app
> fix(vscode): Copy/Paste commands in vscode for Mac

- apps/vs-code-designer-react/src/app/app.tsx
- apps/vs-code-designer-react/src/app/servicesHelper.ts
- Add getAppIdentity and isExplicitAuthRequiredForManagedIdentity callbacks in workflowService for vscode
- Add useMemo dependency
Closes #2655 
https://github.com/Azure/LogicAppsUX/assets/102700317/8d351be2-0147-49dc-84e2-fab8294c023f
> fix(vscode): Create an OAuth connection to Key vault

- apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesigner.tsx
- apps/vs-code-designer-react/src/app/servicesHelper.ts
- libs/services/designer-client-services/src/lib/base/function.ts
Adjusted functions service methods to use passed Base URL, previously the request URIs were hard coded and breaking on some environments.
As far as I could tell this was the only affected service in Mooncake.
// I've tested this live/locally in Portal + Mooncake
> fix(Designer): Fixes Mooncake function app service issue

- apps/vs-code-designer/src/README.md
- apps/vs-code-react/src/app/overview/app.tsx
- Fix image path in extension readme
- Add missing useMemo dependency
> fix(vscode): Resources image path in readme

- libs/designer-ui/src/lib/editor/base/utils/parsesegments.ts
Altered our parseHtmlSegments function for the HTML editor to use the normal lexical `createEditor` function instead of the headless version.
As far as I can tell this fixes the issue without any other negative side-effects.
Cherry-picked from https://github.com/Azure/LogicAppsUX/pull/2706
> fix(Designer): Fixed HTML editor parameter value initialization

- libs/designer-ui/src/lib/card/index.tsx
- libs/designer-ui/src/lib/card/scopeCard/index.tsx
- libs/designer-ui/src/lib/monitoring/statuspill/__test__/statuspill.spec.tsx
- libs/designer-ui/src/lib/monitoring/statuspill/index.tsx
- libs/designer-ui/src/lib/utils/utils.ts
- libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
Our `StatusPill` component was not correctly showing the full duration string in the tooltip.
This adds some extra logic to calculate the full duration string from run data.
Fixes https://github.com/Azure/LogicAppsUX/issues/2714
> fix(Designer): Monitoring - StatusPill component `duration` in tooltip 

- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/designer/src/lib/core/state/panel/panelSlice.ts
Our check for a missing trigger was depending on a redux flag for the panel that wouldn't catch all situations it needed.
I adjusted the serialization `getTrigger` method to return an empty object if it finds the placeholder trigger in state, this keeps the same behavior from before but covers the correct state scenarios.
I also fixed the `addingTrigger` state to better reflect state, but it doesn't have any logical effect at the moment after the previous change.
Fixes https://github.com/Azure/LogicAppsUX/issues/2730
> fix(Designer): Fixed trigger serialization check 

- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/designer/src/lib/core/actions/bjsworkflow/settings.ts
**Fix 1:**
The connection reference format for hybrid trigger seems to be missing the quotes around the reference key:
**Fix2:**
Currently on the v3 designer, for a manifest based operation, we default the splitOn value to be added as `"@triggerOutputs()['<property_path>']",` defaulted here:
https://github.com/Azure/LogicAppsUX/blob/c2e7189c55629b61d0f2608cdf5a3d4c75af1f1c/libs/designer/src/lib/core/actions/bjsworkflow/settings.ts#L525
But for hybridTriggers, it would need to be `"@triggerBody()['<property_path>']",`
AB#24273174
> fix(Designer): Add missing quotes around reference key for hybrid triggers

- libs/designer-ui/src/lib/arrayeditor/index.tsx
- libs/designer-ui/src/lib/combobox/index.tsx
- libs/designer-ui/src/lib/dictionary/index.tsx
- libs/designer-ui/src/lib/dropdown/index.tsx
- libs/designer-ui/src/lib/editor/base/index.tsx
- libs/designer-ui/src/lib/editor/monaco/index.tsx
- libs/designer-ui/src/lib/editor/string/index.tsx
- libs/designer-ui/src/lib/html/index.tsx
- libs/designer-ui/src/lib/picker/filepickereditor.tsx
- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
- libs/designer-ui/src/lib/table/index.tsx
- [Yes] The commit message follows our guidelines
- [N/A] Tests for the changes have been added (for bug fixes/features)
- [N/A] Docs have been added / updated (for bug fixes / features)
Bugfix to update data-automation-ids to be used by playwright tests.
data-automation-ids are not available to be consumed by tests because they are passed as props to react components and not used anywhere else.
data-automation-ids are now correctly set on DOM elements so they can be identified by playwright
* **Does this PR …
> fix(Power Automate): Correctly set data-automation-ids on DOM elements

- libs/services/designer-client-services/src/lib/base/search.ts
Fixes https://github.com/Azure/LogicAppsUX/issues/2768
We initially checked for empty value properties because with how we were requesting custom connectors and operations, backend was returning infinite nextlinks, I've tested for this behavior again and this is no longer an issue we need to adjust for.
> fix(Designer): Search requests now only rely on nextlinks, not the value length

- libs/data-mapper/src/lib/components/breadcrumb/EditorBreadcrumb.tsx
- libs/data-mapper/src/lib/mapDefinitions/MapDefinitionDeserializer.ts
- libs/data-mapper/src/lib/mapDefinitions/MapDefinitionSerializer.ts
- libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionDeserializer.spec.ts
- libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionSerializer.spec.ts
- libs/data-mapper/src/lib/utils/DataMap.Utils.ts
- libs/data-mapper/src/lib/utils/Schema.Utils.ts
- libs/data-mapper/src/lib/utils/__test__/DataMapUtils.spec.ts
Bug fix. Fixes #2592
Currently all JSON loops are also made into arrays
JSON loops will be created as normal, not as arrays.
No
> fix(Data Mapper): Fix JSON loops to not be arrays

- libs/chatbot/src/lib/ui/chatbot.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
- With our recent fix to serializing workflows without triggers, we were not handling the matching deserialization instance
- Workflows would appear to just be blank with no option to add anything
- We now add the placeholder trigger node on deserialization if there is no trigger
- Also added some catches so we don't over-initialize the placeholder node
Fixes https://github.com/Azure/LogicAppsUX/issues/2795
---
> fix(Designer): Workflows without triggers now properly deserialize

- libs/designer/src/lib/core/actions/bjsworkflow/connections.ts
- libs/designer/src/lib/core/utils/outputs.ts
- libs/utils/src/lib/models/logicAppsV2.ts
1. For deserialization of workflow, adding the HybridTrigger case to extract the connectionReferenceKey
2. For adding the SplitOn value, adding the hybridTrigger connectionReferenceKey type to get the AliasPathParsing
> fix(Designer): Add connectionReferenceKeyFormat for hybrid triggers for deserialization

- apps/vs-code-designer/src/package.json
Hello from the Azure extension team!
We are organizing the workspace `view/title` commands into submenus so that there is less clutter in the workspace menu. See https://github.com/microsoft/vscode-azureresourcegroups/blob/main/api/README.md#viewtitle-commands for more details. 
Here's what that looks like for Logic Apps:
We've done the same for all of our extensions. Here's what it looks like for Azure Functions:
AB#24363706
> feat(vscode): Organize Azure workspace commands into submenu

- libs/designer-ui/src/lib/createConnection/index.tsx
- libs/utils/src/lib/models/connector.ts
- The MySQL connector now shows all connection parameters
- We were requiring at least 2 different auth types to show multi-auth, this connector only had 1
- Reworked a bit of the capability filtering to always include cloud capability parameters
I've tested these changes on a variety of connectors with different capabilities to ensure it won't cause regressions
Fixes https://github.com/Azure/LogicAppsUX/issues/2782
> fix(Designer): Fixed filtering of cloud capability parameters

- libs/designer/src/lib/core/queries/connections.ts
With the ReactQuery fixes recently, our queries were correctly no longer fetching on each render, and this was one of the places that actually needed the frequent refetch.
I've added cache/stale time props and now it refetches connections on opening the panel like intended.
Fixes: https://github.com/Azure/LogicAppsUX/issues/2884
> fix(Designer): Select Connection panel now shows recently created connections

- .github/ISSUE_TEMPLATE/bug_report.yml
Now that standard is GA, its a little confusing to differentiate between GA designer and preview designer
We ask users to pick between GA designer and preview designer when our "preview designer" is our GA designer
Now specify its "Fallback Designer" vs "GA designer"
> chore: conditionally show dropdown designerTypes in bugreport

- libs/designer/src/lib/core/queries/connector.ts
This PR fixes issue #2927 
Bugfix
User is unable to navigate past first level of folders in folder picker
This fix restores the expected behavior of user being able to navigate folder picker and select a folder no matter how deeply nested it is.
No
After the fix, we are able to navigate to and selected a folder that's …
> fix(powerautomate): Fix results of getTreeDynamicValues call being cached unexpectedly in hotfix/v2.38 branch

- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/parsers/src/lib/models/operation.ts
- libs/services/designer-client-services/src/lib/base/manifests/terminate.ts
- Manifests can now specify values to exclude for parameter dependency
- Terminate now shows `Code` and `Message` parameters on custom values
Fixes https://github.com/Azure/LogicAppsUX/issues/2906
> fix(Designer): Terminate now shows `Code` and `Message` inputs on custom statuses

- apps/vs-code-designer/src/package.json
- Add path for the icon when is in light theme
> fix(vscode): Add logic app icon path for light theme

- apps/vs-code-designer/src/app/azuriteExtension/executeOnAzuriteExt.ts
- apps/vs-code-designer/src/app/utils/azurite/activateAzurite.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/main.ts
- apps/vs-code-designer/src/package.json
Starts Azurite via vscode extension command.
Prompts user to configure azurite.location setting if empty.
Will suggest default directory: **C:\Users\<User>\.logicapps\azurite**
User is redacted in telemetry.
The azurite location setting is saved to the Logic App Extension Global setting and then passed to the Azurite Extension scoped to Workspace only. This is so that it does not override Global.
Once enabled, this setting is configured for all Logic App Projects.
On Logic App Project open. "Enable AutoStart" proceeds to set AutoStart setting to true and prompt for location setting.
Auto Start setting "checked"
User Input - Default location: C:\Users\<User>\.logicapps\azurite
If empty, it will be the default location: …
> feat(vscode): Azurite Start & Default Location

- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/createConnectionTab.tsx
Fixed https://github.com/Azure/LogicAppsUX/issues/2953
Two instances of connection parameter `parameter?.uiDefinition.constraints` were not null-safe, and have been converted to optional references.
> fix(Designer): Fixed rare connection creation parameter null-safety issue

- libs/services/designer-client-services/src/index.ts
- libs/services/designer-client-services/src/lib/base/gateway.ts
- libs/services/designer-client-services/src/lib/base/search.ts
- libs/services/designer-client-services/src/lib/common/azure.ts
- libs/services/designer-client-services/src/lib/consumption/search.ts
- libs/services/designer-client-services/src/lib/standard/search.ts
- libs/utils/src/lib/models/subscription.ts
- Previously our subscription fetch requests were not requesting valid nextlinks
- Subscription fetch now uses the same valid nextlink logic that we use for our other calls
> fix(Designer): Fixed bug with subscription fetch request `nextlink`s

- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/services/designer-client-services/src/lib/workflow.ts
For Hybrid Triggers (HT), based on the referenced parameters from the actions, the trigger's input definition (schema property) needs to be updated to read these values during run time.
This discussion talks more on what is the issue: https://github.com/Azure/LogicAppsUX/discussions/2855
**Fix:** Added a **nullable hook** during flow serialization **as suggested** that sends the serialized definition to the host and accepts the modified definition with just the inputs of the HT being modified.
_Example scenario for the fix:_
Serialized workflow being sent to the host, the references from the actions would be used like below:
Return from the host: Only the schema properties from the trigger would be modified to use the dynamic inputs from the referenced parameters. 
Code-view of the …
> fix(designer): Add dynamic inputs for serialized workflow

- libs/designer/src/lib/core/state/connection/connectionSelector.ts
We currently have an issue where some ServiceProvider connectors are failing during connection creation when using ManagedIdentity.
This is due to us prioritizing the connector we get from operation manifests on manifest based operations, however the connector we get from the manifest is missing some data.  This led to the connection issue by the connector missing some of the connection parameters needed for Managed Identity connection creation.
This PR fixes the issue best we can on the front-end, making manifest based operations use the service call connector instead when it is a service provider operation.
> fix(Designer): Fixed issue with some MI ServiceProvider connections failing  

- libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
- libs/designer/src/lib/ui/common/LoopsPager/LoopsPager.tsx
Fixes #3016 
Actions inside nested nested loops doesn't update when parent loop changes iteration
When an actions fails the failed iterator max and min wasn't limiting the nested loop, therefore user could iterate in repetitions that didn't exist
Now when updating parent loop iteration it also updates children loops actions
For each loop …
> fix(designer): Nested loops actions update in monitoring view

- libs/parsers/src/lib/swagger/parser.ts
Added extra option on SwaggerParser to skip schema validation.
This was option was enabled in legacy designer and not carried over to new designer.
This was causing operations to fail on load that had invalid schemas, even if they still functioned fine (again this was the behavior in legacy designer). 
Fixes https://github.com/Azure/LogicAppsUX/issues/3055
> fix(Designer): Disabled operation schema validation when parsing incoming swaggers

- apps/designer-standalone/src/app/AzureLogicAppsDesigner/Services/FileSystemConnectionCreationClient.ts
- libs/services/designer-client-services/src/lib/connection.ts
- libs/services/designer-client-services/src/lib/standard/connection.ts
- package-lock.json
- **What kind of change does this PR introduce?** 
This PR adds an improvment to the current file system connection client.
When a new connection is added, the password for the app service configuration is written as palin text in the config
In this PR, we make the changes to reference the password as app settings in the configuration.
No this is not a breaking change. Existing connections will still continue to work. For new connections password will be configured in app settings.
The connection creation experience still …
> feat(designer): File system client configure password as App settings

- libs/designer/src/lib/ui/settings/index.tsx
If you opened the tracked properties it would initialize with an empty object value, that would then error out on save.
This has been fixed so that if an empty object is passed it is converted to undefined and clears out the state value.
Fixes https://github.com/Azure/LogicAppsUX/issues/3091
> fix(Designer): Fixed issue with empty Tracked Properties

- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
Previously we have always deserialized case nodes with an extra "cases" phantom operation using parameter data meant for the case operations.
Now we only deserialize to the case operation data like intended.
We will be hotfixing this into our current release as it is a regression.
This was found in our current release due to some extra pre-save validation we added.
Cherry pick of this PR https://github.com/Azure/LogicAppsUX/pull/3119
> fix(Designer): Fixed creation of phantom "cases" node input object - cherrypick release 2.55

- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
Previously we have always deserialized case nodes with an extra "cases" phantom operation using parameter data meant for the case operations.
Now we only deserialize to the case operation data like intended.
We will be hotfixing this into our current release as it is a regression.
This was found in our current release due to some extra pre-save validation we added.
Fixes https://github.com/Azure/LogicAppsUX/issues/3118
Fixes https://github.com/Azure/LogicAppsUX/issues/3117
> fix(Designer): Fixed creation of phantom "cases" node input object

- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
Operations with a retry policy setting were deserializing as normal inputs and not as settings.
Over in the initialization code we filter it out, but the dynamic data initialization did not.
Carrying that filtering over to the dynamic data init fixed the issue.
Fixes https://github.com/Azure/LogicAppsUX/issues/3133
> fix(Designer): Retry policy setting now de/serializing properly

- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/utils/src/lib/helpers/functions.ts
The value we were swapping back into our target doesn't include the rest of the parameters so it ended up overwriting information
Fixes: https://github.com/Azure/LogicAppsUX/issues/3153
> fix(designer): swapInputsLocation replacing whole input instead of only replacing source item

- libs/designer/src/lib/core/actions/bjsworkflow/connections.ts
- libs/utils/src/lib/models/connector.ts
Added support for additional audiences on Managed Identity connections
This does not replace the existing `audiences` prop on MI connections, it just adds a separate `additionalAudiences` prop
This is currently only used on the Azure Monitor Logs connector, it was needed for MI to function properly in standard
> feat(Designer): Added support for additional audiences on Managed Identity connections

- libs/designer/src/lib/core/utils/outputs.ts
Enclosing outputs merge only if `isRequestHybridTrigger` flag is set.
Here are the sample outputs that were used to test the scenarios:
https://docs.google.com/document/d/1-gPlN3IxPn5OomHG-pQKx4ASaBbSwVhUIQCSt2fFwhM/edit?usp=sharing
> fix(Designer): Ensure outputs merge only based on isRequestApiConnection FF

- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
- libs/parsers/src/lib/common/helpers/keysutility.ts
Some connectors like `Dataverse` have an alternate swagger dynamic parameter formatting.
Normally the parameter keys follow this format:
> body.$.other.parameterName
But the mentioned alternate formatting instead is as follows:
> body.$.body/other/parameterName
I've added an extra step in the parameter parsing to convert the parameter key + other data as needed so that it de/serializes the swagger dynamic parameters correctly.
Fixes: https://github.com/Azure/LogicAppsUX/issues/2920
> fix(Designer): Fixed issue with some alternate swagger-based dynamic parameter formatting

- libs/designer-ui/src/lib/createConnection/gatewayPicker.tsx
- libs/services/designer-client-services/src/lib/base/apimanagement.ts
- libs/services/designer-client-services/src/lib/base/appService.ts
- libs/services/designer-client-services/src/lib/base/function.ts
- libs/services/designer-client-services/src/lib/base/gateway.ts
Several of our Azure resource requests were not making the 'nextLink' requests when available, so requests for large amounts of resources would only return the first 100.
I've converted these resource requests to use our existing recursive request function to get all resources now.
Fixes https://github.com/Azure/LogicAppsUX/issues/3159
> fix(Designer): Modified several azure resource requests to be recursive

- libs/designer-ui/src/lib/createConnection/index.tsx
Fixed issue where OAuth was not showing on some connectors with `gateway` capability.
I'm not aware of this being of any issue within Logic Apps, but it was found in power automate and could have theoretically also impacted some of our connectors depending on how they were configured.
This has been checked against our known gateway capable connector setups.
Fixes https://github.com/Azure/LogicAppsUX/issues/3177
> fix(Designer): Fixed issue where OAuth was not showing on some connectors with `gateway` capability

- libs/designer/src/lib/ui/Designer.tsx
Very small perf fix removing unnecessary API calls
> fix(designer): Disable Browse preloading when in monitoring or readOnly view

- libs/designer/src/lib/core/utils/parameters/helper.ts
The `Initialize Variable` had a recent bug where it would not show the value field, and say there was an issue with dynamic data.
This was caused by a recent PR using our `clone()` function on a possibly undefined object.  This returns an empty object which caused issues (it was expecting it to still be null).  This PR fixes the issue.
Fixes https://github.com/Azure/LogicAppsUX/issues/3210
Will need to be hotfixed to live and staging
> fix(Designer): Fixed issue on the initialize variable action

- libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
- Fix decision on which search service is going to use.
> fix(designer): Fix search service operations

- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/validation.ts
The `inputsLocationSwapMap` can currently be used to modify the location of input parameters, however it only works for objects.
This adds support for primitives.
No
Minor minor followups to  #3197
> feat(designer): inputsLocationSwapMap manifest property to support non-objects

- libs/services/designer-client-services/src/lib/standard/run.ts
Fixes #3213 
Rendering of the inputs/outputs was failing because of a null property error
> fix(designer): Add property check for content in inputs/outputs object

- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/createConnectionTab.tsx
We had an oAuth connection setting that wasn't being sent in the initial pre-auth connection request, which was needed for a small number of connectors using oAuth, the setting has been added in this PR.
AB#25013483
> fix(Designer): OAuth - Passed redirect url value from oauth setting in connection parameters

- apps/vs-code-designer/src/app/commands/funcCoreTools/updateFuncCoreTools.ts
- Add brew constants and functions in the brew clause
- Update was failing if brew wasn't installed as it was executing brew functions
> fix(vscode): Fix check brew also when npm is package manager

- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/designer/src/lib/core/state/selectors/actionMetadataSelector.ts
- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
- libs/designer/src/lib/core/utils/swagger/operation.ts
- libs/parsers/src/lib/swagger/parser.ts
- **What kind of change does this PR introduce?** Bug fix
- **What is the current behavior?** If a swagger is provided but does not contain the expected operation ID, the entire designer crashes with the error: `Cannot read properties of undefined (reading 'description')`
- **What is the new behavior (if this is a feature change)?** In the above scenario where the swagger does not contain the expected operation ID, we fall back to the description & docs link provided before the swagger is parsed.
- **Does this PR introduce a breaking change?** No.
- Before (upon clicking "About" tab for affected connector):
- After (sanitized due to feature in progress):
AB#25043399
> fix(designer): Update 'about' tab to handle falsy property values

- libs/designer/src/lib/common/utilities/error.ts
This change adds a case to the error handling for desktop flow runs. Currently clicking running a desktop flow returns an http request with status code 202 (Accepted) and the statusRun "Running". This results in a severe warning displayed in the messageBar with the text "Accepted". This change will handle the scenario in the same way a "Succeeded" response is handled -- consistent with how we handle this in v1.
Please see [Product Backlog Item 25046387](https://msazure.visualstudio.com/One/_workitems/edit/25046387): Accepted Message Displays with Warning UI in Test Run for Desktop Flows
AB#25072667
> fix(designer): ErrorHandling - Added case to flow run error handling for flowStatus Running

- libs/designer/src/lib/ui/panel/recommendation/browseView.tsx
- libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
The designer search service function constants need to bind this before being called.
> fix(designer): bind the search operations methods

- libs/designer-ui/src/lib/expressioneditor/index.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickeroption.tsx
Our multiline editor didn't actually support multiline (Prevented users from going onto new lines unless text overflowed previous lines). This PR fixes that as well as fixing the token insertion offset/linenumber 
Fixes #3281
> fix(designer): Support Expression editor multiline

- libs/designer/src/lib/core/utils/parameters/helper.ts
Aligns behavior with V1 where the property names are lowercased
No breaking change, actions using this editor are not discoverable in production yet
> fix(designer): FloatingActionMenuOutputs editor to lowercase serialized dynamically added property names (for consistency with V1)

- .github/workflows/production-build.yml
Fixes an issue where during the production deployment action, the branch name was not appearing in the run name
Should now appear as:
> Production Build - [ hotfix/v2.34 ] - patch
> fix(meta): Fixed branch name in production build action

- libs/data-mapper/src/lib/components/configPanel/AddOrUpdateSchemaView.tsx
Bug fix
Adding new files only support .xsd or all files choices
https://github.com/Azure/LogicAppsUX/issues/3302
By default, the file extension is "Custom files" which includes .xsd and .json.
(html input element does not support any renaming or separation of "Custom files" when adding >2 extension types for supported types)
no
- **Please Include Screenshots or Videos of the intended …
> fix(Data Mapper): Browse dialog only includes .XSD and All files

- libs/designer/src/lib/core/graphlayout/elklayout.ts
Added spacing property between nodes and edges so they don't overlap.
Mostly applies to situations where a node and it's children share the same parent node
Fixes https://github.com/Azure/LogicAppsUX/issues/3347
> fix(Designer): Fixed an edge-node overlap bug

- libs/designer/src/lib/core/DesignerProvider.tsx
Prevents throwing  for MISSING_DATA error in IntlProvider. This makes it so if language/locale data is missing, we log the error and allow fallback to default language/locale, instead of failing to load the designer.
We throw the error which causes designer to not load. Screenshot below.
We log MISSING_DATA error instead of throwing, as this does not look to be a fatal error.
No.
- …
> fix(designer): Don't throw for MISSING_DATA error in IntlProvider

- libs/designer/src/lib/core/utils/swagger/operation.ts
- libs/services/designer-client-services/src/lib/base/connection.ts
When requesting connectors by connection for managed connectors, we were not correctly passing errors back to the UI.
This has been fixed, and we now also stringify the error object so it won't appear as `[Object] object`
Fixes https://github.com/Azure/LogicAppsUX/issues/3328
> fix(Designer): Fixed error bubbling on managed connector request error

- libs/data-mapper/src/lib/core/state/DataMapSlice.ts
- libs/data-mapper/src/lib/utils/Function.Utils.ts
Bug fix
The source schema nodes do not load on the initial render even if it has connections. Because the source schema nodes that have connections do not appear, it confuses the user into thinking the map has not saved properly. Once the user selects the source nodes to appear again, it shows connections.
https://github.com/Azure/LogicAppsUX/issues/3283
On the initial render, map renders the source nodes with connections. It leaves out the source nodes without connections.
- **Does this PR introduce a …
> fix(Data Mapper): not showing initial source Schema with connections

- libs/designer-ui/src/lib/searchbox/index.tsx
Added autofocus to search bar in recommendation panel
Now when users click `add node` their focus will automatically be moved to the search bar
Also verified this is announced on screen readers as well
Fixes https://github.com/Azure/LogicAppsUX/issues/3371
> feat(Designer): Recommendation panel now autofocuses to search bar

- libs/designer-ui/src/lib/combobox/index.tsx
Fix combobox filtering to use display name instead of value to have parity with v1 designer
AB#25265513
> fix(designer): Fix combobox filtering to use display name instead of value

- libs/designer/src/lib/core/utils/parameters/helper.ts
Bug fix
Validate parameter always throws error for existence of unknown parameters.
If the host is calling validate parameter on save then they can pass in the fag to the function to throw error for unknown parameters, by default it wont be throwing if called from designer code.
Yes, any host method calling "validateParameter" exported function should pass in the argument which specifies …
> fix(designer): Do not throw error on unknown parameters during validation by default

- libs/designer-ui/src/lib/floatingactionmenu/floatingactionmenuinputs/helper.ts
Fix designer load for existing hybrid triggers. The issue is that items in hybrid triggers would be serialized in the location: `inputs.schema.rows.items`, while for a flow that's saved from the v1 designer the items woudl be in `inputs.schema.items` directly.
To repro the issue: save a flow with a hybrid trigger on the v1 designer, open the same flow on the v3 designer, and click on the trigger, where you'll see an exception and everything disappearing.
AB#25323883
> fix(designer): Fix designer load for existing hybrid triggers

- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
Our previous OpenAPI format parsing was not accounting for the intermediate folder structure, i.e.
> body.$.body/content.body/content/appId
So parameters were getting parsed incorrectly with their path as 
> content.body.content.appId
It now is properly parsed to become just
> content.appId
> fix(Designer): Fixed issue with nested openapi swagger parameter format

- libs/data-mapper/src/lib/components/fileDropdown/fileDropdown.tsx
Bug fix
Users have inconsistent behavior of at times being able to paste local path to add schema panel. If this works, reloading map will crash since the schema cannot be found in Artifacts/Schema folder.
Users will not be able to paste anything to the ComboBox to prevent local path pasting.
no
n/a
AB#25434352
> fix(Data Mapper): User able to paste path directly into "Select existing"

- apps/vs-code-designer/src/app/tree/subscriptionTree/SubscriptionTreeItem.ts
Fixes #3459 
Resource tree doesn't update
> fix(vscode): Update logic app list in tree view after creating logic app in azure

- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
When the invoker connection toggle is on and then the flow is saved, the toggle turns back off.
**Existing issue:**
_**Before flow save;** User Invoker's Connection setting: **On**_
_**After flow save:**_
Setting turns back off
InvokerSetting is determined by the `impersonation` object set in the connectionReferences:
Current fix to read the `impersonation` object and determine if the setting needs to be turned on during flow save and deserialization
> fix(Designer): Invoker connection UI toggle doesn't retain after flow save

- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
Fix for #3462 
Bug fix
(When creating a new workflow) Clicking on settings tab for any action beyond the first will crash
No crash, properly cleaning up store state (workflowSlice.operations) when trigger is added and removed
No
> fix(designer): Cleanup placeholder trigger when trigger is added

- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionConfigFile.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/initLogicAppCodeProjectVScode/InitCodeProject.ts
- apps/vs-code-designer/src/app/commands/initProjectForVSCode/DotnetInitVSCodeStep.ts
- apps/vs-code-designer/src/app/commands/initProjectForVSCode/InitVSCodeStepBase.ts
- apps/vs-code-designer/src/constants.ts
- Now we recommend our logic apps extension when users have a logic app projects in a vscode workspace and don't have the extension installed, instead of the functions extension
> fix(vscode): Update recommendations for logic apps project

- libs/designer-ui/src/lib/editor/base/index.tsx
- libs/designer-ui/src/lib/editor/base/nodes/extendedTextNode.tsx
- libs/designer-ui/src/lib/editor/base/plugins/TokenTypeahead.tsx
- libs/designer-ui/src/lib/editor/base/plugins/tokenpickerbutton/index.tsx
- libs/designer-ui/src/lib/editor/base/utils/parsesegments.ts
- libs/designer-ui/src/lib/html/index.tsx
- libs/designer-ui/src/lib/querybuilder/Row.tsx
- libs/designer-ui/src/lib/querybuilder/querybuilder.less
Fixes -https://github.com/Azure/LogicAppsUX/issues/3497
Other HTML ui bugs fixed
- Text from HTML node (extendedTextNode) uncopyable
- Tokenpickerbutton not properly being offset in new lines of HTML editors
Other
- Adding a prop to also make it possible to only show the expression editor
> fix(designer): Html Editor not showing proper tokens

- libs/chatbot/src/lib/ui/panelheader.tsx
Changed Copilot tag from saying In-Development to Preview
From:
To:
> fix(Copilot): Changing In-development to Preview

- libs/designer/src/lib/ui/panel/recommendation/recommendationPanelContext.tsx
- libs/services/designer-client-services/src/lib/search.ts
Introduce new methods in the search service to help the recommendation view work without relying on prefetched data. this includes:
* `getOperationById` to help retrieve the operation by id upon click.
* `getOperationsByConnector` to help retrieve the list of operations for a specific connector, when the connector header is clicked on from the browse or search views.
The change has been smoke tested for Power Automate integration without returning any operation in the prefetch call, and completely relying on the new method callbacks.
- **What is the new behavior (if this …
> feat(designer): Add support for recommendation view to work without depending on prefetched data

- libs/parsers/src/lib/manifest/parser.ts
The hybrid trigger output in the manifest has two properties: body and headers. 
For setting the split-on we assume the outputs to have only 1 property which breaks setting spliton for hybrid triggers
Fixing this to ensure the spliton gets set even when there are more than one output properties and keeping the logic of looking for `firstKey` intact
**Without the fix,** the tokens get set with the wrong spliton and here is how the tokens get added:
> fix(Designer): Fix spliton for hybrid triggers with headers schema in outputs

- libs/data-mapper/src/lib/components/testMapPanel/TestMapPanel.tsx
bug fix
the test panel does not let users cut/copy/paste using the mouse right click context menu
the test panel lets users cut/copy/paste using the mouse right click context menu
no
- Before:
- After:
> fix(Data Mapper): Paste into test tool using right mouse click not working

- libs/designer/src/lib/core/utils/tokens.ts
- package-lock.json
Output tokens are now filtered out by their relation to other nodes with regards to the graph / loop structure in the workflow.
Ex: If a node follows a loop, tokens coming from within the loop are no longer accessible outside of the loop.
Tokens from outside of loops can still be accessed from within loops.
This filtering only applies on `For each` and `Until` graph nodes.  Things like `Switch`, `Conditional`, `Scope` are not affected.
This follows the behavior shown in legacy designer.
In the image below, previously you could access the `Current Time` node outputs which could lead to strange behavior since it could be run multiple times.  Now you can see that the `Current Time` node outputs are not accessible from the `Response` node.
> This behavior was noticed during EiPaaS feature …
> fix(Designer): Filtering out tokens that should be inaccessible by loop scope logic

- libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchHeader/index.tsx
- libs/designer/src/lib/ui/panel/recommendation/browseView.tsx
- libs/designer/src/lib/ui/panel/recommendation/operationGroupDetailView.tsx
- libs/designer/src/lib/ui/panel/recommendation/recommendationPanelContext.tsx
Remove action type filtering for where the prefetched operations is empty, given how browse would be empty otherwise. A subsequent change needed here is to have the connector details view not respect the 'actions' filter type in such case, given how there'd be no other way for users in the browse view to list triggers when trying to add actions.
> fix(designer): Remove action type filtering for where the prefetched operations is empty

- libs/chatbot/src/lib/ui/styles.less
Changing the font size and color of "Preview" and making Logic Apps logo bigger
Before:
After:
> fix(Copilot): Changing style of Preview tag

- libs/designer-ui/src/lib/tokenpicker/index.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickeroption.tsx
use getValueSegmentFromToken to get expression value of dynamic content
-fixes https://github.com/Azure/LogicAppsUX/issues/3437
> fix(designer): Token Picker Expression to use Extracted Value

- .vscode/settings.json
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/NewCodeProjectTypeStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/ProjectCodeCreateStepBase.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/SetLogicAppNameStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/ScriptProjectCreateStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createNewCodeProject.ts
- apps/vs-code-designer/src/app/commands/createNewProject/createProjectSteps/ProjectCreateStepBase.ts
- apps/vs-code-designer/src/app/commands/createNewProject/createProjectSteps/ScriptProjectCreateStep.ts
- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/iacGestureHelperFunctions.ts
- apps/vs-code-designer/src/app/utils/taskUtils.ts
- libs/vscode-extension/src/lib/models/project.ts
---
This PR introduces both a bug fix and a feature update. It improves the handling and naming of Logic App project folders and integrates a more dynamic structure for managing workspace folders and initializing git repositories in custom Logic App projects.
---
Currently, the naming convention for Logic App projects and the structure of the workspace folders are static, defaulting to "LogicApp". Additionally, the git repository initialization doesn't check if the workspace folder is already part of a git repository, leading to potential redundant initializations.
---
- **Dynamic Folder Naming**: The Logic App project folders are now named based on the user input (`context.logicAppName`). If no name is provided, it defaults to "LogicApp", if it is a custom code workspace. If it is a …
> feat(vscode): Added wizard prompt to set logic app name by User 

- .github/workflows/production-build.yml
- .versionrc
- CHANGELOG.md
- apps/vs-code-designer/src/package.json
- libs/chatbot/package.json
- libs/data-mapper/package.json
- libs/designer-ui/package.json
- libs/designer/package.json
- libs/parsers/package.json
- libs/services/designer-client-services/package.json
- libs/services/intl/package.json
- libs/utils/package.json
- libs/vscode-extension/package.json
- package.json
Seems like there was a moving of Data mapper into Vscode Designer, and our prod pipeline was referencing unused vs-code-data-mapper code. This should fix our prod build
> chore(ci): Removal of apps/vs-code-data-mapper in prod pipeline

- libs/designer/src/lib/ui/settings/settingsection.tsx
Bug fix
Error messages under editors show up, but the parameter-error element is not focusable, so the error message is not visible to keyboard users.
Error message is alerted when the element is rendered -- for reference, `msla-input-parameter-error` render happens 1) when the user initially leaves a required editor field blank, and 2) when the parameters panel is opened.
No
- **Please …
> fix(designer): Alert error messages for required editor fields

- apps/vs-code-designer/src/app/utils/funcCoreTools/funcVersion.ts
- Update permissions specifically to func core tools file executable
> fix(vscode): Update permissions to binary func file

- libs/chatbot/src/lib/ui/styles.less
- libs/designer-ui/src/lib/chatbot/chatbot.less
Making minor tweaks to dark mode in the "Preview" subheader and in the error message background color.
Before:
After:
> fix(copilot): Dark Mode Adjustments

- libs/designer-ui/src/lib/token/inputToken.tsx
Caused by https://github.com/Azure/LogicAppsUX/pull/3636 which moved FOCUS_COMMAND to CLICK_COMMAND, we do this so that it doesn't close the tokenpicker immediately after an expression is clicked
> fix(designer): Fixed an issue where when selecting an expression token opens tokenpicker

- libs/data-mapper/src/lib/components/commandBar/EditorCommandBar.tsx
bug fix
generate is disabled when save is disabled
generate xslt button is always enabled after the schemas are defined
no
> fix(Data Mapper): Reenabled Generate On Clean State

- apps/vs-code-designer/src/app/commands/createCodeless/createCodeless.ts
This pull request to the `apps/vs-code-designer` app modifies the `createCodeless` function to allow `workspaceFolder` to be either a string or an object with a `uri` property, instead of just a string.
Main code change:
* <a href="diffhunk://#diff-2635cfa991b8fa950c0b76e46d2058c2c771d27a278847b77938d7f14ce5709cL35-R35">`apps/vs-code-designer/src/app/commands/createCodeless/createCodeless.ts`</a>: The `createCodeless` function now allows `workspaceFolder` to be either a string or an object with a `uri` property.
> fix(vscode): Add validation for workspace folder path as string

- apps/vs-code-designer/src/app/utils/funcCoreTools/funcVersion.ts
This pull request to apps/vs-code-designer/src/app/utils/funcCoreTools improves the functionality of the codebase by adding a check to see if the function CLI exists before changing its permissions to 0o777 in `funcVersion.ts`.
Main change:
* <a href="diffhunk://#diff-436495b34a1c79b441856b49bb7d4d20c84e4dd38eb2d2f58aa9dae0e50c2f65R168-R173">`apps/vs-code-designer/src/app/utils/funcCoreTools/funcVersion.ts`</a>: Added a check to see if the function CLI exists before changing its permissions to 0o777.
> fix(vscode): Add validation of func command

- libs/designer-ui/src/lib/editor/base/index.tsx
- libs/designer-ui/src/lib/editor/base/plugins/FocusHandler.tsx
adding back the FOCUS_COMMAND, but separating the logic of tokenpicker into CLICK_COMMAND
> fix(designer): Fixes an issue where after inserting a token, token picker button doesn't appear 

- __mocks__/workflows/Panel.json
- libs/designer-ui/src/lib/editor/base/utils/parsesegments.ts
- libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickeroption.tsx
- libs/designer/src/lib/core/utils/parameters/__test__/segment.spec.ts
- libs/designer/src/lib/core/utils/parameters/segment.ts
- libs/designer/src/lib/core/utils/parameters/tokensegment.ts
- libs/designer/src/lib/core/utils/tokens.ts
Fixes https://github.com/Azure/LogicAppsUX/issues/3624
Fixes https://github.com/Azure/LogicAppsUX/issues/3622
I'll summarize the issue cause going through the code can be confusing, basically, there were 2 places where we ended up doing patchwork
1. parseSegment.ts - this is where we would patch it by using the segment value instead of the token value (when they should be the same thing) - the reason for this was in segment.ts/tokensegment.ts for variables and output tokens instead of passing the expressions and values respectively to set the token value, we were using name/variable name. 
2. tokens.ts - now when actions are renamed, its reflected in the tokenpicker tokens (previously we were not renaming those actions, so they would keep their original names and not be created properly)
> fix(designer): Using segment values instead of token values, which fails in the Condition Editors

- apps/vs-code-designer/src/app/utils/vsCodeConfig/settings.ts
This pull request to the `vs-code-designer` app improves the `getGlobalSetting` function in `settings.ts` by replacing the logical OR with the nullish coalescing operator to ensure that the default value is returned only when the global value is `null` or `undefined`.
Main code change:
* Replaced logical OR with nullish coalescing operator in `getGlobalSetting` function to ensure it returns default value only when global value is `null` or `undefined`.
> fix(vscode): Fix nullish setting when getting user settings

- libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickeroption.tsx
Feature
Sections of the token picker show all items no matter how many are in the section. Sections cannot be collapsed or expanded and there is no way to see how many items are in a section.
This PR is a follow-up to: #3675
This PR is also part of the following proposal: #3635
All token picker sections with more than **six** items show "See More (X)" where "X" is the count of items in that section, allowing the section to be collapsed/expanded. Behavior is not changed for expressions tab since this is already …
> feat(designer-ui): Add "See More" to all token picker sections

- libs/designer-ui/src/lib/editor/base/index.tsx
Bug fix
Text can be bolded, italicized, etc. in non-HTML editors using keyboard shortcuts. (See #3700.)
Plaintext editor is used when toolbar is not shown, preventing use of rich text. Fixes #3700.
No
It's very difficult to show, but I tried my best using keystrokes in the GIF below.
> fix(designer-ui): Prevent text formatting in non-HTML inputs

- libs/designer-ui/src/lib/html/plugins/toolbar/helper/Change.tsx
Note: I recommend viewing the changes without whitespace diff. ;)
Bug fix
There is a race condition currently in `convertEditorState`, where because `editor.update()` is not synchronous, the `return` statement actually occurs before `editor.update()` completes, meaning that you will be given back an empty array. Though this is rare, it means that `<HTMLEditor>` can end up with `value == []` during its `onBlur` call, wiping out the field contents.
This PR makes `convertEditorState` into a promise-based method, …
> fix(designer-ui): Ensure `convertEditorState` returns a non-empty value

- apps/designer-standalone/src/app/LocalDesigner/pseudoCommandBar.tsx
The `Errors` panel button now behaves as it does in portal, disabling itself when there are no errors, and enabling itself when there are
> fix(Designer): Standalone - Errors command bar button now behaves as it does in portal

- apps/vs-code-designer/src/app/commands/binaries/validateAndInstallBinaries.ts
- apps/vs-code-designer/src/app/utils/dotnet/dotnet.ts
Bug ticket: https://dev.azure.com/msazure/One/_workitems/edit/25869315
Create a custom code project.
Build the project (open integrated terminal / run dotnet build
Open logic app on designer - logic app finds the dlls and runs accordingly.
Close VS Code
Reopen VS Code with the custom project
Confirm that lib/custom folder with its contents exists
Open logic app on designer - the lib folder will be emptied and the action fails because it can't find the custom code contract.
Recording: https://clipchamp.com/watch/QGl5FTzBYjL
/
Bug fix
https://dev.azure.com/msazure/One/_workitems/edit/25869315
> fix(designer): Custom Code Workspace fix empty lib folder

- libs/services/designer-client-services/src/lib/gateway.ts
@rllyy97 & @pranaydubeymicrosoft Came to the agreement previously that the `getConfig` method will not return a promise but instead a config dictionary. This change seeks to address an inconsistency between that thought process and the interface.
https://github.com/Azure/LogicAppsUX/pull/3404/files/ae3f4d9c138c127e538f8f09217cedb4684f6954#r1350657553
This is also linked to the work done to enable OPDG dropdown for Enterprise connectors in V3 Designer for Power Automate as without it the functionality causes a build error in that PR.
https://msazure.visualstudio.com/OneAgile/_git/power-platform-ux/pullrequest/9089007?path=/packages/powerautomate-core/src/shared/models/gateways/gateway.ts
- **What kind of change does this PR …
> fix(designer): Inconsistency in IGatewayService interface

- libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchCard/index.tsx
This pull request includes a single change to the `OperationSearchCard` component in the `libs/designer-ui` library. The `data-automation-id` attribute in the component was updated to use the `id` property from the `operationActionData` object, ensuring unique and specific automation ids for each operation action.
Main change:
* <a href="diffhunk://#diff-083a65d862371639bfa34480567b11d48cc733fad9a5762c79e9333ad3e75ee7L41-R41">`libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchCard/index.tsx`</a>: Updated the `data-automation-id` attribute in the `OperationSearchCard` component to use the `id` property from the `operationActionData` object.
> test(designer): Fix automation id of search cards to be operation id so it's unique

- apps/vs-code-designer/src/app/commands/createCodeless/createCodeless.ts
Validation for workspace folder path as string
Fixes #3711 & #3734
> fix(vscode): Add validation for workspace folder path as string (#3659)

- libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickeroption.tsx
Fixes https://github.com/Azure/LogicAppsUX/issues/3437
> fix(designer): Fixes using a token in expression editor not getting correct segment value

- apps/designer-standalone/src/app/LocalDesigner/customEditorService.tsx
- libs/designer-ui/src/lib/settings/settingsection/__tests__/customTokenField.spec.tsx
- libs/designer-ui/src/lib/settings/settingsection/customTokenField.tsx
- libs/services/designer-client-services/src/lib/editor.ts
Bug fix. Addressing _CustomEditor missing readonly/disabled state_ #3788 
New behavior: pass the current `disabled` value as props to the Custom Editor. 
The new prop is additive and optional, no breaking change.
| custom editor in local designer   |
|---|
| ![laux-custom-editor-disabled](https://github.com/Azure/LogicAppsUX/assets/92312794/a4f66f19-80e8-4a6a-9788-43b9c9f5b5e4)
|
> fix(Designer): CustomEditor missing readonly/disabled state

- libs/designer/src/lib/core/BJSWorkflowProvider.tsx
This pull request to the `libs/designer` repository makes a change to the `BJSWorkflowProvider` component in the `BJSWorkflowProvider.tsx` file. The code adds an import statement for the `useDeepCompareEffect` hook and replaces the usage of `useEffect` with `useDeepCompareEffect`. This change ensures that side effects are only triggered when the dependencies have actually changed, even if they are complex objects.
* <a href="diffhunk://#diff-d5e57861a3fd496fe4efcb77979f90fa2fa7a7b25731ebd2d5ed26b81db74064R11-R13">`libs/designer/src/lib/core/BJSWorkflowProvider.tsx`</a>: Replaced the usage of `useEffect` with `useDeepCompareEffect` in the `BJSWorkflowProvider` component. <a href="diffhunk://#diff-d5e57861a3fd496fe4efcb77979f90fa2fa7a7b25731ebd2d5ed26b81db74064R11-R13">[1]</a> <a …
> fix(designer): issue where designer would constantly rerender if anything about hte window changed

- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
This pull request to the `vs-code-designer` app removes the code responsible for setting the HTML content of the webview panel and updating the panel metadata. Instead, it adds a new code block to show an information message to the user if changes were made to logic app files, instructing them to restart the designer.
Fixes #2908 
Main code changes:
* Removed code responsible for setting the HTML content of the webview panel and updating the panel metadata. Added code to show an information message to the user if changes were made to logic app files, instructing them to restart the designer.
https://github.com/Azure/LogicAppsUX/assets/102700317/85a5dc7a-368a-4b5f-a48d-78aca40ee731
> feat(vscode): Remove designer refresh and add window message

- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerBase.ts
- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
- apps/vs-code-designer/src/app/commands/workflows/unitTest/createUnitTest.ts
- apps/vs-code-designer/src/app/commands/workflows/unitTest/editUnitTest.ts
- apps/vs-code-designer/src/app/commands/workflows/unitTest/openUnitTestResults.ts
- apps/vs-code-designer/src/app/commands/workflows/unitTest/runUnitTest.ts
- apps/vs-code-designer/src/app/utils/unitTests.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/package.json
- apps/vs-code-react/src/app/designer/DesignerCommandBar/index.tsx
- apps/vs-code-react/src/app/designer/app.tsx
- apps/vs-code-react/src/state/DesignerSlice.ts
- libs/vscode-extension/src/lib/models/extensioncommand.ts
This pull request includes various changes to enhance the unit testing functionality in the `vs-code-designer` and `vs-code-react` apps. The most important changes include adding new files and functions related to unit tests, updating the `DesignerCommandBar` component to support saving unit test definitions, and adding new commands and imports for unit tests.
Main unit testing changes:
* Added new functions `saveUnitTestDefinition` and `getUnitTestName` to the `unitTests.ts` file in the `utils` folder of the `vs-code-designer` app. (apps/vs-code-designer/src/app/utils/unitTests.ts)
* Added new commands related to unit tests in the `package.json` file of the `vs-code-designer` app. (apps/vs-code-designer/src/package.json)
* Updated the `DesignerCommandBar` component to include a save …
> fix(vscode): Register unit test commands

- apps/vs-code-designer/src/app/commands/binaries/validateAndInstallBinaries.ts
This pull request modifies the error message logging and display in the `validateAndInstallBinaries` function in the `validateAndInstallBinaries.ts` file of the `vs-code-designer` app. The changes improve the user experience by showing only the error message and providing a link to troubleshooting documentation. The telemetry context is also updated to include only the error message.
Main changes:
* Modified error message logging and display in the `validateAndInstallBinaries` function to show only the error message and provide a link to troubleshooting documentation. Updated the telemetry context to include only the error message.
> fix(vscode): Add troubleshoot dependencies message

- libs/designer-ui/src/lib/tokenpicker/tokenpickerpivot.tsx
This pull request includes a single change in the `libs/designer-ui/src/lib/tokenpicker/tokenpickerpivot.tsx` file. The change sets the color of the pivot styles to `#323130`.
Fixes #3826 
Main change:
*  Set the color of the pivot styles to `#323130`.
> fix(designer): Add default text color for token picker pivot

- apps/vs-code-designer/src/app/commands/appSettings/getLocalSettingsFile.ts
- apps/vs-code-designer/src/app/commands/workflows/configureWebhookRedirectEndpoint/configureWebhookRedirectEndpoint.ts
- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
- apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForLocal.ts
- apps/vs-code-designer/src/app/commands/workflows/openOverview.ts
- apps/vs-code-designer/src/app/commands/workflows/switchDebugMode/switchDebugMode.ts
- apps/vs-code-designer/src/app/commands/workflows/useSQLStorage.ts
- apps/vs-code-designer/src/app/debug/validatePreDebug.ts
- apps/vs-code-designer/src/app/utils/azurite/activateAzurite.ts
- apps/vs-code-designer/src/app/utils/codeless/connection.ts
- apps/vs-code-designer/src/app/utils/codeless/parameter.ts
- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
- apps/vs-code-designer/src/app/utils/dotnet/dotnet.ts
- apps/vs-code-designer/src/app/utils/funcCoreTools/funcHostTask.ts
- apps/vs-code-designer/src/app/utils/verifyIsProject.ts
- apps/vs-code-designer/src/app/utils/vsCodeConfig/tasks.ts
- apps/vs-code-designer/src/app/utils/vsCodeConfig/verifyVSCodeConfigOnActivate.ts
- apps/vs-code-designer/src/app/utils/workspace.ts
This pull request to `apps/vs-code-designer` replaces occurrences of the function `getFunctionProjectRoot` with `getLogicAppProjectRoot` and `tryGetFunctionProjectRoot` with `tryGetLogicAppProjectRoot` in multiple files. This change reflects a change in terminology and ensures the correct function is used in the logic app context.
> refactor(vscode): Update functions name to get logic app project in vscode

- libs/data-mapper/src/lib/core/state/Store.ts
fix #3507 
- can undo adding initial schemas
- undo is disabled until adding both of the schemas and making an action
> fix(Data Mapper): Disabled allowing undo add schema

- libs/data-mapper/src/lib/components/configPanel/SelectExistingSchema.tsx
- libs/data-mapper/src/lib/components/fileDropdown/fileDropdown.tsx
fix for #3724 
doesn't display error messages for failing loading schema
displays error messages for failing loading schema
> fix(Data Mapper): Display Error Message for Failing Schema Load

- host.json
- workflow-designtime/host.json
This pull request removes the `host.json` and `workflow-designtime/host.json` files used for configuring the Azure Functions host and the workflow design-time host. The removed content includes the version of the host and the extension bundle information. These files are only used in Logic Apps project. Removing these as our repo is not a Logic App project
Main change:
* Removed the `host.json` and `workflow-designtime/host.json` files used for configuring the Azure Functions host and the workflow design-time host.
> refactor(repo): Remove unused host.json files

- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
This pull request includes an update to the `startDesignTimeApi` function in `startDesignTimeApi.ts` file. The update modifies the value of `settingsFileContent.Values[ProjectDirectoryPath]`.
Fixes #3863 
Main change:
* Updated the `startDesignTimeApi` function to modify the value of `settingsFileContent.Values[ProjectDirectoryPath]`.
> fix(vscode): Fix project path in workflow-designtime folder

- apps/designer-standalone/src/components/LocalizationSettings.tsx
- libs/services/intl/src/IntlProvider.tsx
We had indonesian translated, however we weren't using it. This should enable it to be used
> fix(localization): Adding Indonesian as a language to intl provider

- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/setMethodName.ts
This pull request to `apps/vs-code-designer` adds a new method `validateFunctionName` to the `setMethodName` class in `setMethodName.ts`. This method checks if the function name is empty or invalid and returns an error message if so. It is used as the `validateInput` function for the `showInputBox` method in the `shouldPrompt` method.
Fixes #3830 
Main change:
* Added a new method `validateFunctionName` to the `setMethodName` class.
> fix(vscode): Add validate input for function name in workspace creation

- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/parsers/src/lib/common/constants.ts
Reverts Azure/LogicAppsUX#3782
> fix(designer): Revert change "tokens with 'body/value' should use triggerBody rather than triggerOutput"

- apps/vs-code-designer/src/app/commands/workflows/unitTest/runUnitTest.ts
- apps/vs-code-react/src/app/designer/app.tsx
- apps/vs-code-react/src/state/DesignerSlice.ts
- libs/designer/src/lib/core/BJSWorkflowProvider.tsx
- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/mockResultsTab/mockResultsTab.tsx
- libs/utils/src/lib/models/unitTest.ts
This pull request includes various changes to different files in the codebase. The most important changes include adding a new interface `UnitTestDefinition` to the `libs/utils/src/lib/models/unitTest.ts` file, updating the `BJSDeserializer.ts` file to accept a `UnitTestDefinition` object as a parameter, and updating the `BJSWorkflowProvider.tsx` file to accept a `UnitTestDefinition` object or `null` as a prop.
Main interface changes:
* Added a new interface `UnitTestDefinition`.
* Updated the `BJSDeserializer.ts` file to accept a `UnitTestDefinition` object as a parameter in the `deserializeUnitTestDefinition` function. 
* Updated the type of the `unitTestDefinition` prop in `BJSWorkflowProviderProps` to accept a `UnitTestDefinition` object or `null`.
Other important changes:
* Added a …
> feat(vscode): Update unit test definition for vscode deserialization

- libs/designer-ui/src/lib/querybuilder/Row.tsx
- libs/designer-ui/src/lib/token/inputToken.tsx
We were having an issue where the tokens deleted weren't focusing the editor after deletion, causing the blurring not to happen, causing serialization to never happen
> fix(designer): Changes not serializing when token deleted without editor being focused

- libs/designer/src/lib/core/state/designerOptions/designerOptionsInterfaces.ts
- libs/designer/src/lib/core/state/designerOptions/designerOptionsSlice.ts
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
Modfified the designerOptionsInterface to accept suppressCastingForSerialize as optional and add it to parametersTab.
The cast no longer appears in the Power Automate V3 desginer.
> feat(designer): enable support prevent casting in complex array editors

- .github/workflows/Deploy-Documentation.yml
- .github/workflows/compile-loc.yml
- .github/workflows/production-build.yml
- .github/workflows/test.yml
- package.json
This pull request includes updates to the Node.js and npm versions in various files to require a minimum Node.js version of 18 and npm version of 9. The most important changes include updating the Node.js version in the `jobs` section of `.github/workflows/production-build.yml` and updating the Node.js versions in the `matrix` section of `.github/workflows/test.yml`.
Main version updates:
* <a href="diffhunk://#diff-20fbc76be4bae1652559385109766d3a3a185d70ae392c77fab423e41f5b6b16L62-R65">`.github/workflows/production-build.yml`</a>: Updated the Node.js version in the `jobs` section from 16 to 20. <a href="diffhunk://#diff-20fbc76be4bae1652559385109766d3a3a185d70ae392c77fab423e41f5b6b16L62-R65">[1]</a> <a href="diffhunk://#diff-20fbc76be4bae1652559385109766d3a3a185d70ae392c77fab423e41f5b6b1 …
> chore: Bump minimum node version to 18 and move official build version to 20

- apps/logic-apps-ux-docs/docs/intro.md
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
This pull request includes changes to improve the code and documentation. The most important changes include updating the `visible` property of an object in a TypeScript file and updating the required version of Node.js in the documentation.
Code changes:
* Updated the `visible` property of the `monitoringTabItem` object in `usePanelTabs` to `isMonitoringView` instead of `!isScopeNode && isMonitoringView`, and removed the `isScopeNode` variable from the function.
Documentation changes:
* Updated the required version of Node.js in the documentation to v18 or higher.
> fix(designer): Update condition on when to render monitoring view

- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
This pull request includes a change to the `getOrCreateDesignTimeDirectory` function in the `startDesignTimeApi.ts` file. The change adds a check to handle a specific case where the `designTimeDirectory` is already part of the `projectRoot`.
Main change:
* Added a check in the `getOrCreateDesignTimeDirectory` function to handle a specific case where the `designTimeDirectory` is already part of the `projectRoot`.
Fixes #3827
> fix(vscode): Add validation for design-time folder

- apps/vs-code-designer/src/app/commands/funcCoreTools/validateFuncCoreToolsIsLatest.ts
The change adds a new line of code to call the `setFunctionsCommand` function after installing the Func Core Tools binaries. Otherwise, the func executable will not have set the right permission until the user reloads vscode
* Added a new line of code to call the `setFunctionsCommand` function after installing the Func Core Tools binaries.
> fix(vscode): Add set function core tools command right after installing an update

- libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
The scratch tab was being shown in production builds due to its visibility check not being carried over properly in the panel refactor that was done recently.
This PR just adds that visibility check back in, hiding the tab in production builds.
> fix(Designer): Re-added the scratch tab visibility check

- libs/designer-ui/src/lib/panel/recommendationpanel/searchResult.tsx
- libs/designer/src/lib/core/queries/browse.ts
- libs/designer/src/lib/core/state/panel/panelSlice.ts
- libs/designer/src/lib/ui/panel/recommendation/browseView.tsx
- libs/designer/src/lib/ui/panel/recommendation/recommendationPanelContext.tsx
- libs/utils/src/lib/helpers/stringFunctions.ts
Fixes https://github.com/Azure/LogicAppsUX/issues/3924
In Azure `(stage)` locations, the operation search flow was not showing any operations that were not local to the project.
This has now been fixed, the operation search flow now operates as it should in `(stage)` locations
I've also fixed a few other small search panel related bugs
> fix(Designer): Fixed search issue in (stage) locations

- libs/parsers/src/lib/swagger/parser.ts
- package-lock.json
Fixes #3940 by adding extra option on SwaggerParser to skip spec validation.
This was causing errors in new designer for swaggers that were failing validation even if they still functioned correctly.
By adding this new parameter in the validation, it allows the swaggers to pass validation and the app to continue running.
Very similar fix to this previous fix: https://github.com/Azure/LogicAppsUX/pull/3066
> fix(consumption): Disabled Spec Validation for incoming Swagger

- libs/designer/src/lib/ui/Designer.tsx
Added another check to our search preloading so that it doesn't batch with the rest of our requests in Portal.
**This shaves off about 4~5 seconds of waiting** on each initialization in most cases, since it was including the first heavy operation request with all of the node initialization requests, so we wouldn't show nodes as initialized until that request was returned.
We had this feature a while back but was removed when the batch API  was going through changes because it actually sped things up at the time.  After the batch api reverted most of those changes we didn't revert ours.
I'm embarrassed I didn't notice this sooner
---
> feat(Designer): Search preload is now delayed until nodes are initialized

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
Create connection button appearance changed back to primary.
(Was a regression with the connection panel refactor)
> fix(Designer): Create connection button appearance to primary

- Localize/lang/strings.nl.json
- Localize/loc/nl/strings.json.lcl
- libs/services/intl/src/compiled-lang/strings.nl.json
Loc fix for #3972.
`{methode}` is not a valid interpolation:
Fixed interpolation.
No.
N/A
> chore: Fix `{methode}` in Dutch language

- libs/designer-ui/src/lib/editor/base/index.tsx
- libs/designer-ui/src/lib/html/index.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/Toolbar.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/HTMLChangePlugin.tsx
Bug fix
Users are able to switch to Lexical WYSIWYG view in raw HTML editor, even if their raw HTML is not supported by Lexical. #3857 
The "toggle code view" button is disabled if the user is in plaintext editor mode and the plaintext HTML is not supported by Lexical.
No
> fix(designer-ui): Prevent users from switching to WYSIWYG view if raw HTML is not supported

- libs/designer-ui/src/lib/editor/base/utils/editorToSegment.ts
- libs/designer-ui/src/lib/editor/base/utils/parsesegments.ts
Bug fix.
Note: I tried to add tests but if there is an infinite loop, Jest doesn't ever stop executing, and using mocks to stop the test early didn't yield useful results.
If `@{` is entered into the HTML editor, the designer freezes. See discussion entries here: #3996 
The above will not freeze the designer.
No
N/A
> fix(designer-ui): Prevent designer freezing when `@{` is typed into HTML editor

- libs/designer-ui/src/lib/editor/base/utils/parsesegments.ts
Bug fix
If `<br>` (or any HTML entity) is used in an expression token, it will be consumed by the Lexical DOM parser, and thus the token mapping will not properly substitute the token.
See screenshots.
No
Before:
After:
> fix(designer-ui): Prevent expression `<>`s from being parsed by DOM parser

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/_test__/createConnection.spec.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
Fix for #4004 _Connection fields are duplicated and invalid for connector with Credentials support (Desktop Flow)_
**Checklist**
* Type of change: Fix.
* Breaking change: No.
* Docs have been added / updated: N/A. 
**Change description**
The issue is only applicable when using Credentials annotations in connector definition - only Power Automate Desktop Flow is concerned.
The connection parameter component is using the react `key` props as the parameter key used in the create connection payload. 
The code path using Credentials may default to the default parameters (non-credentials), but then passed another `key` value. Consequently, the payload did not contain the expected values for these parameters.
This PR fixes this inconsistency by passing the right "parameter key" to the `key` …
> fix(Designer): wrong parameter key for CreateConnection with Credentials enabled

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/_test__/createConnection.spec.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
- libs/services/designer-client-services/src/lib/connectionParameterEditor.ts
**Checklist**
* Type of change: fix.
* Breaking change: no.
* N/A. Docs have been added / updated (for bug fixes / features)
**Changes**
_Current behavior:_ the custom editor for Credentials mapping (connections parameters) is not disabled while the panel is in loading state.
_Fix:_ pass the `isLoading` props to the custom component so it can handle it and be disabled during the loading.
> fix(Designer): pass isLoading props to custom CredentialsMappingEditor component

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/_test__/createConnectionWrapper.spec.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnectionWrapper.tsx
This is a proposed fix for _Missing "value" property in create connection JSON payload_ #4011
**Checklist.**
* Type of change: Fix.
* Breaking change: No.
* N/A. Docs have been added / updated (for bug fixes / features)
**Change description**
Issue: #4011 _Missing "value" property in create connection JSON payload_ 
The lack of `value` property is due to the serialization from JS to JSON when no actual parameter value was present (`value: undefined`). This is the case for connectors with parameters with ui definition annotations as _required_ and _hidden_.
> undefined, Function, and Symbol values are not valid JSON values. If any such values are encountered during conversion, they are either omitted (when found in an object)
> -- …
> fix(Designer): fix missing property in create connection payload JSON

- libs/designer-ui/src/lib/html/plugins/toolbar/helper/__test__/util.spec.ts
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/util.ts
Bug fix
Strings with `<a>` or `<u>` in them are valid in Lexical, but the current checker code does not support them and so users cannot switch from raw editor to rich editor if their strings contain one of these tags.
Strings with `<a>` or `<u>` in them are considered valid when switching to Lexical.
No
Before:
After:
> fix(designer-ui): Indicate Lexical support for `<a>` and `<u>` tags

- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
Adding a new swagger-based trigger will now initialize with proper outputs and tokens.
It looked like we were initializing outputs for triggers with split-on defined during workflow load, and only for manifest-based operations when adding new triggers.  This was just a missed case.
Fixes https://github.com/Azure/LogicAppsUX/issues/4009
> fix(Designer): Fixed split-on data bug when adding new trigger

- libs/designer/src/lib/common/constants.ts
- libs/designer/src/lib/core/actions/bjsworkflow/settings.ts
- libs/designer/src/lib/core/utils/outputs.ts
Fixing bug where V3 triggers chosen from the on-create trigger selection wizard are created with SplitOn off by default.
New behavior loads as on by default:
> fix(designer): Split On is off by default in V3

- libs/designer/src/lib/ui/styles.less
Bug fix
Due to a bug in #3557, styling w/ left panel was broken, causing collapsed left panel to overlap mini-map controls.
Mini-map controls are now visible.
No
**Before**
**After**
> fix(designer): Prevent collapsed left panel from hiding minimap

- apps/vs-code-designer/src/app/utils/bundleFeed.ts
Fixes semver unable to validate a foldername as a version.
> Fix(VSCode): Validate foldername

- libs/designer-ui/src/lib/connectorsummarycard/connectorsummarycard.less
- libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchCard/operationSearchCard.less
https://github.com/Azure/LogicAppsUX/assets/13208452/7d75f55a-ee50-4932-bed4-cb91e1fa3003
This pull request includes changes to the `operationSearchCard.less` file in the `libs/designer-ui` library. The changes primarily focus on improving the visibility of focus outlines on elements to enhance accessibility.
* [`libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchCard/operationSearchCard.less`](diffhunk://#diff-3be4d70dbd9f99e1cae7bcb90ee822dce51f3611cfa521633f8defa44e8ba7ddL18-R18): The focus outline has been changed from having no outline to a 1px solid outline with the color #605e5c. This change improves the visibility of the focus state on elements.
* [`libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchCard/operationSearchCard.le …
> fix(designer): Add focus border to search cards for keyboard nav

- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
Fixed a schema parameter parsing issue **_in standard_**.
Parameters marked as required are now shown as required.
Continuation of this PR https://github.com/Azure/LogicAppsUX/pull/3941
Will potentially be hotfixing to release branches
> fix(Designer): Fixed APIM required parameter issue in Standard

- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/actions/bjsworkflow/settings.ts
- libs/designer/src/lib/core/parsers/ParseReduxAction.ts
- libs/designer/src/lib/core/utils/loops.ts
- libs/designer/src/lib/core/utils/outputs.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/swagger/operation.ts
The `Split-On` setting is now disabled for stateless workflows.
Stateless workflow triggers have no split-on values with this change, essentially defaulting to the previous "off" state.
Fixes https://github.com/Azure/LogicAppsUX/pull/4053
> fix(Designer): Split on is now disabled for stateless workflows

- apps/designer-standalone/src/app/SettingsSections/contextSettings.tsx
- apps/designer-standalone/src/state/workflowLoadingSlice.ts
- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/actions/bjsworkflow/settings.ts
- libs/designer/src/lib/core/parsers/ParseReduxAction.ts
- libs/designer/src/lib/core/state/designerOptions/designerOptionsInterfaces.ts
- libs/designer/src/lib/core/utils/loops.ts
- libs/designer/src/lib/core/utils/outputs.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/swagger/operation.ts
- libs/designer/src/lib/ui/panel/nodeSearchPanel/nodeSearchPanel.tsx
- libs/designer/src/lib/ui/panel/panelRoot.tsx
- libs/designer/src/lib/ui/panel/recommendation/recommendationPanelContext.tsx
Added designer host option to force enable split-on.
Recently we added a change that disabled split-on automatically on stateless workflows, which caused a regression in PA since they are all stateless but still use split-on.
When this option is set to `true`, the split-on setting will appear as normal on stateless workflows
Fixes https://github.com/Azure/LogicAppsUX/issues/4091
> fix(Designer): Added host option to force enable split-on

- libs/services/designer-client-services/src/lib/base/connection.ts
Adjusted our connection test request function to not run the request through batch.
During my investigation, running some connector test requests through batch would fail _specifically_ when going through the batch api, with no other changes in the request.
We have a catch over in the portal httpClient where if a request has any explicit headers set, it will not go through batch, so I've just added a dummy header for now.
Fixes https://github.com/Azure/LogicAppsUX/issues/3781
> fix(Designer): Changed test connection request to not run through batch api

- libs/services/designer-client-services/src/lib/base/connection.ts
- libs/utils/src/lib/helpers/connections.ts
Added more logic to avoid checking uniqueness on connection names that are already known.
This avoids some edge cases that would lead to us checking lots of known connection ids and making connection creation feel very slow.
**TLDR: Connection creation should feel much faster in some situations**
> fix(Designer): Added connection name check to avoid known connection name strings

- libs/designer/src/lib/core/utils/parameters/helper.ts
Add a nullcheck to prevent parameters that are not dependent from being added to the payload for update.
This fixes a bug whereby the Trello create a card action in Power Automate would fail. Currently, .[*] wildcard parameters missing the id field will cause updateParameterAndDependencies to fail. The result is that the value is never set in the designer. 
With fix:
> fix(Designer): Skip non-dependent parameters in updateParameterAndDependencies

- libs/designer/src/lib/core/BJSWorkflowProvider.tsx
- libs/designer/src/lib/core/state/designerOptions/designerOptionsInterfaces.ts
- libs/designer/src/lib/core/state/designerOptions/designerOptionsSelectors.ts
- libs/designer/src/lib/core/state/designerOptions/designerOptionsSlice.ts
- libs/services/designer-client-services/src/lib/base/connection.ts
Added a catch to not load graph state until after the host options are available in redux.
Was just a race condition that wasn't accounted for.
Added explicit hooks for `useAreDesignerOptionsInitialized` and `useAreServicesInitialized`
> fix(Designer): Added catch for designer options race condition

- libs/designer/src/lib/core/actions/bjsworkflow/settings.ts
Bug fix
Currently, stateless workflows in LAUX do not support split on, but do in PAuto. A host option was added to allow this behavior, but does not cover `settings.ts:getSplitOn()`.
Stateless workflows in PAuto will return the correct value from `settings.ts:getSplitOn()`.
No
N/A
> fix(designer): Fix stateless workflow check in `getSplitOn`

- libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
Bug fix
In OpenAPI, when a trigger outputs a token of the format `outputs.$.body.Title` or `outputs.$.body/Title`, this is inserted into the workflow as `@triggerOutputs()?['Title']`, which is not valid.
**Before:**
**After:**
> fix(designer): OpenAPI tokens from SharePoint trigger use `triggerOutputs` instead of `triggerBody`

- apps/vs-code-designer/src/app/commands/deploy/deploy.ts
- apps/vs-code-designer/src/app/tree/slotsTree/SlotsTreeItem.ts
- apps/vs-code-designer/src/app/utils/codeless/connection.ts
- package-lock.json
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...) Fixed deploy/create commands for slots
- **What is the current behavior? Deploy to slot, deploys to production slot only.  Create slot doesn't enable system identity.
- **What is the new behavior (if this is a feature change)? Deploy slot allow to select or create slot for deployment.  Create slot enables system identity for non-production slot.
- **Does this PR introduce a breaking change?** No
> fix(vscode): enable slot create/deploy extension commands.

- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerBase.ts
The changes primarily simplify the handling of resolved connections by removing unnecessary parsing and error handling.
The key changes are:
* The `connectionsData` is now directly resolved and assigned to `this.connectionData`, eliminating the need for parsing and error handling. The `resolvedConnections` variable is now of type `ConnectionsData`, which is directly assigned to `this.connectionData`. Previously, `resolvedConnections` was parsed into `parsedConnections` inside a try-catch block, and `parsedConnections` was then assigned to `this.connectionData`. This change simplifies the code and reduces the risk of errors by removing the parsing and error handling step.
Fixes #3987
> fix(vscode): Parse interpolated connections data as JSON

- libs/designer/src/lib/ui/panel/panelRoot.tsx
The changes include the introduction of a resizable panel feature and the addition of new styles and dependencies.
* Introduced state variables `isResizing` and `width` to manage the resizing process. Also, added `startResizing` and `stopResizing` functions to control the resizing state.
* Added a `resize` function to handle the resizing process and attached it to the `mousemove` event. The `mouseup` event is attached to the `stopResizing` function. Both event listeners are cleaned up in the `useEffect` hook.
* Modified the `Panel` component to support the new resizable feature and added a new `div` element which triggers the resizing process on `mousedown` event. 
* Minimum size is 300px
https://github.com/Azure/LogicAppsUX/assets/102700317/f5baef75-dfed-438b-a55e-3532e9c13298
> feat(designer): Resizable side panel

- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/azureScriptWizard.ts
- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
- apps/vs-code-designer/src/package.json
The changes aim to streamline the codebase, improve the user experience, and enhance the maintainability of the code. 
* Removed unnecessary imports and the `SaveAzureContext` class. The `createAzureWizard` function no longer requires the `projectPath` parameter, and the `SourceControlPathListStep` class has been changed from a prompt step to an execute step. The `ConfigureInitialLogicAppStep` class now includes a `showLoadingPrompt` property. 
* The `callStandardApi` function no longer requires the `scriptContext` parameter. The `callConsumptionApi` function and the `callManagedConnectionsApi` function have been updated to use `localSubscriptionId` and `localResourceGroup` instead of `subscriptionId` and `resourceGroup`. The `gatherAndValidateInputs` function now always launches the …
> fix(vscode): Remove update local.settings.json and api calls in deployment scripts

- libs/designer/src/lib/core/utils/outputs.ts
For hybrid triggers, the output tokens come from one of the three scenarios:
1. Floating action menu
2. Entity outputs/dynamic outputs
3. Header schema
We need to merge all three outputs for it to be available in next actions.
Issue: Currently after flow save, the schemaToReplace has a "properties" parent object and hence during the merge is adding an additional "properties" object inside one. This is causing a bad merge and hence the floating action menu tokens aren't being generated.
Fix: Merge the "rows" object based on where it's present.
> fix(designer): Fix the token merge for FAM and entity outputs for hybrid triggers

- apps/vs-code-designer/src/app/commands/createNewCodeProject/createNewCodeProject.ts
- apps/vs-code-designer/src/app/utils/binaries.ts
- apps/vs-code-designer/src/package.json
The most significant changes involve the removal of the `showPreviewWarning` function from `createNewCodeProject.ts` and the removal of the "preview" status from several features in `package.json` and `binaries.ts`.
* The `showPreviewWarning` function was removed and its functionality was moved to the `createNewCodeProjectInternal` function. The `extensionCommand` was added to the import statement from `../../../constants`. 
* The "preview" label was removed from the message in the `promptInstallBinariesOption` function.
* The "preview" status was removed from several features, including the "Validate and install dependency binaries" and "Reset binaries dependency settings" commands, and the "autoRuntimeDependenciesPath" and "autoRuntimeDependenciesValidationAndInstallation" settings. The …
> feat(vscode): Remove preview flags for onboarding experience

- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/actions/bjsworkflow/settings.ts
As the node initialization happens in the designer today, the spliton that's used to generate the output token keys from the manifest is either retrieved from the manifest or explicitly null. this causes the token outputs to ignore spliton and assume it's off when spliton is yet to be computed, causing the node dependency keys to be incorrect.
> fix(designer): fix spliton token references for newly added triggers

- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerBase.ts
The changes focus on improving the handling of connections data and reducing the risk of errors during the parsing process.
* Replaced the direct parsing of `connectionsData` with a conditional parsing. Now, `connectionsData` is parsed only if it's not an empty string, otherwise an empty object is used. This change reduces the risk of JSON parsing errors when `connectionsData` is an empty string.
Fixes #4151
> fix(vscode): Add validation for no connections

- libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
New behavior for handling of OpenAPI tokens was added in #4122. However, this turned out to be only a surface-level "mitigation" in that it did not address the root cause of the issue. The root cause was fixed in #4148. Therefore, with that fix, I am reverting the new behavior that was added in #4122 which is no longer needed.
> fix(designer): Removed new OpenAPI token behavior added in #4122

- libs/designer/src/lib/core/utils/parameters/helper.ts
- package-lock.json
Added an operation parameter sort case that makes parameters with data that depends on other parameters always come after the parameter it sources data from.  This overrides sorting by visibility which was causing the parameters to be out of order previously
Fixes: https://github.com/Azure/LogicAppsUX/issues/3900
> fix(Designer): Operation parameters are now sorted by their dependent parameters

- apps/vs-code-designer/src/app/commands/deploy/deploy.ts
- apps/vs-code-designer/src/app/tree/slotsTree/SlotsTreeItem.ts
- apps/vs-code-designer/src/app/utils/codeless/connection.ts
Fixed deploy/create commands for slots
- **What is the current behavior? Deploy to slot, deploys to production slot only.  Create slot doesn't enable system identity.
- **What is the new behavior (if this is a feature change)? 
Deploy slot allow to select or create slot for deployment.  Create slot enables system identity for non-production slot.
- **Does this PR introduce a breaking change?**
No
> fix(vscode): Enable create/deploy slot commands

- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
- libs/parsers/src/lib/common/schemaprocessor.ts
- libs/services/designer-client-services/src/lib/base/apimanagement.ts
##Main Changes
Fixed issue causing schema body parameters to not appear as required.
Parameters marked as required do not render as required if their parent in their path (like body) isn't also required.
With APIM, in Portal the body param isn't able to be set as required, which was causing this issue.
With this change, dynamic data parameters now render as required when the schema is defined as required, and on APIM schemas specifically I've added a check to make `body` required if it has required parameters (since you can't do it yourself in portal).
> fix(Designer): Fixed issue causing schema parameters to not appear as required

- apps/vs-code-designer/src/app/commands/binaries/resetValidateAndInstallBinaries.ts
- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/app/utils/binaries.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/onboarding.ts
- apps/vs-code-designer/src/package.json
This pull request primarily focuses on setting the opt-in as default for binaries installation.
- Reset binaries -> set the auto installation as true and binaries settings path to undefined
- Disabled binaries -> set the auto installation as false and binaries settings path to undefined
- Binaries settings paths are set later in logic.
* A new function `disableValidateAndInstallBinaries` has been added to disable the auto validation and installation of binary dependencies.
* The `promptInstallBinariesOption` function has been renamed to `installBinaries` and its install always installs the binaries unless the setting is set to true.
* The default value for the `autoRuntimeDependenciesValidationAndInstallation` setting has been changed from `null` to `true` in `package.json`.
> feat(vscode): Binaries dependencies opt-in  by default

- apps/vs-code-designer/src/package.json
The change modifies the condition for the `azureLogicAppsStandard.deploySlot` command to exclude matches that end in an 's'. This negative lookahead assertion ensures that the deploy action is not shown in the Slots tree item.
> fix(vscode): Remove deploy slot action to only slot and not slots tree item

- apps/designer-standalone/src/app/AzureLogicAppsDesigner/Utilities/Workflow.ts
- apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesigner.tsx
Removed resolving app settings within connection parameters during initialization.
Previously we treated app settings like we do workflow parameters, where we resolve them to get their actual values.
This caused issues when app settings held key-vault values, since we can't and shouldn't resolve key-vault values in Designer.
Currently, dynamic data requests made by sending the key-vault value doesn't get resolved and the request fails.
Now that we keep the app-setting values as-is, the request backend evaluates both the app-setting and the key-vault for us.
> fix(Designer): Removed resolving app settings within connection parameters during initialization

- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/parsers/addNodeToWorkflow.ts
Bug fix
If an empty switch block is loaded into designer, it will break the panel, and cannot have any cases added to it.
Above are fixed and behave as expected.
Context: `subOperation` could be `undefined`, and so `Object.keys()` call would fail. Also, use of `any` prevented the `cases == undefined` case from being type-checked.
No
- **Please Include Screenshots or Videos of the …
> fix(designer): Fix two places where `undefined` switch `cases` caused fatal errors

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/_test__/createConnection.spec.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnectionWrapper.tsx
- libs/services/designer-client-services/src/lib/connection.ts
- libs/services/designer-client-services/src/lib/standard/connection.ts
Following the update of the connection creation API in [this PR](https://msazure.visualstudio.com/One/_git/PowerApps-PowerApps-RP/pullrequest/9399971), it is now possible to pass a credential id in the call.
This PR updates the `ConnectionCreationInfo` contract to pass additional properties.
This field will be leverage in the caller to read the selected credential id, when used.
This update will be used in the Power Automate portal to create a connection with the passed credential id (in [this PR](https://msazure.visualstudio.com/OneAgile/_git/power-platform-ux/pullrequest/9531232))
- **What kind of change does this PR introduce?**
The `ConnectionCreation` component is passing a `setParameterValues` callback to the credential …
> feat(designer):  [ConnectionCreation] Adding hidden parameter field in ConnectionCreationInfo to pass selected credential id

- libs/designer-ui/src/lib/arrayeditor/util/serializecollapsedarray.ts
- libs/designer-ui/src/lib/arrayeditor/util/util.ts
- libs/designer-ui/src/lib/authentication/util.ts
- libs/designer-ui/src/lib/dictionary/util/serializecollapseddictionary.ts
- libs/designer-ui/src/lib/editor/base/utils/__test__/editorToSegment.spec.ts
- libs/designer-ui/src/lib/editor/base/utils/editorToSegment.ts
- libs/designer-ui/src/lib/editor/base/utils/parsesegments.ts
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/HTMLChangePlugin.tsx
Bug fix
If a token containing `}` is added to the HTML editor, it will disappear: #4195
Tokens are now properly retained even if they contain a `{`. Note: If a token contains `@{`, it may have issues with parsing.
Closes #4195.
I don't think so, though a lot of internal signatures have changed to make `nodeMap` non-optional.
- **Please Include Screenshots or Videos of the intended …
> fix(designer-ui): Retain tokens inserted into HTML editor if they contain `}`

- apps/vs-code-designer/src/onboarding.ts
This pull request includes a change to the `startOnboarding` function in the `onboarding.ts` file of the `vs-code-designer` app. The change removes the call to `onboardBinaries` within this function. This function is already called in the installBinaries function.
> fix(vscode): Remove double onboarding binaries validation

- apps/vs-code-designer/src/app/commands/dataMapper/FxWorkflowRuntime.ts
- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
The changes involve the addition of a new function `updateProjectPath` and its subsequent usage in different parts of the codebase. Furthermore, the `createJsonFile` function has been refactored to remove the merging of new settings into an existing file.
* Imported the `updateProjectPath` function and used it in `startBackendRuntime` to update the project path in the settings file. 
* A new function `updateProjectPath` has been added. This function updates the project path in a settings file located in a given directory.
* The `createJsonFile` function has been refactored to remove the merging of new settings into an existing file. Instead, the function now only writes the provided content to the file if the file does not already exist. A detailed comment has been added to explain the …
> fix(vscode): Fix total overwriting of host and local settings JSON files

- libs/designer/src/lib/core/BJSWorkflowProvider.tsx
- libs/designer/src/lib/core/state/workflow/workflowInterfaces.ts
- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
- libs/designer/src/lib/core/utils/workflow.ts
Split on settings are now visible again in Consumption workflows
Fixes: https://github.com/Azure/LogicAppsUX/issues/4194
Workflow kind on Consumption workflows was being set to stateless, causing split on to be disabled.
Consumption passes in `undefined` as it's kind, and that value is now kept instead of being overwritten.
> fix(Designer): Fixed Consumption split on issue

- apps/vs-code-designer/src/app/commands/workflows/switchDebugMode/StatelessWorkflowsListStep.ts
- apps/vs-code-designer/src/app/commands/workflows/switchToDotnetProject.ts
- apps/vs-code-designer/src/app/commands/workflows/unitTest/createUnitTest.ts
- apps/vs-code-designer/src/app/utils/codeless/common.ts
- apps/vs-code-designer/src/app/utils/workspace.ts
- apps/vs-code-designer/src/package.json
This pull request primarily focuses on refactoring the hard-coded 'workflow.json' filename to use a constant, `workflowFileName`, across various files in the `apps/vs-code-designer` directory. This change improves code maintainability and consistency. Additionally, there are changes in the `createUnitTest.ts` file to enhance the unit test creation process by prompting the user to select a workflow if one is not provided. 
* Replaced the hard-coded 'workflow.json' filename with the `workflowFileName` constant.
* Several changes were made to enhance the unit test creation process. If a workflow node is not provided, the user is now prompted to select a workflow. Additional utility functions were also added to support this feature.
https://github.com/Azure/LogicAppsUX/assets/102700317/45e9404 …
> feat(vscode): Create unit test via command palette

- libs/services/intl/src/IntlProvider.tsx
This pull request includes a significant change to the `loadLocaleData` function in the `IntlProvider.tsx` file. The modification ensures that any strings with a key that has symbols get compiled to be in the default object rather than exported individually as a module.
* [`libs/services/intl/src/IntlProvider.tsx`](diffhunk://#diff-24a037dcc98b8383728091c7c66ee17595ceba2c85fd61594bd3145f6b4d0006L75-R77): Modified the `loadLocaleData` function to compile any strings with a key that has symbols into the default object. This change prevents these strings from being exported individually as a module, thus improving the organization and accessibility of the strings.
Before:
After:
> fix(designer): Fix issue where some strings wouldn't be localized in azure portal and power automate

- libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
- libs/designer/src/lib/core/utils/outputs.ts
- libs/designer/src/lib/core/utils/tokens.ts
We were updating the outputs of dynamic data calls; however, the already existing parameters were no updated with the proper titles. This fixes the issue to get those updated Token Titles
Fixes https://github.com/Azure/LogicAppsUX/issues/4132
Before: 
After:
> fix(designer): Update Existing Input Parameters For Subsequent Actions Once Dynamic Data is Fetched

- libs/designer/src/lib/ui/common/LoopsPager/LoopsPager.tsx
- libs/services/intl/src/IntlProvider.tsx
- libs/utils/src/lib/helpers/__test__/functions.spec.ts
- libs/utils/src/lib/helpers/functions.ts
This pull request primarily focuses on improving the functionality of the `LoopsPager` component in the `libs/designer/src/lib/ui/common/LoopsPager/LoopsPager.tsx` file. The changes include the introduction of a new function to find the previous and next failed pages, a modification to the sorting of failed repetitions, and adjustments to the handling of failed iteration properties. ALastly, the `FindPreviousAndNextPage` function was tested in `libs/utils/src/lib/helpers/__test__/functions.spec.ts` and implemented in `libs/utils/src/lib/helpers/functions.ts`.
Improvements to `LoopsPager`:
* [`libs/designer/src/lib/ui/common/LoopsPager/LoopsPager.tsx`](diffhunk://#diff-b8a3966d76571aa606548b1b1b08a6f8442a55647ccb04bbf3cc006f3adfb330L9-R10): Imported the `FindPreviousAndNextPage` function …
> fix(designer): Fix issue in run history page where loops pager would only go to first error when clicking next failure

- libs/designer/src/lib/ui/settings/sections/general.tsx
This pull request primarily focuses on updating the `General` component in the `libs/designer/src/lib/ui/settings/sections/general.tsx` file. The changes revolve around the introduction of a new `useNodeMetadata` hook and the use of a new `isTrigger` variable to modify the behavior of the `CustomValueSlider` setting.
* [`libs/designer/src/lib/ui/settings/sections/general.tsx`](diffhunk://#diff-a97ce766b7f4a0ed6117256aa57522a701295e9f8a30bec0686207a5060ddd7fL4-R4): Imported the `useNodeMetadata` hook from the `../../../core` module. This new hook is used to fetch metadata for a specific node.
* [`libs/designer/src/lib/ui/settings/sections/general.tsx`](diffhunk://#diff-a97ce766b7f4a0ed6117256aa57522a701295e9f8a30bec0686207a5060ddd7fR47-R50): Introduced a new …
> fix(designer): Seperate values of degree of parallelism for triggers and actions

- apps/vs-code-designer/src/app/commands/workflows/unitTest/createUnitTest.ts
- apps/vs-code-designer/src/app/commands/workflows/unitTest/editUnitTest.ts
- apps/vs-code-designer/src/app/utils/unitTests.ts
This pull request introduces several changes to the `apps/vs-code-designer` package to improve the handling and creation of unit tests. The changes include the addition of a unit test name validation function, the modification of the `createUnitTest` and `editUnitTest` functions to improve user prompts and workflow selection, and the addition of a function to retrieve a list of unit tests in a local project.
*  Modified the `createUnitTest` function to validate the unit test name and to use the `projectPath` in the `pickWorkflow` and `getWorkflowsPick` functions. 
* Modified the `editUnitTest` function to prompt the user to select a unit test file if one is not provided and to use the `projectPath` in the `pickUnitTest` and `getUnitTestPick` functions.
* Added the `validateUnitTestName` …
> feat(vscode): Add edit unit test from command palette

- libs/logic-apps-shared/src/utils/src/lib/helpers/functions.ts
Adjusted the comparison in our deep compare util method to account for arrays, was previously comparing by reference on non-objects which was causing failures.
This led to arrays that had the same information returning as not equal, which made us skip over existing connection references and making a new one for each action with a MI connection.
Stringifying then comparing will give us a proper comparison for any data type in this util function.
(This is the only instance we use this function as well, so I'm not worried about any other side effects)
Will be hotfixing this into our staging release we started earlier today.
Should be live by March 8th.
> fix(Designer): Fixed connection reference bug for MI connections

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/_test__/createConnection.spec.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnectionWrapper.tsx
- libs/services/designer-client-services/src/lib/connection.ts
- libs/services/designer-client-services/src/lib/standard/connection.ts
This reverts commit 2d43902c95b9eeb9ec9536939309c3224431e8e9.
@adboillo We are reverting this https://github.com/Azure/LogicAppsUX/pull/4193 as the change causes issue when creating connections for service provider.
I think mainly the main issue is here libs/services/designer-client-services/src/lib/standard/connection.ts with the `...optional('additionalParameterValues', additionalParameterValues),`
Fixes #4264
> fix(designer): Revert - Adding hidden parameter field in ConnectionCreationInfo to pass selected credential id (#4193)

- .github/workflows/production-build.yml
- .versionrc
- libs/data-mapper/src/lib/__test__/intl-test-helper.tsx
- libs/designer-ui/src/lib/__test__/intl-test-helper.tsx
- libs/designer/src/lib/__test__/intl-test-helper.tsx
- libs/logic-apps-shared/jest.config.ts
- libs/logic-apps-shared/package.json
bug fix
mainly fixed deployment script to use new library
no
> fix(Designer): fixed some scripts related to moving libs

- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/package.json
This pull request primarily focuses on improving error handling in the `generateDeploymentScripts.ts` file and updating command titles in the `package.json` file of the `vs-code-designer` application. The most significant changes include the addition of a `COMMON_ERRORS` constant, modifications to error handling in `generateDeploymentScripts.ts`, and updates to the titles of several commands in `package.json`.
* Added a check for a specific error message (`COMMON_ERRORS.OPERATION_CANCELLED`) in the `generateDeploymentScripts` and `gatherAndValidateInputs` functions. If this error is encountered, a localized error message is thrown. 
* Added a `COMMON_ERRORS` constant to handle common error messages. This constant is used in the error handling logic in `generateDeploymentScripts.ts`.
* …
> fix(vscode): Add error handle scenario for operation cancelled

- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
- apps/vs-code-designer/src/main.ts
The changes revolve around the `downloadExtensionBundle` function. The function was removed from `startDesignTimeApi.ts` and added to `main.ts`, changing the location and timing of when the extension bundle is downloaded.
These changes suggest a shift in the strategy for handling extension bundles, moving the download operation from a later stage (`promptStartDesignTimeOption`) to an earlier stage (`activate`) in the application lifecycle.
> feat(vscode): Download extension bundle in extension activation instead of project initialization

- libs/designer-ui/src/lib/modals/DeleteNodeModal.tsx
- libs/designer/src/lib/ui/common/DeleteModal/DeleteModal.tsx
This PR fixes the fact that the discard pop up message doesn't display the updated node name if the node name has been changed. Now, we define the node name in the DeleteModal.tsx file and pass it down through the props so that when the node name is updated, this is correctly displayed in the discard pop up.
Fixes #4277
> fix(Consumption): Adding node name to props to account for change

- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/azureScriptWizard.ts
- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
- apps/vs-code-designer/src/app/utils/taskUtils.ts
- apps/vs-code-designer/src/constants.ts
This pull request includes changes to improve user input validation and error handling in the Azure Script Wizard and related components. The most important changes include adding input validation to the Azure Wizard prompts, reordering the title property in the Azure Wizard creation, and refactoring error handling across multiple methods. 
User input validation:
* Added input validation to ensure the logic app name, storage account name, and App Service plan name cannot be empty in the `setLogicappName`, `setStorageAccountName`, and `setAppPlantName` classes respectively. 
* Refactored error handling in multiple methods. The refactoring includes removing the usage of `handleError` method, logging the error messages directly to the output channel, and throwing new errors with the error …
> fix(vscode): Fix error handling and displaying and add input validations

- apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesigner.tsx
- libs/designer/src/lib/core/queries/connections.ts
- libs/designer/src/lib/ui/Controls.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnectionWrapper.tsx
- libs/logic-apps-shared/src/utils/src/lib/helpers/connections.ts
We currently have issues saving service provider / built-in connections if there are also managed api / azure connections of the same connector name in the same logic app.  This is now fixed and service provider connections are now saved with proper references.
This was happening because our service provider connections were getting saved with the name as the reference key.  This doesn't cause issues normally because with service provider connections the name normally matches the key, but in the case that a MAPI connector shares the name (ex. sql) it will leave the name as `sql` and the reference might become `sql-1` or `sql-2`.  Then during save it saves with a reference to `sql` which is the MAPI connection instead of the service provider connection.
Fixes …
> fix(Designer): Fixed issue where connection references would sometimes overlap

- apps/vs-code-designer/src/app/commands/workflows/exportLogicApp.ts
- apps/vs-code-react/src/app/export/export.less
- apps/vs-code-react/src/app/export/status/status.tsx
This pull request primarily focuses on improving the user feedback during the workflow export process in the VS Code Designer and React applications. The changes include adding success messages in the `ExportEngine` class, updating the status rendering in the React application, and adding new styles for the status items.
* Added success messages in the `ExportEngine` class to inform the user when the workflows are exported successfully. These messages are added in two places, once when the resource group name is not provided or the template does not exist, and once after the parameters and settings are updated.
* Updated the `renderStatus` function to include an icon and a spinner for the status items. The spinner is shown for the last item if the final status is not 'Succeeded'. Also, …
> feat(vscode):  Improve status step indicator for export experience

- libs/data-mapper/src/lib/components/canvasControls/CanvasControls.tsx
- libs/designer-ui/src/lib/editor/base/plugins/tokenpickerbutton/index.tsx
- libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchHeader/index.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickerheader.tsx
- libs/designer/src/lib/ui/Controls.tsx
- libs/designer/src/lib/ui/connections/dropzone.tsx
- libs/designer/src/lib/ui/menuItems/copyMenuItem.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
- libs/designer/src/lib/ui/settings/sections/runafterconfiguration/runafterActionSelector.tsx
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature (logging)
**What is the current behavior?** (You can also link to an open issue here)
N/A
**What is the new behavior (if this is a feature change)?**
Logging has been added for:
- Minimap controls (zoom, etc.)
- Copy & paste
- Add parallel branch
- Connector filtering in search panel
- "Run After" selection (no PII, just action count)
- Token picker open, close
- Token picker header buttons
- Expression editor expression insertion (no PII)
**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No
**Please Include Screenshots or Videos of the intended change**:
> feat(designer): Add verbose telemetry for a number of scenarios

- apps/vs-code-designer/src/package.json
The changes mainly involve the standardization of the naming convention for logic app-related commands and descriptions. The previously used title case has been replaced with sentence case.
* The title of the command "Create Logic App in Azure..." has been changed to "Create logic app in Azure...". Similar changes have been made to the titles of other commands related to logic apps, including "Create Logic App in Azure... (Advanced)", "Delete Logic App...", "Convert to NuGet-based Logic App project", and "Use SQL storage for your Logic App project". The description of the default version of the Azure Functions runtime has also been updated to use sentence case.
> fix(vscode): Update command titles

- libs/designer-ui/src/lib/card/subgraphCard/index.tsx
- libs/designer-ui/src/lib/card/subgraphCard/subgraphCard.less
- libs/designer/src/lib/ui/CustomNodes/SubgraphCardNode.tsx
Adding parameter error messaging to the subgraph scope nodes. This is the only type of error that subgraph nodes can have since all other types of errors are handled at the scope level. Before, there would only be error messaging in the node panel itself and in the errors command bar panel but now it will display a message in the subgraph node itself, how it does for other nodes. 
Before:
After:
> fix(consumption): Adding 'Invalid Parameter' message to Subgraph nodes

- libs/designer-ui/src/lib/card/scopeCard/index.tsx
- libs/designer-ui/src/lib/card/scopeCard/scopeCard.less
- libs/designer/src/lib/core/actions/bjsworkflow/move.ts
- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
This PR includes many minor UI fixes to both scope nodes and subgraph nodes. Here is a list of all those changes:
1. We now show a note icon in the card footer when there is a note added to a scope node. For this we first needed to pass the note down through props and then adjust the display so it matched the current display on the operation nodes.
2. We removed the 'Add a node' button option from subgraph nodes since users cant add notes to this type of node. For this we had to check if the node was a subgraph node and not include the 'Add a note' option for those cases. Now they only have the 'Delete' option
3. Scope nodes had the old loading spinner but now it has been updated to match the current operation node spinner but in the 'inverted' style.
4. When you move a node and the panel …
> fix(Consumption): Multiple minor changes to scope and subgraph nodes

- libs/logic-apps-shared/src/parsers/lib/manifest/parser.ts
only include root outputs if explicitly set in the manifest.
Fixes https://github.com/Azure/LogicAppsUX/issues/3967
> fix(desinger): Remove Outputs if includeRootOutputs is not set

- libs/designer/src/lib/ui/panel/recommendation/recommendationPanelContext.tsx
Fixed issue where some service provider operations would not appear in search / browse.
This was due to our deduplication of operations was solely dependent on operation ids, but service provider operation ids do not have their connector / api in the id to help differentiate. 
I've adjusted the uniqueness check to account for api ID as well as operation id.
Fixes https://github.com/Azure/LogicAppsUX/issues/4343
> fix(Designer): Fixed issue where some service provider operations would not appear in search / browse

- apps/designer-standalone/src/app/AzureLogicAppsDesigner/Utilities/Workflow.ts
- apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesigner.tsx
Reverts the following commit: https://github.com/Azure/LogicAppsUX/commit/4ba6a0c76ef7ec8a3b37803b8b4fafbdb5e73b9f
Connections with app settings in certain parts of the connection were causing issues during initialization with the following change.
> fix(Designer): Reverted app settings resolve change

- apps/vs-code-designer/src/app/commands/parameterizeConnections.ts
- apps/vs-code-designer/src/app/utils/codeless/parameterizer.ts
This pull request primarily focuses on enhancing the parameterization of connections in the VS Code Designer application. The main changes include the addition of a function to check if connections are already parameterized, and the subsequent use of this function in the `parameterizeConnections` command. 
* A new function `isConnectionsParameterized` is added. This function checks if the connections data is already parameterized by examining various connection types and their properties. If any connection is found to be parameterized, the function returns `true`.
* Before parameterizing connections, the `parameterizeConnections` command now checks if the connections are already parameterized using the `isConnectionsParameterized` function. If they are, it shows an information message and …
> fix(vscode): Implement function to determine if connections have been already parameterized

- libs/designer/src/lib/core/utils/parameters/helper.ts
This PR addresses the issue that when initializing or setting a variable to false, when reopening designer, it won't populate this value correctly, leaving it as an empty string, even though it would show up correctly in the code view. This is because when we were checking to see if there was a value and the value was false, it would take this to mean there was no value. Now we add an extra check such that if the type is a boolean and the value is false, it will accept this as a valid value. 
fixes #4342
> fix(Consumption): Adding check for valid 'false' value

- apps/designer-standalone/src/app/AzureLogicAppsDesigner/Utilities/Workflow.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/utils/swagger/operation.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/http.ts
Only resolve app settings if they are used in resource ids.
This allows users to have key vault references in app settings / connections data without causing the initialization issues we were seeing when subscriptions had app settings values.
The only bad behavior with this change is when a user has a key vault reference as an app setting that is used in place of a subscription ID, I don't see a way around that one.
I've also updated a couple situations where we weren't parsing errors properly and returning generic errors on accident.
> fix(Designer): Only resolve app settings if they are used in resource ids

- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
- libs/designer-ui/src/lib/unitTesting/assertionsPanel/assertionField.tsx
- libs/designer-ui/src/lib/unitTesting/outputMocks/ouputsSettings.tsx
- libs/designer-ui/src/lib/unitTesting/outputMocks/outputMocks.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
- libs/designer/src/lib/core/state/unitTest/unitTestInterfaces.ts
- libs/designer/src/lib/core/state/unitTest/unitTestSelectors.ts
- libs/designer/src/lib/core/state/unitTest/unitTestSlice.ts
- libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/mockResultsTab/mockResultsTab.tsx
This pull request primarily involves changes to improve the unit testing functionality of the application. The major changes include modifications to handle validation errors for both assertions and mocks, updates to the `UnitTestState` interface, and enhancements to the mock results handling in the unit test slice. Additionally, the outputs of workflows are parsed into a more structured format. 
* The `UnitTestState` interface has been updated to include validation errors for both assertions and mocks.
* Custom hooks have been created to return the validation errors for assertions and mocks.
* The `updateMock` action has been updated to validate the parameter and update the validation errors state.
* The `UnitTestState` interface has been updated to include validation errors for both …
> feat(designer): Add validation errors to output mocks

- libs/designer-ui/src/lib/unitTesting/outputMocks/outputMocks.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
- libs/utils/src/lib/models/unitTest.ts
This pull request primarily focuses on refactoring the structure of action results and the way they are handled in the codebase. The changes involve updating the `ActionResults` object, modifying how action results are assigned in `getTriggerActionMocks`, and adjusting how action results are deserialized in `deserializeUnitTestDefinition`. Additionally, the `OperationMock` interface has been updated to include a `properties` object.
* The `getTriggerActionMocks` function now assigns action results within a `properties` object with a `status` key.
* The `deserializeUnitTestDefinition` function now retrieves the action result from the `properties` object's `status` key in both the `triggerMocks` and `actionMocks` objects. 
* The `OperationMock` interface has been updated to replace the …
> fix(designer): Update action result properties of mock actions

- libs/designer/src/lib/core/parsers/deleteNodeFromWorkflow.ts
In this PR we are removing the nodeId from idReplacements when the node is deleted. This fixes the issue that if you add a node, change the name, then delete it, if you add the node again it will use the name you changed it to rather than the default name. 
Fixes #4366
> fix(consumption): Deleting idReplamenent when deleting node

- libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
- libs/designer/src/lib/core/utils/outputs.ts
For the most part [this PR](https://github.com/Azure/LogicAppsUX/pull/4215) seems to behave as intended where we follow the steps
1. Initialize graph and all the input parameters
2. At this point, the workflow is already visible, and if input parameters contain dynamic data, it begins to start fetching them
3. Once dynamic data is fetched to populate the downstream tokens (added in the last PR)
4. Once a user clicks on a downstream action with that updated token, it should be populated with the new title
The case I see that doesn't fully work currently is if a user clicks on the downstream action in between steps 1 and 3. This is because the dynamic data is not yet loaded, and thus the updated title name is not actually fetched yet.
> fix(designer): Fixes an issue where titles were sometimes not updating input tokens from dynamic data

- libs/data-mapper/src/lib/utils/DataMap.Utils.ts
- libs/data-mapper/src/lib/utils/__test__/DataMapUtils.spec.ts
> fix(Data Mapper): Deserialize source edge for custom function with dash in its name

- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerBase.ts
- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForAzureResource.ts
- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
- apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewBase.ts
- apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForAzureResource.ts
- apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForLocal.ts
- apps/vs-code-designer/src/app/commands/workflows/openOverview.ts
- apps/vs-code-designer/src/app/commands/workflows/unitTest/createUnitTest.ts
- apps/vs-code-react/src/app/designer/DesignerCommandBar/index.tsx
- apps/vs-code-react/src/app/designer/app.tsx
- apps/vs-code-react/src/app/designer/servicesHelper.ts
- apps/vs-code-react/src/app/designer/utilities/runInstance.ts
- apps/vs-code-react/src/app/overview/app.tsx
- apps/vs-code-react/src/state/DesignerSlice.ts
- libs/designer/src/lib/core/BJSWorkflowProvider.tsx
- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/mockResultsTab/mockResultsTab.tsx
- libs/services/designer-client-services/src/lib/standard/run.ts
This pull request includes changes to the VS Code Designer application, specifically to the handling of unit tests and workflow monitoring. The changes introduce a new `runId` parameter to several functions and methods, modify the `OpenDesignerBase` class and its subclasses, and adjust how unit tests are created. 
Enhancements to Unit Test and Monitoring Workflow Handling:
* Send `runId` from Overview and Monitoring pages to designer pages. This allows to call the run instance API to get the outputs from the actions.
* Call the outputs API for all the actions within the workflow to populate the mock results when designer is loaded for unit test
* Added `workflowRuntimeBaseUrl` and `runId` as class properties and constructor parameters in `OpenDesignerBase` class and its subclasses.
* …
> feat(vscode): Load run output data from monitoring view into unit test

- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
Secure string workflow parameters now pass validation.
Previously our value / default value checking was verifying the values were objects, they are now evaluated just as-is like strings.
> fix(Designer): Secure string workflow parameters now pass validation

- apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesigner.tsx
- apps/vs-code-react/src/app/designer/app.tsx
- libs/designer/src/lib/core/BJSWorkflowProvider.tsx
- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
Mainly allows workflow params and app settings to be used inside of each other.
I modified the expression evaluator to be recursive, so any number of workflow parameters or app settings inside of each other will be evaluated properly.
This should support any number / combination of chaining so if you wanted to chain something crazy like this `AS -> WFP -> WFP -> AS -> AS -> WFP` it should work as you'd expect (but we're going to look at you funny)
The only requirement is that app settings will have to get passed into the BJSWorkflowProvider
> fix(Designer): Allow WorkflowParameters and AppSettings to be used within each other in dynamic data

- apps/vs-code-designer/src/app/commands/workflows/unitTest/editUnitTest.ts
- apps/vs-code-designer/src/app/commands/workflows/unitTest/openUnitTestResults.ts
- apps/vs-code-designer/src/app/commands/workflows/unitTest/runUnitTest.ts
- apps/vs-code-designer/src/app/tree/unitTestTree/index.ts
- apps/vs-code-designer/src/app/tree/unitTestTree/testFile.ts
- apps/vs-code-designer/src/app/tree/unitTestTree/testWorkflow.ts
- apps/vs-code-designer/src/app/tree/unitTestTree/testWorkspace.ts
- apps/vs-code-designer/src/app/utils/unitTests.ts
- apps/vs-code-designer/src/extensionVariables.ts
- apps/vs-code-designer/src/main.ts
- apps/vs-code-designer/src/package.json
This pull request primarily modifies the unit test handling in the `vs-code-designer` application. The changes include modifying the way unit tests are run, simplifying the `TestFile` class, and updating the handling of test files and workspaces in the unit test tree. 
* Refactored the `runUnitTest` function to simulate running a unit test and return a test result. The function now takes an additional `IActionContext` argument.
* Removed the `parseUnitTest` method and the `name`, `file`, `fileTestItem`, and `unitTest` properties from the `TestFile` class. The `run` method now calls the `runUnitTest` function and updates the test run based on the returned result.
* Updated several functions to use the file system path of URIs instead of the URI path, and to take an additional …
> feat(vscode): Add edit and view results for test files

- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/LogicAppCreateStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/workflowDesigner/DesignerConfig.ts
- apps/vs-code-designer/src/app/commands/dataMapper/DataMapperExt.ts
- apps/vs-code-designer/src/app/commands/dataMapper/FxWorkflowRuntime.ts
- apps/vs-code-designer/src/app/commands/dataMapper/dataMapper.ts
- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
- apps/vs-code-designer/src/constants.ts
This pull request mainly focuses on improving the codebase of the VS Code Designer app by refactoring constants and modifying function parameters to enhance maintainability. The changes are primarily related to the handling of settings and configuration in the application.
* The constant `APP_KIND` has been replaced with `appKindSetting` to enhance code readability and maintainability.
* Additional constants `localSettingsFileName` and `logicAppKind` have been imported to standardize the naming conventions and enhance code readability.
* A new constant `appKindSetting` has been added to standardize the naming conventions.
* The function `startDesignTimeApi` has been modified to replace the `updateProjectPath` function with the `addOrUpdateLocalAppSettings` function.
* The function …
> fix(vscode): Add app kind setting to local settings creation and update on design time

- libs/designer-ui/src/lib/html/plugins/toolbar/helper/HTMLChangePlugin.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/__test__/util.spec.ts
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/util.ts
Bug fix
If one uses `<img src="...">` in raw HTML editor, the `src` attribute is deleted.
`src` and `alt` attributes are retained on `<img>` tags.
No
Before:
After:
> fix(designer-ui): Add support for `<img src=>` in raw HTML editor

- libs/designer-ui/src/lib/connectorsummarycard/index.tsx
Add data-automation-id for connector summary card
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature: add automation id to improve automated UI test stability and robustness with respect to UI/styling or locale changes.
**What is the current behavior?** (You can also link to an open issue here)
Two connector summary cards cannot be distinguished from each other, except by their content - which is a localized text.
**What is the new behavior (if this is a feature change)?**
Adding `data-automation-id` prop to the component, where the value is the connector `id`, in order to guarantee a consistent way to distinguish and select the right element when using automated tests.
**Does this PR introduce a breaking change?** (What changes might users need …
> feat(Designer): Add data-automation-id for connector summary card

- apps/vs-code-designer/src/app/commands/workflows/exportLogicApp.ts
- apps/vs-code-designer/src/extensionVariables.ts
- apps/vs-code-react/src/app/export/instanceSelection/instanceSelection.tsx
- apps/vs-code-react/src/app/export/navigation/navigation.tsx
- apps/vs-code-react/src/app/export/summary/managedConnections.tsx
- apps/vs-code-react/src/app/export/summary/summary.tsx
- apps/vs-code-react/src/app/export/validation/validation.tsx
- apps/vs-code-react/src/app/export/workflowsSelection/workflowsSelection.tsx
- apps/vs-code-react/src/run-service/export/index.ts
- libs/vscode-extension/src/lib/models/extensioncommand.ts
This pull request primarily focuses on the addition of telemetry logging and context passing in the `apps/vs-code-designer` and `apps/vs-code-react` applications. The changes include the addition of the `IActionContext` type, logging of telemetry in various parts of the applications, and passing the `vscode` context to the `ApiService` class. 
* Imported `IActionContext` from `@microsoft/vscode-azext-utils` and added it as a parameter in the `ExportEngine` class and `exportLogicApp` function. Telemetry logging was added in various methods of the `ExportEngine` class. 
* Imported `IActionContext` from `@microsoft/vscode-azext-utils` and added a `logTelemetry` function in the `ext` namespace.
* Various files: Imported `VSCodeContext` from `../../../webviewCommunication` and used …
> feat(vscode): Improve export telemetry

- apps/designer-standalone/src/app/AzureLogicAppsDesigner/Utilities/Workflow.ts
We now resolve any app settings in connections data that does not contain a keyvault reference.
Our last fix of only resolving app settings in resource ids did not apply to enough situations, we saw customers use app settings other ways we didn't know about so we're going back to resolving nearly everything.
This is just for standalone, nothing here needs to be merged into portal through packages.
> fix(Designer): Resolve all app settings except key vault reference values

- libs/designer-ui/src/lib/pager/index.tsx
- libs/designer/src/lib/ui/common/LoopsPager/LoopsPager.tsx
This pull request includes changes to the `libs/designer-ui/src/lib/pager/index.tsx` and `libs/designer/src/lib/ui/common/LoopsPager/LoopsPager.tsx` files. The changes primarily focus on improving the readability and functionality of the code.
Improvements to readability:
* [`libs/designer-ui/src/lib/pager/index.tsx`](diffhunk://#diff-d1f4ef0b4caec1dd683763f7b7748b7cf23648a83b10ed08d864dd7c98a901aaL79-R80): The variables `failedMax` and `failedMin` have been declared separately to enhance code readability.
Improvements to functionality:
* [`libs/designer/src/lib/ui/common/LoopsPager/LoopsPager.tsx`](diffhunk://#diff-b8a3966d76571aa606548b1b1b08a6f8442a55647ccb04bbf3cc006f3adfb330L99-R99): The condition to set the `max` property of `failedIterationProps` has been updated to include the …
> fix(designer): Fix issue where next failure is disabled when there is only 1 failure

- libs/designer-ui/src/lib/html/htmleditor.less
This pull request includes changes to the `htmleditor.less` file in the `libs/designer-ui` directory. The changes focus on modifying the color scheme of certain elements.
* [`libs/designer-ui/src/lib/html/htmleditor.less`](diffhunk://#diff-ea81d5a7f1817f9d23b6f4092b5beb5edd248de1237601ad46cd0400d215c42fL71-R71): The color of the text has been updated from `#777` to `#757575` to provide a more consistent color scheme across the application and improve readability.
> fix(designer): Adjust HTML editor toolbar color to fit contract requirements of 4.5:1

- libs/logic-apps-shared/src/designer-client-services/lib/base/connection.ts
- libs/logic-apps-shared/src/utils/src/lib/models/connection.ts
- package-lock.json
We now run a testLink request first, and if it fails we run a testRequest as well.
Only if both fail is the connection is shown as a failure.
This keeps priority on testLink which has been working in 99% of cases.
The testLink error is also the one shown over the testRequest error.
> fix(Designer): Connection TestLink / TestRequest both require failure to show error

- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
- apps/vs-code-designer/src/main.ts
This pull request primarily focuses on the refactoring of the `generateDeploymentScripts` function The changes aim to improve how connections are parameterized in the function. 
* Removed the `parameterizeConnectionsInProjectLoadSetting` from the import statement and replaced it with the `isConnectionsParameterized` function. This change indicates a shift in how connections are parameterized. Checks if the connections are parameterized using the `isConnectionsParameterized` function.
* In the `activate` function in `apps/vs-code-designer/src/main.ts`, the `promptParameterizeConnections` function call is no longer awaited. This change suggests that the function does not return a promise that needs to be resolved or that the function's completion is not critical to the flow of the …
> fix(vscode): Check connections parameterization during generate deployment scripts command

- apps/vs-code-designer/src/app/commands/createNewCodeProject/createNewCodeProject.ts
- apps/vs-code-designer/src/app/commands/parameterizeConnections.ts
- apps/vs-code-designer/src/app/utils/codeless/parameterizer.ts
This pull request mainly involves updates to import statements in several files under `apps/vs-code-designer/src/app/`. The changes are focused on replacing the usage of certain utility functions from the `@microsoft/utils-logic-apps` package with their counterparts from the `@microsoft/logic-apps-shared` package. 
*The `isString` function is now imported from `@microsoft/logic-apps-shared` instead of `@microsoft/utils-logic-apps`. 
* The `isEmptyString` function is now imported from `@microsoft/logic-apps-shared` instead of `@microsoft/utils-logic-apps`. 
* The `isEmptyString` function is now imported from `@microsoft/logic-apps-shared` instead of `@microsoft/utils-logic-apps`.
> fix(vscode): Update imports to shared library

- libs/designer-ui/src/lib/unitTesting/assertionsPanel/assertionButtons.tsx
- libs/designer-ui/src/lib/unitTesting/outputMocks/actionResult.tsx
This pull request primarily focuses on the enhancement of internationalization (i18n) in the `libs/designer-ui` package. The changes include the addition of unique identifiers to the internationalization function `intl.formatMessage()` in both `assertionButtons.tsx` and `actionResult.tsx` files. 
* Added unique identifiers to the `intl.formatMessage()` function for 'Delete assertion' and 'Edit assertion' text. This will help in providing translations for these texts in different languages.
* Added unique identifiers to the `intl.formatMessage()` function for 'Action Result', 'Is successful', 'Timed out', 'Is skipped', and 'Has failed' text. This will help in providing translations for these texts in different languages.
> fix(designer): Add id's to format message

- libs/designer-ui/src/lib/pager/index.tsx
- libs/designer/src/lib/ui/common/LoopsPager/LoopsPager.tsx
Hotfix of https://github.com/Azure/LogicAppsUX/pull/4468
> fix(desiger): Fix issue where next failure is disabled when there is only 1 failure

- apps/vs-code-designer/src/app/commands/workflows/unitTest/openUnitTestResults.ts
- apps/vs-code-designer/src/extensionVariables.ts
- apps/vs-code-react/src/app/unitTest/index.tsx
- apps/vs-code-react/src/app/unitTest/unitTest.less
- apps/vs-code-react/src/router/index.tsx
- apps/vs-code-react/src/run-service/types.ts
- apps/vs-code-react/src/state/UnitTestSlice.ts
- apps/vs-code-react/src/state/store.ts
- apps/vs-code-react/src/stateWrapper.tsx
- apps/vs-code-react/src/webviewCommunication.tsx
- apps/vs-code-react/src/webviewCommunication/index.tsx
- apps/vs-code-react/src/webviewCommunication/messageTypes.ts
- libs/vscode-extension/src/lib/models/extensioncommand.ts
- libs/vscode-extension/src/lib/models/project.ts
This pull request primarily focuses on the implementation of unit test results display in the VS Code extension for Logic Apps. It introduces a new webview to display unit test results, and refactors the existing codebase to support this feature. 
* In `apps/vs-code-designer/src/app/commands/workflows/unitTest/openUnitTestResults.ts`, several utility functions were added to manage webview panels and to get webview HTML. 
* The `openUnitTestResults` function in was refactored to open the unit test results in a webview panel instead of using the `OpenDesignerForLocalProject` class.
* A new Redux slice, `UnitTestSlice`, was added to manage the state of unit test results.
* A new React component, `UnitTestResults`, was introduced to display unit test results in a webview. 
* The …
> feat(vscode): Implement results view webview

- apps/designer-standalone/src/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
- libs/designer-ui/src/lib/code/index.tsx
- libs/designer-ui/src/lib/code/util.ts
- libs/designer-ui/src/lib/index.ts
- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/delete.ts
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/customcode.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/customcode.ts
Standalone Consumption was running into errors of:
Host Service Not Initialized 
When adding a new Action
Consumption in all skus were running into errors of:
Custom Code Service Not Initialized
When editing a existing editor
> fix(Designer): Consumption Services Not Being Initialized

- libs/designer/src/lib/core/utils/parameters/helper.ts
On optional parameters, we should not use the default value, as there are times where the customer wants to keep the value unset.
Fixes https://github.com/Azure/LogicAppsUX/issues/4481
> fix(designer): Only use default value when the parameter is required

- apps/vs-code-designer/src/app/commands/workflows/unitTest/editUnitTest.ts
- apps/vs-code-designer/src/app/commands/workflows/unitTest/openUnitTestResults.ts
- apps/vs-code-designer/src/app/utils/unitTests.ts
- apps/vs-code-designer/src/constants.ts
This pull request primarily focuses on changing the directory structure of the unit tests in the VS Code Designer App. The `developmentDirectoryName` constant has been removed, and the `testsDirectoryName` constant has been capitalized. As a result, the unit tests are no longer nested under the `.development` directory and are now directly under the project path in a `Tests` directory.
* The import of `developmentDirectoryName` has been removed and the `testsDirectoryName` is now used directly under the `projectPath` in the `pickUnitTest` function. 
* Similar to the previous file, the `developmentDirectoryName` is no longer imported and the `testsDirectoryName` is used directly under the `projectPath` in the `pickUnitTest` function.
* The `developmentDirectoryName` is no longer imported …
> feat(vscode): Update path in workspace to save unit tests

- apps/designer-standalone/src/app/AzureLogicAppsDesigner/Utilities/Workflow.ts
When a user has a connection string containing "$&" we end up in an infinite loop when trying to resolve the connection references, unable to load designer, unable to load connections tab, etc. This fixes it in designer standalone - will need to also make this change in portal
Happening due to:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter
> fix(designer): Fix Infinite Loop on resolving app settings

- apps/vs-code-designer/src/app/commands/workflows/switchToDotnetProject.ts
Cherry pick of following PR:
https://github.com/Azure/LogicAppsUX/pull/4533
> fix(vscode): Keep host.json when converting to NuGet based project

- .vscode/launch.json
- apps/vs-code-designer/extension-copy-svgs.js
- apps/vs-code-designer/package.json
- apps/vs-code-designer/tsup.config.ts
- pnpm-lock.yaml
This pull request primarily modifies the build and packaging process for the `vscode-designer` application. The changes include updating the build path and tasks in `.vscode/launch.json`, refactoring the `copyFiles` function in `extension-copy-svgs.js`, simplifying the scripts in `package.json`, and adding a new `tsup.config.ts` file.
* The extension development path and output files path have been updated to reflect changes in the project's structure. The pre-launch task has been simplified from `npm: build:vscode-designer` to `npm: build`.
* The `copySVG` function has been removed, and the `copyDoc` function now copies files from `./src` instead of `./`. The destination path for the `copyFiles` function has also been updated.
* The `type` attribute has been removed, and the `build` …
> meta(vscode): Fix vscode building

- libs/designer-ui/package.json
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/util.ts
- pnpm-lock.yaml
**Note: I have tests for this, but they will be added in a follow-up PR once this fix rolls out.**
Bug fix [security]
Certain maliciously crafted payloads, if provided into the raw HTML editor, may permit XSS attacks. Please ping me directly if there are questions about specifics.
Use of `DOMParser` instead of `document.createElement` prevents malicious HTML from being executed.
No
- …
> fix(designer-ui): Prevent certain malicious HTML from executing in raw HTML editor

- apps/vs-code-designer/tsup.config.ts
This pull request includes a minor change to the `tsup.config.ts` file in the `apps/vs-code-designer` directory. The `keepNames` property has been added to the configuration object passed to the `defineConfig` function. This property, when set to `true`, instructs the bundler to preserve the original names of the variables, functions, and classes in the output bundle.
> fix(vscode): Add keepNames to tsup config

- libs/logic-apps-shared/src/parsers/lib/common/helpers/expression.ts
Dynamic data call would be interrupted by checking the value for a template expression.
This template fix has now been improve to catch non-string values.
Fixes: https://github.com/Azure/LogicAppsUX/issues/4578
Fixes: https://github.com/Azure/LogicAppsUX/issues/3450
Possibly fixes: https://github.com/Azure/LogicAppsUX/issues/4358
> fix(Designer): Fixed issue where dynamic data call would fail when value is non-string

- libs/designer/src/lib/core/actions/bjsworkflow/connections.ts
- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/designer/src/lib/core/state/connection/connectionSelector.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
There were a couple spots we were potentially passing null data to `Object.keys` function calls which errors.
I've just added some `?? {}` catches to avoid these errors.
> fix(Designer): Fixed issue where we weren't handling null connection references fully

- .github/workflows/production-build.yml
- package.json
- turbo.json
This pull request primarily focuses on modifying the build process for the VS Code Designer extension. The changes include updating the GitHub Actions workflow for production builds, adding a new npm script for packing the extension, and updating the Turbo configuration file.
GitHub Actions workflow:
* [`.github/workflows/production-build.yml`](diffhunk://#diff-20fbc76be4bae1652559385109766d3a3a185d70ae392c77fab423e41f5b6b16L87-R103): Un-commented and updated the command to pack the VS Code Designer extension. Also un-commented and updated the step to archive the packed extension as an artifact. Finally, the artifacts for the release action were updated to include the packed extension.
Npm scripts:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b648 …
> meta(vscode): Add new vsix build to artifacts production build

- .github/workflows/production-build.yml
This pull request primarily focuses on changes in the `.github/workflows/production-build.yml` file. The changes pertain to the packaging and path of the VSCode Designer Extension in the GitHub actions workflow. 
* [`.github/workflows/production-build.yml`](diffhunk://#diff-20fbc76be4bae1652559385109766d3a3a185d70ae392c77fab423e41f5b6b16R87): Added a new step to pack the VSCode Designer Extension in the GitHub actions workflow. The path of the VSCode Designer Extension was updated in the artifact upload and release actions. [[1]](diffhunk://#diff-20fbc76be4bae1652559385109766d3a3a185d70ae392c77fab423e41f5b6b16R87) [[2]](diffhunk://#diff-20fbc76be4bae1652559385109766d3a3a185d70ae392c77fab423e41f5b6b16L99-R104)
> meta(vscode): Fix typo in vsix path in production build

- .github/workflows/production-build.yml
This pull request includes a small change to the `.github/workflows/production-build.yml` file. The change simplifies the 'Pack VSCode Designer Extension' job by removing an unnecessary dash before the `run` command.
> meta(vscode): Fix typo in yaml

- libs/logic-apps-shared/src/designer-client-services/lib/consumption/manifests/functions.ts
- libs/logic-apps-shared/src/designer-client-services/lib/consumption/manifests/invokeWorkflow.ts
- libs/logic-apps-shared/src/designer-client-services/lib/consumption/manifests/swaggerFunctions.ts
Adds operation settings for the Azure Function action in consumption, it was just missing from the manifest.
Adds missing settings to the Azure Workflow action as well.
Fixes https://github.com/Azure/LogicAppsUX/issues/4593
> fix(Designer): Added proper settings to the Azure Function operation

- apps/vs-code-react/src/app/designer/DesignerCommandBar/index.tsx
- libs/designer-ui/src/lib/utils/utils.ts
- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/functions.ts
Refactored some of our commonly run reduce + spread calls to be for loops.
This was done with the intention of speeding things up but I'm seeing no noticeable difference between initialization times.
The test workflow I ran with 100+ actions of different connector / connections initialized both before and after this PR in ~16 seconds (runs slower than normal during performance diagnostics)
> chore(Designer): Converted some commonly used reduce/spreads to for loops

- apps/Standalone/src/dataMapperV1/state/SchemaDataLoader.ts
This pull request includes a change to the `loadSchemaFromMock` function in the `SchemaDataLoader.ts` file. The change modifies the return statement to handle both ES6 module imports and CommonJS module imports. This is done by checking for a `default` property on the imported `schema` object, which would exist in the case of an ES6 module import. If the `default` property exists, it is returned; otherwise, the original `schema` object is returned. This change ensures the function works correctly regardless of the module system used in the imported schema file.
> fix(dataMapper): Fix issue loading schemas in stand alone

- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
- libs/designer/src/lib/ui/connections/dropzone.tsx
Fixes #4666 
This pull request primarily involves changes to two files: `ScopeCardNode.tsx` and `dropzone.tsx` located in `libs/designer/src/lib/ui/`. The changes mainly revolve around adding dependency and scope-related features to the `ScopeCardNode` and `DropZone` components.
Key changes include:
Dependency and Scope-related Changes:
* [`libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx`](diffhunk://#diff-3214690825743eaad95edb802e46b6e315b56a1b05018d5af76d43741adef851L6-R11): Imported the `useTokenDependencies` hook, used it to fetch dependencies for a given scope, and included these dependencies in the draggable item's data. [[1]](diffhunk://#diff-3214690825743eaad95edb802e46b6e315b56a1b05018d5af76d43741adef851L6-R11) [[2]](diffhunk://#diff-3214690825743eaad95edb802e46b6e315b56a1 …
> fix(designer): Fix issue where scopes could drag/drop into themselves

- libs/designer-ui/src/lib/card/scopeCard/index.tsx
- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
This pull request primarily focuses on improving the user interaction with the `ScopeCard` component in the `libs/designer-ui` package. The changes introduced include the addition of a focus state for the `ScopeCard` and the use of optional chaining for `runData` properties.
Here are the most important changes:
User Interaction Improvement:
* [`libs/designer-ui/src/lib/card/scopeCard/index.tsx`](diffhunk://#diff-a89043898373470bd84f869c820776a801fe861cefd3f6d4bc02fc909f706b81L36-R49): Implemented a focus state for the `ScopeCard` by using `useRef` and `useEffect` hooks from React. This allows the card to be focused programmatically when the `setFocus` prop is true. [[1]](diffhunk://#diff-a89043898373470bd84f869c820776a801fe861cefd3f6d4bc02fc909f706b81L36-R49) …
> fix(designer): fix issue where scope nodes didn't get focused when they were jumped to

- libs/designer-ui/src/lib/infoDot/index.tsx
Fixes #4697
This pull request primarily focuses on changes in the `InfoDot` component in the `libs/designer-ui/src/lib/infoDot/index.tsx` file. The changes involve the removal of the `alt` prop and the subsequent use of the `description` prop as the `alt` attribute for the `img` element.
* Removed the `alt` prop from the `InfoDot` component's props. This change simplifies the component's API by reducing the number of props it accepts.
* Updated the `alt` attribute of the `img` element within the `InfoDot` component to use the `description` prop instead of the removed `alt` prop. This ensures that the `img` element still has a meaningful `alt` attribute for accessibility purposes.
> fix(deisgner): Fix a11y issue where info bubbles had no announcement to description in tooltip

- libs/designer-ui/src/lib/code/util.ts
- libs/designer/src/lib/common/constants.ts
- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/customcode.ts
1. Updating Token Picker Results based on Demo Comments
2. Updating Boilerplate Code based on Demo Comments
3. Removed customcode initialization/add connector-specifc code and changed to be based on parameter
4. Changed Initialization to be off of CodeFile location instead of NodeId
> fix(designer): More Custom Code improvements

- __mocks__/workflows/Conditionals.json
- e2e/designer/mock-copypastescope.spec.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
1. Fixes https://github.com/Azure/LogicAppsUX/issues/4724
2. Fixes https://github.com/Azure/LogicAppsUX/issues/4722
3. Fixes an issue where pasting the same scopes wouldn't properly delete the run after of the repeat nodes creating 2 action buttons in one edge
> fix(Designer): Copy Paste Fixes

- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
very small change to use scopeId instead as the id has an idTag and isn't one of the nodeIds
> fix(designer): Deleting a scope node brings panel to wrong id

- libs/designer/src/lib/core/utils/parameters/helper.ts
- Bug Fix
- When using the expression editor to use the "null" value it correctly specifies the expression type is Null Literal, but when the value is formatted, its formatted as ${null} instead of @null which results in the null being treated as a String Literal instead of a Null Literal value. 
- Link to Issue: https://github.com/Azure/LogicAppsUX/issues/3433
- Note: This issue also mentions a similar issue occurs for True/False values and other keywords. This doesn't address all the keywords, just the null expression ones since that's the ones we're seeing on the PA …
> fix(designer): Null Literal are casted as String Literals

- apps/vs-code-designer/src/app/utils/appSettings/localSettings.ts
This pull request includes a change in the `getLocalSettingsJson` function within the `apps/vs-code-designer/src/app/utils/appSettings/localSettings.ts` file. The function has been updated to use the `existsSync` method instead of the `pathExists` method from the `fse` module.
> fix(vscode): Update path exist function

- libs/designer-ui/src/lib/recurrence/dropdownControl.tsx
- libs/designer-ui/src/lib/recurrence/textInput.tsx
This pull request includes changes to two components in the `libs/designer-ui/src/lib/recurrence` directory. Both changes add a `required` attribute to form elements, which will enforce that these fields must be filled out by the user.
* [`libs/designer-ui/src/lib/recurrence/dropdownControl.tsx`](diffhunk://#diff-e602cf4d4fa3a779d805c8d92b4729d39d17c4c1fd2c52e3528a5b582ec34753R104): Added a `required` attribute to the `DropdownControl` component, which will enforce that a selection must be made from the dropdown by the user.
* [`libs/designer-ui/src/lib/recurrence/textInput.tsx`](diffhunk://#diff-cc846eed09fbf24dae089e99041c7bfb55986627f14c64cfc79b5854924ccf0bR65): Added a `required` attribute to the `TextInput` component, which will enforce that the text input field must be filled out by …
> fix(designer): Fix required screen announcement for required recurrence fields

- package.json
- pnpm-lock.yaml
- turbo.json
This pull request primarily includes updates to dependencies and package integrity checks in the `package.json` and `pnpm-lock.yaml` files. The updates include version bumps, reordering of dependencies, and updates to the integrity hashes of various packages.
Dependency Updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R15-R16): The versions of `@types/react` and `@types/react-dom` were added, and the version of `turbo` was updated. The order of some dependencies was also adjusted. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R15-R16) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L52-R59)
* …
> chore(meta): Upgrade turbo version with new terminal UI

- .github/workflows/test.yml
This pull request includes a minor change to the `.github/workflows/test.yml` file. It adds a new job step to the workflow which builds the vscode extension using Turbo.
> chore(meta):  Add vscode extension build to test runner

- apps/vs-code-designer/package.json
- apps/vs-code-react/package.json
- package.json
- turbo.json
https://github.com/Azure/LogicAppsUX/assets/13208452/4031203e-8668-4904-bbbe-b002257ba64d
This pull request primarily involves changes to the build scripts in the `package.json` files of the `vs-code-designer` and `vs-code-react` applications, as well as modifications to the `turbo.json` file. The main changes include the removal of the `build:vscode-react` script from the `vs-code-designer` application and its addition to the `vs-code-react` application, the removal of the `build:vscode-react` script from the root `package.json` file, and the addition of dependencies in the `turbo.json` file.
* [`apps/vs-code-designer/package.json`](diffhunk://#diff-910a12f0b9fcbead593b5611662c5a1685cafd5a50eafd7ee495a7ed628ed17cL41-R41): The `build:vscode-react` script was removed from the …
> fix(vscode): fix turbo dependency for vscode build setup

- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
- libs/designer-ui/src/lib/tokenpicker/index.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickersection.tsx
Fixes https://github.com/Azure/LogicAppsUX/issues/4781
Also reverting: 
https://github.com/Azure/LogicAppsUX/pull/4744
because it was causing
> fix(Designer): Only show dropdown for array editor when there are options

- apps/docs/docs/vscode.md
This pull request includes changes to the `vscode.md` documentation file in the `apps/docs/docs` directory. The changes primarily involve updates to the instructions for setting up and running the Azure Logic Apps extension in Visual Studio Code. The important changes include updating the prerequisites, modifying the build command, simplifying the debug instructions, and changing the library import statement.
* Updated the prerequisites section to replace the instructions to clone the repository and install dependencies with a reference to the Getting Started section. Removed the instructions to install Azure Functions Core Tools and nx.
*  Changed the build command from `npm run build:vscode-designer` to `npm run build:extension`.
* Simplified the debug …
> chore(docs): Update building vscode extension docs

- e2e/designer/tokenRemoval.spec.ts
- libs/designer/src/lib/core/actions/bjsworkflow/delete.ts
This pull request primarily focuses on enhancing the token removal functionality in the workflow design process. The most significant changes include adding a new test case to verify token removal when a trigger is deleted, importing a new token type for deletion, and modifying the `deleteOperation` and `removeAllTokensFromNode` functions to handle trigger deletion.
Key changes include:
Token Removal Test:
* [`e2e/designer/tokenRemoval.spec.ts`](diffhunk://#diff-40403c79907f771d8e7b1e1e05be8490d591bde15b702d49732dbbea194bf2e0R48-R71): A new test case has been added to verify that tokens are correctly removed from parameters when a trigger is deleted. This ensures that any references to the deleted trigger are also removed, maintaining the integrity of the workflow.
Token Type Import:
* …
> fix(Designer): Trigger deletion should also remove dependant tokens through the workflow

- libs/designer/src/lib/core/index.ts
Exporting the `ValueSegmentConvertor` class and it's option for generating tokens for `AdaptiveCardTriggerEditor`
V1 uses Parameter Service to generate tokens, but V3 has a ValueSegmentConvertor to do the same. Hence exporting this class.
> fix(designer): Export the ValueSegmentConvertor class for use in PPUX

- .github/workflows/base-coverage.yml
- .github/workflows/test.yml
- apps/vs-code-designer/package.json
- apps/vs-code-designer/src/app/utils/codeless/__test__/parameterizer.test.ts
- apps/vs-code-designer/test-setup.ts
- apps/vs-code-designer/vitest.config.ts
- package.json
- turbo.json
This pull request primarily focuses on extending the testing suite to include unit tests for the vscode extension. 
* Added a new script `test:extension-unit` to run the extension unit tests using vitest.
* Added setup for the extension unit tests, including importing the necessary libraries and defining the `afterEach` cleanup function.
* Defined the configuration for the extension unit tests, including the testing environment, coverage settings, and setup files.
* Added steps to run the extension unit tests in the GitHub actions workflows. 
* Added the `test:extension-unit` command to the root `package.json` and `turbo.json` files to enable running the extension unit tests from the root directory. 
* Removed the `connectionProperties` field from the test data, possibly to align with …
> feat(vscode): Add initial setup for unit testing with vitest in extension code

- libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchHeader/operationSearchHeader.less
Bug fix (styling, accessibility)
For screens which are vertically narrow, buttons in the actions side panel are not visible when searching, due to the sticky header covering them.
For screens <420px tall, the search header is no longer sticky, allowing all actions to be seen if scrolled.
No
> fix(designer-ui): [a11y] Prevent sticky search header from hiding action buttons in side panel

- libs/designer-ui/src/lib/editor/base/index.tsx
Bug fix
Hovering over a button which has no `title` attribute in the HTML toolbar causes the field's placeholder to appear as the `title`.
Aforementioned placeholder title only appears when hovering over the editable content.
No
> fix(designer-ui): Prevent field placeholder from being used as title on HTML toolbar

- libs/designer-ui/src/lib/html/plugins/toolbar/ColorPickerTextInput.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/DropdownItemElement.ts
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/DropdownItems.tsx
Bug fix (accessibility)
HTML toolbar color picker popover cannot be focused by keyboard. Fixes #4457.
HTML toolbar color picker auto-focuses when selected.
No
> fix(designer-ui): [A11Y] Auto-focus color picker in HTML toolbar

- libs/data-mapper/src/lib/components/edge/ConnectionEdge.tsx
- libs/data-mapper/src/lib/components/nodeCard/functionCard/ExpandedFunctionCard.tsx
- libs/data-mapper/src/lib/components/nodeCard/functionCard/SimpleFunctionCard.tsx
removing right click menu 
Data Mapper crashes because it is using a shared component that references Designer state
removing instead of fixing as DMV2 will not use the same context menu
does not block users, they can still delete using the delete key or from the function menu
> Fix(Data Mapper): Disabling context menu as it causes app to crash

- libs/designer-ui/src/lib/connectorsummarycard/connectorsummarycard.less
- libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchCard/operationSearchCard.less
Bug
When designer is set to dark mode, triggers and actions title does not show
https://msazure.visualstudio.com/One/_workitems/edit/27320697
Triggers and actions titles now shows when app is in dark mode
No
> fix(designer): fix actions and triggers title not showing in dark theme

- apps/vs-code-designer/package.json
This pull request includes a modification to the `vscode:designer:pack` script in the `apps/vs-code-designer/package.json` file. The change adds the `-w` option to the `pnpm` command in the script, which allows the command to run in the current workspace. This change ensures that the `build:extension` script is run in the correct context.
> fix(vscode): Update command to build all projects for extension

- apps/vs-code-designer/package.json
- turbo.json
This pull request primarily focuses on improving the build process in the `vs-code-designer` and `turbo.json` files. The most important changes include modifying the `vscode:designer:pack` script in `package.json` and adding dependencies in `turbo.json`.
* The `vscode:designer:pack` script was modified. The `pnpm -w run build:extension` command was removed from the script, which now only runs `vscode:designer:pack:step1` and `vscode:designer:pack:step2`.
* The `vscode-designer#build:extension` task now depends on the `build` task.
* The `vscode:designer:pack` task now depends on the `vscode-react#build:extension` task instead of the `build` task.
> chore(meta): Update build dependency in turbo for vscode

- libs/designer-ui/src/lib/html/htmleditor.less
Bug fix
Power Automate side-panel uses a custom width which leads to the following behavior:
This is a cosmetic issue introduced by #4823.
Padding adjustments now display this correctly:
Validated that LAUX standalone panel renders correctly after changes also:
No
> fix(designer-ui): Prevent padding on HTML toolbar from creating scrollbar

- libs/designer-ui/src/lib/expressioneditor/index.tsx
- libs/designer-ui/src/lib/unitTesting/assertionsPanel/assertion.tsx
- libs/designer-ui/src/lib/unitTesting/assertionsPanel/assertionField.tsx
- libs/designer-ui/src/lib/unitTesting/conditionExpression/index.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/ui/panel/assertionsPanel/assertionsPanel.tsx
This pull request primarily introduces read-only functionality to the ExpressionEditor and ConditionExpression components in the `libs/designer-ui` library. It also includes changes to the serialization and deserialization of unit test definitions, and to the parameter value conversion in the `libs/designer` library.
Read-only functionality:
* Added `isReadOnly` prop to `ExpressionEditorProps` and `ExpressionEditor` function. The `isReadOnly` prop is used to set the `readOnly` property of the editor component. 
* Added `isReadOnly` prop to `GetConditionExpressionHandler` and used it in `AssertionField`. 
* Added `isReadOnly` prop to `ConditionExpressionProps` and `ConditionExpression` function. The `isReadOnly` prop is used to control the visibility of the `Callout` component and the …
> fix(vscode): Cast and uncast condition expression for unit test

- libs/designer-ui/src/lib/html/plugins/toolbar/DropdownColorPicker.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/MoveWrapper.tsx
Bug fix (a11y)
Color picker hex field and palette buttons can be accessed by keyboard, but the two sliders cannot.
All fields of the color picker can now be accessed by keyboard, and controlled using arrow keys (and optionally +shift to move a larger distance at once).
No
> fix(designer-ui): Allow color picker sliders to be accessed by keyboard

- libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
Bug fix
The fix in #4215 (for issue #4132) was updated with the change in #4377, which allowed token titles to be set with a `dispatch` call. However, in #4483, this behavior was changed to use `builder.addCase`. Unfortunately, `builder.addCase` does not work for actions created within the same class it is called.
This means token titles are not being set:
This PR calls `updateExistingInputTokenTitles` directly from `addDynamicOutputs` instead of relying on `builder.addCase`.
This ensures that token titles are …
> fix(designer): `updateExistingInputTokenTitles` is not invoked when dynamic outputs load

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
- apps/Standalone/src/designer/components/LocalizationSettings.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts
- libs/logic-apps-shared/src/designer-client-services/lib/consumption/search.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/search.ts
Fixed issue where our api calls were not respecting the selected language settings of portal.
If the user had their language set to chinese for example, their requests would not have the proper header and return results in english, when it should be requested with chinese headers.
I added the missing header to only our search requests.
Fixes https://github.com/Azure/LogicAppsUX/issues/4885
> fix(Designer): Fixed search locale not respecting portal language settings

- libs/designer-ui/src/lib/editor/base/index.tsx
This pull request includes a change to the `BaseEditor` component in the `libs/designer-ui/src/lib/editor/base/index.tsx` file. The `spellCheck` attribute has been added to the `ContentEditable` component and set to `false`. This change will prevent the browser from checking the spelling within the `ContentEditable` component.
fixes #4861
> fix(designer): Turn off spell check in editors

- libs/designer/src/lib/core/state/unitTest/unitTestInterfaces.ts
- libs/designer/src/lib/core/state/unitTest/unitTestSlice.ts
- libs/designer/src/lib/ui/panel/assertionsPanel/assertionsPanel.tsx
This pull request introduces several changes to the unit testing logic and the assertions panel in the designer library of the application. The most significant changes include the modification of the `UpdateAssertionsPayload` interface to `AddAssertionPayload`, the addition of a new interface `UpdateAssertioExpressionPayload`, and the introduction of a new function `checkAssertionsErrors` in the unit test slice. Moreover, the `unitTestSlice` itself has undergone several changes, including the replacement of `updateAssertions` with `addAssertion` and `updateAssertionExpression`. Lastly, the assertions panel has been updated to use the new actions from the unit test slice.
* The `UpdateAssertionsPayload` interface has been replaced with `AddAssertionPayload` which takes in a single …
> fix(vscode): Update asssertions redux actions

- libs/designer-ui/src/lib/styles.less
- libs/designer-ui/src/lib/unitTesting/conditionExpression/conditionExpression.less
- libs/designer-ui/src/lib/unitTesting/conditionExpression/index.tsx
This pull request primarily focuses on updating the UI styling for the Condition Expression component in the `libs/designer-ui` package. The changes include importing a new LESS file, adding new styles, and applying these styles to the Condition Expression component.
UI Styling Updates:
* Imported the new `conditionExpression.less` file which contains the styles for the Condition Expression component.
* Created a new LESS file where the styles for the Condition Expression component in dark theme are defined. It also imports a `variables.less` file for color definitions.
* Applied the new `msla-condition-expression-callout` class to the `Callout` component in the `ConditionExpression` function. This class is defined in the newly added `conditionExpression.less` file.
> fix(vscode): Add styles for dark mode for condition expression callout

- apps/Standalone/src/designer/app/SettingsSections/contextSettings.tsx
- apps/Standalone/src/designer/state/workflowLoadingSelectors.ts
- apps/Standalone/src/designer/state/workflowLoadingSlice.ts
- libs/designer/src/lib/core/DesignerProvider.tsx
- libs/designer/src/lib/core/state/designerOptions/designerOptionsInterfaces.ts
- libs/logic-apps-shared/src/intl/src/IntlProvider.tsx
- libs/logic-apps-shared/src/intl/src/__test__/IntlProvider.spec.tsx
- libs/logic-apps-shared/src/intl/src/__test__/intl.spec.tsx
- libs/logic-apps-shared/src/intl/src/index.ts
- libs/logic-apps-shared/src/intl/src/intl.tsx
This pull request primarily introduces the ability to override strings for localization in the application. This is achieved by adding a new `stringOverrides` property to several state and interface definitions, and modifying related functions and components to handle this new property. The changes also include the addition of a new checkbox in the `ContextSettings` component to allow users to toggle the test string override.
Here are the most important changes:
**State and Interface Updates:**
* [`apps/Standalone/src/designer/state/workflowLoadingSlice.ts`](diffhunk://#diff-e48356fbe118c8cea9880406f8cc5809a509614a466f83ddbcdf814c8dacdc6eR32): Added a `stringOverrides` property to the `WorkflowLoadingState` interface and the `hostOptions` object within it. This property is a record of …
> feat(designer): Add ability for host to send in overrides for internationalized strings

- .github/workflows/coverage-report.yml
This pull request includes a minor update to the `coverage-report.yml` workflow file. Specifically, the version of `pnpm/action-setup` has been updated from `9` to `9.1.3` to ensure we are using the latest stable version of the package. This change will help maintain the stability and reliability of our CI/CD pipeline.
> fix(meta): Update pnpm version in coverage-report

- libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
Bug fix
non string connection parameters were written in appsettings as non string values causing string operations to fail.
Connection parameter values will be stringified before putting them as settings.
No
> fix(designer): Stringifying appsetting values during connection creation

- .gitmodules
- libs/designer/src/lib/core/state/templates/store.ts
This pull request primarily focuses on refactoring the path and name of a submodule in the codebase. The submodule `libs/designer/src/lib/core/templates/samples` has been renamed to `libs/designer/src/lib/core/templates/templateFiles`. Additionally, the reference to this submodule in the `templatesPathFromState` constant has been updated to reflect this change.
Submodule renaming and path update:
* [`.gitmodules`](diffhunk://#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584L1-R3): The submodule `libs/designer/src/lib/core/templates/samples` has been renamed to `libs/designer/src/lib/core/templates/templateFiles`, and the path has been updated accordingly.
Reference update in the codebase:
* …
> chore(git): Rename templatesManifestFolder

- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
- apps/vs-code-designer/src/assets/FunctionProjectTemplate/FunctionsProjNet8
- apps/vs-code-designer/src/assets/FunctionProjectTemplate/FunctionsProjNetFx
- apps/vs-code-designer/src/assets/RuleSetProjectTemplate/RulesFunctionsProj
This pull request includes changes to three different project templates in the `apps/vs-code-designer` directory. The common change across all three templates is the update of the `Microsoft.Azure.Workflows.WebJobs.Sdk` package from version `1.0.1` to `1.1.0`.
* Updated the `Microsoft.Azure.Workflows.WebJobs.Sdk` package from version `1.0.1` to `1.1.0`.
> fix(vscode): Update Workflows Webjobs sdk version

- libs/designer/src/lib/core/utils/loops.ts
- libs/logic-apps-shared/src/parsers/lib/common/helpers/__test__/keysutility.spec.ts
- libs/logic-apps-shared/src/parsers/lib/swagger/__test__/fixtures/outlook.ts
This pull request primarily focuses on correcting spelling mistakes across different files in the codebase. The term 'attachements' has been corrected to 'attachments' in multiple places. 
* Corrected the spelling of 'attachments' in the comment section of the function `getTokenExpressionValueForManifestBasedOperation`.
* Fixed the spelling of 'attachments' in multiple test cases under the 'Parameter Key Utility Tests'.
* Updated the 'x-ms-summary' property value from 'Attachement Id' to 'Attachment Id' in the `Outlook` export object.
Fixes #4948
> fix(designer): Fix attachment wording

- apps/Standalone/src/dataMapperV1/app/DataMapperStandaloneDesignerV2.tsx
- apps/vs-code-react/src/app/dataMapper/appV2.tsx
- apps/vs-code-react/src/app/dataMapper/services/dataMapperFileService.ts
- libs/data-mapper-v2/src/components/addSchema/AddOrUpdateSchemaView.tsx
- libs/data-mapper-v2/src/components/addSchema/AddSchemaPanel.tsx
- libs/data-mapper-v2/src/components/addSchema/SelectExistingSchema.tsx
- libs/data-mapper-v2/src/components/addSchema/tree/SchemaTree.tsx
- libs/data-mapper-v2/src/components/addSchema/tree/TreeNode.tsx
- libs/data-mapper-v2/src/components/commandBar/EditorCommandBar.tsx
- libs/data-mapper-v2/src/constants/FunctionConstants.tsx
- libs/data-mapper-v2/src/constants/ReactFlowConstants.ts
- libs/data-mapper-v2/src/core/services/dataMapperFileService/dataMapperFileService.ts
- libs/data-mapper-v2/src/core/services/index.ts
- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
- libs/data-mapper-v2/src/mapHandling/MapDefinitionSerializer.ts
- libs/data-mapper-v2/src/models/Connection.ts
- libs/data-mapper-v2/src/ui/DataMapperDesigner.tsx
- libs/data-mapper-v2/src/utils/Connection.Utils.ts
- libs/data-mapper-v2/src/utils/Icon.Utils.tsx
- libs/data-mapper-v2/src/utils/Schema.Utils.ts
- libs/data-mapper/tsconfig.json
- libs/logic-apps-shared/src/designer-client-services/lib/search.ts
none
1. **Created new service to manage calls that go to vscode and interact with the file system**
this prevents us from passing functions down multiple components to be called
2. **Data Mapper is able to be loaded into VSCode, with limited functionality**
3. **Connections saved in the store and save using save button**
no
- **Please Include Screenshots or Videos of the intended …
> Feat(Data Mapper): Able to save data map

- apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewBase.ts
- apps/vs-code-react/vite.config.ts
This pull request primarily focuses on streamlining the codebase in two files: `openMonitoringViewBase.ts` and `vite.config.ts`. The most significant changes include the removal of a method in the `OpenMonitoringViewBase` class and an adjustment to the configuration in `vite.config.ts`.
* The `getPanelOptions` method was removed from the `OpenMonitoringViewBase` class. This method previously returned webview options for the panel. Its removal suggests that the default options are now being used or they're being defined elsewhere.
* The configuration for Vite, a build tool used in the project, was modified. The `base` option was added and set to `'./'`, which changes the base public path when serving or building the project.
> fix(vscode): Add base path for svgs and remove duplicated code

- libs/designer-ui/src/lib/token/token.less
A small styling change to increase the size of the input token and the number of visible characters in the token name. 
**Before**
**After:**
> feat(designer): Update input token styling to increase size

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/__test__/createConnection.spec.tsx
- libs/logic-apps-shared/src/utils/src/lib/models/connector.ts
In the context of creating a creating a connection with a credential (instead of username+password), the connector will return the list of credential types that are supported.
Today, this field is the enum string name of the credential connection type.
In order to query CDS without having to manually map the enum to its ordinal, we are adding the value in the AAPT-Connector contract.
Updating here, so that the info is passed to the UX
[Design note here](https://microsoft.sharepoint.com/:w:/t/MicrosoftFlowCore/EcbBBxvLdcZJrOhlDAltL-kBKDIOHLGKZmP4uA0lV64r-g?e=zBNWNj)
[AAPT-Connector PR here](https://msazure.visualstudio.com/One/_git/AAPT-connectors/pullrequest/10231609): [uiflow] Adding the type enum value to credential mapping
- …
> feat(designer): [CredentialMapping] Updating the schema

- apps/vs-code-designer/__mocks__/vscode.ts
- apps/vs-code-designer/src/app/commands/appSettings/decryptLocalSettings.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/ScriptProjectCreateStep.ts
- apps/vs-code-designer/src/app/commands/createNewProject/createProjectSteps/ScriptProjectCreateStep.ts
- apps/vs-code-designer/src/app/commands/dataMapper/FxWorkflowRuntime.ts
- apps/vs-code-designer/src/app/commands/dataMapper/extensionConfig.ts
- apps/vs-code-designer/src/app/utils/appSettings/__test__/localSettings.test.ts
- apps/vs-code-designer/src/app/utils/appSettings/localSettings.ts
- apps/vs-code-designer/src/app/utils/codeless/__test__/templates.test.ts
- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
- apps/vs-code-designer/src/app/utils/fs.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/vitest.config.ts
This pull request introduces changes primarily aimed at refactoring the project's settings management, improving code readability, and enhancing the test coverage. The modifications include consolidating imports, replacing hardcoded values with constants, adjusting the structure of local settings, and adding new test cases.
* Consolidated imports from 'vscode' into a single line.
* Replaced hardcoded values with constants and expanded the import list for better readability. 
* Similar changes were made as in `ScriptProjectCreateStep.ts` for code consistency.
* The local settings structure was adjusted to include a design time flag and improved key-value mapping. The function `getLocalSettingsSchema` was added to generate the schema based on the project path and design time flag.
*  New …
> fix(vscode): Fix designtime local.settings overwriting 

- apps/vs-code-designer/src/app/commands/workflows/getDebugSymbolDll.ts
- apps/vs-code-designer/src/app/utils/bundleFeed.ts
- apps/vs-code-designer/src/constants.ts
This pull request primarily focuses on refactoring the `apps/vs-code-designer` codebase to replace the usage of `defaultBundleId` with `extensionBundleId`. This change is reflected across multiple files and functions. 
* The `debugSymbolDll` import statement now includes `extensionBundleId` and the `bundleFolder` path now uses `extensionBundleId` instead of the hard-coded string. 
* The `defaultBundleId` import has been removed and replaced by `extensionBundleId` in all instances. This includes changes in the `getBundleFeed`, `getBundleDependencyFeed`, and `addDefaultBundle` functions. 
* The `defaultBundleId` constant has been removed.
> fix(vscode): Update functions extension bundle to workflows

- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
This pull request includes changes to the `generateDeploymentScripts.ts` file in the `vs-code-designer` app. The changes primarily focus on simplifying the code and improving the readability. The `projectRoot` parameter has been removed from the `generateDeploymentScripts` function, and it is now defined within the function itself. The `connectionsData` object is now created using a ternary operator to avoid unnecessary conditionals. The `window` import has been removed and replaced with `vscode.window` for better clarity.
* Removed the `projectRoot` parameter from the `generateDeploymentScripts` function and defined it within the function using `vscode.Uri.file(projectPath)`.
* Simplified the creation of the `connectionsData` object using a ternary operator. Replaced …
> fix(vscode): Allow script generation without connections and click in project root

- libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchHeader/index.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts
Arjun helped increase the number of operations we can request for at once from 2.5k to 5k, speeding things up by a couple calls!
Operation search/browse should load a little quicker from this small change.
I also fixed a small UI bug in search, the dropdowns were not the right width after updating to V9 a few weeks ago.
Fixed screenshot below:
> feat(Designer): Increased browse operation request page size to 5k

- libs/designer-ui/src/lib/html/plugins/toolbar/helper/__test__/util.spec.ts
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/util.ts
Feature
Users are unable to use `class`-attribute-based styling in HTML editor, despite this being a valid use case. This was excluded at dev time in favor of `style`, but as `class` is still widely used, this change permits use of it.
This PR allows use of CSS `class` attributes, as well as various `<table>` attributes that users often rely on for formatting emails.
No
- **Please …
> feat(designer-ui): Allow makers to use `class` attributes and `table` styling in raw HTML

- apps/vs-code-designer/src/app/commands/binaries/validateAndInstallBinaries.ts
- libs/vscode-extension/src/lib/models/bundleFeed.ts
This pull request primarily focuses on renaming a property in the `IBundleDependencyFeed` interface and updating its references in the `validateAndInstallBinaries` function. 
* The `dotnetMulti` property in the `IBundleDependencyFeed` interface has been renamed to `dotnetVersions`. This change is to give a more accurate description of the property's purpose.
* In the `validateAndInstallBinaries` function, the reference to `dotnetMulti` has been updated to `dotnetVersions` to match the renamed property in the `IBundleDependencyFeed` interface.
> fix(vscode): Update bundle dependencies to dotnetVersions

- apps/vs-code-designer/src/app/tree/unitTestTree/index.ts
This pull request primarily focuses on refactoring the unit test tree structure in the `apps/vs-code-designer` application. The changes include importing a new utility function to get unit test names, removing the usage of the `path.basename(uri.fsPath)` to get the test name, and creating a new test item with the help of the imported utility function.
* Imported the `getUnitTestName` utility function to fetch the unit test name more accurately.
* Removed the usage of `path.basename(uri.fsPath)` to get the test name, which was previously used to create the test item.
*  Created a new test item using the `getUnitTestName` utility function and added it to the existing workflow test's children. This change also includes the removal of the existing file test return statement.
> fix(vscode): Update unit test tree when adding test file

- apps/vs-code-designer/src/app/commands/binaries/validateAndInstallBinaries.ts
- libs/vscode-extension/src/lib/models/bundleFeed.ts
Update bundle dependencies to dotnetVersions
Cherry-pick of following:
https://github.com/Azure/LogicAppsUX/pull/5014
> fix(vscode): Update bundle dependencies to dotnetVersions 

- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
Bug fix to ensure skipped actions and nonmockable actions are not mocked when a unit test is created from an existing run.
Skipped actions and nonmockable actions are mocked when a unit test is created from an existing run.
Only mockable actions that have the success or failed state are mocked.
No
> fix(designer): Ensure skipped actions are not mocked

- apps/docs/docs/tsg.mdx
This pull request includes a change to the `tsg.mdx` file in the `apps/docs/docs` directory. The change provides additional instructions on how to sanitize a HAR file before sending it, which includes uploading the file to a sanitizer tool, downloading the sanitized zip file, and then uploading this sanitized file as an attachment to the incident/issue.
> feat(docs): Add sanitizing instructions to HAR file

- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/HybridLogicAppsSteps/ConnectedEnvironmentStep.ts
- apps/vs-code-designer/src/app/commands/deploy/deploy.ts
- apps/vs-code-designer/src/app/commands/deploy/deployToFileShare.ts
- apps/vs-code-designer/src/app/tree/slotsTree/SlotTreeItem.ts
- apps/vs-code-designer/src/app/tree/subscriptionTree/SubscriptionTreeItem.ts
This pull request primarily focuses on expanding the deployment capabilities of the application, specifically allowing deployment to a file share. The changes also include some refactoring to improve the code efficiency and readability.
* Added a condition to check if the deployment is to a file share and if so, it calls the `deployToFileShare` function. Also, imported the `deployToFileShare` function from `deployToFileShare.ts`.
* Created a new file that contains the `deployToFileShare` function and other helper functions necessary for deploying to a file share.
* Refactored the telemetry properties to use the connected environment name instead of the container app name.
* Added `customLocation` and `fileShare` properties to the `SlotTreeItem` class.
* Modified the `SubscriptionTreeItem` …
> feat(vscode): Introduce connected environment and file share step

- apps/docs/docs/vscode.md
This pull request simplifies the steps for building a private vsix from the compiled project in the `vscode.md` file. The changes include replacing the initial three steps with two simpler ones. The new steps involve running a single command that compiles the project and packs it into a vsix file, and then confirming the successful creation of the vsix file.
* Replaced the initial three steps for building a private vsix with two simpler steps. The new steps involve running a command that compiles the project and packs it into a vsix file, and then confirming the successful creation of the vsix file.
> docs(vscode): Update build private vsix steps

- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
Bug fix to ensure unit test is editable if assertionString is modified to be invalid in the code view.
The designer from the unit test with the invalid assertionString does not render.
Designer renders and the invalid assertionString populates as blank.
No
> fix(designer): Fixed invalid assertionStrings preventing editing of unit test

- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/mockResultsTab/mockResultsTab.tsx
Work item Link: https://msazure.visualstudio.com/One/_workitems/edit/28661067
- **What kind of change does this PR introduce?** 
Bug fix
- **What is the current behavior?**
The Mock Results Tab displays a blank page when a user selects an action with no mockable outputs, leading to confusion as there is no indication that no mockable outputs are available.
The Mock Results Tab now displays a message indicating that no mockable outputs are available for the selected action, providing clarity to the user and improving the user experience.
- **Does this PR introduce a breaking change?**
No breaking changes. Users will not need to make any changes to their application due to …
> fix(designer): Fix empty mock results tab when mock unsupported 

- libs/designer/src/lib/core/state/templates/templateSlice.ts
- libs/designer/src/lib/ui/styles.less
- libs/designer/src/lib/ui/templates/connections/connector.tsx
- libs/designer/src/lib/ui/templates/index.tsx
There was an issue with the import path given for dynamic imports and according to this limitation https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations this was only failing when integrated in portal.
> fix(templates): Fixing dynamic imports of workflow images to always contain hard coded extension

- apps/vs-code-designer/src/app/commands/workflows/switchToDotnetProject.ts
Bug fix to add parameters.json to the csproj file when converting to a .Net project
parameters.json file is not properly included in the resulting .csproj file, which causes build issues when opened in VSCode or Visual Studio
converted file opens and builds properly in VSCode
No
N/A
> fix(vscode): Add Parameters.json in .Net project conversion

- apps/vs-code-designer/src/app/tree/unitTestTree/index.ts
Bug fix
1. When a new unit test is created, it cannot be run from the unit test blade
2. When a unit test is deleted, it continues to appear in the unit test blade
1. When a new unit test is created, it can immediately be run from the unit test blade
2. When a unit test is deleted, it is removed from the unit test blade
No
> fix(designer): Fixed unit test blade bugs for created/deleted tests

- libs/logic-apps-shared/src/designer-client-services/lib/consumption/manifests/functions.ts
The function operation's output token `body` was previously not appearing.
Having type = `any` was an invalid value, removing it makes the token appear as expected
Fixes https://github.com/Azure/LogicAppsUX/issues/5122
> fix(designer): Fixed function operation output body token issue

- libs/designer/src/lib/core/state/unitTest/unitTestSlice.ts
[work Item Link](https://msazure.visualstudio.com/One/_workitems/edit/28547983)
Bug fix
When an assertion is deleted, the "Assertion name already exists." warning continues to display even though the assertion with the duplicate name has been removed.
The validation errors are cleared and revalidated when an assertion is deleted. This ensures that the "Assertion name already exists." warning is removed when the assertion with the duplicate name is deleted. Additionally, all remaining assertions are revalidated to ensure the state is consistent.
1. Updated the `deleteAssertion` reducer to call `checkAssertionsErrors(state)` after deleting an assertion and its associated validation errors. This ensures that the validation errors are cleared and revalidated after the deletion.
2. Ensured …
> fix(designer): allow designer to revalidate assertions when it is deleted

- apps/vs-code-designer/src/app/commands/workflows/switchToDotnetProject.ts
Fit and Finish: Refactor GetArtifactNamesFromProject to separate the parameters.json file into its own separate artifact class to remove ambiguity with the connections.json file
Strict refactoring, no behavior change
Strict refactoring, no behavior change
No
Strict refactoring, no behavior change
> fix(vscode): Refactor Parameters.json into a separate artifact class when converting to NuGet project

- libs/designer-ui/src/lib/card/scopeCard/index.tsx
- libs/designer-ui/src/lib/card/subgraphCard/index.tsx
- libs/designer-ui/src/lib/nodeCollapseToggle/index.tsx
Scope nodes' expand/collapse toggle was not triggerable via keyboard, it would instead open the nodes' details panel.
This has been fixed and scope nodes can now be expanded / collapsed via keyboard.
> fix(designer): Fixed scope node collapse button keyboard interaction

- libs/designer-ui/src/lib/editor/base/utils/__test__/editorToSegment.spec.ts
- libs/designer-ui/src/lib/editor/base/utils/__test__/parsesegments.spec.ts
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/__test__/util.spec.ts
- libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts
- libs/logic-apps-shared/src/parsers/lib/common/helpers/__test__/keysutility.spec.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/color.spec.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/functions.spec.ts
Vitest does not support Jest's `%p` in `.each` test names (see [`.each` in Vitest docs](https://vitest.dev/api/#test-each)). Upon transition from Jest to Vitest, these were not updated. This PR updates those to their equivalent value.
Example change in test names before and after:
> test(all): Switch use of `%p` in `it.each` to specific parameter types for Vitest compat

- libs/designer/src/lib/ui/panel/connectionsPanel/selectConnection/__test__/selectConnection.helpers.spec.ts
- libs/designer/src/lib/ui/panel/connectionsPanel/selectConnection/connectionTable.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/selectConnection/selectConnection.helpers.ts
Bug fix
Email is not shown in connection table if connection object uses `accountName` instead of `authenticatedUser`.
Connection table shows email regardless of format.
No
> fix(designer): Add support for `accountName` field

- libs/designer-ui/src/lib/panel/panel.less
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/connectionDisplay.tsx
When side panel is narrow, connection information (below parameter inputs) wraps very awkwardly and can flow off the screen if a connection name is too long.
Even in narrow side panels, connection information wraps correctly, and ellipsis is used if connection name is too long.
UI changes only.
> fix(designer-ui): Fix wrapping of connection display when panel is narrow

- libs/designer-ui/src/lib/html/plugins/toolbar/Format.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/buttons/FormatBoldButton.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/buttons/FormatButton.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/buttons/FormatItalicButton.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/buttons/FormatLinkButton.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/buttons/FormatUnderlineButton.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/buttons/HtmlViewToggleButton.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/buttons/RedoButton.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/buttons/UndoButton.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/hooks/useCloseDropdownOnScroll.ts
Formatting buttons in the WYSIWYG toolbar are all hosted within `Format.tsx`, making them difficult to reuse or extend.
All formatting buttons have been moved to their own reusable components. This change is similar to what was done in #5158, and will be used in future work.
No functional or breaking changes. Refactoring only.
> fix(designer-ui): Extract toolbar format buttons into component files

- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/http.ts
This pull request primarily involves changes to error handling in two functions, `loadDynamicValuesForParameter` and `fetchDynamicValuesForParameter`, within the `libs/designer/src/lib/core/utils/parameters/helper.ts` file. The changes improve the way error messages are extracted from the error object, allowing for more robust error handling.
* In both `loadDynamicValuesForParameter` and `fetchDynamicValuesForParameter`, the error message extraction logic has been modified. Now, it first checks if the error has a `response` property before trying to extract the `data` property. If there's no `response` property, it falls back to the `data` property of the error object. This change ensures that the appropriate error message is extracted and displayed, even if the error object structure …
> fix(vscode): Add validation for error response structure

- libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/http.spec.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/http.ts
This pull request includes changes to the `libs/logic-apps-shared` package, specifically to the `http` utility and its associated tests. The changes primarily focus on enhancing the error handling capabilities of the `parseErrorMessage` function and ensuring its behavior is thoroughly tested.
* The `parseErrorMessage` function has been modified to ensure that if `error.data.error.message` is not available, `undefined` is returned instead of potentially returning a truthy value that isn't a message. This change ensures that the function's behavior is more predictable and consistent.
* A comprehensive suite of tests for the `parseErrorMessage` function has been added. These tests cover various scenarios to ensure the function behaves as expected when provided with different types and …
> feat(designer): Add unit testing for parseErrorMessage function

- libs/designer/src/lib/core/utils/loops.ts
Previously if you had an action's output being split by a foreach node, if you added a token from the split value to a nested action, the token would be defined as `item()['key']` rather than `items('foreach_action')['key']`.
The issue here was that the `items()` token relied on having arrayData for the parent foreach, and the population of that arrayData was only being called if we were creating the foreach node as well.  If the node already existed, we skipped it and thus add a `item()` token instead.
In this PR I removed the check on if we are creating a new foreach node, instead populating the array details both if we create a foreach, and if it already exists.
Fixes https://github.com/Azure/LogicAppsUX/issues/5119
> fix(Designer): Fixed foreach dynamic item() / items() token issue

- libs/logic-apps-shared/src/utils/src/lib/models/connection.ts
Fields for object & tenant IDs are missing from `ConnectionProperties.authenticatedUser`.
Above fields have been added.
No breaking changes.
> fix(shared): Add `objectId` and `tenantId` to `authenticatedUser`

- libs/designer/src/lib/core/state/designerView/designerViewInterfaces.ts
- libs/designer/src/lib/core/state/designerView/designerViewSelectors.ts
- libs/designer/src/lib/core/state/designerView/designerViewSlice.ts
- libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
- libs/designer/src/lib/ui/CustomNodes/SubgraphCardNode.tsx
- libs/designer/src/lib/ui/common/DeleteModal/DeleteModal.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
When a node is deleted, it is first "selected". This is not problematic today where it is possible to select only one node at a time, but to support future work where multiple nodes may be selected, it is not sufficient.
Node deletion modal is decoupled from selected node. It now tracks its own node ID for deletion.
The `useShowDeleteModal` selector is not exported so there should be no breaking changes.
Below illustrates post-change, functionality remains intact as it exists today.
> feat(designer): Allow deleting a node without affecting selected node ID in state

- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/LogicAppHostingPlanStep.ts
- apps/vs-code-designer/src/app/commands/deploy/storageAccountSteps/CustomLocationStorageAccountStep.ts
- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
- apps/vs-code-designer/src/app/tree/subscriptionTree/SubscriptionTreeItem.ts
This pull request primarily focuses on changes in the `vs-code-designer` application, specifically in the `createLogicAppSteps` and `openDesigner` commands. The changes include the importation of new modules, the modification of method parameters, and the update of API versions. The changes aim to enhance the application's functionality and maintain its compatibility with the latest API versions.
1. Changes in `LogicAppHostingPlanStep.ts`:
* Imported `CustomLocationListStep`, `sendAzureRequest`, and `HTTP_METHODS` from their respective modules. These new imports are used in the subsequent changes in this file.
* In the `getSubWizard` method, the logic was updated to add `CustomLocationListStep` and `ResourceGroupListStep` to `promptSteps` when `useHybrid` is true. A new method …
> feat(vscode): Add stage regions for deployment and sql connection string for hybrid

- apps/vs-code-designer/src/app/commands/deploy/storageAccountSteps/CustomLocationStorageAccountStep.ts
This pull request includes a change to the `CustomLocationStorageAccountStep` class in the `apps/vs-code-designer/src/app/commands/deploy/storageAccountSteps/CustomLocationStorageAccountStep.ts` file. The change modifies the condition in the `getSubWizard` method to check for `useHybrid` instead of `customLocation` in the `wizardContext` object.
> fix(vscode): Add hybrid in decision for storage account SQL

- libs/designer/src/lib/ui/styles.less
Fluent had a few styling changes that were a part of the recent update.
These changes were only visible in portal.
We don't see them in standalone since we are importing both the new and the old files in standalone (since data-mapper-v1 is still using old react-flow)
I've adjusted our styling to fix these two issues.
---
> fix(designer): Fixed small portal css issue with upgrading reactflow

- libs/designer-ui/src/lib/panel/panelUtil.ts
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/aboutTab.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/codeViewTab.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/monitoringTab/monitoringTab.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/requestTab.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/retryTab.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/settingsTab.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
- libs/designer/src/lib/ui/settings/__tests__/settingsection.spec.tsx
- libs/designer/src/lib/ui/settings/index.tsx
- libs/designer/src/lib/ui/settings/sections/datahandling.tsx
- libs/designer/src/lib/ui/settings/sections/general.tsx
- libs/designer/src/lib/ui/settings/sections/networking.tsx
- libs/designer/src/lib/ui/settings/sections/runafter.tsx
- libs/designer/src/lib/ui/settings/sections/security.tsx
- libs/designer/src/lib/ui/settings/sections/tracking.tsx
- libs/designer/src/lib/ui/settings/settingsection.tsx
The tabs in the panel are tightly coupled with the `useSelectedNodeId()` selector property from the state, meaning that no matter how a tab is rendered or what its parent is, it will always show the Redux state's selected node.
The tabs in the panel are now decouple from the `useSelectedNodeId()` selector, and instead use a prop, allowing `nodeDetailsPanel.tsx` to decide which node should be rendered in the panel.
There should be no breaking changes, just a refactor to pass values from the Redux state higher in the React hierarchy.
> feat(designer): Decouple panel tabs from `useSelectedNodeId()`

- libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheader.spec.tsx.snap
- libs/designer-ui/src/lib/panel/panelheader/panelheader.tsx
Fixes an issue where the autofocus property on one of our fluent buttons was causing a large amount of console errors.
Fixes: https://github.com/Azure/LogicAppsUX/issues/5189
> fix(designer): Fixed fluent `autoload` property causing console error issue

- libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheader.spec.tsx.snap
- libs/designer-ui/src/lib/panel/panelheader/panelheader.tsx
Fixes an issue where the autofocus property on one of our fluent buttons was causing a large amount of console errors.
Patching into version 4.44
> fix(designer): Fixed fluent autoload property causing console error issue

- libs/designer-ui/src/lib/panel/panel.less
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/connectionDisplay.tsx
A badge is shown to reveal the reason a connection is in read-only state, if specified.
No breaking changes. Some class name changes.
> feat(designer-ui): Add badge for read-only connection to show reason

- libs/designer/src/lib/core/utils/parameters/helper.ts
This pull request includes changes to the `updateDynamicDataInNode` function in the `helper.ts` file to improve error handling and ensure that only valid parameters are added to the `parameterDynamicValues` array.
Key changes include:
*  Modified the `updateDynamicDataInNode` function to store the result of `fetchDynamicValuesForParameter` in a variable and check if it is not null or undefined before pushing it to the `parameterDynamicValues` array.
> fix(designer): Add validation for parameters with dynamic values

- libs/designer-ui/src/lib/panel/__test__/__snapshots__/panelcontainer.spec.tsx.snap
- libs/designer-ui/src/lib/panel/panel.less
- libs/designer-ui/src/lib/panel/panelcontainer.tsx
- libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheader.spec.tsx.snap
- libs/designer-ui/src/lib/panel/panelheader/panelheader.tsx
- libs/designer/src/lib/ui/Designer.tsx
If using left-side panel, pinned nodes cause incorrect padding, show the pinned node on the right instead of left, and prevent the collapse chevron from appearing in the correct place. (See screenshots section.)
Padding, button position, and node order has been corrected. (See screenshots section.)
No major impact.
> fix(designer-ui): Fix UI issues with pinned node when using left-side panel

- libs/designer/src/lib/core/graphlayout/__test__/elklayout.spec.ts
- libs/designer/src/lib/core/graphlayout/elklayout.ts
- libs/designer/src/lib/ui/CanvasFinder.tsx
- libs/designer/src/lib/ui/Designer.tsx
- Split the focusNode and initialization centering logic apart
- Moved CanvasFinder component to it's own file
- Fixed issue where width and height were not being passed to operation nodes
Fixes https://github.com/Azure/LogicAppsUX/issues/5224
> fix(designer): Canvas properly centered on load

- libs/designer/src/lib/core/utils/parameters/helper.ts
Prior to #5207, there was a bug where an `undefined` parameter could be passed despite the invoked method not accepting `undefined`, due to a use of `any`. This was fixed in #5207 by adding an `!isNullOrUndefined` check, but the typing was not updated to force this constraint, meaning that the removal of that conditional still compiles:
Types have been updated to force the requirement that no item is `undefined`:
No breaking changes.
> fix(designer): Improve types in `updateDynamicDataInNode` to prevent issues

- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/swagger/inputsbuilder.ts
This PR fixes an issue where during parameter value initialization, some parameters do not seem to be read from the initial workflow data properly.
After investigating, what appears to be happening is that if we have body parameters with a nested path like the following `body.feature.test`, our initialization logic on some connectors/actions would first read `body.feature` and the value would be the object `{ test:  value }`.  This is an issue because we also have logic in place that removes read values from the object we pull the values from (to track which parameter values are not used, then we treat them as invisible parameters).  After we remove the parent data, if we dig in to try and reach the `test` parameter, it will have been removed by the prior read.
To fix this, I created a …
> fix(designer): Fixed issue with some advanced parameters not initializing properly

- apps/vs-code-designer/src/app/utils/codeless/connection.ts
Added telemetry for expired connection keys and information message when keys have been refreshed.
> feat(vscode): Add telemetry for refreshing expired connection keys

- libs/designer-ui/src/lib/panel/__test__/__snapshots__/panelcontainer.spec.tsx.snap
- libs/designer-ui/src/lib/panel/panelcontainer.tsx
This is a hotfix for some focus-related issues we are seeing in Power Automate after taking v4.45.
The code affected in this change is no longer in main branch, so this PR addresses the issue directly in v4.45.
> fix(designer-ui): Remove `forceFocusInsideTrap` attribute (v4.45 only)

- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForAzureResource.ts
- apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForAzureResource.ts
- apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForLocal.ts
Send node local settings to monitoring view in remote app
> fix(vscode): Load node settings to monitoring view in remote app

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/__test__/createConnection.spec.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/tenant.ts
Tenant picker is shown even if tenant service is not provided, resulting in an error:
Tenant picker is only shown if tenant service is provided.
No breaking changes.
> fix(designer): Do not show tenant picker if tenant service is not enabled

- libs/designer-ui/src/lib/ariaSearchResults/ariaSearchResultsAlert.tsx
If `showAlert` is `false`, `AriaSearchResultsAlert` will return `undefined`. This is [valid in React 18](https://github.com/reactwg/react-18/discussions/75), but not prior versions, and results in [an error](https://react.dev/errors/152?invariant=152&args%5B%5D=Tp):
We now return `null` instead of `undefined` which is valid in React versions 17 and lower.
No breaking changes.
> fix(designer-ui): Prevent `AriaSearchResultsAlert` from returning `undefined`

- downloadTemplates.js
- libs/designer-ui/src/lib/panel/panelheader/panelheader.tsx
Our panel focus code was a little too aggressive and was firing off when users would be renaming a node.
Each keypress would send focus to the collapse button.
This PR just removes the focus useEffect that caused this.
We have a refactored panel component in main and this is not an issue, this functionality will be returned in our next release.
> fix(designer): Fix node rename focus issue

- apps/vs-code-designer/src/app/utils/bundleFeed.ts
Fixes extension bundle URL for dependencies
> fix(vscode): Auto Runtime Dependencies installation of latest FuncCoreTools

- downloadTemplates.js
- libs/designer/src/lib/core/state/templates/templateSlice.ts
* [] Bug fix
Uses URL to load template images
Uses file stream to download the image, then uses the relative url to load the image
> feat(Templates): Download Template Image Instead of Using URL

- apps/vs-code-designer/src/app/commands/appSettings/downloadAppSettings.ts
- apps/vs-code-designer/src/app/utils/appSettings/localSettings.ts
Sometimes workflow-designtime local.settings.json has the key AzureWebJobsSecretStorageType removed and AzureWebJobsStorage added.
Ensures that the workflow-designtime local.settings.json has the key AzureWebJobsSecretStorageType with the approriate value and AzureWebJobsStorage removed.
This change should prevent users from encountering the following host start up error:
"Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'."
> fix(vscode): Fixed issue where isDesignTime is not set properly and to correct workflow-designtime local.settings.json

- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/HybridLogicAppsSteps/ContainerAppNameStep.ts
- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/LogicAppHostingPlanStep.ts
This pull request introduces a new step for creating Logic Apps in hybrid environments, ensuring that container app names are validated and unique within a resource group. The key changes include the addition of the `ContainerAppNameStep` class and its integration into the existing Logic App creation workflow.
* Introduced `ContainerAppNameStep` class to prompt for and validate container app names. This class ensures that the names are unique within the specified resource group and meet naming conventions.
* Imported `ContainerAppNameStep` to integrate it into the Logic App creation steps.
* Modified the `LogicAppHostingPlanStep` class to include `ContainerAppNameStep` in the prompt steps for hybrid plans, ensuring container app names are validated during the creation process.
> feat(vscode): Introduce check for duplicate names in container app

- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
- libs/data-mapper-v2/src/ui/hooks/useAutoLayout.ts
Updating the Auto-layout logic so it only updates the position on first load and also only when there are intersecting function-nodes.
This prevents any auto-layout when a new function node is added (Day 0 scenario)
> fix(Data Mapper): Update auto layout logic to only run when there are intersecting nodes on canvas

- libs/designer-ui/src/lib/copyinputcontrol/copyinputcontrol.less
- libs/designer-ui/src/lib/styles.less
This pull request includes changes to the `libs/designer-ui` library, specifically focusing on the `copyinputcontrol` component's styles. The most important changes involve removing background colors for input elements and updating the main styles file to include the `copyinputcontrol` styles.
* Removed the background color for the input element in the default theme.
* Removed the background color for the input element in the dark theme.
* Added an import statement for the `copyinputcontrol` styles.
> fix(designer): Import copy control CSS

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/__test__/mocks/connectionParameters.ts
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
- libs/logic-apps-shared/src/utils/src/lib/models/connector.ts
- Removed oauth tenant selection for connectors that were not supposed to have it
- Now dependent on the `tenantId` custom parameter in the oAuthSettings
Fixes https://github.com/Azure/LogicAppsUX/issues/5293
> fix(Designer): OAuth tenant selection visibility logic fix

- libs/designer/src/lib/ui/common/EdgeContextualMenu/EdgeContextualMenu.tsx
Fixed edge context menu positioning.
The position values being passed were relative to the viewport, so we need to use `fixed` to position relative to the viewport.
> fix(designer): Fixed edge context menu positioning

- libs/designer-ui/src/lib/panel/__test__/__snapshots__/panelcontainer.spec.tsx.snap
- libs/designer-ui/src/lib/panel/__test__/panelcontainer.spec.tsx
- libs/designer-ui/src/lib/panel/panelUtil.ts
- libs/designer-ui/src/lib/panel/panelcontainer.tsx
- libs/designer-ui/src/lib/styles.less
- libs/designer/src/lib/ui/Designer.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
- libs/designer/src/lib/ui/panel/panelRoot.tsx
This reverts commit a38b9e3381ea69dca86007d7c02e254b33492f4a
The changes to the panel were causing the height to be unrestricted with no scrolling behavior
> fix(designer): Fixed scrolling issue on panels

- libs/designer-ui/src/lib/panel/__test__/__snapshots__/panelcontainer.spec.tsx.snap
- libs/designer-ui/src/lib/panel/__test__/panelcontainer.spec.tsx
- libs/designer-ui/src/lib/panel/panelUtil.ts
- libs/designer-ui/src/lib/panel/panelcontainer.tsx
- libs/designer-ui/src/lib/styles.less
- libs/designer/src/lib/ui/Designer.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
- libs/designer/src/lib/ui/panel/panelRoot.tsx
This reverts commit https://github.com/Azure/LogicAppsUX/commit/a38b9e3381ea69dca86007d7c02e254b33492f4a
The changes to the panel were causing the height to be unrestricted with no scrolling behavior
> fix(designer): Fixed scrolling issue on panels (v4.57)

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
- libs/designer-ui/src/lib/panel/__test__/__snapshots__/panelcontainer.spec.tsx.snap
- libs/designer-ui/src/lib/panel/__test__/panelcontainer.spec.tsx
- libs/designer-ui/src/lib/panel/panelUtil.ts
- libs/designer-ui/src/lib/panel/panelcontainer.tsx
- libs/designer-ui/src/lib/styles.less
- libs/designer/src/lib/core/DesignerProvider.tsx
- libs/designer/src/lib/ui/Designer.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
- libs/designer/src/lib/ui/panel/panelRoot.tsx
Reuse of `height: 100%` causes some issues w/ designer height and panel height. See also #5384.
Containers are now properly aligned using flex sizing attributes to prevent reuse of `height: 100%`.
I've verified this change works in:
- Power Automate Portal (requires adding `display: flex` to `.fl-V3DesignerPage-innerContainer` in host code base)
- LAUX standalone w/ top command bar
- LAUX standalone w/ floating command bar
I am unable to test in Logic Apps Portal.
> fix(designer): Un-revert panel changes & fix sizing to accommodate that change

- .github/ISSUE_TEMPLATE/bug_report.yml
This pull request includes a small but important change to the bug report issue template to improve the clarity and completeness of bug reports.
* Added a new dropdown field to capture the operating system being used by the reporter.
> meta(bugs): Add operating system dropdown for bug report

- e2e/designer/TokenPicker.spec.ts
This pull request includes enhancements to the `e2e/designer/TokenPicker.spec.ts` file, focusing on improving the test coverage for the Expression Editor and dynamic content handling.
Enhancements to test coverage:
* Added a new test case to verify that the Expression Editor works correctly with dynamic content. The test navigates to the mock workflow, interacts with the Parse JSON operation, and checks the visibility and content of the Expression Editor. (`e2e/designer/TokenPicker.spec.ts`)
* Included additional steps in the test setup to interact with the Parse JSON operation and the Content field, ensuring that the Expression Editor is properly triggered. (`e2e/designer/TokenPicker.spec.ts`)
> test(designer): Add smoke test for expression editor including dynamic content

- apps/vs-code-designer/src/app/commands/workflows/unitTest/createUnitTest.ts
- apps/vs-code-designer/src/assets/UnitTestTemplates/TestClassFile
- apps/vs-code-designer/src/assets/UnitTestTemplates/TestProjectFile
[work Item Link](https://msazure.visualstudio.com/One/_workitems/edit/29074612)
Currently, the Logic Apps extension only supports creating unit tests using the designer panel (codeless scenario). There is no option to create a C# unit test project for developers who prefer a code-first approach.
This PR adds the ability to create an empty C# unit test project when users choose the "codeful" scenario from both the "Show run" UI and the right click "create unit test" command from a workflow. The new feature:
1. Prompts the user to choose between "codeless" and "codeful" scenarios
2. For the "codeful" scenario, creates a new C# test project with:
- A .csproj file
- A test class file with sample unit tests
- Necessary folder structure and configuration
This change enhances the existing …
> feat(vscode): Add C# Unit Test Project Creation for Logic Apps

- libs/designer-ui/src/lib/combobox/helpers/__test__/isComboboxItemMatch.spec.ts
- libs/designer-ui/src/lib/combobox/helpers/isComboboxItemMatch.ts
- libs/designer-ui/src/lib/combobox/index.tsx
If an invalid regular expression (can be as simple as `[` or something large and complex like in my GIFs) is entered into the search input for a combobox, the designer will crash.
All input into combobox is permitted.
Not a breaking change.
> fix(designer-ui): Prevent designer crashing when invalid regex is entered into combobox

- apps/vs-code-designer/src/package.json
The current Logic Apps extension does not include the C# Dev Kit as a dependency, meaning users have to manually install the C# development tools and xUnit testing framework support.
[Work Item Link](https://msazure.visualstudio.com/One/_workitems/edit/29074630)
With this change, the C# Dev Kit will be automatically installed alongside the Logic Apps extension. The C# Dev Kit supports the xUnit testing framework, which will be leveraged in the frontend for implementing the unit test codeful approach. This ensures that users have the necessary tools for C# development and xUnit testing without any additional manual installation steps.
N/A
> feat(vscode): Added C# dev kit as a Dependency to Logic Apps

- libs/designer-ui/src/lib/html/plugins/toolbar/helper/HTMLChangePlugin.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/util.ts
This pull request focuses on improving the handling of encoded and decoded values in the HTML editor plugin. The main changes involve ensuring that values are properly encoded and decoded at the correct stages of processing.
* Modified `convertEditorState` to decode the `id` attribute value before processing and re-encode it afterward.
* Updated `canReplaceSpanWithId` to encode the key value before comparison.
* Adjusted `getDomFromHtmlEditorString` to encode the wrapped HTML string before sanitization and decode it afterward.
https://github.com/user-attachments/assets/650e4490-4405-42bc-9e57-5f27ccfdad83
Fixes #5487 
- When getting the `element.getAttribute('id')` the class wasn't getting decoded therefore token didn't match the id of the tag element. Was getting …
> fix(designer): Encode and Decode tokens with html tags

- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
- libs/designer/src/lib/ui/CanvasFinder.tsx
- libs/designer/src/lib/ui/panel/nodeSearchPanel/nodeSearchPanel.tsx
This pull request includes several updates to the `workflowSlice` in the `libs/designer` module, focusing on managing the collapsed state of graph nodes. The changes introduce new actions to handle the collapsed graph IDs and update the relevant components to use these new actions.
Fixes #5495 
Fixes #5486 
- Added `setCollapsedGraphIdsFromNodeId` and `clearCollapsedGraphIds` actions to manage the collapsed state of graph nodes.
- Removed the call to `getParentsUncollapseFromGraphState` from the `setFocusNode` action.
- Exported the new actions from the slice.
- Imported and dispatched the `clearCollapsedGraphIds` action in the `CanvasFinder` component. 
- Imported and dispatched the `setCollapsedGraphIdsFromNodeId` action in the `NodeSearchPanel` component. …
> fix(designer): Set aside collapsed slice action when search and clear them when found

- libs/data-mapper-v2/src/components/canvas/ReactFlow.tsx
- libs/data-mapper-v2/src/components/common/DropdownTree.tsx
- libs/data-mapper-v2/src/components/common/reactflow/CanvasNode.ts
- libs/data-mapper-v2/src/components/common/reactflow/CanvasNode.tsx
- libs/data-mapper-v2/src/components/common/reactflow/edges/IntermediateConnectedEdge.tsx
- libs/data-mapper-v2/src/components/common/reactflow/styles.ts
- libs/data-mapper-v2/src/components/schema/tree/RecursiveTree.tsx
- libs/data-mapper-v2/src/components/schema/tree/SchemaTree.tsx
- libs/data-mapper-v2/src/components/schema/tree/useNodePosition.ts
- libs/data-mapper-v2/src/constants/ReactFlowConstants.ts
- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
- libs/data-mapper-v2/src/ui/styles.ts
- libs/data-mapper-v2/src/utils/Edge.Utils.ts
- libs/data-mapper-v2/src/utils/Schema.Utils.ts
With Connections
One set of Connections scrolled away
All source and target scrolled away
> feat(Data Mapper): Show connections when one node is scrolled out

- libs/designer/src/lib/core/state/workflow/__test__/workflowSelectors.spec.ts
- libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
- libs/designer/src/lib/ui/CanvasFinder.tsx
- libs/designer/src/lib/ui/panel/nodeSearchPanel/nodeSearchPanel.tsx
This pull request includes several changes to the workflow state management and related tests in the `libs/designer` directory. The changes focus on improving the handling of collapsed graph IDs and simplifying the related code.
* Modified the `reduceCollapsed` function to handle children more efficiently by using a conditional spread operator. Updated `getParentsUncollapseFromGraphState` to only uncollapse nodes that are currently collapsed. 
* Refactored the `setCollapsedGraphIds` action to directly use `getParentsUncollapseFromGraphState`. Removed the `clearCollapsedGraphIds` action and simplified the export list accordingly. 
*  Updated tests to reflect the changes in how collapsed graph IDs are handled. Replaced individual test cases with a `describe` block for better organization …
> fix(designer): Reduce children for nodes that only have children

- libs/designer/src/lib/core/state/workflow/__test__/workflowSelectors.spec.ts
- libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
- libs/designer/src/lib/ui/CanvasFinder.tsx
- libs/designer/src/lib/ui/panel/nodeSearchPanel/nodeSearchPanel.tsx
Cherry-pick of the following:
https://github.com/Azure/LogicAppsUX/pull/5509
https://github.com/Azure/LogicAppsUX/pull/5515
> fix(designer): Set aside collapsed slice action when search and reduce children for nodes that only have children

- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
- libs/designer-ui/src/lib/tokenpicker/index.tsx
- libs/designer-ui/src/lib/tokenpicker/nl2fExpressionAssistant.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickeroption.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickersection.tsx
- libs/designer-ui/src/lib/tokenpicker/util.ts
- libs/logic-apps-shared/src/designer-client-services/lib/copilot.ts
- libs/logic-apps-shared/src/utils/src/lib/models/index.ts
- libs/logic-apps-shared/src/utils/src/lib/models/token.ts
right now copilot is not given reference input data, making the ai expression builder not as great as a user experience as possible. 
Allow Copilot to reference dynamic input/data while creating expression, allowing for a better user experience.
> feat(designer): Allow Copilot to reference dynamic input/data while creating expression

- libs/designer/src/lib/core/utils/outputs.ts
- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
In OpenAPI flows, the output token are generated in a format that breaks the runtime:
@outputs('Get_items')?['body']?['body/value']
This PR covers a missing case of passing the alias-allowing flag for dynamic outputs, the tokens are now generated as expected (@outputs('Get_items')?['body/value']).
Addressing gap for OpenAPI that was introduced in a recent check-in, not affecting non-OpenAPI formats.
> fix(Designer): Patch the gap in aliasing flag for dynamic outputs

- libs/designer/src/lib/core/utils/outputs.ts
- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
Patch the gap in aliasing flag for dynamic outputs
> chore(meta): Cherry-pick fix to patch the gap in aliasing flag for dynamic outputs

- libs/designer-ui/src/lib/tokenpicker/index.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickersection.tsx
Fixed issue with making token-picker fullscreen
Fixed issue with token picker being slightly off the bottom of the screen
Cleaned up unnecessary size logic
// This is a cherry-pick into 4.71
> fix(Designer): Fixed token-picker fullscreen issue

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
- apps/Standalone/src/designer/app/SettingsSections/contextSettings.tsx
- apps/Standalone/src/designer/state/workflowLoadingSlice.ts
- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
- libs/designer/src/lib/core/actions/bjsworkflow/copypaste.ts
- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/actions/bjsworkflow/settings.ts
- libs/designer/src/lib/core/parsers/ParseReduxAction.ts
- libs/designer/src/lib/core/state/designerOptions/designerOptionsInterfaces.ts
- libs/designer/src/lib/core/utils/loops.ts
- libs/designer/src/lib/core/utils/outputs.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/swagger/operation.ts
- libs/logic-apps-shared/src/designer-client-services/lib/workflow.ts
Fixes #5420 
As part of changes have removed the hostOption - forceEnableSplitOn... I have added a method in WorkflowService for the host to implement if spliton is supported in an app.. if not specified this is always set to true. Only change is needed in LA portal for this to be implemented to we can set it to false for stateless workflow
> fix(designer): Setting split on supported and calculations correctly for stateless workflow

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/queries/connections.ts
- libs/designer/src/lib/core/utils/swagger/operation.ts
- libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/connectionEntry.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/selectConnection/connectionTable.tsx
- libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
In old designer, if a connection api id or a connection id did not have a `/` at the start of the id it would load the matching operations with no issue. In new designer this situation would cause the operation load to fail.
This PR just adds the `/` into the ids if they are missing in a few places
Fixes https://github.com/Azure/LogicAppsUX/issues/5436
> fix(Designer): Connection objects can now have ids without the starting slash

- libs/designer-ui/src/lib/picker/filepickerPopoverHeader.tsx
In certain cases (Azure Portal), file picker's Fluent overflow component can cause a render loop due to the length of `overflowItems` (as calculated by Fluent's `partitionBreadcrumbItems` method) switching between 0 and 1 constantly, provoked by `maxDisplayedItems` being updated based on `overflowItems`'s length.
`maxDisplayedItems` is hardcoded to 2, so that it cannot cause `overflowItems` to be updated accidentally.
- This may be a bug in Fluent, or may be a bug in how the component is coded
- In Power Automate, it seems that the overflow component simply does not render even in subfolders:
<br>![image](https://github.com/user-attachments/assets/98b28138-8e54-4a9d-a1b3-8b40a7395884)
> fix(designer-ui): Force `maxDisplayedItems: 2` to mitigate file picker render loop

- libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts
- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
Issue: When dynamic schema could not be fetched or returns empty parameters we always return the current dynamic schema parameter as the sole input, while doing so other dynamic data was not removed which caused the recursive call for dynamic schema [feature added in april]
> fix(designer): Fixing the recursive call in dynamic data load

- libs/designer/package.json
- libs/designer/src/lib/__test__/redux-test-helper.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/undoRedo.ts
- libs/designer/src/lib/core/state/__test__/undoRedoSlice.spec.ts
- libs/designer/src/lib/core/state/undoRedo/undoRedoSlice.ts
- libs/designer/src/lib/core/state/undoRedo/undoRedoTypes.ts
- pnpm-lock.yaml
Undo/redo is using zlib compression library. 
Updating undo/redo to use pako library instead as suggested.
No feature impact, just changing compression library. Undo/redo isn't live yet.
> fix(designer): Update undo/redo compression to use pako instead of zlib library

- libs/logic-apps-shared/src/designer-client-services/lib/base/connection.ts
Connection fetch is now recursive over nextlinks
Previously only showed first 30 results since we only made one request
Fixes https://github.com/Azure/LogicAppsUX/issues/5361
> fix(Designer): Connection fetch is now recursive over nextlinks

- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/utils/__test__/loops.spec.ts
- libs/designer/src/lib/core/utils/loops.ts
fixes #5425 
Tests are pending and will be covered in next iteration
> fix(designer): Correctly verify parents arrays are in spliton while adding implicit foreach

- libs/designer-ui/src/lib/picker/__test__/helpers.test.ts
- libs/designer-ui/src/lib/picker/filepickerEditor.tsx
- libs/designer-ui/src/lib/picker/filepickerPopover.tsx
- libs/designer-ui/src/lib/picker/filepickerPopoverHeader.tsx
- libs/designer-ui/src/lib/picker/filepickerPopoverItem.tsx
- libs/designer-ui/src/lib/picker/helpers.ts
- libs/designer/src/lib/core/queries/connector.ts
- libs/logic-apps-shared/src/designer-client-services/lib/connector.ts
- libs/logic-apps-shared/src/designer-client-services/lib/consumption/connector.ts
Issues with file picker:
- In Power Automate, the '...' breadcrumb sometimes does not show at all. **This is due to a bug in `react-breadcrumb` which was fixed in v9.0.4, while Power Automate currently uses v9.0.3. https://github.com/microsoft/fluentui/pull/30005**
- In Azure Logic Apps, browsing to a folder that would show the '...' breadcrumb can crash the page. (Mitigated with #5576)
- Following the mitigation for the above issue, only the first and last breadcrumb will ever show in the file picker header, even if there is room to show more.
- Long file names can render outside of the header container.
***Note:** I wanted to get `text-overflow: ellipsis` working on the header, but doing so requires adding `overflow: hidden` to the individual breadcrumb `li` element, which breaks …
> fix(designer-ui): Optimize file picker partitioning and fix overflow

- libs/designer/src/lib/core/actions/bjsworkflow/__test__/initialize.spec.ts
- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/utils/outputs.ts
- libs/designer/src/lib/core/utils/parameters/__test__/dynamicdata.spec.ts
- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
- libs/logic-apps-shared/src/designer-client-services/lib/operationmanifest.ts
- libs/logic-apps-shared/src/parsers/lib/common/schemaprocessor.ts
- libs/logic-apps-shared/src/parsers/lib/manifest/__test__/parser.spec.ts
- libs/logic-apps-shared/src/parsers/lib/manifest/parser.ts
This is a hotfix PR containing two reverts:
- #5537 (254a51ad644576335ea3422130cce4f79c32b06c)
- #5360 (2e27773cd24e5a67fd33a1656a789b3ec0d8c10a)
Unfortunately, the change to aliasing has broken us in other ways that were not fixed by our initial hotfix for v4.74.1. Therefore, we are reverting that hotfix, as well as the initial dynamic data aliasing change, until we can figure out how to fix the scenario entirely.
> chore(designer): Revert dynamic data aliasing changes in v4.74

- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
Regression was introduced few weeks back due to which nested dynamic schema was also adding the parent object as an input in inputs along with leaf parameters showing extra parameters, did not cause any issue in serialization just UI bug. Fixes #5624
> fix(designer): Removing parent object from dynamic inputs when parameter is nested

- apps/vs-code-designer/src/app/commands/pickFuncProcess.ts
- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
- apps/vs-code-designer/src/extensionVariables.ts
Upon Ctrl+Shift+P Reload Window selection or File -> Open Workspace From File..., when a logic app workspace is opened, the func.exe process is not always terminated.
func.exe processes launched by the extension is cleaned up.
This change should prevent users from having any linger func.exe instances which may cause instability when using any logic app extension features.
> fix(vscode): Extension cleanup

- libs/designer/src/lib/core/actions/bjsworkflow/__test__/initialize.spec.ts
- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/utils/outputs.ts
- libs/designer/src/lib/core/utils/parameters/__test__/dynamicdata.spec.ts
- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
- libs/logic-apps-shared/src/designer-client-services/lib/operationmanifest.ts
- libs/logic-apps-shared/src/parsers/lib/common/schemaprocessor.ts
- libs/logic-apps-shared/src/parsers/lib/manifest/__test__/parser.spec.ts
- libs/logic-apps-shared/src/parsers/lib/manifest/parser.ts
Our proposed fix (#5661) for the aliasing issues in Power Automate was not approved, so additional work is required before we can take aliasing changes.
This cherry-pick PR is mostly the same as #5621 but for v4.86. Looks like LA is using v4.85 and v4.88 but not v4.86 so this should not affect LA portal.
> This is a hotfix PR containing two reverts:
> 
> * #5537 (254a51ad644576335ea3422130cce4f79c32b06c)
> * #5360 (2e27773cd24e5a67fd33a1656a789b3ec0d8c10a)
> 
> Unfortunately, the change to aliasing has broken us in other ways that were not fixed by our initial hotfix for v4.74.1. Therefore, we are reverting that hotfix, as well as the initial dynamic data aliasing change, until we can figure out how to fix the scenario entirely.
Also reverting unit test changes made for the above PRs …
> chore(designer): Revert dynamic data aliasing changes in v4.86

- libs/designer-ui/src/lib/panel/panelcontainer.tsx
When the `suppressDefaultNodeSelectFunctionality` designer option is enabled we just hide the node details panel.
This was old behavior that got changed/removed during the panel refactor PA did.
The `suppressDefaultNodeSelectFunctionality` option is used in BPT to avoid opening the panel during our token selection over in BPT and this was noticed as broken upon updating.
> fix(Designer): Fixed issue with `suppressDefaultNodeSelectFunctionality`

- .versionrc
This pull request includes a small change to the `.versionrc` file. The change adds a new entry for the `libs/data-mapper-v2/package.json` file to the versioning configuration.
* [`.versionrc`](diffhunk://#diff-5530fb07101d34a455c1f664800f0f8d4f6424ce779af3f5c99d9517e3e7539dR25-R28): Added a new entry for `libs/data-mapper-v2/package.json` to the versioning configuration.
> chore(designer): Bump data mapper v2 version

- apps/vs-code-designer/src/assets/FunctionProjectTemplate/FunctionsProjNet8
This pull request includes a small but significant change to the `apps/vs-code-designer/src/assets/FunctionProjectTemplate/FunctionsProjNet8` file. The change ensures that local lock file assemblies are copied during the build process.
* Added the `CopyLocalLockFileAssemblies` property to ensure local lock file assemblies are copied.
> feat(vscode): Add copy file assemblies for .net 8 projects

- libs/logic-apps-shared/src/designer-client-services/lib/consumption/run.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
This pull request introduces logging enhancements and removes a content size check within the `ConsumptionRunService` and `StandardRunService` classes. These changes aim to improve the traceability and debugging capabilities of the services.
* Included a logging statement to log the content size in the `ConsumptionRunService` and `StandardRunService` class. 
* Removed the content size check that returned `undefined` if the size exceeded 262144 bytes.
Fixes: #5658
> feat(designer): Handle high content size in monitoring view 

- libs/designer/src/lib/core/actions/bjsworkflow/undoRedo.ts
- libs/designer/src/lib/core/utils/undoredo.ts
Cherry-pick: Parameters panel re-rendering on undo/redo should be after setting root state on undo/redo click (#5795)
* Update state history after setting root state on undo/redo click
* Add log for decompressed and compressed state sizes
---------
On undo/redo click, we update the state history item index (which is used to re-render parameters panel) before setting the root state. This causes the parameters panel to not re-render immediately on undo/redo click.
We now set the root state on undo/redo click first, then update state history on undo/redo click to update state history item index after, which would trigger re-rendering of parameters panel as expected.
Also added a log to track compressed vs decompressed size.
> chore(meta): Cherry-pick fix(designer): Parameters panel re-rendering on undo/redo should be after setting root state on undo/redo click

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/formInputs/legacyManagedIdentityPicker.tsx
Fixed issue where the legacy managed identity dropdown would show the first option as selected, but not actually have it selected. If you only had one managed identity this would prevent you from creating the connection.
> fix(Designer): Fixing issue with managed identity connection creation (4.105)

- apps/Standalone/src/designer/app/SettingsSections/contextSettings.tsx
- apps/Standalone/src/designer/state/workflowLoadingSlice.ts
- libs/designer/src/lib/core/parsers/ParseReduxAction.ts
- libs/designer/src/lib/core/state/designerOptions/designerOptionsInterfaces.ts
- libs/designer/src/lib/core/state/designerOptions/designerOptionsSlice.ts
- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
- libs/designer/src/lib/ui/panel/nodeSearchPanel/nodeSearchPanel.tsx
Added host option to collapse all graph nodes by default
Renamed existing redux action to be clearer
With the host option enabled the initial load is much faster, but we are essentially just delaying some of the elk/react flow graph initialization to when the graphs are expanded for the first time.  All "data" for the workflow is still being loaded at startup. (ie. if someone loads the flow and immediately saves, all the data will still be there)
Fixes https://github.com/Azure/LogicAppsUX/issues/4995
> feat(Designer): Added host option to collapse all graph nodes by default

- apps/vs-code-designer/src/README.md
This pull request includes an update to the `README.md` file for the Azure Logic Apps (Standard) extension in Visual Studio Code. The update introduces a new feature and provides relevant information and links.
New feature introduction:
* [`apps/vs-code-designer/src/README.md`](diffhunk://#diff-69c5b43bdf2eb0abae618f74af3299bd2be0f3184c8ebdbebdf45aa44e84f8fdR7-R10): Added a section about the Logic Apps Hybrid Deployment Model, which allows workflows to run on customer-managed infrastructure, including on-premises, private clouds, or third-party public clouds.
> docs(vscode): Add Logic Apps (Standard – Hybrid) announcement to vscode readme

- libs/designer/src/lib/core/templates/utils/helper.ts
- libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/quickViewPanel.tsx
- libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/summaryTab.tsx
- libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/workflowTab.tsx
- libs/designer/src/lib/ui/panel/templatePanel/templatePanel.tsx
- libs/designer/src/lib/ui/templates/cards/templateCard.tsx
- libs/designer/src/lib/ui/templates/templateoverview.tsx
- libs/logic-apps-shared/src/utils/src/lib/models/template.ts
Currently, we only have "isMultiWrokflowTemplate" upon template creation. In queries such as when users leave in template generation processes, we are unable to tell if it was a multi-workflow scenario. To be able to detect this, adding telemetry for all template telemetry cases.
> meta(Templates): Add Telemetry for Multi-Workflow for Non-Creation Scenarios

- apps/vs-code-designer/src/app/utils/credentials.ts
This pull request includes a small change to the `apps/vs-code-designer/src/app/utils/credentials.ts` file. The change modifies a condition to check for any logged-in sessions instead of more than one session.
*  Changed the condition from `currentLoggedInSessions.length > 1` to `currentLoggedInSessions.length > 0` to ensure the function handles any number of logged-in sessions.
> fix(vscode): Fix decision on amount of sessions

- libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
Adjusted workflow id path for getting child workflow.
The workflow id path during binding was changed, and this reference was not updated.
> fix(Designer): Fixed workflow ID path for getting child workflow

- .azure-pipelines/1esmain.yml
- .azure-pipelines/templates/stage-artifacts.yml
This pull request includes changes to the Azure Pipelines configuration to add a new parameter for publishing versions. The most important changes include modifying the `extends:` section in the main pipeline file and adding a new parameter definition in the `stage-artifacts.yml` template.
Pipeline configuration updates:
* Modified the `extends:` section to include a new `parameters` block for `publishVersion`.
* Added a new parameter definition for `publishVersion` to allow version specification during the artifact staging process.
> meta(vscdoe): Add parameter to template pipeline

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
Previously we were only sending data from the code view, but now we are just replacing the definition with the code view data
> fix(designer): Standalone Consumption Code view to pass in rest of workflow data

- libs/logic-apps-shared/src/designer-client-services/lib/base/connection.ts
Added null catches for broken connections.
We had a customer issue and their connection object somehow was missing the entire `API` object.
The catches added in this PR should filter those connections out since they are unusable without that data.
> fix(Designer): Null catch on connection query

- libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickeroption.tsx
You can now search for tokens by the section names.  This works with action names (with renaming), variables, etc.
Fixes https://github.com/Azure/LogicAppsUX/issues/6038
> feat(Designer): Adding section names to token search

- libs/designer/src/lib/ui/Designer.tsx
- libs/designer/src/lib/ui/common/DragPanMonitor/DragPanMonitor.tsx
Dragging a node to the edge of the canvas now pans in that direction.
This variable based on how close to the edge you are.
This also is clamped so you can't accidentally pan way off into no-man's-land.
Fixes https://github.com/Azure/LogicAppsUX/issues/6037
> fix(Designer): Canvas pans when dragging a node to the edge of the canvas

- libs/designer/src/lib/ui/panel/recommendation/browseView.tsx
If custom connectors had extra capabilities, our filtering was removing them from browse view.
This has now been fixed and we ignore the capabilities check only if it does not include both 'triggers' and 'actions'
> fix(Designer): Fixed custom connector browse with extra capabilities

- .gitignore
- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/base/appService.ts
Fixes https://github.com/Azure/LogicAppsUX/issues/6046
> fix(designer): Use Default swagger Host when api host is not set

- apps/vs-code-designer/src/app/commands/workflows/unitTest/createUnitTest.ts
- apps/vs-code-designer/src/assets/UnitTestTemplates/TestClassFile
- apps/vs-code-designer/src/assets/UnitTestTemplates/TestProjectFile
[Add `coverlet.collector` to package reference in generated `csproj`](https://msazure.visualstudio.com/One/_workitems/edit/30156094)
[Implement consistent handling of hyphens in `unitTestName` and `WorkflowName` inputs](https://msazure.visualstudio.com/One/_workitems/edit/30192393)
[Compile error - rootPath missing `this` reference](https://msazure.visualstudio.com/One/_workitems/edit/30199593)
[Formatting issue in mock generator helper doc comments](https://msazure.visualstudio.com/One/_workitems/edit/30199679)
[Uncomment `var actionMocks` in `PREPARE Mock` section](https://msazure.visualstudio.com/One/_workitems/edit/30199718)
- **[Bug][Frontend]** [Add `coverlet.collector` to package reference in generated `csproj`](#) to improve code coverage collection capabilities.
- …
> fix(vscode): Resolve Hyphen Handling, Mock Generator Formatting, and Add Missing Reference Errors in Templates

- libs/designer-ui/src/lib/editor/base/utils/keyvalueitem.ts
- libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/parameters/segment.ts
- libs/designer/src/lib/core/utils/validation.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/stringFunctions.spec.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
By default when stringifying expressions we were escaping the characters. However, this is quite confusing to the user, especially when handling something like `array(split(variables('something'), '\n'))` to be created by: 
```
array(split(variables('something'), '
'))
```
This PR was handling "unescaping" the default behavior of tokens before serialization and then re-escaping the characters before deserializing
Fixes: https://github.com/Azure/LogicAppsUX/issues/3496
I've also tested this to work on other editors (dictionary, authentication, etc)
Fixes https://github.com/Azure/LogicAppsUX/issues/6070 where quotes were being added unncessarily
Fixed a bug where authentication editor inputs were not being defaulted to string type
> feat(designer): No longer escapes characters in token expressions

- libs/logic-apps-shared/src/parsers/lib/swagger/parameterprocessor.ts
This pull request includes a small change to the `ParametersProcessor` class in the `libs/logic-apps-shared/src/parsers/lib/swagger/parameterprocessor.ts` file. The change removes the encoding of the `name` property of a parameter.
* Removed the `encodePropertySegment` function call for the `name` property, leaving the `name` property as is.
- Before
- After
> fix(designer): Remove encoding in parameter name

- libs/designer-ui/src/lib/html/plugins/toolbar/helper/util.ts
Ensures no untrusted content is ever directly added to the DOM
> fix(Designer): Prevent HTML editor from allowing DOM-based XSS

- libs/designer-ui/src/lib/styles.less
Fixed fluent drawer stutter caused by some generated CSS on the fluent component.
Also fixed an issue where we were rendering component shadows outside of our application bounds, just added `overflow: hidden` to our base component.
> fix(designer): Fixed fluent drawer stutter

- apps/vs-code-designer/src/app/commands/workflows/unitTest/createUnitTest.ts
This PR addresses an issue where the C# Dev Kit extension does not generate a `.sln` file automatically under certain conditions. The proposed fix introduces a new "Reload Window" button to simplify the user's experience. Additionally, the localized message to the user (`localize('info.generateCodefulUnitTest', 'Generated unit test "{0}" in "{1}"', unitTestName, unitTestFolderPath)`) has been removed as it is no longer necessary.
The `.sln` file generation is not triggered automatically under the following conditions:
- Opening a folder with multiple C# projects.
- Opening a C# project directly without an existing `.sln` file.
- Opening a multi-root workspace containing C# files across multiple folders.
For our use case (opening a C# project without an existing `.sln`), `.sln` file …
> fix(vscode): Simplify .sln File Generation with Reload Window Button

- apps/vs-code-designer/src/app/commands/createNewCodeProject/createNewCodeProject.ts
- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
This pull request includes changes to the `apps/vs-code-designer` project, focusing on code cleanup and removal of preview warnings. The most important changes include the consolidation of import statements and the removal of `showPreviewWarning` calls from specific functions.
Code cleanup:
* Consolidated import statements by removing unnecessary `extensionCommand` and `showPreviewWarning` imports.
* Removed the `extensionCommand` import as it is no longer needed.
> fix(vscode): Remove warning preview messages to non preview features

- libs/designer/src/lib/ui/settings/sections/general.tsx
This pull request includes changes to the `libs/designer/src/lib/ui/settings/sections/general.tsx` file to improve accessibility by updating the `ariaLabel` properties for better clarity.
Accessibility improvements:
* Updated `ariaLabel` from `concurrencyTitle` to `concurrencySubLabel` to provide a more accurate description.
* Updated `ariaLabel` from `concurrencyTitle` to `degreeOfParallelism` to ensure the label matches the slider's function.
Fixes #6096
> fix(designer): Accessibility - Set right aria label for concurrency control inputs

- apps/vs-code-designer/src/assets/UnitTestTemplates/TestNugetConfig
- apps/vs-code-designer/src/assets/UnitTestTemplates/TestProjectFile
**Title**: fix(vscode): Update `Microsoft.Azure.Workflows.WebJobs.Extension` Version and Correct NuGet Reference
The `.csproj` file currently references the `Microsoft.Azure.Workflows.WebJobs.Extension` package with version `1.96.*`, which needs to be downgraded to `1.94.*` for compatibility. Additionally, the NuGet reference in the `nuget.config` file was outdated and needed to be corrected to point to the most recent version of the `microsoft-azure-logicapp-test-sdk`.
The `.csproj` file has been updated to reference `Microsoft.Azure.Workflows.WebJobs.Extension` version `1.94.*` instead of `1.96.*`. The `nuget.config` file has also been updated to reference the latest version of the `microsoft-azure-logicapp-test-sdk`.
> fix(vscode): Update Microsoft.Azure.Workflows.WebJobs.Extension Version and Correct NuGet Reference

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Utilities/resourceUtilities.ts
- libs/designer/src/lib/core/queries/operation.ts
- libs/designer/src/lib/core/state/connection/connectionSelector.ts
Connector ID query is now only keyed as lowercase, the actual fetch is now done with the raw connector id.
We have a user in west-europe that is seeing different swagger responses seemingly due to a casing issue.
This is being merged to v5.2 just for a private slot deployment to confirm the issue.
// I also lowered our standalone page size to 500 since 1000k was failing due to response data size constraints.
> fix(Designer): Modified connector swagger fetch to have proper casing

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/base/connection.ts
This pull request includes several updates to the `AzureLogicAppsDesigner` and `BaseConnectionService` to enhance localization support and improve code consistency. The most important changes are summarized below:
* Added `locale` parameter to the `getDesignerServices` function to support localization in API requests.
* Updated `_getAzureConnector` and `_getOpenApiDocument` methods to include `Accept-Language` headers in API requests if `locale` is provided.
> fix(designer): Add locale to connections API call for connectors and swagger

- libs/designer/src/lib/ui/connections/edge.tsx
Converted our EdgeContent `foreignObject` to use the `EdgeLabelRenderer` component from `@xyflow/react`.
This was done due to some screen readers not being able to read the content inside the `foreignObject` element.
The `EdgeLabelRenderer` does not seem to have this issue and has no visual difference, while also being reachable by screen readers.
Fixes https://github.com/Azure/LogicAppsUX/issues/6106
> fix(Designer): Switched edge labels from foreign object to xyflow component

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
Just doing it to match our portal code
> fix(standalone): Passing Appsettings to standalone designer services

- libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/parameters/tokensegment.ts
Fixes https://github.com/Azure/LogicAppsUX/issues/6239
> fix(designer): Default nested items to use item token brandcolor/icon

- libs/designer-ui/src/lib/editor/base/utils/initialConfig.ts
Updating Lexical on this PR https://github.com/Azure/LogicAppsUX/pull/6213 ended up introducing a previously silently failing error on extending nodes. 
Fixes: https://github.com/Azure/LogicAppsUX/issues/6361
> fix(designer): Error Being thrown On Extended Text Node

- e2e/designer/tabFocus.spec.ts
- libs/designer-ui/src/lib/panel/panelcontainer.tsx
- libs/designer-ui/src/lib/settings/settingsection/settingexpressioneditor.tsx
- libs/designer/src/lib/ui/settings/sections/general.tsx
This pull request includes several updates to the `libs/designer-ui` and `libs/designer` packages to improve accessibility and clean up unused code. The most important changes include the removal of unused hooks and the addition of `aria-label` attributes to enhance accessibility.
Code cleanup:
* [`libs/designer-ui/src/lib/panel/panelcontainer.tsx`](diffhunk://#diff-e44f6b12c96ecc0e646b5ea7f2609188da7ab3066c4933c9cbd5bf0d65801f8eL14-R14): Removed unused `useRef` and `useEffect` hooks. [[1]](diffhunk://#diff-e44f6b12c96ecc0e646b5ea7f2609188da7ab3066c4933c9cbd5bf0d65801f8eL14-R14) [[2]](diffhunk://#diff-e44f6b12c96ecc0e646b5ea7f2609188da7ab3066c4933c9cbd5bf0d65801f8eL80-L82) [[3]](diffhunk://#diff-e44f6b12c96ecc0e646b5ea7f2609188da7ab3066c4933c9cbd5bf0d65801f8eL93-L100)
Accessibility …
> fix(a11y): Fix auto focus of panel and fix field names

- libs/data-mapper-v2/src/components/functionConfigurationMenu/inputDropdown/InputDropdown.tsx
- libs/data-mapper-v2/src/components/functionConfigurationMenu/inputDropdown/styles.ts
- libs/data-mapper-v2/src/components/functionConfigurationMenu/inputTab/InputList.tsx
- libs/data-mapper-v2/src/components/functionConfigurationMenu/inputTab/inputTab.tsx
- libs/data-mapper-v2/src/components/functionConfigurationMenu/inputTab/styles.tsx
- libs/data-mapper-v2/src/components/schema/tree/styles.ts
- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
- libs/data-mapper-v2/src/utils/ReactFlow.Util.ts
> fix(Data Mapper): Update Function config panel to fix wrapping, delete logic, placement of action items, info bubble 

- apps/vs-code-designer/src/app/commands/nodeJs/validateNodeJsInstalled.ts
- apps/vs-code-designer/src/app/utils/__test__/azure.test.ts
- apps/vs-code-designer/src/app/utils/__test__/binaries.test.ts
- apps/vs-code-designer/src/app/utils/binaries.ts
- apps/vs-code-designer/test-setup.ts
This pull request includes several changes to improve error handling, add unit tests, and refactor the codebase for better readability and maintainability. The most important changes include updating error handling in the `binaries.ts` file, adding unit tests for Azure-related functions, and refactoring the `downloadAndExtractDependency` function.
* Updated error handling in `getLatestFunctionCoreToolsVersion`, `getLatestDotNetVersion`, and `getLatestNodeJsVersion` functions to log errors to telemetry and use fallback versions. 
* Added unit tests for `getResourceGroupFromId` and `getStorageConnectionString` functions in `azure.test.ts` to ensure proper functionality and error handling.
* Refactored `downloadAndExtractDependency` function to directly use `axios.get` instead of a separate …
> feat(vscode): Add unit test for installing binaries and fix return values

- libs/designer/src/lib/ui/CustomNodes/GraphContainerNode.tsx
- libs/designer/src/lib/ui/CustomNodes/SubgraphCardNode.tsx
This pull request introduces several updates to the `GraphContainerNode` and `SubgraphCardNode` components in the `libs/designer/src/lib/ui/CustomNodes` directory. The changes include the addition of new selectors and modifications to the way run data is retrieved and used.
* Added `useParentRunId` and `removeIdTag` imports. Modified the logic to use `removeIdTag` for `graphContainerId` and `useParentRunId` to get `parentRunId`. Updated `runData` to conditionally use `parentRunId` or `graphContainerId`. 
* Added `useParentRunId` import. Removed unused `data` parameter from `SubgraphCardNode` component. Updated `runData` logic to use `parentRunId` and `parentRunData`. Modified `SubgraphCard` component to use `parentRunData?.status` for the `active` prop.
> fix(designer): Correctly add inactive class for subgraph cards

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnectionWrapper.tsx
Custom connection cache is now updated properly when creating a new custom connector connection.
We hold custom connectors in a different query cache initially so when creating we also need to add it to another cache.
Fixes: https://github.com/Azure/LogicAppsUX/issues/6117
> fix(Designer): Custom connection cache is now updated properly

- .github/workflows/private-vsix-build.yml
- .github/workflows/production-build.yml
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnectionWrapper.tsx
This pull request introduces a new GitHub Actions workflow to automate the building and testing of a private VSIX (Visual Studio Code extension) package. The workflow is designed to run tests on different Node.js versions and build the VSIX package with specific configurations.
The idea is to have a pipeline in which creates a VSIX that closely resembles a release version. This pipeline requires a branch name as input, runs the tests, and builds the VSIX in GitHub. As a result, we will be able to distribute a more solid private vsix
* Added a new workflow named "Private vsix build" that includes two jobs: `test` and `build`. The `test` job runs on multiple Node.js versions (18.x, 20.x, 22.x) and caches the turbo build setup. The `build` job sets up Node.js version 20, replaces …
> meta(vscode): Add pipeline to test and build private feature vsix

- libs/data-mapper-v2/src/components/canvas/useReactflowStates.ts
- libs/data-mapper-v2/src/components/schema/tree/SchemaTree.tsx
- libs/data-mapper-v2/src/components/schema/tree/SchemaTreeNode.tsx
- libs/data-mapper-v2/src/components/schema/tree/styles.ts
- libs/data-mapper-v2/src/components/test/TestPanel.tsx
> fix(Data Mapper): Refactor to remove extra styling and clear out test results

- e2e/designer/mock-copypastescope.spec.ts
- libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
- libs/designer/src/lib/ui/common/DesignerContextualMenu/CopyTooltip.tsx
- libs/designer/src/lib/ui/common/DesignerContextualMenu/DesignerContextualMenu.tsx
- libs/designer/src/lib/ui/common/DesignerContextualMenu/__test__/CopyTooltip.spec.tsx
- libs/designer/src/lib/ui/common/DesignerContextualMenu/__test__/__snapshots__/CopyTooltip.spec.tsx.snap
Fixes - #6076 
Tooltip wasn't rendering properly in vscode as well as in portal. The tooltip was getting rendered at the top left corner of the screen instead of the target element.
Tooltip is now rendering in a location related to the target element. In both cases when using the contextual menu and when using `Ctrl`+`C`
Cosmetic change non functionality affected 
Unit tests - Added to the CopyTooltip component
E2E - Updated e2e tests
https://github.com/user-attachments/assets/04a9f16d-00fe-4807-aaaa-2419e1a4b8e9
https://github.com/user-attachments/assets/3c483780-bef5-4452-929a-ee1f373246ab
> fix(designer): Render copied tooltip properly

- libs/data-mapper-v2/src/components/functionConfigurationMenu/inputTab/InputList.tsx
- libs/data-mapper-v2/src/components/functionConfigurationMenu/inputTab/inputTab.tsx
- libs/data-mapper-v2/src/utils/Function.Utils.ts
> fix(Data Mapper): Add updateDragList for remove/add and fix custom value shown

- libs/designer-ui/src/lib/editor/base/utils/keyvalueitem.ts
- libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/parameters/segment.ts
- libs/designer/src/lib/core/utils/validation.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/stringFunctions.spec.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
…ions (#6131)"
This reverts commit a3f6e31c76e630f32c3fac7bb60f1690f6cc0fca.
> fix(designer): revert No longer escapes characters in token expressions

- apps/vs-code-designer/src/app/commands/createCodeless/createCodeless.ts
- apps/vs-code-designer/src/app/commands/dataMapper/dataMapper.ts
- apps/vs-code-designer/src/app/commands/workflows/configureWebhookRedirectEndpoint/configureWebhookRedirectEndpoint.ts
- apps/vs-code-designer/src/app/utils/__test__/binaries.test.ts
- apps/vs-code-designer/src/app/utils/__test__/workspace.test.ts
- apps/vs-code-designer/src/app/utils/verifyIsProject.ts
- apps/vs-code-designer/src/app/utils/workspace.ts
- apps/vs-code-designer/test-setup.ts
Current behavior pops the following error `Cannot read properties of undefined (reading 'uri')` when the vscode extension is initialized in a workspace that doesn't have any Logic App projects in it.
New behavior will handle properly the initialization of the vscode extension for workspaces in which there are no Logic App projects in it
I added unit test for this. This will help us control this scenario in the future and if there are any updates on the logic. 
Fixing scenarios in which the workspaces don't have Logic Apps projects in it 
https://github.com/Azure/LogicAppsUX/issues/6274#issuecomment-2623119932
> fix(vscode): Handle extension initialization when there aren't logic apps projects

- e2e/designer/tokens/escapeExpressionTokens.spec.ts
- e2e/designer/tokens/tokenRemoval.spec.ts
- libs/designer-ui/src/lib/editor/base/plugins/OpenTokenPicker.tsx
- libs/designer-ui/src/lib/tokenpicker/index.tsx
- libs/designer-ui/src/lib/tokenpicker/plugins/InitializeTokenPickerExpressionHandler.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/parameters/segment.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/stringFunctions.spec.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Previously we were escaping expressions on deserialization and unescaping expression on serialization. Now instead, this is done strictly on the ui-layer where before the tokenpicker expression editor is opened, the expression gets escaped; then when the token gets added/updated, the expression gets unescaped.
Fixes https://github.com/Azure/LogicAppsUX/issues/6515
Fixes https://github.com/Azure/LogicAppsUX/issues/6529
Cherry-picked from: https://github.com/Azure/LogicAppsUX/pull/6539
> fix(Designer): hotfix/5.18 - Expression fix

- e2e/designer/tokens/escapeExpressionTokens.spec.ts
- e2e/designer/tokens/tokenRemoval.spec.ts
- libs/designer-ui/src/lib/editor/base/plugins/OpenTokenPicker.tsx
- libs/designer-ui/src/lib/tokenpicker/index.tsx
- libs/designer-ui/src/lib/tokenpicker/plugins/InitializeTokenPickerExpressionHandler.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/parameters/segment.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/stringFunctions.spec.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Previously we were escaping expressions on deserialization and unescaping expression on serialization. Now instead, this is done strictly on the ui-layer where before the tokenpicker expression editor is opened, the expression gets escaped; then when the token gets added/updated, the expression gets unescaped.
Fixes https://github.com/Azure/LogicAppsUX/issues/6515
Fixes https://github.com/Azure/LogicAppsUX/issues/6529
Cherry-picked from: https://github.com/Azure/LogicAppsUX/pull/6539
> fix(Designer): hotfix/5.35 - Expression fix

- __mocks__/runs/LoopsPager/SuccessRun.json
- __mocks__/workflows/LoopsPager.json
- apps/Standalone/src/designer/app/LocalDesigner/LogicAppSelector/LogicAppSelector.tsx
- e2e/designer/monitoringView/loopsPager.spec.ts
- e2e/designer/monitoringView/monitoringView.spec.ts
- libs/designer/src/lib/ui/CustomNodes/GraphContainerNode.tsx
- libs/designer/src/lib/ui/CustomNodes/SubgraphCardNode.tsx
- libs/designer/src/lib/ui/common/LoopsPager/LoopsPager.tsx
With the old behavior the loop pager wasn't getting rendered and also the content inside the subgraph node was getting the inactive class
Loop pager now renders correctly and the content inside the subgraph node doesn't render as inactive
It is not a breaking change
Already added e2e tests for this behavior
> fix(designer): Loop pager visibility in do-until action

- libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Current regex fails on test string "_example_string" with leading underscores
New regex accounts for leading underscores
Addressed in existing unit tests
N/A
> fix(vscode): Correct toPascalCase regex

- apps/Standalone/src/templates/app/LocalTemplates.tsx
- apps/Standalone/src/templates/app/TemplatesStandard.tsx
- e2e/templates/createWorkflowPanel.spec.ts
- e2e/templates/viewtemplate.spec.ts
- libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
- libs/designer/src/lib/core/state/templates/manifestSlice.ts
- libs/designer/src/lib/core/state/templates/store.ts
- libs/designer/src/lib/core/state/templates/templateOptionsSlice.ts
- libs/designer/src/lib/core/state/templates/templateSlice.ts
- libs/designer/src/lib/core/state/templates/templateselectors.ts
- libs/designer/src/lib/core/templates/TemplatesDataProvider.tsx
- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/createWorkflowPanel.tsx
- libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/quickViewPanel.tsx
- libs/designer/src/lib/ui/templates/basics/multiworkflow.tsx
- libs/designer/src/lib/ui/templates/basics/singleworkflow.tsx
- libs/designer/src/lib/ui/templates/parameters/displayParameters.tsx
- libs/designer/src/lib/ui/templates/templateview.tsx
- libs/logic-apps-shared/src/utils/src/lib/models/template.ts
- overrides basics & parameters info when present from viewTemplateData
- Moved ViewTemplateDetails interface to template model file for reusability
- Using viewTemplateDeatails only when currentTemplateName === viewTemplateDetails.id (extra protection)
- kind is set to viewTemplateDetails kind only when following is present from the template manifest
e2e tests on prefilled data on viewTemplate selection
https://github.com/user-attachments/assets/3a19e529-bc88-49c7-a0ca-b3f25e9039df
> feat(Templates): Support ViewTemplate data Override

- libs/data-mapper-v2/src/mapHandling/MapDefinitionDeserializer.ts
- libs/data-mapper-v2/src/mapHandling/__test__/MapDefinitionDeserializer.spec.ts
extra '/' added in deserialization
https://msazure.visualstudio.com/One/_workitems/edit/31371895/
> Fix(Data Mapper): extra '/' added to custom values on for/if

- apps/vs-code-designer/test-setup.ts
- libs/designer-ui/src/lib/unitTesting/conditionExpression/index.tsx
- libs/designer-ui/src/lib/unitTesting/outputMocks/errorDetails.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
This pull request includes several changes to the `apps/vs-code-designer` and `libs/designer-ui` packages. The most important changes involve updating import paths, modifying function parameters, and improving mock setup for testing.
* Changed the import path for `TokenGroup` to use `@microsoft/logic-apps-shared` instead of a relative path.
* Updated the import path for `ChangeState` to use a relative path.
* Modified the `ConditionExpression` component to use `selectedMode` instead of `selectedKey`.
* Added `_event: any` as the first parameter to `handleErrorMessageChange` and `handleErrorCodeChange` functions.
* Removed redundant mock setup for `vscode` to ensure cleaner test configuration.
* Added `tabProps` as a dependency in the `useMemo` hook for `mockResultsTabItem` to ensure …
> fix(vscode): Fix build and test errors for dev branch

- e2e/designer/tokens/escapeExpressionTokens.spec.ts
- libs/designer-ui/src/lib/tokenpicker/index.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx
- libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/stringFunctions.spec.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Fixes: https://github.com/Azure/LogicAppsUX/issues/6618
User should always have the same expression, whether its opening an existing expression, saving a new expression, viewing it on the code view, etc. regardless of escape character - all of which should be handled behind the scenes
E2E test and Unit tests have been added
> fix(Designer): Fixes an issue where '\"'  causing json errors in expressions

- apps/vs-code-designer/src/app/utils/tree/__test__/assets.test.ts
Tests in apps/vs-code-designer/src/app/utils/tree/__test__/assets.test.ts fail locally due to mismatched OS path separators
Use path.join on expected value in assert
Fix existing test, no new tests required
N/A
> fix(vscode): Bug with path separator in local tests

- apps/vs-code-designer/src/package.json
Logic App project creation and workflow creation was removed from the azure blade previously. 
Logic App project creation and workflow creation is accessible from the azure blade again.
> fix(vscode): Add workflow and logic app creation back to azure blade

- e2e/designer/editors/dictionary.spec.ts
- libs/designer-ui/src/lib/editor/base/utils/helper.ts
- libs/designer-ui/src/lib/editor/base/utils/keyvalueitem.ts
Currently it goes by the parsed value, but doesn't account for tokens.
Now does not default with tokens 
Added E2E test
> fix(designer): Dictionary Editor to not use string interpolation for tokens if ANY value type

- apps/vs-code-designer/src/app/commands/createCodeless/createCodelessSteps/ScriptSteps/ScriptWorkflowNameStep.ts
- apps/vs-code-designer/src/app/commands/createCodeless/createCodelessSteps/WorkflowNameStepBase.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/SetLogicAppNameStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/SetWorkspaceName.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/setMethodName.ts
- apps/vs-code-designer/src/constants.ts
Fixes #6643 
Workspace names/ Logic app names allow spaces and special characters apart from the allowed ones in their name
Workspace names/ Logic app names now do not allow spaces and special characters apart from the allowed ones.
Currently tested by vendors
> fix(vscode): Add validation for workspace and logic app name

- e2e/designer/real-api/monitoring/NestedLoops/nestedLoops.spec.ts
- libs/designer/src/lib/core/store.ts
- libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
- playwright.config.ts
Fixed loop causing rerender in monitoring view
Components were being _fully_ rerendered for some reason when `setRepetitionRunData` was called, and it was recursively being called in the useEffect.
We now catch it if the data is already present and the rerenders are prevented.
> [!IMPORTANT]
> **TESTS**: Improved our real-api loop monitoring e2e test to cover this issue
> **RISK**: Low risk, Carlos and I have both tested all loop scenarios 
> [!NOTE]
> Cherry-picked from https://github.com/Azure/LogicAppsUX/pull/6686
> fix(Designer): Fixed loop causing rerender in monitoring view (v5.44)

- apps/vs-code-designer/src/app/utils/__test__/UnitTesting/unitTestUtils.test.ts
- apps/vs-code-designer/src/app/utils/unitTests.ts
1. Currently use path "../../../../" as relative workspace path in test settings config (invalid)
2. Set StatusCode property in ctor of all generated classes
1. Change path to "../../../../../" for workspace path in test settings config
2. Only set StatusCode property in generated classes which extend MockOutput
Added updated tests for generateClassCode/createTestSettingsConfigFile to catch these bugs
N/A
> fix(vscode): automated testing bug in config workspace path and C# class generation

- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/__test__/FileManagement.test.ts
- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/iacGestureHelperFunctions.ts
- apps/vs-code-designer/test-setup.ts
[Work Item: [Bug] Create test from run: Debug adapter process has terminated unexpectedly](https://msazure.visualstudio.com/One/_workitems/edit/31450115)  
- When adding a folder to the workspace, the code currently inserts the folder at the **front** of the existing workspace.
- This causes VS Code to reload the extension, terminating any active debugging session.
- The new folder is now added to the **end** of the workspace.
- Prevents VS Code from reloading the extension and terminating the debugging session.
- No breaking changes introduced. Other functionality remains unaffected.
- ✅ Unit tests added to:  
`apps\vs-code-designer\src\app\commands\generateDeploymentScripts\__test__\FileManagement.test.ts`
N/A
> fix(vscode): Adjust Folder Insertion to End of Workspace 

- apps/vs-code-designer/src/app/utils/binaries.ts
Binaries dependency installation is not cleaning the folder if there is a previous installation, causing some issue while trying to extract the content from the new installation
Now we clean the folder and then extract the contents of the new installation, making it as a fresh installation and making sure none of the previous ones remains.
> [!NOTE]
> **TEST** - Is quite hard to test since vitest doesn't provide a way to create in-memory file system. This will come more handy once we implement e2e tests in vscode
> **Risk** - Low risk as its fixing an ongoing issue
https://github.com/user-attachments/assets/1850a85f-82b2-42b3-8888-9c3b59c2eb54
> fix(vscode): Clean dependency installation folder before extracting content

- apps/vs-code-designer/src/app/commands/initProjectForVSCode/InitVSCodeStepBase.ts
- apps/vs-code-designer/src/app/utils/verifyIsProject.ts
VSCode with no folder opens causes an issue when creating a workspace. Designtime directory does not always create.
Check that there are no folders open before creating a workspace.
Ensure that design time directory is created with new logic app projects in a workspace.
> fix(vscode): Workspace fixes for empty vscode and designtime directory creation

- apps/vs-code-designer/src/app/commands/workflows/unitTest/createUnitTest.ts
- apps/vs-code-designer/src/app/utils/__test__/UnitTesting/unitTestUtils.test.ts
updateCsprojFile is never called in create unit test from run, which can result in misconfigured csproj file
Add updateCsprojFile call after ensureCsprojFile
saveBlankUnitTest/createUnitTestFromRun to be covered in vendor testing (no E2E tests currently)
N/A
> fix(vscode): updateCsprojFile not called in create from run

- libs/designer/src/lib/ui/templates/connections/workflowconnections.tsx
- libs/logic-apps-shared/src/utils/src/lib/models/template.ts
When going to connections tab, an existing connection, if exists, will automatically be used.
Add option to allow overriding managed api connections, so the specified connection provided by the caller will automatically be selected.
Manually tested locally
> feat(template): Support overriding managed api connections

- package.json
- tsconfig.base.json
Switched tsconfig target from ESNext to ES2020
> [!IMPORTANT]
> **RISK**: 
> Medium risk:  This shouldn't change anything functionally, but the built files will be slightly different
> 
> **BREAKING**: 
> ES target is going from `ESNext` to `ES2020`, everything should be working the same and during testing everything seemed to be working fine
> feat(Designer): Switched ES target to ES2020

- libs/designer/tsup.config.ts
Modified our XYFlow import to have correct pathing.
Was breaking over in AI Foundry from the `~`, confirmed no effect on our projects.
Last PR didn't fix all instances of the issue: https://github.com/Azure/LogicAppsUX/pull/6791
> fix(Desinger): Modified css export again

- apps/vs-code-designer/src/app/commands/createNewCodeProject/cloudToLocalHelper.ts
- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
- apps/vs-code-designer/src/app/commands/parameterizeConnections.ts
- apps/vs-code-designer/src/app/utils/codeless/__test__/parameterizer.test.ts
- apps/vs-code-designer/src/app/utils/codeless/parameterizer.ts
* [ x] Bug fix
Parameterize connections command relies on a check which checks connections if they are parameterized. Currently, that check only checks connections until they see one connection that is parameterized but then skips the rest. This change will make sure that check will return true if all connections are parameterized.
> fix(vscode): Fix parameterize connection checks to check all connections

- libs/designer-ui/src/lib/modals/DeleteNodeModal.tsx
- Delete modal has a slow animation that makes it look like its taking a slightly long time to load
- Remove the animation of loading the background of the modal, thus its makes it look like its loading faster or there is no delay
https://github.com/user-attachments/assets/fb5afc8f-658c-4cd1-a801-f0c3f01ca09c
https://github.com/user-attachments/assets/47fa07c7-a11a-4d7d-97b8-1f7488f773be
> feat(designer): Remove animation for delete node modal

- libs/designer/src/lib/core/parsers/addNodeToWorkflow.ts
- When adding action to scope and subgraph nodes, the logic to sum the number of items in the scope card was returning always 1.
- Now the logic to sum the number of items in the scope card is working correctly
https://github.com/user-attachments/assets/130dc1d2-b3d7-455a-aeb6-bcf869bd5a70
https://github.com/user-attachments/assets/cc4ece15-5de8-4af1-877f-eb7d524f00c2
> fix(designer): Fix item count when adding operations in scope and subgraph

- libs/designer/src/lib/core/state/templates/templateselectors.ts
- libs/designer/src/lib/core/templates/TemplatesDesignerProvider.tsx
- libs/designer/src/lib/ui/panel/templatePanel/panel.less
- libs/designer/src/lib/ui/templates/review/ReviewAddPanel.tsx
- libs/designer/src/lib/ui/templates/styles.less
Templates review tabs no longer show auth + parameters if there are no values to display.
Templates provider has new `useExternalRedux` flag to prevent redux provider creation.
Cherry-picked from https://github.com/Azure/LogicAppsUX/pull/6828
> feat(Templates): Review tab improvements + Template provider useExternalRedux flag

- libs/designer/src/lib/core/state/templates/templateselectors.ts
- libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/quickViewPanel.tsx
- libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/summaryTab.tsx
- libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/workflowTab.tsx
- libs/designer/src/lib/ui/templates/basics/resource.tsx
- libs/designer/src/lib/ui/templates/basics/singleworkflow.tsx
Made the `useWorkflowTemplate` hook + usage null-safe.
Was throwing errors over in AI-Foundry due to a race condition with an async-thunk call.
> fix(Templates): Made `useWorkflowTemplate` hook + usage null safe

- libs/designer/src/lib/core/actions/bjsworkflow/connections.ts
- libs/designer/src/lib/ui/panel/connectionsPanel/connectionsPanel.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/selectConnection/selectConnection.tsx
Skipping auto creation of oauth connection in designer and only enabled it for templates.
Also skipping auto creation when it is multi auth connector [this is the actual bug]
> fix(designer): Skip auto create connection for oauth in designer and for multi auth

- libs/logic-apps-shared/src/designer-client-services/lib/base/template.ts
Small change to remove custom path while fetching templates from storage account, now entire path will be set in endpoint url
> fix(templates): Removing extra path from templates load when getting from storage

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
- Behavior to determine whether there were new keys was inverted, therefore the connections were not being updated correctly and saving from standalone app was saving resolved connections
- Agent connector id was incomplete and therefore not updating agentConnections
- Saving from standalone app now saves correct connections without resolving them
- Added logic to handle hasNewConnectionRuntimeUrl
> fix(standalone): Fix connections update in standalone

- apps/vs-code-designer/src/app/utils/verifyIsProject.ts
Fixes  #6866
- isLogicAppProject is checking for a single workflow.json file, which does not allow having the csharp file inside the workflow folder.
- Checking for isLogicAppProject now not only checks for a single workflow.json file, which allows having the csharp file 
https://github.com/user-attachments/assets/769e4c3a-4e89-4923-9ed9-73efe6f3bc90
> fix(vscode): Update validation to allow having the csharp file inside the workflow folder

- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
- Renamed `repetitions` to `iterations` in the `runData` object to improve clarity.
- Added a new property `runIndex` with an initial value of `0` to the `nodeMetadata` object.
> fix(designer): Fix correct property for subgraph iteration

- libs/designer/src/lib/ui/panel/templatePanel/panel.less
- libs/designer/src/lib/ui/templates/templateDisplay.tsx
Converted the `TemplateDisplay` description to markdown to match the data coming in from templates.
> feat(Templates): Converted `TemplateDisplay` description to markdown

- libs/designer/src/lib/core/templates/TemplatesDataProvider.tsx
- libs/designer/src/lib/ui/templates/gallery/templatesgallerywithsearch.tsx
- libs/designer/src/lib/ui/templates/templateview.tsx
Since this is tied to a component, when component unmounts this was not getting called so moved this so data provider, since it is data initialization.
> fix(templates): Moving workflow metadata initialization in templatesdataprovider

- apps/vs-code-designer/src/app/commands/__test__/pickCustomCodeNetHostProcess.test.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/CreateNewProjectInternal.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppFilesStep.ts
- apps/vs-code-designer/src/app/commands/pickCustomCodeNetHostProcess.ts
- apps/vs-code-designer/src/app/commands/pickFuncProcess.ts
- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesigner.ts
- apps/vs-code-designer/src/app/debug/validatePreDebug.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/package.json
Launch configuration for .net8 custom code functions project incorrectly targets CustomCodeNetFxWorker
Update launch config to use new pickCustomCodeNetHostProcess command to pick the dotnet.exe child process of the running func host corresponding to logic app
Added unit tests for pickCustomCodeNetHostProcess
N/A
> fix(vscode): .Net 8 custom code debugger fix

- libs/designer/src/lib/core/index.ts
Exported `validateWorkflowsBasicInfo` and `useExistingWorkflowNames` for use in templates flow outside designer.
> feat(Designer): Exported 2 extra state methods for templates

- e2e/templates/app.spec.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/template.ts
- package.json
Removing template bundling from packages.
We have tested in all clouds and we are able to pull templates from our new storage account, so bundling the templates is no longer needed.
> [!IMPORTANT]
> Risk: Low - We have tested this change in all clouds
> feat(Templates): Removing template bundling from packages

- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/SetLogicAppNameStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/__test__/SetLogicAppNameStep.test.ts
- apps/vs-code-designer/test-setup.ts
Fixes #6822
Logic app name validation in create project flow does not catch duplicate logic app name in workspace
Fix validation to catch duplicate LA name
Added unit tests for SetLogicAppNameStep (prompt/validate)
N/A
> fix(vscode): logic app name validation misses duplicate name

- libs/designer-ui/src/lib/editor/base/editor.less
- libs/designer-ui/src/lib/editor/base/plugins/tokenpickerbutton/agentParameterButton.tsx
Used built-in `appearance` prop instead of style overrides for agent parameter button
https://github.com/user-attachments/assets/1bad953c-4d15-41ef-8327-68e680f33eda
https://github.com/user-attachments/assets/6e2056b5-b01f-4946-8ce1-f87c94395106
> fix(designer): Agentic Loops - Agent parameter button styling fix

- libs/designer-ui/src/lib/panel/panelResizer.tsx
- libs/designer-ui/src/lib/panel/panelcontainer.tsx
- libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
- Innermost panel wasn't rendering and sizing in a right way since the chat panel was introduced
- Now panel resize rely on the drawer reference rather than relying on the window width
No breaking changes
https://github.com/user-attachments/assets/c614f7f1-e9b8-4466-a4a2-3322ab74a069
https://github.com/user-attachments/assets/5d2d6daf-20fe-4621-9f55-5ed37c2eff39
> fix(designer): Fix panel resize

- libs/designer-ui/src/lib/querybuilder/Row.tsx
- libs/designer/src/lib/common/constants.ts
- libs/designer/src/lib/core/utils/__test__/segment.spec.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/parameters/segment.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
We're uncasting on all parameters unless explicitly defined in the swagger to suppressCasting. However, it causes issues such as:
https://github.com/Azure/LogicAppsUX/issues/6896 where if users use expressions with base64, encodeUri, etc it ends up not showing on deserialization. Worse, if the editor is then changed later on, during serialization, the cast is lost altogether.
This is meant so we only uncast when the format is explicitly defined in the parameter. Thus, it should only uncast on editors that are casted on serialization
> fix(designer): Prevent Uncast from ocurring by default

- apps/vs-code-designer/src/app/commands/createCustomCodeFunction/createCustomCodeFunction.ts
- apps/vs-code-designer/src/app/commands/createCustomCodeFunction/createCustomCodeFunctionSteps/FunctionNameStep.ts
- apps/vs-code-designer/src/app/commands/createCustomCodeFunction/createCustomCodeFunctionSteps/__test__/FunctionNameStep.test.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/CreateNewProjectInternal.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/__test__/LogicAppNameStep.test.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppNameStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppNamespaceStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/__test__/FunctionAppNameStep.test.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/__test__/FunctionAppNamespaceStep.test.ts
- apps/vs-code-designer/test-setup.ts
- Function app name input validation doesn't check for other function apps in workspace with same name
- Function name input validation doesn't check for other functions in the same function app with same name
- Context storing functions projects for workspace isn't updated after creating new project with functions
All above bugs fixed
Added unit tests for FunctionAppNameStep/FunctionNameStep/FuncationAppNamespaceStep validation
N/A
> fix(vscode): bug in function name/function app name/function app namespace input validation, update context when creating new functions project

- apps/vs-code-designer/src/app/utils/__test__/UnitTesting/unitTestUtils.test.ts
- apps/vs-code-designer/src/app/utils/unitTests.ts
Currently, when generating C# class definitions for action mocks, any output property named "StatusCode" is included in the generated class. Because the base class (`MockOutput`) already defines a `StatusCode` property (with a different type, e.g. `HttpStatusCode?`), this duplicate declaration leads to a type mismatch during unit test validation. For example, actions such as `Call_External_API` result in errors like:
> *"The workflow '' associated with unit test '' has action mock 'Call_External_API' that has 'outputs' that has status code of invalid type. Expected type: 'string', Actual type : 'Integer'"*
With this fix, we now filter out any property where `propertyName` equals `"StatusCode"` from the generated class definition. This ensures that the only `StatusCode` in the output is …
> fix(vscode): Delete statusCode from root def

- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/LogicAppNameStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/NewCodeProjectTypeStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/WorkspaceSettingsStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/__test__/LogicAppNameStep.test.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppFilesStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/TargetFrameworkStep.ts
- apps/vs-code-designer/src/app/commands/createNewProject/createNewProject.ts
- apps/vs-code-designer/src/app/commands/createNewProject/createProjectSteps/NewProjectLogicAppTypeStep.ts
- apps/vs-code-designer/src/app/utils/customCodeUtils.ts
- apps/vs-code-designer/src/app/utils/workspace.ts
- libs/vscode-extension/src/lib/models/project.ts
- "Create New Project" options include new LA, new LA with custom code, and new LA with rules engine
- Rules engine generated settings files has undefined target framework
- Update "Create New Project" options to allow both creating new LA with custom code/rules engine and creating custom code/rules engine for existing LA (max one per LA)
- Fix bug in generated settings file for rules engine (default to .NET framework)
Added step to existing vendor test to cover "Create New Project" https://msazure.visualstudio.com/One/_workitems/edit/32120152
N/A
> feat(vscode): Add Create New Project option to create custom code/rules engine for existing LA

- libs/designer-ui/src/lib/agentinstruction/index.tsx
- libs/designer-ui/src/lib/arrayeditor/expandedsimplearray.tsx
- libs/designer-ui/src/lib/arrayeditor/index.tsx
- libs/designer-ui/src/lib/dictionary/dictionaryeditor.less
- libs/designer/src/lib/core/utils/parameters/__test__/segment.spec.ts
- libs/designer/src/lib/core/utils/parameters/__test__/uncast.spec.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/parameters/segment.ts
- libs/designer/src/lib/core/utils/parameters/uncast.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
1. Fixes an issue where using a token in complex array editor ends up deserializing in collapsed form and is unable to change back to expanded form (removes quotes around the token)
2. Fixes an issue where casting was happening on ever parameter with format instead of specific format types
3. Fixed a bug where simple array editor was always showing required label
4. Cosmetic format default agent parameter channel schema
> fix(designer): Array Editor Bugfixes

- libs/designer/src/lib/core/templates/utils/helper.ts
Changed the order of summary tab and workflow tab, so that the information of the workflow will open up first for accessibility purposes as per discussed with the templates team
> feat(Templates): Move summary tab before workflow tab

- libs/designer-ui/src/lib/templates/model.ts
- libs/designer-ui/src/lib/templates/templatesContent.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
- libs/designer/src/lib/core/state/templates/panelSlice.ts
- libs/designer/src/lib/core/state/templates/tabSlice.ts
- libs/designer/src/lib/ui/configuretemplate/tabs/connectionsTab.tsx
- libs/designer/src/lib/ui/configuretemplate/tabs/model.tsx
- libs/designer/src/lib/ui/configuretemplate/tabs/parametersTab.tsx
- libs/designer/src/lib/ui/configuretemplate/tabs/profileTab.tsx
- libs/designer/src/lib/ui/configuretemplate/tabs/publishTab.tsx
- libs/designer/src/lib/ui/configuretemplate/tabs/reviewPublishTab.tsx
- libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
- libs/designer/src/lib/ui/configuretemplate/tabs/workflowsTab.tsx
- libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
- libs/designer/src/lib/ui/panel/configureTemplatePanel/configureWorkflowsPanel/tabs/customizeWorkflowsTab.tsx
- libs/designer/src/lib/ui/panel/configureTemplatePanel/configureWorkflowsPanel/tabs/selectWorkflowsTab.tsx
- libs/designer/src/lib/ui/panel/configureTemplatePanel/configureWorkflowsPanel/usePanelTabs.tsx
- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/basicsTab.tsx
- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/connectionsTab.tsx
- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/parametersTab.tsx
- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/reviewCreateTab.tsx
- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/usePanelTabs.tsx
- libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/summaryTab.tsx
- libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/workflowTab.tsx
Tab will only be enabled when 1. enableWizard is true and 2. isWizardUpdating is not true.
- enableWizard is true when there are selected workflows, meaning tabs will be disabled when no workflows are selected
- isWizardUpdating is used to determine temporarily disabling tabs or setting spinner/disabling panel until initialization or deletion is complete
To be coming: With each tab validation, we may turn the tab status to error
- UI elements are still to be polished (i.e. tab icons will not be always in progress once validation is implemented)
- Validation tests will be added along with validation logic & UI in the next PR (error tab status is not fixed yet)
https://github.com/user-attachments/assets/ff3c4d17-8c25-4092-8c38-4b3c02aaf601
> feat(Templates): Custom Templates Tab Management

- apps/vs-code-designer/src/app/utils/__test__/UnitTesting/unitTestUtils.test.ts
- apps/vs-code-designer/src/app/utils/unitTests.ts
Currently, when generating C# class definitions for action mocks, any output property named "StatusCode" is included in the generated class. Because the base class (`MockOutput`) already defines a `StatusCode` property (with a different type, e.g. `HttpStatusCode?`), this duplicate declaration leads to a type mismatch during unit test validation. For example, actions such as `Call_External_API` result in errors like:
> *"The workflow '' associated with unit test '' has action mock 'Call_External_API' that has 'outputs' that has status code of invalid type. Expected type: 'string', Actual type : 'Integer'"*
With this fix, we now filter out any property where `propertyName` equals `"StatusCode"` from the generated class definition. This ensures that the only `StatusCode` in the output is …
> fix(vscode): Delete statusCode from root def 

- libs/designer-ui/src/lib/chatbot/chatbot.less
- Text for code tags in Markdown component inside the chat bubble was getting overflow
- Text for code tags in Markdown component inside the bubbles wraps avoiding overflow
https://github.com/user-attachments/assets/8d756d73-3439-4c70-9278-6c80eb0865b9
https://github.com/user-attachments/assets/13815ca6-91c7-41ec-9afb-6bfbd6a2d8cf
> fix(designer): Add styles for code tags inside the chat bubble

- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
- First load wasn't setting the metadata from the general run data as iteration count is not undefined
- New behavior now load the data from the general run data
> fix(designer): Load agent run data from general run data

- apps/vs-code-designer/src/app/utils/__test__/UnitTesting/unitTestUtils.test.ts
- apps/vs-code-designer/src/app/utils/unitTests.ts
- Check for existing test with matching name does not work as expected
- Fix existing check, also check for other folders in Tests/logicAppName/workflowName with matching name
Added unit tests for validateUnitTestName
N/A
> fix(vscode): Add unit test name validation check for existing test/folder with same name

- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/package.json
- User-facing commands for run unit test, create unit test, edit unit test, open test results which fail due to not having the logic app context
- Remove commands
No changed behavior
N/A
> fix(vscode): Remove user-facing commands for automated testing

- apps/vs-code-designer/src/app/commands/__test__/parameterizeConnections.test.ts
- apps/vs-code-designer/src/app/commands/binaries/validateAndInstallBinaries.ts
- apps/vs-code-designer/src/app/commands/funcCoreTools/validateFuncCoreToolsIsLatest.ts
- apps/vs-code-designer/src/app/commands/parameterizeConnections.ts
- apps/vs-code-designer/src/app/utils/__test__/workspace.test.ts
- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
- apps/vs-code-designer/src/app/utils/dotnet/dotnet.ts
- apps/vs-code-designer/src/app/utils/workspace.ts
- apps/vs-code-designer/src/assets/UnitTestTemplates/TestBlankClassFile
- When the user opens an empty workspace a prompt appears "You must have a workspace open to perform this action."
- Avoid unintended prompt by removing prompt from getWorkspaceLogicAppFolders and returning empty array if workspace is empty
N/A
N/A
> fix(vscode): prompt appearing when empty workspace opened

- libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
This pull request introduces a default value for the `agentHistoryReductionType` property in the `manifest/agentloop.ts` file. The change ensures that the property defaults to `'maximumTokenCountReduction'` if no value is provided.
* **Default value added to `agentHistoryReductionType`:**
- A default value of `'maximumTokenCountReduction'` was added to the `agentHistoryReductionType` property in the `manifest/agentloop.ts` file to ensure consistent behavior.
> feat(designer): Add "maximumTokenCountReduction" as default in agent settings

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
- libs/designer/src/lib/core/state/global.ts
- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
- https://github.com/Azure/LogicAppsUX/pull/7105
> fix(designer): Reset id replacements when reset designer dirty state 

- apps/vs-code-designer/src/app/commands/__test__/pickCustomCodeNetHostProcess.test.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/CreateNewProjectInternal.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppFilesStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/initLogicAppCodeProjectVScode/InitCodeProject.ts
- apps/vs-code-designer/src/app/commands/debugLogicApp.ts
- apps/vs-code-designer/src/app/commands/pickCustomCodeNetHostProcess.ts
- apps/vs-code-designer/src/app/commands/pickFuncProcess.ts
- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/app/utils/__test__/customCodeUtils.test.ts
- apps/vs-code-designer/src/app/utils/azurite/activateAzurite.ts
- apps/vs-code-designer/src/app/utils/customCodeUtils.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/main.ts
- apps/vs-code-designer/src/package.json
- Logic app projects with custom code require starting two separate debuggers for the logic app and local custom code function
- Add new 'logicapp' debug configuration provider which has 'funcRuntime' and 'customCodeRuntime' properties and starts two debuggers for logic app and custom code function simultaneously
TODO
> feat(vscode): New debug config provider for logic app project with custom code

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/LogicAppSelectionSetting/AzureStandardLogicAppSelector.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Utilities/HybridAppUtilities.ts
- apps/vs-code-designer/src/app/commands/deploy/hybridLogicApp/cleanResources.ts
- apps/vs-code-designer/src/app/commands/deploy/hybridLogicApp/index.ts
- apps/vs-code-designer/src/app/utils/codeless/hybridLogicApp/connectedEnvironment.ts
- apps/vs-code-designer/src/app/utils/codeless/hybridLogicApp/hybridApp.ts
- apps/vs-code-designer/src/constants.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/connector.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/hybrid.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/operationmanifest.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/search.ts
The backend version will be updating the hybrid api versions soon, so this prevents us from having to update the version in every place that uses it
> fix(desinger): Move Hybrid Api versions to a single location in Libraries

- libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
- libs/designer/src/lib/core/state/templates/manifestSlice.ts
- libs/designer/src/lib/core/state/templates/templateselectors.ts
- libs/designer/src/lib/core/templates/TemplatesDataProvider.tsx
- libs/designer/src/lib/ui/templates/gallery/templatesgallery.tsx
Moved `filteredTemplateNames` out of Redux state.
This was being calculated in a useEffect based off of other state values, and sometimes was hitting a race condition causing bugs.
Since we calculate it only using state values, I just moved it to a useSelector hook so that it will always be up to date.
> fix(Templates): Refactored `filteredTemplateNames` out of state / into selector 

- libs/designer-ui/src/lib/panel/recommendationpanel/recommendation.less
- libs/designer/src/lib/ui/panel/recommendation/actionSpotlight.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/localStorage.ts
1. Persist user saving Browse Action Spotlight expand/collapse in Local Storage
2. lastAssistantMessage output in Agent Loop
> fix(designer): Browse Action Spotlight to Local Storage

- apps/docs/docs/Development/portal.mdx
This pull request updates the documentation for setting up and using a private npm registry with Verdaccio in the Logic Apps Portal repository. The changes clarify configuration steps and improve instructions for package installation.
* Added instructions for configuring an `.npmrc` file in the `Client/React` directory to resolve `@microsoft` packages to the private registry while maintaining global registry settings for other packages.
* Clarified the process for installing packages from Verdaccio by updating the `package.json` versions and running `npm install`.
> docs(verdaccio): Add registry config for verdaccio development

- libs/designer/src/lib/ui/connections/edge.tsx
This reverts commit cba12921e800d070de1f88366d215129416a6cff.
Reverting introducing btoa as it breaks designer on non-latin characters
> fix(Designer): Non-latin characters in action name breaking designer

- libs/designer/src/lib/core/templates/utils/queries.ts
- libs/designer/src/lib/ui/templates/review/ResourceDisplay.tsx
Fixed the `useSubscriptions` import in the `ResourceDisplay` component.
Added an extra query key to template queries to prevent overlap with other queries.
Cherry-pick of https://github.com/Azure/LogicAppsUX/pull/7192
> fix(Templates): Fixed query issue in Templates

- libs/designer-ui/src/lib/templates/templatesPanelFooter.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
- libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/configureWorkflowsPanel.tsx
- libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/tabs/customizeWorkflowsTab.tsx
- libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/usePanelTabs.tsx
- libs/designer/src/lib/ui/configuretemplate/panels/customizeParameterPanel/customizeParameterPanel.tsx
- libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/base/templateresource.ts
- libs/logic-apps-shared/src/designer-client-services/lib/templateresource.ts
- Using the previously added structure to add split publish buttons for workflows & parameters panels
- for parameter panel, the rollback TODO logic is written
> feat(Templates): Split button for publish for workflow & parameter tabs

- .gitignore
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/LogicAppSelectionSetting/AzureConsumptionLogicAppSelector.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/LogicAppSelectionSetting/AzureStandardLogicAppSelector.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Queries/FetchConsumptionApps.ts
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Queries/FetchStandardApps.ts
- apps/Standalone/src/designer/app/DesignerShell/designer.tsx
- apps/Standalone/src/environments/environment.ts
- libs/designer-ui/src/lib/editor/base/utils/keyvalueitem.ts
- libs/designer-ui/src/lib/flyout2/__test__/flyout2.spec.tsx
- libs/designer-ui/src/lib/tokenpicker/index.tsx
- libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Fixed an issue where dictionary editor was throwing a validation error when using \, so extending our escape character to all instances of \.
Giving standalone users an optional hidden subscriptionIds.json file, so they developers filter which workflows to load by sub (mostly because if there are a lot of flows, it can take a while to load them all)
Fixed an issue where we would show no dynamic options in the Expression editor even though there were tokens available
> fix(designer): Fixed issue with \ in Dictionary editor serialization

- apps/vs-code-designer/src/app/commands/funcCoreTools/validateFuncCoreToolsIsLatest.ts
- apps/vs-code-designer/src/app/commands/nodeJs/validateNodeJsIsLatest.ts
- apps/vs-code-designer/src/app/utils/__test__/binaries.test.ts
- apps/vs-code-designer/src/app/utils/binaries.ts
- apps/vs-code-designer/src/app/utils/nodeJs/nodeJsVersion.ts
- apps/vs-code-designer/src/constants.ts
- Current behavior just choose from nodejs or github to get the latest version of function core tools. If the nodejs fails the installation fails in general
- Now latest version is user has nodejs falls on the npm installation, if this fails it falls into github to get the lates version
- Not a breaking change
> fix(vscode): Add fallback for function core tools installation

- apps/vs-code-designer/src/app/commands/funcCoreTools/validateFuncCoreToolsIsLatest.ts
- Check for outdated function core tools, but only installs it if the major version between local installation and newest is the same
- Now if the major version between the newest and local version is different, it will mark it as outdated and will install it
- Not a breaking change
-
> fix(vscode): Auto update function core tools for major version difference

- libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
Fixes #7367 
- When running a workflow in overview page in vscode was sending the auth token in the POST API call causing a 400 error
Now run trigger api call doesn't include bearer token
- Tested in local and remote workflows
- Portal uses a different approach to run the workflows. This only affects vscode
> fix(vscode): Add noAuth to run trigger

- libs/designer-ui/src/lib/panel/recommendationpanel/connectorAvatar/index.tsx
Modified connector icon log to be a warning instead of an error.
Fixes https://github.com/Azure/LogicAppsUX/issues/7402
> fix(Designer): Modified connector icon error log as warning

- apps/vs-code-designer/src/app/utils/unitTests.ts
Trigger types (e.g. Recurrence) missing from ListMockableOperations response. All triggers should be mockable
Skip this check for triggers
> fix(vscode): Bypass isMockable check for trigger mocks

- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Revert previous change on replaceWhiteSpaceWithUnderscore and instead to make it so by default c# custom code file is execute_csharp_script_code
- **Users**: 
- **System**:
> fix(designer): Fix C Sharp Custom Code Unable to Save Due to #

- apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
- libs/designer/src/lib/core/configuretemplate/utils/helper.ts
Previously, the logic for replacing connection key names in the workflow definition was too broad and could unintentionally affect other entries. This fix ensures only exact connection name references are updated.
Users: Incorrect definitions are saved in template and thus creating invalid workflows
Developers: Safer logic reduces risk of accidental regressions when handling workflow definitions.
System: No expected impact on performance or architecture; string replacement logic is more precise.
> fix(templates): Featured connectors and parameter definition fix cherry pick

- apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
- e2e/templates/app.spec.ts
- libs/designer/src/lib/core/configuretemplate/utils/queries.ts
- libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
- libs/designer/src/lib/ui/templates/gallery/templatesfullgalleryview.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/base/template.ts
Fixes three critical issues: 
(1) Custom template queries now pull from the subscription level, not just resource group,
(2) the blank template appears only in the 'All' tab as intended,
(3) query cache now correctly stores raw template workflows.
All of these were blockers for the release because they prevented users from saving and viewing templates correctly.
- Users: Users will now see and save templates correctly, resolving previous blockers for release.
- Developers: Ensure cache key usage is consistent going forward; downstream code may need to consider this update.
- System: None expected, but verify if broader system-level template flows may be indirectly affected due to query or cache logic changes.
@bonica-ayala @divyaswarnkar 
NA
> fix(templates): Fixing query cache for template workflows to allow correct data saving

- .github/workflows/version-release.yml
- scripts/update-versions.js
The version calculation logic for patch releases had a flaw where it used the current branch's package.json version instead of finding the actual latest patch for the target version line. This caused incorrect version numbers when creating patches for hotfix branches that were based on older major.minor versions.
For example, if main branch was at 5.110.0 but you needed to patch 5.109.x, the system would incorrectly create 5.110.1 instead of 5.109.3.
This fix updates the patch version calculation to:
- Detect hotfix branch patterns (hotfix/X.Y)
- Query git tags to find the latest patch version for the correct major.minor line
- Calculate the next patch version based on the actual version being patched
- **Users**: No direct user impact - this is internal release tooling
- **Developers**: …
> Correct patch version calculation for hotfix branches 

- scripts/update-versions.js
The update-versions.js script was recently converted to ES modules (using import instead of require), but it still used the CommonJS `__dirname` variable. This causes a runtime error during the GitHub Actions workflow:
```
ReferenceError: __dirname is not defined in ES module scope
```
This fix adds the ES module equivalent of `__dirname` using `fileURLToPath(import.meta.url)` and `path.dirname()`.
- **Users**: No direct user impact - this is internal release tooling
- **Developers**: Release workflow will no longer fail at the "update version in package files" step
- **System**: Fixes broken version update functionality in release pipeline
The fix follows the standard ES module pattern for recreating `__dirname`:
- Uses `import.meta.url` to get current module URL
- Converts to file path …
> fix(scripts): Add ES module __dirname equivalent for update-versions.js

- apps/vs-code-designer/src/app/utils/__test__/unitTestUtils.test.ts
- apps/vs-code-designer/src/app/utils/unitTests.ts
Updating buildClassDefinition such that array objects always have a name. It is currently possible that an array object have a empty name which results in invalid mock output c# files.
- **Users**: Mock output files will now be generated correctly when http action schema with arrays are passed in.
- **Developers**: None.
- **System**: None.
> fix(vscode): Unit Test Array Object Name

- apps/vs-code-designer/src/app/utils/__test__/unitTestUtils.test.ts
- apps/vs-code-designer/src/app/utils/unitTests.ts
Updating buildClassDefinition such that array objects always have a name. It is currently possible that an array object have a empty name which results in invalid mock output c# files.
- **Users**: Mock output files will now be generated correctly when http action schema with arrays are passed in.
- **Developers**: None.
- **System**: None.
> fix(vscode): Unit Test Array Object Name #7472

- libs/designer/src/lib/ui/panel/connectionsPanel/selectConnection/__test__/connectionTableDetailsButton.spec.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/selectConnection/connectionTableDetailsButton.tsx
Fixes issues where Built-In connectors (Azure Functions, Service Bus, Azure Blob Storage) display an invalid creation date of "January 1, 1970 at 5:30 AM" instead of the actual creation time. This occurs when the connection's `createdTime` property is missing or set to epoch 0. The solution hides the entire creation date section in the connection details popover when this condition is detected, providing a cleaner user experience.
- **Users**: Users will no longer see confusing "January 1, 1970" creation dates for Built-In connector connections. The connection details dialog will simply omit the creation date section when the data is invalid.
- **Developers**: No API changes. The fix is contained to the UI presentation layer.
- **System**: No performance or architectural impact. Minimal …
> fix(designer): hide connection creation date when showing epoch 0

- libs/designer-ui/src/lib/text/index.tsx
- libs/designer/src/lib/ui/panel/recommendation/recommendationPanelContext.tsx
Updates the "Add a trigger" and "Add an action" panel headers to use proper semantic HTML heading markup instead of generic text components. This resolves an accessibility violation where text visually appeared as a heading but wasn't programmatically defined as one.
- **Users**: No visual changes; improved accessibility for screen reader users
- **Developers**: XLargeText component now supports semantic HTML elements via `as` prop
- **System**: Better semantic structure, no performance impact
Thanks to @Xiaoyu-Huang for reporting this accessibility issue in #7281
No visual changes - this is a semantic markup improvement only.
fixes #7281
> fix(designer): use semantic h2 heading for Add a trigger panel header

- libs/designer-ui/src/lib/card/addActionCard/__test__/__snapshots__/addActionCard.spec.tsx.snap
- libs/designer-ui/src/lib/card/addActionCard/__test__/addActionCard.spec.tsx
- libs/designer-ui/src/lib/card/addActionCard/index.tsx
This PR fixes an accessibility issue where screen readers (NVDA and Narrator) were unable to announce tooltip information when focusing on the "Add a trigger" button in the Logic Apps designer. The root cause was that the `aria-describedby` attribute was pointing to the TooltipHost component rather than an element containing accessible content for screen readers.
The fix adds a hidden element containing the tooltip text that screen readers can access through the `aria-describedby` attribute, while maintaining the existing visual tooltip functionality for sighted users.
- **Users**: Screen reader users (NVDA, Narrator) can now hear tooltip information when focusing on "Add a trigger" buttons, improving accessibility compliance
- **Developers**: No API changes; only internal DOM structure …
> fix(designer-ui): improve screen reader accessibility for 'Add a trigger' button tooltip

- libs/designer-ui/src/lib/panel/panel.less
- libs/designer-ui/src/lib/panel/panelcontent.tsx
This PR fixes an accessibility issue where scrollable content in the "About" tab was not accessible by keyboard navigation. The issue prevented users who rely on keyboard navigation from accessing the full content within the About tab, violating WCAG 2.1.1 requirements.
Fixes #7280
- **Users**: Improves accessibility for keyboard-only users who can now navigate and scroll through content in the About tab using their keyboard
- **Developers**: No API changes - only adds conditional keyboard accessibility attributes to the panel content container
- **System**: No performance impact - only adds tabIndex and ARIA attributes when the About tab is selected
1. Navigate to any workflow action panel
2. Switch to the "About" tab
3. Press Tab to focus the scrollable content area
4. Use arrow keys to …
> fix(designer-ui): make About tab scrollable content keyboard accessible

- apps/vs-code-designer/src/app/commands/workflows/enableAzureConnectors.ts
Fix for #6782. "Use connectors from Azure" command does not prompt for subscription/resource group and update local.settings.json in some scenarios in workspaces with multiple logic apps, fixed to work as intended.
- **Users**: Working "Use connectors from Azure" command for multi-logic app projects
- Andrew Eldridge (andrew-eldridge)
> fix(vscode): fix "Use connectors from Azure" for workspace with multiple logic apps

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Utilities/Workflow.ts
- apps/vs-code-react/src/app/designer/utilities/workflow.ts
- libs/vscode-extension/src/lib/services/Workflow.ts
Previously, we were recursively resolving connection references. While this approach makes sense when repeated replacements (of app settings or parameters) are necessary, it's not ideal in this case. For connectionData, which has a well-defined and fixed structure, recursive resolution isn't needed.
We encountered an ICM where a user mistakenly used an appSetting that referenced itself. Although this is technically a user error, our recursive logic caused an infinite loop, freezing the Designer.
Since we're dealing specifically with connectionData, a single-pass replacement is both safer and more efficient. It avoids potential infinite loops and better aligns with the static nature of the data.
- **Users**: Prevents Designer freezing due to infinite loops caused by improperly configured …
> fix(designer): Fixing standalone+vscode resolving connection references in standalone causing infinite loop

- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/HybridLogicAppsSteps/ConnectEnvironmentStep.ts
- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/HybridLogicAppsSteps/HybridAppCreateStep.ts
- apps/vs-code-designer/src/app/commands/deploy/deploy.ts
- apps/vs-code-designer/src/app/commands/deploy/hybridLogicApp/index.ts
- apps/vs-code-designer/src/app/commands/workflows/exportLogicApp.ts
- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForAzureResource.ts
- apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForAzureResource.ts
- apps/vs-code-designer/src/app/commands/workflows/openOverview.ts
- apps/vs-code-designer/src/app/utils/codeless/connection.ts
- apps/vs-code-designer/src/app/utils/codeless/getAuthorizationToken.ts
- apps/vs-code-designer/src/app/utils/subscription.ts
Sometimes the default tenant used to get auth token does not have required permissions. Fix by explicitly passing tenant when available.
- **Users**: Fix 401 issues related to invalid tenant across multiple commands
@andrew-eldridge
> fix(vscode): use correct tenant in getAuthorizationToken

- libs/designer/src/lib/ui/Designer.tsx
With the layout changes, we were no longer centering the graph on mount
https://github.com/Azure/LogicAppsUX/issues/7570
so when switching to the editable code view and back it was causing the graph to start at 0,0
- **Users**: Remounting the UI now centers the graph
- **System**: 
@vgouth for finding the issue
> fix(designer): Center Graph on Mount

- libs/designer-ui/src/lib/agentinstruction/index.tsx
Changes the agent instruction to use the correct value Type (string). It was inheriting the valueType from the manifest (array) as it should be serialized as so, but because the Agent instruction is combined with user instruction during serialization; however as an editor it should be of string type.
- **Users**: Can use string-accepted tokens instead of array-accepted
- **System**: 
@kewear for raising the issue
> fix(designer): Agent Instruction Value Type set incorrectly 

- apps/vs-code-designer/src/app/commands/createCodeful/CodefulWorkflowCreateStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/__test__/ConvertToWorkspace.test.ts
- apps/vs-code-designer/src/app/commands/createNewProject/createProjectSteps/FolderListStep.ts
- apps/vs-code-designer/src/app/utils/__test__/workspace.test.ts
- apps/vs-code-designer/src/app/utils/workspace.ts
Update getWorkspaceFolder to always find and return the workspace folder corresponding to the project root. If the project root is not a workspace folder, returns the parent workspace folder
- **Users**: Avoids possible edge case errors where context.workspaceFolder.Name is undefined
- **Developers**: Addresses type errors
@andrew-eldridge
> fix(vscode): Update getWorkspaceFolder to always return WorkspaceFolder

- Localize/lang/strings.pl.json
- Localize/loc/pl/strings.json.lcl
The extra braces in the polish translation were breaking the localization compilation
- **Users**: No Change
- **Developers**: No Change
- **System**: Language Compilation won't break
N/A
N/A
> fix(localization): update placeholder syntax for milliseconds in Polish strings

- libs/designer/src/lib/ui/styles.less
The React Flow control buttons (zoom in/out, fit view, search, minimap toggle) had transparent backgrounds in the light theme, making them difficult to read when the workflow graph extended beneath them. This change adds explicit white backgrounds to ensure the buttons remain visible and usable.
- **Users**: Improved visibility of control buttons when workflow graphs extend beneath them. No behavioral changes.
- **Developers**: No API changes or new patterns introduced.
- **System**: No performance impact - only CSS changes.
N/A
- Added `background: @ms-color-white;` to `.react-flow__controls-button`
- Added `background: @ms-color-white;` to `.react-flow__controls`
- Added `background: @ms-color-white;` to `.react-flow__minimap`
> fix(designer): Add opaque backgrounds to React Flow control buttons

- libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts
it was placed similar to our other inline operations for testing; however, because the python operation is actually under the ACA connector instead on inline, the mock shows up as well.
- **Users**: Removal of the mocked inline python operation
- **Developers**: Removal of an operation in search and operation manifest services
@lambrianmsft catching the issue
> fix(designer): Remove all references to Mock Python Operation 

- libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts
it was placed similar to our other inline operations for testing; however, because the python operation is actually under the ACA connector instead on inline, the mock shows up as well.
- **Users**: Removal of the mocked inline python operation
- **Developers**: Removal of an operation in search and operation manifest services
@lambrianmsft catching the issue
> fix(designer): Remove all references to Mock Python Operation

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/OAuthService.ts
- apps/vs-code-react/src/app/designer/services/oAuth.ts
- libs/logic-apps-shared/src/designer-client-services/lib/consumption/connection.ts
- libs/logic-apps-shared/src/designer-client-services/lib/oAuth.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
Previously for oauth we're defaulting to `token` in the parameter which for almost all oauth cases works; however, some connections (example Twitter) it does use a different parameter set name for listing consent links. 
- **Users**: Users will now be able to use twitter connections
- **Developers**: Changes in the oauth service to allow oauthKey to be passed
- **System**: 
@abatishchev for finding issue
> fix(designer): Modify OAuth to accept parameter Name

- libs/designer/src/lib/ui/templates/filters/templatesearchfilters.styles.ts
- libs/designer/src/lib/ui/templates/filters/templatesearchfilters.tsx
- libs/designer/src/lib/ui/templates/gallery/templatesgallery.styles.ts
- libs/designer/src/lib/ui/templates/gallery/templatesgallery.tsx
- libs/designer/src/lib/ui/templates/gallery/templatesgallerywithsearch.styles.ts
- libs/designer/src/lib/ui/templates/styles.less
This PR migrates the templates gallery from LESS to makeStyles (Fluent UI v9 CSS-in-JS) as part of the ongoing migration effort. It also fixes multiple alignment and spacing issues in the templates gallery UI:
- Moves the sort dropdown to be inline with tabs and properly aligned with template cards
- Fixes subscription box padding that had extra space
- Ensures status dropdown doesn't extend past card boundaries
- Updates grid to support 4 columns instead of 3
- Makes filter dropdowns span equally at 20% width each
- **Users**: Improved visual alignment and consistency in the templates gallery. All elements are now properly aligned within the same maximum width boundary.
- **Developers**: New makeStyles patterns established for templates components. Removes dependency on LESS files for …
> fix(templates): Migrate templates gallery to makeStyles and fix alignment issues

- libs/designer/src/lib/ui/CustomNodes/SubgraphCardNode.tsx
With a recent refactor of the node handles, two instances were missed on the subgraph nodes.
This led to black dots being shown when the handles should be invisible.
I swapped these out for the new DefaultHandle component.
- **Users**: Removed black dots from subgraph nodes
@ccastrotrejo @Eric-B-Wu
> fix(Designer): Fixed missed handle instances

- apps/vs-code-designer/src/app/commands/workflows/enableAzureConnectors.ts
Cherry-pick of the following PR: #7564 
Fix for #6782. "Use connectors from Azure" command does not prompt for subscription/resource group and update local.settings.json in some scenarios in workspaces with multiple logic apps, fixed to work as intended.
- **Users**: Working "Use connectors from Azure" command for multi-logic app projects
- **Developers**: Not impacted
- **Systems**: Not impacted
- Andrew Eldridge (andrew-eldridge)
> fix(vscode): "Use connectors from Azure" for workspace with multiple logic apps

- libs/designer/src/lib/ui/styles.less
This change adds `box-sizing: content-box` to the control buttons style in the designer UI to fix layout issues where buttons were not displaying correctly with their intended dimensions.
- **Users**: Improved visual consistency of control buttons in the designer interface
- **Developers**: No API changes or breaking changes
- **System**: Minimal performance impact, purely cosmetic CSS fix
@rllyy97
> fix(Designer): Update control buttons style to use content-box sizing

- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
- apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForLocal.ts
- apps/vs-code-designer/src/app/utils/__test__/getDebugSymbolDll.test.ts
- apps/vs-code-designer/src/app/utils/getDebugSymbolDll.ts
- apps/vs-code-react/src/app/designer/app.tsx
- apps/vs-code-react/src/app/designer/servicesHelper.ts
- libs/vscode-extension/src/lib/models/workflow.ts
Cherry-pick of the following PR: #7692 
Added functionality to support multiple initialization based on extension bundle ID for VS Code extensions. This enhancement allows different VS Code extensions to initialize with their own configuration while maintaining compatibility with existing single-extension workflows.
- **Users**: No user-facing changes - internal functionality enhancement
- **Developers**: New multi-initialize capability available for VS Code extension development
- **System**: Enhanced extension initialization system with bundle ID support
@ccastrotrejo
> feat(vscode): Add multi-initialize support based on extension bundle ID

- apps/vs-code-designer/package.json
- apps/vs-code-designer/src/main.ts
- pnpm-lock.yaml
Update @microsoft/vscode-azext-azureutils dependency from ^0.3.9 to 0.3.9-beta version for VS Code designer package and register azure utils extension variables.
- **Package Dependency**: Updated `@microsoft/vscode-azext-azureutils` from `^0.3.9` to `0.3.9-beta` in `apps/vs-code-designer/package.json`
- **Extension Registration**: Added `registerAzureUtilsExtensionVariables(ext)` call in `apps/vs-code-designer/src/main.ts` to properly register azure utils extension variables
- **Import**: Added import for `registerAzureUtilsExtensionVariables` from the azure utils package
- **Lock File**: Updated `pnpm-lock.yaml` to reflect the new beta version dependency
- **Users**: Users with Microsoft tenant will now be able to create Storage accounts and Logic apps from vscode extension
- …
> chore(vscode): Update vscode-azext-azureutils to 0.3.9-beta

- libs/designer/src/lib/common/constants.ts
- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
- libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
Agent tools with only a handoff action will now be hidden from the UX, instead only being accessible from the handoff edge (for now, keyboard accessible access will come later)
This functions similar to how we hide actions within collapsed graph nodes, they are only hidden from the graph view.
Handoff action data is still accessible and stored in state.
- **Users**: Handoff actions and their containing tools are now hidden from the workflow graph
> feat(Designer): Handoff tools are hidden from the graph

- apps/vs-code-designer/src/app/commands/createNewProject/createProjectSteps/ScriptProjectCreateStep.ts
- apps/vs-code-designer/src/app/commands/dataMapper/FxWorkflowRuntime.ts
- apps/vs-code-designer/src/app/utils/appSettings/localSettings.ts
- apps/vs-code-designer/src/app/utils/binaries.ts
Cherry-pick of the following PR - #7785
Updates VS Code extension worker runtime configuration from Node.js to .NET for Logic Apps projects and adds execute permissions for Azure Functions Core Tools binaries. This aligns the runtime configuration with Azure Logic Apps standards which primarily use .NET-based workflows, and fixes binary execution issues on Unix systems.
Needed to update permissions due to the following:
- https://github.com/Azure/azure-functions-core-tools/issues/3766
- https://github.com/Azure/azure-functions-core-tools/pull/3797
- **Users**: VS Code extension users creating new Logic Apps projects will use .NET runtime by default; improved binary execution on macOS/Linux
- **Developers**: Runtime configuration is now consistent with Azure Logic Apps standards; …
> feat(vscode): Update worker runtime to .NET and add func binary permissions

- apps/Standalone/src/mcp/app/McpStandard.tsx
- libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Adds Close Blade support to the MCP Wizard and revises the Register MCP Server handler to correctly handle workflow creation process
- **Users**: Users can now close the MCP wizard via a new button, improving usability.
- **Developers**: Refactored registration logic may affect API consumers or extension contributors.
- **System**: Minor adjustment to handler parameters; generally low architectural risk but pay attention to regression possibilities.
@preetriti1, @Eric-B-Wu
> feat(Mcp): Add Close Blade Support + Revised Register Mcp Server Call

- apps/Standalone/src/mcp/app/McpStandard.tsx
- libs/designer/src/lib/core/index.ts
- libs/designer/src/lib/core/mcp/utils/serializer.ts
- libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Adding connector info in server create payload.
This is needed for API center to show mcp server details in their UI
- **Users**: User will be able to see connector information in their mcp server
- **Developers**: Added new details in create payload which keeps it extensible
@atuannguyen1101 @Elaina-Lee @Eric-B-Wu 
NA
> feat(mcp): Adding server info in create payload from connector

- .github/workflows/pr-ai-validation.yml
This PR adds `labeled` and `unlabeled` event types to the AI PR validation workflow triggers. Currently, the workflow only runs on PR open, edit, and synchronize events. Adding label change triggers ensures the AI validation runs when labels are modified on PRs.
- **Users**: No user-facing impact
- **Developers**: AI PR validation will now automatically run when labels are added or removed from PRs
- **System**: Minimal impact - just adds two additional trigger events to existing workflow
N/A
N/A - Infrastructure change only
> fix(ci): Add label change triggers to AI PR validation workflow

- libs/designer-ui/src/lib/arrayeditor/collapsedarray.tsx
- libs/designer-ui/src/lib/arrayeditor/expandedcomplexarray.tsx
- libs/designer-ui/src/lib/arrayeditor/expandedsimplearray.tsx
- libs/designer-ui/src/lib/arrayeditor/index.tsx
- libs/designer-ui/src/lib/dictionary/index.tsx
- libs/designer/src/lib/ui/mcp/parameters/ParameterEditor.tsx
Adding capability for different editors other than string editor to help user type various inputs
- css is still broken, will be coming in a separate PR
- **Users**: Users can access different editors
- **Developers**: ParameterEditor uses different editors
- **System**: n/a
@preetriti1
> feat(Mcp): Add different editor support for parameters in Mcp

- libs/designer/src/lib/ui/settings/sections/general.tsx
Removing the default action count and letting users define it
- **Users**: Won't block users anymore and they will need to set the couunt if needed
- **Developers**: NA
- **System**: More than 100 actions can run/added by default now
> fix(designer): Remove default action count

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/ChildWorkflow.ts
The _workflowsRequestSchema cache was being shared between two different purposes: storing "workflows with request triggers" and caching individual workflow schemas. When getWorkflowTriggerSchema() or getLogicAppSwagger() added schemas for any workflow to this cache, it contaminated the "workflows with request triggers" list, causing the combobox to not show the actual returned response.
Separated into two distinct caches:
- _workflowsWithRequestTrigger: string[] - immutable list of workflow names with request triggers
- _schemaCache: Record<string, any> - general cache for all individual schema fetches
- **Users**: No longer see inconsistent workflow dropdown lists
- **Developers**: Cache architecture with separated concerns
- **System**: Eliminates race conditions in cache mutations; …
> fix(standalone): Race condition causing fetching childworkflows in parallel to miss flows

- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
There was a bug we were selecting the agent node id as the active node id rather than the tool id
- **Users**: Users should see the newly created action and tool parameters in side-by-side panels now
- **Developers**: No dev changes
- **System**: No System Changes
@Eric-B-Wu
> fix(designer): When creating agent tool to properly set the right active node

- libs/designer/src/lib/ui/mcp/connectors/ConnectorBrowseView.tsx
- libs/designer/src/lib/ui/panel/recommendation/browseView.tsx
In Designer and MCP we moved instead of loading all the operations in browse to just loading all the connectors. In doing so we also filter based on connector capabilities. Some connectors (26 connectors) seem to not have 'actions'  or 'triggers' capabilities and they end up being filtered out from our browse experience.
- **Users**: In browse, users should be able to see the previously filtered out connectors
- **Developers**: Changing some of the processing of the api results so that if a connector doesn't have either `actions` or `triggers` to show by default
- **System**: 
@eric-b-wu
> fix(designer/mcp): Fixing Browse not picking up all connectors

- libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
This change prevents agent operations from being incorrectly treated as triggers in the node details panel. Previously, agent operations would display trigger-related information because they are root nodes, but agents should not be considered triggers for UI purposes.
- **Users**: Agent operations will no longer incorrectly display trigger information in the node details panel
- **Developers**: Added logic to distinguish between triggers and agent operations using operation type checking
- **System**: Minor performance impact from additional type checking
@ccastrotrejo @rllyy97
> fix(designer): prevent agent operations from displaying trigger info

- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/handoff.ts
Added a new `x-ms-is-node-id` input parameter property.
Currently all this does is remap the parameter value with our node id replacement object.
For example on handoff nodes, the input is the id of another agent node, so if that targetted node changes it's ID, we need to update the parameter value as well. 
- **Users**: No change
- **Developers**: Added a new `x-ms-is-node-id` input parameter property
@rllyy97, @Eric-B-Wu
> feat(Designer): Added `x-ms-is-node-id` input parameter property

- .azure-pipelines/templates/stage-artifacts.yml
<\!-- Select one -->
<\!-- Select one based on potential impact -->
<\!-- Brief context: What does this change and why? -->
Fixed a syntax error in the Azure Pipeline template where a closing quote was missing in the `TargetFolder` parameter of the `stage-artifacts.yml` template. This was causing potential pipeline failures due to malformed YAML.
<\!-- Who/what is affected? -->
- **Developers**: Ensures Azure Pipeline artifacts are staged correctly without syntax errors
- **System**: Prevents potential pipeline build failures due to malformed YAML syntax
<\!-- How was this tested? -->
<\!-- Tag team members who contributed ideas, reviews, or implementation -->
<\!-- Visual changes only -->
> fix(pipeline): Add missing closing quote in stage-artifacts template

- libs/designer/src/lib/core/actions/bjsworkflow/handoff.ts
- libs/designer/src/lib/ui/connections/handoffEdge.tsx
- libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/guid.spec.ts
This PR improves the handoff naming system in the Logic Apps designer by replacing predictable source/target-based IDs with unique GUID-based identifiers. This change enhances uniqueness and prevents potential naming conflicts in complex workflows.
- **Users**: No visible changes to user experience - handoffs continue to work the same way
- **Developers**: Handoff IDs are now generated using `customLengthGuid(8)` instead of `handoff_${sourceId}_${targetId}` pattern
- **System**: Improved uniqueness of handoff identifiers, reduced risk of ID collisions
1. **Handoff ID Generation**: Updated `addAgentHandoff` to use `customLengthGuid(8)` for generating unique handoff identifiers
2. **Component Cleanup**: Removed unnecessary handoff selection logic from `handoffEdge.tsx` that relied on …
> feat(designer): improve handoff naming with unique GUIDs

- libs/designer/src/lib/ui/mcp/details/styles.ts
Changing max width of the logic app selector
- **Users**: Dropdown width will take up parent container length instead of confined by max width.
- **Developers**: no dev changes
- **System**: no system changes
@eric-b-wu
> fix(mcp): Revert Max Width of Logic App Selector

- .azure-pipelines/templates/package.yml
Updates the `npx replace-in-file` command syntax in the Azure pipeline template to use the simpler positional arguments format instead of the `--from` and `--to` flags. This follows the recent cross-platform compatibility fix pattern established in PR #7956.
- **Developers**: Improved CI/CD pipeline reliability
- **System**: More consistent replace-in-file command execution in Azure pipelines
> fix(ci): update replace-in-file command syntax in Azure pipeline

- __mocks__/workflows/BasicA2A.json
- libs/designer-ui/src/lib/agentinstruction/index.tsx
- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
- libs/designer/src/lib/common/constants.ts
- libs/designer/src/lib/ui/mcp/details/logicAppSelector.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
- libs/designer/src/lib/ui/panel/recommendation/browseView.tsx
A2A Workflows won't support user instructions. This change conditionally hides the user instructions section in the Agent Instruction editor when the workflow kind is 'agent' (A2A workflow), while keeping the system instructions visible.
- **Users**: A2A workflow users will no longer see the "User Instructions" section in the Agent Instruction
editor.
- **Developers**: Added `hideUserInstructions` prop to AgentInstructionEditor component and updated parameter flow from ParametersTab through SettingTokenField to conditionally hide user instructions based on workflow type
- **System**:  No performance impact
@Eric-B-Wu
> fix(designer): Hide Agent Instructions for A2A Workflows

- libs/designer/src/lib/common/utilities/__test__/error.test.ts
- libs/designer/src/lib/common/utilities/error.ts
Fixed a TypeError that occurred when the error handling code tried to use the 'in' operator on string error messages. The issue happened when `errorRun` contained a string like "Creating foundry agent failed with status: '401'..." instead of an object, causing `Cannot use 'in' operator to search for 'error' in [string]` errors.
The fix extracts error processing logic into a reusable `extractErrorInfo` function with proper type guards to handle various error formats safely.
- **Users**: Eliminates runtime errors when foundry agent creation fails with string error messages
- **Developers**: Provides cleaner, more maintainable error handling code with comprehensive test coverage
- **System**: Improves error handling reliability across the designer workflow monitoring system
**Test …
> fix(designer): handle string error messages and prevent 'in' operator TypeError

- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
- apps/vs-code-react/src/run-service/types.ts
- apps/vs-code-react/src/state/DesignerSlice.ts
- libs/vscode-extension/src/lib/models/workflow.ts
Cherr-pick of the following PR #7985
Fixes a critical bug in the file system connection logic where the success callback was always executed regardless of error state, and improves type safety by replacing generic `any` types with proper TypeScript interfaces.
The main issues resolved:
1. **Missing else clause**: The success callback was executing even when an error occurred in the `net use` command
2. **Poor type safety**: `updateFileSystemConnection` action used `any` type instead of the proper `CompleteFileSystemConnectionData` interface
3. **Debug code cleanup**: Removed console.log statements that were left from debugging
- **Users**: VS Code extension users will now see proper error handling when file system connections fail
- **Developers**: Improved type safety and cleaner error …
> fix(vscode): resolve file system connection callback and improve type safety

- apps/Standalone/src/mcp/app/McpStandard.tsx
- libs/designer/src/lib/core/mcp/utils/__test__/serializer.spec.ts
- libs/designer/src/lib/core/mcp/utils/serializer.ts
Restructuring workflow name(s) at the McpWizard level to be able to log the structured workflow names for telemetry purposes. As well, instead of replacing invalid characters with white characters, replacing with underscore and formatting to remove extra underscore & at front/end.
- **Users**: When workflow(s) are created, they will see updated names
- **Developers**: none
- **System**: none
@DevArjun23
> fix(Mcp): Replace and sanitize names of workflows to be created to match format

- libs/designer/src/lib/common/hooks/experimentation.ts
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/experimentationFlags.ts
Since we are deploying before the A2A integration, channels need to be enabled by default and then disable it once A2A is done (next release)
- **Users**: Users will continue to access the channels tab in this release
- **Developers**: None
> fix(designer): Enable channel tab by default and add a disable flag instead

- .azure-pipelines/1esmain.yml
- .azure-pipelines/templates/package.yml
Refactored the Azure DevOps pipeline to simplify version handling by accepting `publishVersion` as a parameter instead of calculating it inline. This removes the need for complex PowerShell scripts to determine the current version and streamlines the package template workflow.
- **Developers**: Simplified CI/CD pipeline configuration, easier to maintain and debug
- **System**: Cleaner pipeline execution with reduced complexity in version management
> refactor(ci): simplify version handling in package template

- libs/designer/src/lib/core/state/workflow/helper.ts
- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
Refactored the `clearAllRepetitionRunData` action to only clear run data from nodes that are specifically related to agents (non-root graph nodes and agent condition subgraph nodes), rather than clearing data from all nodes indiscriminately.
- **Developers**: Modified workflow state management logic for run data clearing
- **System**: Improved data management by preserving run data for non-agent nodes
N/A
> refactor(designer): clear run data only from agent nodes and subgraphs

- libs/designer/src/lib/core/state/designerView/designerViewSelectors.ts
- libs/designer/src/lib/ui/Designer.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/experimentationFlags.ts
Enable agent loop in stateful workflow behind FF
- **Users**: Users will be able to access/add agent loop in stateful workflow
- **Developers**: Need to make sure backend change for agent loop in stateful is deployment before removing the feature flag
- **System**: Agent loop is accessible in stateful workflows
> fix(designer): Add Agent loop in Stateful behind FF

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
Adding telemetry log for warning in case there is more than one allowedValues for the grantType, since we are parsing to take the first value of the allowedValue
- **Users**: none
- **Developers**: none
- **System**: none
@preetriti1
> chore(Designer): Adding telemetry for grantType allowedValues length not one

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
Adding telemetry log for warning in case there is more than one allowedValues for the grantType, since we are parsing to take the first value of the allowedValue
Cherry picked from: https://github.com/Azure/LogicAppsUX/pull/8079
- **Users**: Will be able to create SP connections on connectors like Dataverse
@preetriti1
> chore(Designer): [v5.157] Adding telemetry for grantType allowedValues length not one

- Localize/loc/de/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
Removes duplicate entries found in localization files across multiple language files. These duplicates could cause conflicts and inconsistencies in the translation system.
- **Users**: None (no user-facing change)
- **Developers**: Reduced noise in localization files; decreased possibility of key collisions
- **System**: Slightly cleaner localization dictionary; no runtime/system impact
- **Tested in**: Verified application strings load with no missing keys after duplicate removal
@ccastrotrejo
N/A - Internal file cleanup
> fix(localization): Remove duplicate entries from language files

- apps/vs-code-designer/src/app/commands/buildCustomCodeFunctionsProject.ts
- apps/vs-code-designer/src/app/utils/workspace.ts
Fixes an issue in the build custom code functions process where the function would fail when the node parameter is null or undefined. Added proper null checking and fallback to workspace root path to prevent build failures.
- **Users**: Improved reliability when building custom code functions - build process will no longer fail unexpectedly
- **Developers**: More robust error handling in VS Code extension build commands
- **System**: No impact on runtime, only improves build stage reliability
- **Tested in**: VS Code extension with custom code functions projects, verified build process works with and without valid node parameters
@ccastrotrejo
N/A - Internal build process improvement
> fix(vscode): Handle null node parameter in custom code functions build process

- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
Fixed a root node run-after setting bug.
Recently we switched `isTrigger` to be separate from our `isRoot` flag in this PR: https://github.com/Azure/LogicAppsUX/pull/8084
There was one spot where we were previously checking for isRoot but were calling it isTrigger, so I swapped it out to only happen on triggers when it needed to happen on all root nodes.
This has been fixed in this PR.
- **Users**: Users will no longer get a validation error when saving workflows with "shared" nodes inside scopes
@rllyy97, @edwardyhe
> fix(Designer): Fixed root node run-after setting in scopes (5.165)

- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/NewCodeProjectTypeStep.ts
- apps/vs-code-designer/src/app/commands/createWorkflow/createWorkflow.ts
- apps/vs-code-designer/src/extensionVariables.ts
- apps/vs-code-designer/src/main.ts
Confusing to enable and disable codeful in two separate sections- now simple flag in main.ts can be easily changed
- **Users**: none
- **Developers**: easier to enable and disable codeful create options
- **System**:
> Add single flag to enable/disable Codeful feature in VS Code Designer

- libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/handoff.ts
Removed message param from handoff.
Only temporary until backend supports it again.
- **Users**: Users will no longer see message param on handoffs
@rllyy97
> fix(Designer): Removed message param from handoff

- libs/designer/src/lib/core/actions/bjsworkflow/mcp.ts
- libs/designer/src/lib/ui/mcp/details/logicAppSelector.tsx
Fixes an issue where changing Logic Apps incorrectly reset the connection store, preventing users from adding/selecting connections. Also, includes a minor UI fix for selector search terms.
- **Users**: Users can now change Logic Apps and select or create connections without being blocked.
- **Developers**: No developer-facing changes.
- **System**: No architectural or performance/system impact.
@DevArjun23 @kewear 
NA
> fix(mcp): Resetting connection store correctly on logic app change

- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/NewCodeProjectTypeStep.ts
- apps/vs-code-designer/src/app/commands/createWorkflow/createWorkflow.ts
- apps/vs-code-designer/src/extensionVariables.ts
- apps/vs-code-designer/src/main.ts
Cherry-pick of the following PR - #8126 
Confusing to enable and disable codeful in two separate sections- now simple flag in main.ts can be easily changed
- **Users**: none
- **Developers**: easier to enable and disable codeful create options
- **System**:
> feat(vscode):  Add single flag to enable/disable Codeful feature in VS Code Designer

- apps/vs-code-designer/src/main.ts
Disabled the codeful feature in VS Code Designer by setting the `codefulEnabled` flag to `false`. This prevents codeful functionality from being used until public preview is ready.
- **Users**: Codeful feature will no longer be available in VS Code Designer
- **Developers**: No API changes, simple flag toggle
- **System**: No performance impact, minimal change to configuration
@ccastrotrejo
N/A - Configuration change only
> feat(vscode): disable codeful feature flag

- apps/vs-code-designer/src/app/commands/createProject/createProjectSteps/projectTypeStep.ts
- apps/vs-code-designer/src/app/tree/subscriptionTree/subscriptionTreeItem.ts
Cherry-pick of the following PR - #8258
Fixes a null reference error that occurs during Logic App creation when `newAppInsightsName` is null or undefined. This happens in advanced creation or hybrid scenarios where the AppInsightsCreateStep tries to access the name using `nonNullProp()` but the value hasn't been set.
The fix adds a simple patch that ensures `newAppInsightsName` is set to an empty string when it's null/undefined, preventing the error while allowing the creation step to be properly skipped.
- **Users**: Users creating Logic Apps in advanced mode will no longer encounter the "Expected value to be neither null nor undefined: newAppInsightsName" error
- **Developers**: No API changes or new patterns introduced
- **System**: Minimal impact, just prevents error condition in VS …
> fix(vs-code): prevent null error in Logic App AppInsights creation

- .azure-pipelines/1esmain.yml
Adds production signing configuration to the VS Code extension pipeline by enabling `signWithProd: true` and specifying the `azureSubscription: "MicroBuild Signing Task (DevDiv)"`. This ensures the VS Code extension is properly signed with production certificates during the build process.
- **Developers**: VS Code extension builds will now be signed with production certificates
- **System**: Improved security and trust for the VS Code extension distribution
@ccastrotrejo
N/A - Pipeline configuration change only
> chore(vscode): add production signing configuration to pipeline

- .azure-pipelines/1esmain.yml
Cherry-pick of the following PR - https://github.com/Azure/LogicAppsUX/pull/8262
Adds production signing configuration to the VS Code extension pipeline by enabling `signWithProd: true` and specifying the `azureSubscription: "MicroBuild Signing Task (DevDiv)"`. This ensures the VS Code extension is properly signed with production certificates during the build process.
- **Developers**: VS Code extension builds will now be signed with production certificates
- **System**: Improved security and trust for the VS Code extension distribution
@ccastrotrejo
N/A - Pipeline configuration change only
> chore(vscode): add production signing configuration to pipeline #8262

- .github/workflows/version-release.yml
Updating the Github action workflow to use Github token
- **Users**: None
- **Developers**: None
- **System**: Release will now use Github_token instead of PAT
> chore: Update release pipeline to use Github_Token instead of personal PAT

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/HttpClient.ts
- libs/designer-v2/src/lib/ui/FloatingRunButton/index.tsx
- libs/vscode-extension/src/lib/services/httpClient.ts
Fixes issue with response headers on VSCode httpClient
Response headers are now under property `responseHeaders` rather than `headers`
- **Users**: Fixes issue with response headers on VSCode httpClient
- **Developers**: Response headers are now under property `responseHeaders` rather than `headers`
@rllyy97
N/A
> fix(DesignerV2): Fixes httpclient response header property issue

- libs/designer-ui/src/lib/styles.less
- libs/designer-v2/src/lib/ui/CustomNodes/NoteNode/index.tsx
- libs/designer-v2/src/lib/ui/DesignerReactFlow.tsx
- libs/designer-v2/src/lib/ui/styles.less
Fixed react-flow issue that was causing nodes to quickly cycle between hidden / visible
Fixed issue with z-indexing causing drag interaction interruptions
- **Users**: Will be able to drag note nodes around as expected
@rllyy97 
N/A
> fix(DesignerV2): Fixed react-flow `NoteNode` visibility and interaction issues

- .github/workflows/update-changelog.yml
Introduced a manually triggered GitHub Actions workflow that validates release tags, generates release notes, and prepends the resulting entry to `CHANGELOG.md`, reducing manual effort during releases.
- **Users**: No direct user-facing changes; automation only.
- **Developers**: Adds a repeatable workflow for generating changelog entries and PRs from tag pairs.
- **System**: New GitHub Actions job that runs `gh`/`jq` with write permissions to update the changelog via PR.
- N/A
- N/A
> chore(ci): add changelog update pipeline

- apps/vs-code-designer/src/app/commands/__test__/buildCustomCodeFunctionsProject.test.ts
- apps/vs-code-designer/src/app/commands/__test__/pickCustomCodeWorkerProcess.test.ts
- apps/vs-code-designer/src/app/commands/buildCustomCodeFunctionsProject.ts
- apps/vs-code-designer/src/app/commands/debugLogicApp.ts
- apps/vs-code-designer/src/app/commands/deploy/deploy.ts
- apps/vs-code-designer/src/app/commands/pickCustomCodeWorkerProcess.ts
- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesigner.ts
Fixes edge case where custom code project is never built before running "deploy" command. Checks whether build is needed prior to deploying. Also fixes issue where an error will occur when attempting to attach to custom code worker process when there is no local function action in workflow. Addresses #8274 and #8273.
- **Users**: Fixes bugs (1) where custom code is not built (empty {la}\lib\custom\*) when deploying, and (2) where error occurs on debugging custom code project with no local function actions
@andrew-eldridge
> fix(vscode): Build custom code on deploy, handle error when fails to attach to custom code worker

- apps/vs-code-designer/src/app/commands/__test__/buildCustomCodeFunctionsProject.test.ts
- apps/vs-code-designer/src/app/commands/__test__/pickCustomCodeWorkerProcess.test.ts
- apps/vs-code-designer/src/app/commands/buildCustomCodeFunctionsProject.ts
- apps/vs-code-designer/src/app/commands/debugLogicApp.ts
- apps/vs-code-designer/src/app/commands/deploy/deploy.ts
- apps/vs-code-designer/src/app/commands/pickCustomCodeWorkerProcess.ts
- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesigner.ts
Cherry-pick of the following PR - #8307
Fixes edge case where custom code project is never built before running "deploy" command. Checks whether build is needed prior to deploying. Also fixes issue where an error will occur when attempting to attach to custom code worker process when there is no local function action in workflow. Addresses #8274 and #8273.
- **Users**: Fixes bugs (1) where custom code is not built (empty {la}\lib\custom\*) when deploying, and (2) where error occurs on debugging custom code project with no local function actions
@andrew-eldridge
> fix(vscode): Build custom code on deploy, handle error when fails to attach to custom code worker 

- .github/workflows/update-changelog.yml
- Ensure the changelog automation fetches the latest commit on the target branch and uses it when generating release notes.
- Add stronger input validation and surface the branch head in the generated notes to avoid mismatches when a new tag does not exist yet.
- **Users**: No user-facing impact.
- **Developers**: Release automation now points to the target branch head and records the short commit hash in the changelog entry.
- **System**: Workflow fetches the target branch, validates inputs, and compares old tags to the resolved head commit when generating notes and changelog links.
None.
None.
> chore(ci): generate release notes from target branch head

- apps/vs-code-designer/src/package.json
Cherry-pick of the following PR: #8320
Remove the `enabledApiProposals` entry from the VS Code extension manifest now that we no longer rely on the `authenticationChallenges` proposal, keeping the extension compliant with marketplace requirements.
- **Users**: None
- **Developers**: Eliminates the need to publish with proposed API opt-in and avoids warnings during reviews
- **System**: No runtime impact; manifest metadata only
N/A
N/A
> chore(vscode): remove authentication API proposal flag 

- apps/vs-code-designer/src/app/commands/pickFuncProcess.ts
- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
- apps/vs-code-designer/src/app/debug/validatePreDebug.ts
- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
- apps/vs-code-designer/src/app/utils/startRuntimeApi.ts
- apps/vs-code-designer/src/extensionVariables.ts
Fix bug where opening designer fails when launch config is missing from launch.json or doesn't exactly match expected launch config (start background func process for runtime api without using launch configs). Fixes #8329 
- **Users**: Fixes issue preventing opening designer with misconfigured launch.json file
@andrew-eldridge @ccastrotrejo @lambrianmsft 
Fixes https://github.com/Azure/LogicAppsUX/issues/8329
> fix(vscode): Start runtime api in background on designer open for each project

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerV2.tsx
- libs/designer-v2/src/lib/ui/FloatingRunButton/index.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/run.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
Users can now run draft workflows without payload
- **Users**: Able to run draft workflow
- **Developers**: Need to make sure draft api is deployed 
> feat(designerv2): Add run draft for non A2A workflows

- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
Remove steps from open designer/save workflow to mitigate open issues:
- validatePartial is returning 500 errors
- startRuntimeApi on open designer is resulting in conflicts with debugger launch tasks
- **Users**: Mitigates issues of not being able to open designer or launch debugger under certain conditions
@andrew-eldridge @ccastrotrejo @lambrianmsft
> fix(vscode): temporarily remove validatePartial, startRuntimeApi to mitigate designer issues
