- apps/vs-code-designer/.eslintrc.json
- apps/vs-code-designer/package.json
- apps/vs-code-designer/src/app/commands/dataMapper/DataMapperExt.ts
- apps/vs-code-designer/src/app/commands/dataMapper/dataMapper.ts
- apps/vs-code-designer/src/app/tree/LogicAppResourceTree.ts
- apps/vs-code-designer/src/extensionVariables.ts
- apps/vs-code-designer/src/main.ts
- apps/vs-code-react/.eslintrc.json
- apps/vs-code-react/jest.config.ts
- apps/vs-code-react/src/app/export/export.tsx
- apps/vs-code-react/src/main.tsx
- apps/vs-code-react/src/state/store.ts
This pull request primarily focuses on introducing ESLint configuration files and removing ESLint disable comments in the `vs-code-designer` and `vs-code-react` applications. The addition of the ESLint configurations will help to enforce code style and quality. The removal of the ESLint disable comments indicates that the code now adheres to the rules specified in the ESLint configurations.
* Added ESLint configuration files for both applications, extending from the root configuration and specifying rules for different file types. 
* Added a `lint` script to the `package.json` to facilitate running ESLint on the codebase.
* Removed ESLint disable comments, indicating that the code now adheres to the rules specified in the ESLint configurations.
> fix(vscode): Add eslint configuration to vs-code-designer and vs-code-react

- apps/docs/docs/Development/portal.mdx
> fix(Doc): Fixing Typo in the Development Doc

- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
Fixes https://github.com/Azure/LogicAppsUX/issues/4648
> fix(desinger): Move non-outputschema dynamic data outside fetch

- .github/workflows/production-build.yml
- apps/Standalone/src/desginer/app/AzureLogicAppsDesigner/laDesigner.tsx
- apps/Standalone/src/desginer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
- apps/Standalone/src/desginer/app/SettingsSections/contextSettings.tsx
- apps/Standalone/src/desginer/state/workflowLoadingSelectors.ts
- apps/Standalone/src/desginer/state/workflowLoadingSlice.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/parsers/ParseReduxAction.ts
- libs/designer/src/lib/core/state/designerOptions/designerOptionsInterfaces.ts
- libs/designer/src/lib/core/state/designerOptions/designerOptionsSelectors.ts
- libs/designer/src/lib/core/state/designerOptions/designerOptionsSlice.ts
- libs/designer/src/lib/core/state/dev/devInterfaces.ts
- libs/designer/src/lib/core/state/dev/devSelectors.ts
- libs/designer/src/lib/core/state/dev/devSlice.ts
- libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
- libs/designer/src/lib/core/state/tokens/tokensSlice.ts
- libs/designer/src/lib/core/store.ts
- libs/designer/src/lib/core/utils/outputs.ts
- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/ui/Designer.tsx
- libs/designer/src/lib/ui/common/PerformanceDebug/PerformanceDebug.tsx
- libs/designer/src/lib/ui/common/PerformanceDebug/Tools/InitializationTimer.tsx
- libs/designer/src/lib/ui/common/PerformanceDebug/Tools/ReduxActionCount.tsx
- libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/functions.spec.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/functions.ts
- productionNpmRCCreator.js
https://github.com/Azure/LogicAppsUX/pull/4656
> fix(designer): Move non-outputschema dynamic data outside fetch

- apps/Standalone/package.json
- libs/chatbot/package.json
- libs/designer-ui/package.json
- libs/designer-ui/src/lib/authentication/util.ts
- libs/designer-ui/src/lib/card/scopeCard/index.tsx
- libs/designer-ui/src/lib/editor/monaco/index.tsx
- libs/designer/package.json
- libs/designer/src/lib/core/actions/bjsworkflow/__test__/serializer.spec.ts
- libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
- libs/designer/src/lib/ui/connections/dropzone.tsx
- package.json
- pnpm-lock.yaml
Monaco has had some issues with Pasting in later versions, I'm going to downgrade it for the timebeing until they address it on their side. 
https://github.com/Azure/LogicAppsUX/issues/4673
> fix(Designer): Downgrade Monaco

- libs/data-mapper-v2/src/components/commandBar/EditorCommandBar.tsx
- libs/data-mapper-v2/src/ui/DataMapperDesigner.tsx
* 
UI for data mapper command bar v2
no command bar for data mapper v2
UI for data mapper command bar v2
no
> feat(Data Mapper): Data Mapper Command Bar v2 UI

- libs/designer-ui/src/lib/constants.ts
Adding "custom" as a editor type, just to align with back-end manifest type
Adding "custom" as a editor type, just to align with back-end manifest type
no
> feat(Designer): Add Custom Editor Type to align with backend type

- libs/designer/src/lib/core/utils/parameters/helper.ts
Bug fix
Old dynamic inputs are not removed from list when static parameter value changes
No
> fix(designer): Fixing clearing of dynamic inputs of parameter value changes

- libs/designer/src/lib/core/utils/parameters/helper.ts
> fix(designer): Adding dispatch in store update call to clear dynamic inputs

- e2e/designer/real-api/custom-code.spec.ts
- e2e/designer/real-api/statelessvariables.spec.ts
- e2e/testSetup/BlankLogicApp/test-app-1/inlineJS/workflow.json
- e2e/testSetup/BlankLogicApp/test-app-1/statelessVariables/workflow.json
- playwright.config.ts
writing some tests based on the tests that vendors run
> test(designer): Add some more real data E2E tests

- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
- libs/designer/src/lib/ui/panel/panelRoot.tsx
Bug fix
Parameters UI show up when operation details are not completely loaded and hence leads to UI where user edits are not persisted
> fix(designer): Fix loading indicator while adding new action

- __mocks__/workflows/Conditionals.json
- e2e/designer/mock-copypastescope.spec.ts
- libs/designer-ui/src/lib/code/util.ts
- libs/designer/src/lib/common/constants.ts
- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
- libs/logic-apps-shared/src/utils/src/lib/helpers/customcode.ts
https://github.com/Azure/LogicAppsUX/pull/4720
https://github.com/Azure/LogicAppsUX/pull/4725
https://github.com/Azure/LogicAppsUX/pull/4726
> fix(designer): Cherry-pick hotfixes for scopes/customcode

- __mocks__/workflows/Panel.json
- apps/Standalone/src/designer/app/LocalDesigner/localDesigner.tsx
- apps/Standalone/src/designer/state/workflowLoadingSlice.ts
- e2e/designer/TokenPicker.spec.ts
- e2e/designer/serialization.spec.ts
- libs/data-mapper/src/lib/components/functionList/FunctionList.tsx
- libs/data-mapper/src/lib/utils/Schema.Utils.ts
- libs/designer-ui/src/lib/azureResourcePicker/index.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickeroption.tsx
- libs/designer/src/lib/ui/panel/nodeSearchPanel/nodeSearchPanel.tsx
- libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
Fixes #4731 
https://github.com/Azure/LogicAppsUX/assets/13208452/1349129f-138b-472b-a778-07034746bace
This pull request primarily focuses on improving the search functionality across various components of the application. The key change in this pull request is the addition of the `ignoreLocation` option in the Fuse search configuration. This option has been added in multiple places across the application, which signifies that the location of the match within the text (i.e., the position of the characters in the match relative to the whole text) will no longer affect the search results. This change could potentially improve the accuracy of search results.
Key changes include:
**Fuse search configuration updates:**
* [`libs/data-mapper/src/lib/components/functionList/FunctionList.tsx`](diff …
> fix(designer): Fix issue where characters later in a token name would carry less relevence in a search

- libs/designer-ui/src/lib/panel/panel.less
Removed css "webkit-fill-available"
> fix(Designer): Removed css "webkit-fill-available"

- libs/designer-ui/src/lib/code/util.ts
> fix(designer): Fixing Customcode tokenpicker action value

- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
- libs/designer-ui/src/lib/tokenpicker/index.tsx
https://github.com/Azure/LogicAppsUX/pull/4783
> fix(Designer): Only show dropdown for array editor when there are options

- .github/workflows/coverage-report.yml
- libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/stringFunctions.spec.ts
This pull request includes changes to the `stringFunctions.spec.ts` file in the `libs/logic-apps-shared/src/utils/src/lib/helpers/__test__` directory. The changes primarily involve the addition of a new function `idDisplayCase` and its corresponding tests.
The most important changes are:
* [`libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/stringFunctions.spec.ts`](diffhunk://#diff-c233ea068c099e5b4bfcdaba0e51bdb2eac286148b6e36df27d4637adc8cf649L1-R3): Imported the `idDisplayCase` function and updated the `describe` block to reflect the changes. The `idDisplayCase` function is expected to format a string with an ID tag correctly.
* [`libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/stringFunctions.spec.ts`](diffhunk://#diff-c233ea068c099e5b4bfcdaba0e51bdb2eac286148b6e36df …
> test(designer): Add tests for display of scope ids

- libs/designer-ui/src/lib/querybuilder/AddSection.tsx
- libs/designer-ui/src/lib/querybuilder/querybuilder.less
Fixes https://github.com/Azure/LogicAppsUX/issues/4797
> fix(designer): Adding many groups to a Condition action requires awkward scroll

- libs/designer-ui/src/lib/editor/base/index.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/ColorPickerTextInput.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/DropdownItems.tsx
- libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchHeader/operationSearchHeader.less
- libs/designer-ui/src/lib/settings/settingsection/__tests__/settingTokenField.spec.tsx
- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
Cherry-picked: #4811, #4813, #4810
> chore(meta): Cherry-pick a11y fixes from main to v4.5.X

- libs/designer-ui/src/lib/editor/base/index.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/ColorPickerTextInput.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/DropdownItems.tsx
- libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchHeader/operationSearchHeader.less
- libs/designer-ui/src/lib/settings/settingsection/__tests__/settingTokenField.spec.tsx
- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
Cherry-picked: #4811, #4813, #4810
> chore(meta): Cherry-pick a11y fixes from main to v4.13.X

- apps/docs/docs/intro.md
This pull request includes changes to the `intro.md` file in the `apps/docs/docs` directory. The changes primarily aim to improve the installation instructions for the system dependencies. 
* Added a link to the official Pnpm installation guide and introduced a new section for Turbo installation with a link to its official installation guide.
> chore(docs): Add turbo installation to prerequisites documentation

- libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
Added operation ID for rule engine action
- **What kind of change does this PR introduce?** 
feature - Added operation id and connector id for new action for rule engine in the backend.
> feat(designer): Add rule execute action in operation manifests

- libs/designer-ui/src/lib/connectorsummarycard/connectorsummarycard.less
- libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchCard/operationSearchCard.less
Bug fix 
some text components not showing in dark mode
original PR here https://github.com/Azure/LogicAppsUX/pull/4826
text now shows in dark mode
https://github.com/Azure/LogicAppsUX/pull/4826
No
Check original PR link
> chore(meta): Cherry-pick dark mode fix from main

- libs/designer-ui/src/lib/html/htmleditor.less
> chore(meta): Cherry-pick padding fix into v4.18

- libs/designer-ui/src/lib/code/util.ts
Cherry pick from:
https://github.com/Azure/LogicAppsUX/pull/4767
> fix(designer): Fixing Customcode tokenpicker action value (#4767)

- e2e/designer/ensureInitializeVariable.spec.ts
- libs/designer-ui/src/lib/label/index.tsx
- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
- playwright.config.ts
> fix(designer): Using custom Label with ariaLabel for parameter editors for a11y

- apps/Standalone/src/dataMapperV1/app/DataMapperStandaloneDesignerV2.tsx
- libs/data-mapper-v2/src/components/addSchema/AddOrUpdateSchemaView.tsx
- libs/data-mapper-v2/src/components/addSchema/AddSchemaPanel.tsx
- libs/data-mapper-v2/src/components/addSchema/SelectExistingSchema.tsx
- libs/data-mapper-v2/src/components/common/DropdownTree.tsx
- libs/data-mapper-v2/src/core/DataMapDataProvider.tsx
- libs/data-mapper-v2/src/core/state/SchemaSlice.ts
- libs/data-mapper-v2/src/models/Tree.ts
- libs/data-mapper-v2/src/ui/DataMapperDesigner.tsx
set up to get schema list from VSCode, and refresh when needed
schema list is a simple mock
> Feat(Data Mapper): Moving away from mock schema list

- .github/workflows/Deploy-Documentation.yml
- .github/workflows/base-coverage.yml
- .github/workflows/compile-loc.yml
- .github/workflows/playwright.yml
- .github/workflows/production-build.yml
- .github/workflows/real-e2e.yml
- .github/workflows/test.yml
> fix(meta): Update pnpm version to use

- e2e/designer/ensureInitializeVariable.spec.ts
> fix(designer): Fixing test file

- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/HybridLogicAppsSteps/ContainerAppCreateStep.ts
- apps/vs-code-designer/src/app/utils/codeless/connectedEnvironment.ts
- apps/vs-code-designer/src/app/utils/codeless/containerApp.ts
> feat(vscode): Update smb API call

- e2e/designer/real-api/custom-code/custom-code.spec.ts
- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
> fix(designer): Fix Real API tests

- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/stringFunctions.spec.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Fixes https://github.com/Azure/LogicAppsUX/issues/4934
> fix(designer): During load, if an array is surrounded by quotes, keep those quotes

- apps/Standalone/src/templates/app/TemplatesStandaloneDesigner.tsx
- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/createWorkflowPanel.tsx
- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/reviewCreateTab.tsx
- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/usePanelTabs.tsx
- libs/designer/src/lib/ui/panel/templatePanel/templatePanel.tsx
- libs/designer/src/lib/ui/templates/TemplatesDesigner.tsx
Video is too long for end-to-end demo, so attaching the zip file of the video
[sanitizeCreateTemplate2.zip](https://github.com/user-attachments/files/15812398/sanitizeCreateTemplate2.zip)
> feat(Templates): End to End Create Experience With Sanitized Parameters

- apps/Standalone/src/App.tsx
- apps/Standalone/src/templates/app/TemplatesStandaloneDesigner.tsx
Moves over the query provider above standaloneDesigner as standaloneDesigner uses query
> fix(Templates): Fix Standalone Breaking For Query Provider Issue

- libs/data-mapper-v2/src/components/codeView/CodeView.tsx
- libs/data-mapper-v2/src/components/codeView/styles.ts
- libs/data-mapper-v2/src/components/commandBar/EditorCommandBar.tsx
- libs/data-mapper-v2/src/components/commandBar/styles.ts
- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
- libs/data-mapper-v2/src/core/state/PanelSlice.ts
- libs/data-mapper-v2/src/types/Svg.d.ts
- libs/data-mapper-v2/src/ui/DataMapperDesigner.tsx
feature
Adding new code view that gets the data map LML from the Redux store
No
once we have some other code in main, data will be shown here
> Feat(Data Mapper): basic version of code view

- apps/Standalone/src/dataMapperV1/state/DataMapDataLoader.ts
- libs/data-mapper-v2/src/components/common/reactflow/FunctionNode.tsx
- libs/data-mapper-v2/src/components/common/reactflow/styles.ts
- libs/data-mapper-v2/src/components/functionList/FunctionListItem.tsx
- libs/data-mapper-v2/src/components/functionList/styles.tsx
- libs/data-mapper-v2/src/core/DataMapDataProvider.tsx
- libs/data-mapper-v2/src/core/DataMapperDesignerProvider.tsx
- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
- libs/data-mapper-v2/src/mapHandling/MapMetadataSerializer.ts
- libs/data-mapper-v2/src/models/Function.ts
- libs/data-mapper-v2/src/ui/DataMapperDesigner.tsx
- libs/data-mapper-v2/src/utils/Function.Utils.ts
- libs/data-mapper-v2/src/utils/__test__/FunctionUtils.spec.ts
- libs/data-mapper-v2/src/utils/reactFlowTesting/NodeInspector.tsx
- libs/data-mapper/src/lib/core/DataMapDataProvider.tsx
- libs/data-mapper/src/lib/core/state/DataMapSlice.ts
- libs/data-mapper/src/lib/core/state/__test__/DataMapSlice.spec.ts
- libs/data-mapper/src/lib/mapDefinitions/MapMetadataSerializer.ts
- libs/data-mapper/src/lib/mapDefinitions/__test__/MapMetadataSerializer.spec.ts
- libs/data-mapper/src/lib/ui/DataMapperDesigner.tsx
- libs/logic-apps-shared/src/utils/src/lib/models/dataMap.ts
able to drag functions onto canvas
https://github.com/Azure/LogicAppsUX/assets/99753874/4e932ea4-babf-4eaa-85ef-541a6c9c7778
> Feat(Data Mapper): Drag functions onto canvas

- apps/vs-code-designer/src/app/commands/workflows/unitTest/runUnitTest.ts
- Bug fix
- When an exception occurs during unit test execution from the Testing blade, UI will perpetually show loading indicator
- When an exception occurs, test is displayed as failed (although no corresponding unit test run file is produced)
- No
> fix(designer): Fix infinite execution in unit test blade on exception

- apps/vs-code-designer/src/app/commands/appSettings/decryptLocalSettings.ts
- apps/vs-code-designer/src/app/commands/binaries/validateAndInstallBinaries.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/ScriptProjectCreateStep.ts
- apps/vs-code-designer/src/app/commands/createNewProject/createProjectSteps/ScriptProjectCreateStep.ts
- apps/vs-code-designer/src/app/commands/dataMapper/FxWorkflowRuntime.ts
- apps/vs-code-designer/src/app/commands/dataMapper/extensionConfig.ts
- apps/vs-code-designer/src/app/utils/appSettings/__test__/localSettings.test.ts
- apps/vs-code-designer/src/app/utils/appSettings/localSettings.ts
- apps/vs-code-designer/src/app/utils/codeless/__test__/templates.test.ts
- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
- apps/vs-code-designer/src/app/utils/fs.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/vitest.config.ts
- libs/vscode-extension/src/lib/models/bundleFeed.ts
Cherry pick of the following: 
- https://github.com/Azure/LogicAppsUX/pull/4983
- https://github.com/Azure/LogicAppsUX/pull/5014
> fix(vscode): Fix dotnet versions and local settings overwrite

- .gitignore
- CHANGELOG.md
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/LogicAppSelectionSetting/AzureStandardLogicAppSelector.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Queries/FetchHybridApps.ts
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Utilities/HybridAppUtilities.ts
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
- apps/Standalone/src/designer/app/DesignerShell/designer.tsx
- apps/Standalone/src/designer/app/LocalDesigner/localDesigner.tsx
- apps/Standalone/src/designer/app/SettingsSections/sourceSettings.tsx
- apps/Standalone/src/designer/components/settings_box.tsx
- apps/Standalone/src/designer/state/historyHelpers.ts
- apps/Standalone/src/designer/state/workflowLoadingSelectors.ts
- apps/Standalone/src/designer/state/workflowLoadingSlice.ts
- apps/Standalone/src/templates/components/DevToolbox.tsx
- apps/Standalone/src/templates/state/WorkflowLoader.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/connector.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/hybrid.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/operationmanifest.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/search.ts
Implementation of hybrid support on Standalone/ Designer
> feat(designer): Hybrid Work on Designer

- libs/logic-apps-shared/src/designer-client-services/lib/__test__/__mocks__/builtInOperationResponse.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/operations/dataoperations.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/operations/operationgroups.ts
Changes also include a typo fix in connector name for data operations
> feat(designer): Adding new operations in data operations

- libs/designer/src/lib/core/utils/parameters/__test__/dynamicdata.spec.ts
- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
> fix(designer): Object inputs must be retained when do not have leaf properties

- libs/designer-ui/src/lib/unitTesting/assertionsPanel/assertion.tsx
- libs/designer-ui/src/lib/unitTesting/assertionsPanel/assertionField.tsx
- libs/designer-ui/src/lib/unitTesting/assertionsPanel/assertions.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/designer/src/lib/core/state/unitTest/unitTestInterfaces.ts
- libs/designer/src/lib/core/state/unitTest/unitTestSelectors.ts
- libs/designer/src/lib/core/state/unitTest/unitTestSlice.ts
- libs/logic-apps-shared/src/utils/src/lib/models/unitTest.ts
Bug fix to ensure assertions are editable in the assertion pane
Assertions are currently not editable
Assertions are editable
No
> fix(designer): Fixed assertion pane editing and correctednaming

- apps/vs-code-designer/src/app/utils/unitTests.ts
Bug fix
getLatestUnitTest reads all test results JSON files
getLatestUnitTest reads only the most recent test results JSON file
No
> fix(designer): Optimize getLatestUnitTest to avoid reading all test files for workflow

- apps/vs-code-designer/src/README.md
This pull request includes updates to the `README.md` file in the `apps/vs-code-designer/src/` directory. The changes introduce new features in the Azure Logic Apps (Standard) extension for Visual Studio Code, including the Azure Logic Apps Rules Engine and .NET 8 Custom Code support.
* Added sections about the Azure Logic Apps Rules Engine and .NET 8 Custom Code support. The Rules Engine is a decision management inference engine that integrates readable, declarative, and semantically rich rules into workflows. The .NET 8 Custom Code support allows developers to integrate .NET 8 custom code into Logic Apps workspaces, offering a smooth transition to the latest .NET version and enhancing the development process.
> docs(vscode): Update Readme fie with latest releases

- libs/designer-ui/src/lib/colorizer/__test__/__snapshots__/colorizer.spec.tsx.snap
- libs/designer-ui/src/lib/colorizer/__test__/colorizer.spec.tsx
- libs/designer-ui/src/lib/colorizer/index.tsx
- libs/designer-ui/src/lib/monitoring/requestpanel/__test__/__snapshots__/requestpanel.spec.tsx.snap
- libs/designer-ui/src/lib/monitoring/retrypanel/__test__/__snapshots__/retrypanel.spec.tsx.snap
Update to aria-label/title of a button to better reflect the on-click action.
When Local time is displayed the tool tip says "Switch to Local time" 
--------------------
When UTC time is displayed the tool tip says "Switch to UTC time format"
The new behavior is when the UTC time is show, the button prompts to switch to local time and when local time is shown, button prompts to switch to UTC time.
- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to …
> fix(designer): Flip the text on toggle for date time UTC or local

- apps/vs-code-react/src/state/DataMapSliceV2.ts
- libs/data-mapper-v2/src/components/commandBar/EditorCommandBar.tsx
- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
- libs/data-mapper-v2/src/mapHandling/MapMetadataSerializer.ts
- libs/data-mapper-v2/src/ui/ReactFlow.tsx
- libs/logic-apps-shared/src/utils/src/lib/models/dataMap.ts
added new metadata for map dimensions, updates fn node position on drop
> Feat(Data Mapper): Able to update and save metadata

- libs/data-mapper-v2/src/components/common/reactflow/ConnectedEdge.tsx
- libs/data-mapper-v2/src/components/common/reactflow/ConnectionLine.tsx
- libs/data-mapper-v2/src/components/common/reactflow/SchemaNode.tsx
- libs/data-mapper-v2/src/components/common/reactflow/styles.ts
> feat(Data Mapper): Update nodes and edges

- apps/vs-code-designer/src/app/commands/workflows/switchToDotnetProject.ts
https://github.com/Azure/LogicAppsUX/pull/5110
https://github.com/Azure/LogicAppsUX/pull/5116
> fix(vscode): Cherry-picked two paramerters.json fixes

- apps/vs-code-designer/src/app/commands/workflows/unitTest/runUnitTest.ts
- apps/vs-code-designer/src/app/tree/unitTestTree/index.ts
…ould result in test blade not being updated with most recent result
Bug fix
When the "run unit test" command is run before opening the test blade, the most recent test results aren't shown when the test blade is opened.
The test blade shows results from the most recent unit test run when opened.
No
> fix(designer): fixed bug with running unit test command before opening test blade

- .gitignore
- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/usePanelTabs.tsx
Removing submodule folder as the submodule path (.gitmodule) has been removed. To prevent /templateFiles folder being added as part of the commit after running the automatic postinstall script, .the path has been added to gitignore.
> fix(build): Remove Submodule Folder

- .gitignore
- apps/Standalone/src/templates/app/TemplatesStandaloneDesigner.tsx
- libs/designer/src/lib/ui/panel/templatePanel/__tests__/createWorkflowPanel.spec.tsx
- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/reviewCreateTab.tsx
- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/usePanelTabs.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/base/template.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/template.ts
- libs/logic-apps-shared/src/designer-client-services/lib/template.ts
Adds workflowName to TemplateService openBladeAfterCreate to direct user to the correct blade of the workflow
> feat(Templates): Change TemplateService with Additional Params

- libs/designer/src/lib/core/actions/bjsworkflow/copypaste.ts
- libs/designer/src/lib/ui/connections/dropzone.tsx
Bug fix
When an action is copied ( Like Get-Items), the dynamic contents are not copied into the copy. 
copyPaste now includes node tokens. 
Before <img width="652" alt="image" src="https://github.com/user-attachments/assets/edc97b4d-c26c-48ca-8d05-9048891c244c">
After <img width="608" alt="image" …
> fix(designer): Fix copyPaste to include dynamic content

- .github/pull_request_template.md
N/A (see screenshots)
N/A (see screenshots)
> meta(all): Improve readability of pull request template

- libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchHeader/index.tsx
Search flow filter dropdowns now have `name` property.
Fixes: https://github.com/Azure/LogicAppsUX/issues/5166
> fix(designer): Added accessible names to search filter dropdowns

- libs/data-mapper-v2/src/components/common/reactflow/SchemaNode.tsx
- libs/data-mapper-v2/src/components/common/reactflow/styles.ts
Unable to view/ interact with right side handle of function node, fixed this with styling. Source schema handle was also off-center by a pixel.
> Fix(Data Mapper): fixed missing handle bug, improved schema handle styling

- apps/vs-code-designer/src/app/commands/workflows/switchToDotnetProject.ts
- apps/vs-code-designer/src/app/utils/codeless/__test__/updateBuildFile.test.ts
- apps/vs-code-designer/src/app/utils/codeless/updateBuildFile.ts
- apps/vs-code-designer/test-setup.ts
- apps/vs-code-designer/vitest.config.ts
Cherry pick of the following
- https://github.com/Azure/LogicAppsUX/pull/5212
> fix(vscode): Remove never from copy settings from publish directory in dotnet projects 

- libs/designer/src/lib/core/utils/parameters/helper.ts
* Add validation for parameterDynamicValues
* Fix commit
> feat(hotfix): hotfix a commit into v4.44

- libs/designer/src/lib/core/graphlayout/__test__/elklayout.spec.ts
- libs/designer/src/lib/ui/CanvasFinder.tsx
- libs/designer/src/lib/ui/Designer.tsx
Cherry-pick #5229 to unblock release of v4.45.X.
> chore(designer): Cherry-pick 'Canvas properly centered on load (#5229)' into v4.45

- downloadTemplates.js
fix(Templates) Fixed Build Fail Due to Templates with Non-Json Artifacts
> fix(Templates): Fixed Build Fail Due to Templates with Non-Json Artifacts

- downloadTemplates.js
fix(Templates) Fixed Build Fail Due to Templates with Non-Json Artifacts
> fix(Hotfix): Fixed Build Fail Due to Templates with Non-Json Artifacts

- libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheader.spec.tsx.snap
- libs/designer-ui/src/lib/panel/panelheader/panelheader.tsx
Cherry-pick of #5198 into v4.45.
> chore(designer): Cherry-pick "Fixed fluent `autoload` property causing console error" into v4.45

- apps/vs-code-designer/src/app/commands/dataMapper/DataMapperPanel.ts
loads and saves v2 metadata with new name, to avoid loading file of incompatible type, and allows for backwards compatibility without overwriting other metadata
> feat(Data Mapper): Renaming metadata file to be compatible with V1

- apps/vs-code-designer/src/app/utils/bundleFeed.ts
> fix(vscode): Auto Runtime Dependencies installation of latest FuncCoreTools

- libs/designer/src/lib/core/templates/utils/helper.ts
Fixed connector filter not displaying proper related templates due to / and uppercase/lowercase issues
> fix(Templates): connector filter not working properly

- apps/vs-code-designer/src/app/commands/dotnet/installDotNet.ts
- apps/vs-code-designer/src/app/commands/funcCoreTools/installFuncCoreTools.ts
- apps/vs-code-designer/src/app/commands/nodeJs/installNodeJs.ts
- apps/vs-code-designer/src/app/utils/binaries.ts
- apps/vs-code-designer/src/app/utils/bundleFeed.ts
Reverts Azure/LogicAppsUX#5225
> fix(vscode): Revert change for: Async Download for Dependencies and Graceful Error Handling

- libs/data-mapper-v2/package.json
- libs/data-mapper-v2/src/ui/ReactFlow.tsx
- pnpm-lock.yaml
> fix(Data Mapper): Fix function node dragging

- libs/designer-ui/src/lib/monitoring/retrypanel/index.tsx
- libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
* Update selector for retry history and add useEffect
* Remove logs
* Update useEffect to useMemo
* Update retryHistory to useMemo
> fix(designer): Update selector for retry history and add useMemo (#5255)

- libs/designer/src/lib/core/actions/bjsworkflow/copypaste.ts
- libs/designer/src/lib/ui/connections/dropzone.tsx
reverting the change from this bug https://github.com/Azure/LogicAppsUX/commit/6ab89920e86836ee7c5b8b3e7d81ad4916ebd904
We need to address the for loop issue before fixing this.
> fix(designer): Fix revert changes in copypaste

- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/HybridLogicAppsSteps/ConnectEnvironmentStep.ts
- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/HybridLogicAppsSteps/HybridAppCreateStep.ts
- apps/vs-code-designer/src/app/commands/deploy/deploy.ts
- apps/vs-code-designer/src/app/commands/deploy/hybridLogicApp/cleanResources.ts
- apps/vs-code-designer/src/app/commands/deploy/hybridLogicApp/connectToSMB.ts
- apps/vs-code-designer/src/app/commands/deploy/hybridLogicApp/index.ts
- apps/vs-code-designer/src/app/commands/deploy/notifyDeployComplete.ts
- apps/vs-code-designer/src/app/commands/deploy/storageAccountSteps/CustomLocationStorageAccountStep.ts
- apps/vs-code-designer/src/app/tree/LogicAppResourceTree.ts
- apps/vs-code-designer/src/app/tree/slotsTree/SlotTreeItem.ts
- apps/vs-code-designer/src/app/tree/subscriptionTree/SubscriptionTreeItem.ts
- apps/vs-code-designer/src/app/utils/codeless/hybridLogicApp/connectedEnvironment.ts
- apps/vs-code-designer/src/app/utils/codeless/hybridLogicApp/hybridApp.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/package.json
- libs/vscode-extension/src/lib/models/context.ts
> fix(vscode): hybrid logic apps bug fixes

- libs/designer/src/lib/core/actions/bjsworkflow/copypaste.ts
- libs/designer/src/lib/ui/connections/dropzone.tsx
> chore(meta): revert copy paste action on v4.45

- e2e/designer/tabFocus.spec.ts
Just adding a test to cover the panel header focus.
Catches the recent issue we had to patch with our portal release.
> chore(Designer): Added panel header focus test

- libs/designer/src/lib/core/actions/bjsworkflow/copypaste.ts
- libs/designer/src/lib/ui/connections/dropzone.tsx
> chore(meta): revert copy paste action on v4.44

- libs/data-mapper-v2/src/components/commandBar/EditorCommandBar.tsx
- libs/data-mapper-v2/src/components/common/selector/FileSelector.tsx
- libs/data-mapper-v2/src/components/functionsPanel/FunctionPanel.tsx
> fix(Data Mapper): Move options for Radio button below the option instead of after RadioGroup

- libs/designer-ui/src/lib/tokenpicker/index.tsx
> fix(designer-ui): Fix Monaco editor disappearing in Dynamic Content view

- libs/designer-ui/src/lib/tokenpicker/index.tsx
Cherry-pick of #5350 into v4.51.
> chore(designer-ui): Cherry-pick "Fix Monaco editor disappearing in Dynamic Content view" into v4.51

- downloadTemplates.js
- libs/designer/src/lib/core/state/templates/templateSlice.ts
- libs/designer/src/lib/ui/templates/filters/templateFilters.tsx
- libs/designer/src/lib/ui/templates/styles.less
- let images be rendered by the url, preventing the build to not render images (no change in UX)
> fix(Templates): Image not Rendering in Prod + Sort By Text

- libs/designer/src/lib/core/actions/bjsworkflow/__test__/initialize.spec.ts
- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/utils/parameters/__test__/dynamicdata.spec.ts
- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
- libs/logic-apps-shared/src/designer-client-services/lib/operationmanifest.ts
- libs/logic-apps-shared/src/parsers/lib/common/schemaprocessor.ts
- libs/logic-apps-shared/src/parsers/lib/manifest/__test__/parser.spec.ts
- libs/logic-apps-shared/src/parsers/lib/manifest/parser.ts
> fix(designer): Dynamic input parameters have extra $ parameter for parent key when aliases are present

- apps/docs/docs/tsg.mdx
Removed the doc section for mitigation since it specified moving to legacy designer
> chore(tsg): Remove legacy designer mitigation steps from tsg

- .prettierrc
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
- libs/designer-ui/src/lib/panel/panel.less
- libs/designer-ui/src/lib/panel/panelcontainer.tsx
- libs/designer-ui/src/lib/panel/panelheader/__test__/panelheader.spec.tsx
- libs/designer-ui/src/lib/panel/panelheader/panelheader.tsx
- libs/designer-ui/src/lib/panel/panelheader/panelheadercomment.tsx
- libs/designer/src/lib/ui/menuItems/commentMenuItem.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
With the pinning of panel, comments were broken:
Before:
After:
> fix(designer): Fix Comments on nodes

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
- libs/designer-ui/src/lib/panel/panel.less
- libs/designer-ui/src/lib/panel/panelcontainer.tsx
- libs/designer-ui/src/lib/panel/panelheader/__test__/panelheader.spec.tsx
- libs/designer-ui/src/lib/panel/panelheader/panelheader.tsx
- libs/designer-ui/src/lib/panel/panelheader/panelheadercomment.tsx
- libs/designer/src/lib/ui/menuItems/commentMenuItem.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
https://github.com/Azure/LogicAppsUX/pull/5370
> fix(designer): Fix Comments on nodes (#5370)

- libs/designer/src/lib/core/state/panelV2/panelSlice.ts
- libs/designer/src/lib/ui/Designer.tsx
Cherry-pick of #5371 into v4.51.
> chore(designer): Hotfix "Ensure panel is closed when nodes are deselected" into v4.51

- libs/designer-ui/src/lib/arrayeditor/expandedcomplexarray.tsx
- libs/designer-ui/src/lib/arrayeditor/expandedsimplearray.tsx
- libs/designer-ui/src/lib/arrayeditor/util/util.ts
- libs/designer-ui/src/lib/combobox/index.tsx
Fixes https://github.com/Azure/LogicAppsUX/issues/5352
> fix(designer): Fix Combobox in Complex/Simple Array editor to properly handle item types

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx
> fix(designer): revert Standalone Designer Command offsetting Add

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx
- libs/designer-ui/src/lib/panel/__test__/__snapshots__/panelContent.spec.tsx.snap
- libs/designer-ui/src/lib/panel/panel.less
- libs/designer-ui/src/lib/panel/panelcontent.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/copypaste.ts
- libs/designer/src/lib/ui/common/EdgeContextualMenu/EdgeContextualMenu.tsx
- libs/designer/src/lib/ui/connections/dropzone.tsx
Fixes https://github.com/Azure/LogicAppsUX/issues/5278
> fix(designer): Copy Paste to include Comments

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
- libs/designer/src/lib/ui/styles.less
Fixed local designer height issue
Fixed react flow controls + minimap margin issue
> fix(designer): Fixed local designer height issue

- libs/data-mapper-v2/src/components/canvas/ReactFlow.tsx
- libs/data-mapper-v2/src/components/codeView/styles.ts
- libs/data-mapper-v2/src/components/common/selector/FileSelector.tsx
- libs/data-mapper-v2/src/components/common/selector/styles.ts
> fix(Data Mapper): Remove animated for the collapsed temporary edge

- libs/data-mapper-v2/src/components/common/reactflow/FunctionNode.tsx
- libs/data-mapper-v2/src/components/common/reactflow/styles.ts
- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
- libs/data-mapper-v2/src/ui/ReactFlow.tsx
- libs/data-mapper-v2/src/utils/Connection.Utils.ts
> fix(Data Mapper): Fixing connection order

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx
- libs/logic-apps-shared/src/parsers/lib/common/schemaprocessor.ts
Fixes https://github.com/Azure/LogicAppsUX/issues/5101
> fix(designer): Adding support for multiple types in the schema processor

- libs/designer/src/lib/ui/common/EdgeContextualMenu/EdgeContextualMenu.tsx
> chore(designer): Cherry-pick "Fixed edge context menu positioning" into v4.58

- libs/data-mapper-v2/src/components/functionsPanel/FunctionPanel.tsx
- libs/data-mapper-v2/src/components/schema/SchemaPanel.tsx
- libs/data-mapper-v2/src/core/state/PanelSlice.ts
> fix(Data Mapper): Hide other panels if one panel opens + Title changes

- apps/vs-code-designer/src/app/utils/dotnet/dotnet.ts
> fix(vscode): Fix determining latest local .NET SDK version

- apps/vs-code-designer/src/LogicAppResolver.ts
> fix(vscode): Standarize workflow id when resolving resource (#5422)

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
- libs/designer-ui/src/lib/panel/__test__/__snapshots__/panelcontainer.spec.tsx.snap
- libs/designer-ui/src/lib/panel/__test__/panelcontainer.spec.tsx
- libs/designer-ui/src/lib/panel/panelUtil.ts
- libs/designer-ui/src/lib/panel/panelcontainer.tsx
- libs/designer-ui/src/lib/styles.less
- libs/designer/src/lib/core/DesignerProvider.tsx
- libs/designer/src/lib/ui/Designer.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
- libs/designer/src/lib/ui/panel/panelRoot.tsx
Cherry pick of the following:
https://github.com/Azure/LogicAppsUX/pull/5397
> fix(designer): Un-revert panel changes & fix sizing to accommodate that change

- apps/vs-code-designer/src/README.md
> docs(vscode): Update Read.me - ACL Keys announcement

- libs/data-mapper-v2/src/mapHandling/MapDefinitionDeserializer.ts
- libs/data-mapper-v2/src/mapHandling/__test__/MapDefinitionDeserializer.spec.ts
functions are re-created during deserialization if they have multiple outputs
functions that are equivalent are combined instead of added twice
> fix(Data Mapper): Able to deserialize function with multiple outputs, without duplicate function

- libs/data-mapper-v2/src/components/canvas/ReactFlow.tsx
- libs/data-mapper-v2/src/components/common/reactflow/FunctionNode.tsx
- libs/data-mapper-v2/src/components/common/reactflow/SchemaNode.tsx
- libs/data-mapper-v2/src/components/common/reactflow/edges/ConnectedEdge.tsx
- libs/data-mapper-v2/src/components/common/reactflow/edges/ConnectionLine.tsx
- libs/data-mapper-v2/src/components/common/reactflow/edges/LoopEdge.tsx
- libs/data-mapper-v2/src/components/common/reactflow/styles.ts
- libs/data-mapper-v2/src/components/functionList/FunctionListItem.tsx
- libs/data-mapper-v2/src/components/functionsPanel/FunctionPanel.tsx
- libs/data-mapper-v2/src/components/schema/SchemaPanel.tsx
- libs/data-mapper-v2/src/components/schema/styles.ts
- libs/data-mapper-v2/src/components/schema/tree/RecursiveTree.tsx
- libs/data-mapper-v2/src/components/schema/tree/SchemaTree.tsx
- libs/data-mapper-v2/src/core/DataMapperDesignerProvider.tsx
- libs/data-mapper-v2/src/core/ThemeConect.ts
- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
- libs/data-mapper-v2/src/core/state/selectors/selectors.ts
- libs/data-mapper-v2/src/ui/styles.ts
- libs/data-mapper-v2/src/utils/search/TrieTree.ts
- libs/data-mapper-v2/src/utils/search/TrieTreeNode.ts
- libs/data-mapper-v2/src/utils/search/useSearch.ts
- Fixing Search to remove unnecessary spacing and elements being shown
- Add Search onClose Icon
- Fixing Hover/Selection State
- Design changes for Node width and tree spacing
- Revert Scrolling to enable scrolling in separate schemas
> fix(Data Mapper): Fix Search and Selection/Hover states

- apps/vs-code-designer/package.json
- apps/vs-code-designer/src/LogicAppResolver.ts
- pnpm-lock.yaml
This pull request introduces updates to the `vs-code-designer` application, focusing on adding support for Azure Resource Graph and refactoring the `LogicAppResolver` to utilize this new client. The most important changes include updating dependencies in `package.json` and modifying the `LogicAppResolver` class to replace the `createContainerClient` with the `ResourceGraphClient`.
* Added `@azure/arm-resourcegraph` dependency to support querying Azure resources.
* Imported `ResourceGraphClient` from `@azure/arm-resourcegraph` and removed the `createContainerClient` import.
* Replaced the `createContainerClient` with `ResourceGraphClient` in the `getSubscriptionSites` method, updating the logic to query container apps using Azure Resource Graph.
> feat(vscode): Implement resource graph to fetch hybrid apps

- apps/vs-code-designer/src/README.md
* Update README.md
* Fix Type
* Update README.md
Fix typo on link
> docs(vscode): Update Read.me - ACL Keys announcement (#5431)

- libs/data-mapper-v2/src/components/common/reactflow/FunctionNode.tsx
- libs/data-mapper-v2/src/ui/styles.ts
> fix(Data Mapper): Remove parent scrolling (scrolling is enabled individually in schemas) + fix function node state

- libs/data-mapper-v2/src/components/test/TestPanelBody.tsx
> fix(Data Mapper): Show error for Test in Response body if content is null

- libs/designer-ui/src/lib/html/plugins/toolbar/helper/__test__/util.spec.ts
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/util.ts
> fix(designer): fix linebreak issues (#5392)

- libs/data-mapper-v2/src/mapHandling/MapDefinitionDeserializer.ts
- libs/data-mapper-v2/src/mapHandling/__test__/MapDefinitionDeserializer.spec.ts
> Feat(Data Mapper): Deserialize JSON loops

- libs/data-mapper-v2/src/components/canvas/ReactFlow.tsx
- libs/data-mapper-v2/src/components/commandBar/EditorCommandBar.tsx
- libs/data-mapper-v2/src/components/schema/tree/SchemaTree.tsx
- libs/data-mapper-v2/src/components/schema/tree/useNodePosition.ts
- libs/data-mapper-v2/src/core/DataMapperDesignerContext.tsx
- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
- libs/data-mapper-v2/src/mapHandling/MapMetadataSerializer.ts
- libs/data-mapper-v2/src/ui/DataMapperDesigner.tsx
- libs/logic-apps-shared/src/utils/src/lib/models/dataMap.ts
> feat(Data Mapper): Reset function node positions

- libs/data-mapper-v2/src/components/common/reactflow/FunctionNode.tsx
- libs/data-mapper-v2/src/components/common/reactflow/SchemaNode.tsx
> fix(Data Mapper): Connect to the source from function node

- libs/data-mapper-v2/src/components/common/reactflow/FunctionNode.tsx
- libs/data-mapper-v2/src/components/schema/tree/RecursiveTree.tsx
- libs/data-mapper-v2/src/ui/DataMapperDesigner.tsx
> fix(Data Mapper): Unselect if clicked outside

- libs/designer/src/lib/ui/common/EdgeContextualMenu/EdgeContextualMenu.tsx
Small change to add data-automation-id for custom menu.
> fix(designer): add data-automation-id for custom menu in EdgeContextualMenu

- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/usePanelTabs.tsx
> fix(Templates): Basic Tab Always Show Error On First Enter

- libs/data-mapper-v2/src/components/canvas/ReactFlow.tsx
- libs/data-mapper-v2/src/components/common/reactflow/edges/IntermediateConnectedEdge.tsx
- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
- libs/data-mapper-v2/src/core/state/selectors/selectors.ts
> feat(Data Mapper): Add delete and selected state for temporary connections 

- libs/designer/src/lib/core/index.ts
> fix(designer): Export updateNodeConnection thunk

- libs/designer-ui/src/lib/html/plugins/toolbar/helper/HTMLChangePlugin.tsx
- libs/designer-ui/src/lib/html/plugins/toolbar/helper/util.ts
Cherry-pick of the following: 
https://github.com/Azure/LogicAppsUX/pull/5508
> fix(designer): Encode and Decode tokens with html tags (#5508)

- libs/data-mapper-v2/src/components/common/reactflow/SchemaNode.tsx
- libs/data-mapper-v2/src/components/common/reactflow/styles.ts
- libs/data-mapper-v2/src/components/common/selector/FileSelector.tsx
- libs/data-mapper-v2/src/components/common/selector/styles.ts
- libs/data-mapper-v2/src/components/schema/SchemaPanel.tsx
> fix(Data Mapper): Enhance search and fix node positions

- libs/data-mapper-v2/src/components/common/reactflow/SchemaNode.tsx
- libs/data-mapper-v2/src/components/common/reactflow/styles.ts
- libs/data-mapper-v2/src/components/test/TestPanelBody.tsx
> fix(Data Mapper): Fix right handle node

- libs/designer-ui/src/lib/tokenpicker/index.tsx
- libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickersection.tsx
Fixed issue with making token-picker fullscreen
Fixed issue with token picker being slightly off the bottom of the screen
Cleaned up unnecessary size logic
Fixed https://github.com/Azure/LogicAppsUX/issues/5498
> fix(Designer): Fixed token-picker fullscreen issue

- libs/data-mapper-v2/src/components/schema/tree/RecursiveTree.tsx
- libs/data-mapper-v2/src/components/schema/tree/styles.ts
> feat(Data Mapper): Add required to non-optional fields

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/ChildWorkflow.ts
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
- libs/designer/src/lib/core/queries/connections.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/connection.ts
- libs/logic-apps-shared/src/designer-client-services/lib/connection.ts
- libs/logic-apps-shared/src/designer-client-services/lib/consumption/connection.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
> fix(designer): Custom connector connections are not loading in designer

- libs/data-mapper-v2/src/components/common/reactflow/FunctionNode.tsx
- libs/data-mapper-v2/src/components/test/TestPanelBody.tsx
- libs/data-mapper-v2/src/ui/DataMapperDesigner.tsx
> fix(Data Mapper): Scroll editor and remove yellow node for full inputs

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/ChildWorkflow.ts
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
- libs/designer/src/lib/core/queries/connections.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/connection.ts
- libs/logic-apps-shared/src/designer-client-services/lib/connection.ts
- libs/logic-apps-shared/src/designer-client-services/lib/consumption/connection.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
This is a cherry pick to customer issue
> fix(designer): Custom connector connections are not loading in designer (#5548)

- libs/data-mapper-v2/src/components/canvas/ReactFlow.tsx
- libs/data-mapper-v2/src/components/common/reactflow/FunctionNode.tsx
- libs/data-mapper-v2/src/components/common/reactflow/SchemaNode.tsx
- libs/data-mapper-v2/src/components/common/reactflow/edges/ConnectedEdge.tsx
- libs/data-mapper-v2/src/components/functionConfigurationMenu/functionConfigurationPopover.tsx
- libs/data-mapper-v2/src/components/functionConfigurationMenu/styles.ts
- libs/data-mapper-v2/src/components/schema/tree/RecursiveTree.tsx
- libs/data-mapper-v2/src/components/schema/tree/SchemaTree.tsx
- libs/data-mapper-v2/src/components/schema/tree/useNodePosition.ts
- libs/data-mapper-v2/src/components/schema/tree/useOnScreen.ts
- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
- libs/data-mapper-v2/src/utils/Connection.Utils.ts
> feat(Data Mapper): Add temporary connections for existing map

- libs/data-mapper-v2/src/components/canvas/ReactFlow.tsx
- libs/data-mapper-v2/src/components/canvas/useReactflowStates.ts
> fix(Data Mapper): Refactor to move logic to custom hook

- libs/designer/src/lib/core/utils/parameters/__test__/dynamicdata.spec.ts
Follow-up for https://github.com/Azure/LogicAppsUX/pull/5526 with adding tests
> test(designer): Add unit tests for dynamic outputs aliasing

- libs/designer/src/lib/ui/connections/__tests__/helpers.spec.ts
- libs/designer/src/lib/ui/connections/dropzone.tsx
- libs/designer/src/lib/ui/connections/helpers.ts
fixes #5535 
https://github.com/user-attachments/assets/2b283f38-aae0-497e-b798-b076207beb7c
> fix(Designer): Scope Nodes can be moved to Invalid locations

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/graphlayout/elklayout.ts
- libs/designer/src/lib/core/queries/connections.ts
- libs/designer/src/lib/core/utils/swagger/operation.ts
- libs/designer/src/lib/ui/CustomNodes/GraphContainerNode.tsx
- libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
- libs/designer/src/lib/ui/common/LoopsPager/LoopsPager.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/connectionEntry.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/selectConnection/connectionTable.tsx
- libs/logic-apps-shared/src/utils/src/lib/helpers/hooks.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Cherry-picking 3 prs to 4.71:
- https://github.com/Azure/LogicAppsUX/pull/5586
- https://github.com/Azure/LogicAppsUX/pull/5572
- https://github.com/Azure/LogicAppsUX/pull/5575
> fix(designer): Fixing hidden edges, connection id slash, loop pager component

- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/appService.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/function.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/manifests/http.ts
- libs/logic-apps-shared/src/designer-client-services/lib/consumption/manifests/apiManagement.ts
- libs/logic-apps-shared/src/designer-client-services/lib/consumption/manifests/appServices.ts
- libs/logic-apps-shared/src/designer-client-services/lib/consumption/manifests/batchWorkflow.ts
- libs/logic-apps-shared/src/designer-client-services/lib/consumption/manifests/invokeWorkflow.ts
- libs/logic-apps-shared/src/designer-client-services/lib/consumption/manifests/swaggerFunctions.ts
> fix(designer): Correctly setting auto casting for manifests and fixing path parameters encoding

- apps/vs-code-designer/src/app/commands/deploy/deploy.ts
This reverts commit 46fb33089a677e530261abdc2e10164f43558c01.
> fix(vscode): Revert convert the authentication type from Raw to MSI when deploying Logic App (#5539)

- libs/logic-apps-shared/src/designer-client-services/lib/consumption/manifests/flatfile.ts
> fix(designer): Fixing the manifest schema for flatfiledecoding

- libs/designer-ui/src/lib/tokenpicker/tokenpicker.less
* [N/A] Tests for the changes have been added (for bug fixes or features)
Better UI for customers
> fix(designer-ui): OK label is too far to the right in expression assistant

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
- libs/designer/src/lib/core/actions/bjsworkflow/connections.ts
- libs/designer/src/lib/core/state/designerOptions/designerOptionsInterfaces.ts
- libs/designer/src/lib/core/state/designerOptions/designerOptionsSlice.ts
- libs/logic-apps-shared/src/designer-client-services/index.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/index.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/userpreference.ts
- libs/logic-apps-shared/src/designer-client-services/lib/userpreference.ts
> feat(designer): Adding support for recently used connection for a connector

- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
> fix(designer): Fixing null type of output for tokens filtering

- libs/data-mapper-v2/src/components/test/TestPanelBody.tsx
> fix(Data Mapper): Update test content in Test panel

- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
> fix(designer): Fixing null type of output for tokens filtering (#5627)

- libs/data-mapper-v2/src/components/functionConfigurationMenu/outputTab/outputTab.tsx
> Fix(Data Mapper): Remove output connection when a new one is added from the menu

- apps/Standalone/package.json
- apps/vs-code-designer/package.json
- libs/logic-apps-shared/package.json
- libs/vscode-extension/package.json
- pnpm-lock.yaml
> chore(Security): Update axios to safer version

- libs/data-mapper-v2/src/components/canvas/ReactFlow.tsx
> fix(Data Mapper): Fix function node drag event

- libs/designer-ui/src/lib/combobox/index.tsx
- libs/designer-ui/src/lib/dropdown/index.tsx
> fix(designer): Doing case insensitive match of dropdown items unless specified

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
- libs/chatbot/src/lib/ui/chatbot.tsx
- libs/data-mapper-v2/src/components/canvas/ReactFlow.tsx
- libs/designer/src/lib/ui/Designer.tsx
fixes #5649 and #5647
- fixes the command bar not properly picking up the overflow
- fixes the action recommendation panel being cut off
- fixes clicking on editable code view with the chatbot selected breaking UI issue
- fixes wrong spacing on the left & minimap issue
https://github.com/user-attachments/assets/3496f3ea-25e1-4799-b828-4e2f62182737
> fix(Designer): Chatbot Panel Overlapping & Disappearing Issues

- downloadTemplates.js
Updating templates release version to follow the current cycle
> chore(Templates): Updating Templates Release Version

- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
Generating template scripts can fail for unexpected reasons. It can refer to lingering func.exe host processes and can break when the func.exe host has not started. 
Users should see more consistent successes when generating deployment scripts and receive better error messaging. Will now check to make sure the stored func.exe process still exists, and if it doesn't will restart the design time process to create a new func.exe.
A more consistent IaC experience.
> fix(vscode): Improve IaC Generation Stability

- libs/data-mapper-v2/src/components/schema/SchemaPanel.tsx
- libs/data-mapper-v2/src/components/schema/SchemaPanelBody.tsx
- libs/data-mapper-v2/src/components/schema/tree/SchemaTree.tsx
> fix(Data Mapper): Use tree's in-built search

- libs/data-mapper-v2/src/components/common/reactflow/styles.ts
> fix(Data Mapper): OnHover border color take the fluent ui's default value

- libs/data-mapper-v2/src/components/functionConfigurationMenu/inputTab/inputTab.tsx
> fix(Data Mapper): Update function desc

- libs/designer-ui/src/lib/tokenpicker/__test__/nl2fExpressionAssistant.spec.tsx
- libs/designer-ui/src/lib/tokenpicker/nl2fExpressionAssistant.tsx
* [N/A] Tests for the changes have been added (for bug fixes or features)
* [n?A] Docs have been added or updated (for bug fixes or features)
There was not much telemetry for expression assistant. We added it.
Answering these questions now:
1) How many users clicked the create expression button
2) How many users clicked the ok button
3) How many users got a response "There was a problem creating an expression .."
4) How many users got a response that wasn't "a problem with creating an expression..."
> chore(designer): Add Telemetry for Expression Editor

- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
- package.json
- pnpm-lock.yaml
Currently on Mac, there are hanging processes and extra func processes that have been created due to a difference in behavior of finding out if the func process exists. In Windows, func is a grandchild process and in *nix, they are children processes.
Extra func are not created, and updated so that func processes are reliably closed during shutdown.
> fix(vscode): Improved IaC for Mac

- .github/ISSUE_TEMPLATE/templates.yml
Adding Templates as part of bug issue submission to automate the process and minimize missing items
> meta(Templates): Add Templates Issue Create Template

- libs/data-mapper-v2/src/components/common/DropdownTree.tsx
- libs/data-mapper-v2/src/components/common/selector/FileSelector.tsx
- libs/data-mapper-v2/src/components/schema/SchemaPanelBody.tsx
> fix(Data Mapper): schema refresh works

- libs/data-mapper-v2/src/components/functionConfigurationMenu/inputDropdown/InputDropdown.tsx
- libs/data-mapper-v2/src/components/functionConfigurationMenu/inputTab/inputTab.tsx
- libs/data-mapper-v2/src/components/functionConfigurationMenu/outputTab/outputTab.tsx
sets custom value as input whenever the dropdown is closed
disallow custom value from the output dropdown as there is no use case for this
> fix(Data Mapper): automatically adding custom values instead of requiring second click

- apps/vs-code-designer/package.json
- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
- apps/vs-code-designer/src/app/utils/bundleFeed.ts
- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
- apps/vs-code-designer/src/extensionVariables.ts
- apps/vs-code-designer/src/main.ts
- pnpm-lock.yaml
Added IaC Metadata to each workflow, capturing extension version and bundle version. Fixed regression with func host closing in windows.
IaC Metadata will be added to each workflow in a logic app. Func hosts launched by the extension in windows will consistently close.
> feat(vscode): IaC Metadata and Fixes

- libs/designer-ui/package.json
- pnpm-lock.yaml
https://github.com/Azure/LogicAppsUX/pull/5685
> chore(designer): update dompurify manually

- libs/data-mapper-v2/src/components/functionConfigurationMenu/inputTab/inputTab.tsx
> fix(Data Mapper): Remove re-ordering icon until we implement the behavior

- apps/Standalone/src/templates/app/TemplatesStandaloneDesigner.tsx
- libs/designer/src/lib/ui/panel/templatePanel/__tests__/createWorkflowPanel.spec.tsx
- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/reviewCreateTab.tsx
- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/usePanelTabs.tsx
- libs/designer/src/lib/ui/templates/TemplatesDesigner.tsx
- Workflow name and stateful-ness are not needed for consumption, so remove displaying those (basic tab)
- Remove validation for undisplayed variables
> feat(Templates): Consumption Support - Remove Unwanted Displaying/Validating from Designer

- libs/data-mapper-v2/package.json
- libs/data-mapper-v2/src/components/functionConfigurationMenu/inputTab/InputList.tsx
- libs/data-mapper-v2/src/components/functionConfigurationMenu/inputTab/inputTab.tsx
- libs/data-mapper-v2/src/components/functionConfigurationMenu/outputTab/outputTab.tsx
- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
- pnpm-lock.yaml
> feat(Data Mapper): Add re-ordering for the input list

- libs/data-mapper-v2/src/components/schema/tree/SchemaTreeNode.tsx
- libs/data-mapper-v2/src/components/schema/tree/styles.ts
> fix(Data Mapper): Show loop onHover or onSelect

- libs/data-mapper-v2/src/components/common/reactflow/edges/useEdgePath.ts
- libs/data-mapper-v2/src/components/schema/tree/SchemaTree.tsx
- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
> feat(Data Mapper): Use virtual tree api for visible nodes and indexes

- libs/designer-ui/src/lib/querybuilder/Group.tsx
- libs/designer-ui/src/lib/querybuilder/Row.tsx
- libs/designer-ui/src/lib/querybuilder/index.tsx
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/functions.spec.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/functions.ts
cherrypick https://github.com/Azure/LogicAppsUX/pull/5772
> fix(designer): Simple Query Builder not deserializing (#5772)

- libs/logic-apps-shared/src/designer-client-services/lib/base/experimentation.ts
- libs/logic-apps-shared/src/designer-client-services/lib/experimentation.ts
> fix(Designer): Update types for experimentation and add a new for value

- libs/data-mapper-v2/src/components/common/panel/Panel.tsx
- libs/data-mapper-v2/src/components/common/panel/styles.ts
- libs/data-mapper-v2/src/components/schema/tree/SchemaTreeNode.tsx
- libs/data-mapper-v2/src/components/schema/tree/styles.ts
> fix(Data Mapper): Show looping icon always for repeating nodes

- libs/data-mapper-v2/src/components/schema/tree/styles.ts
> fix(Data Mapper): Disable pointer events on the handle icon

- libs/data-mapper-v2/src/components/schema/tree/SchemaTreeNode.tsx
- libs/data-mapper-v2/src/components/schema/tree/styles.ts
> fix(Data Mapper): Update looping styles from Private preview sessions

- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/HybridLogicAppsSteps/ConnectedEnvironmentStep.ts
- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/HybridLogicAppsSteps/ContainerAppNameStep.ts
- apps/vs-code-designer/src/app/commands/deploy/hybridLogicApp/connectToSMB.ts
- apps/vs-code-designer/src/app/tree/subscriptionTree/SubscriptionTreeItem.ts
- apps/vs-code-designer/src/app/utils/funcCoreTools/cpUtils.ts
> fix(vscode): hybrid logic apps bug fixes 

- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/connectionsTab.tsx
- libs/designer/src/lib/ui/panel/templatePanel/templatePanel.tsx
- libs/designer/src/lib/ui/templates/__tests__/displayConnections.spec.tsx
- libs/designer/src/lib/ui/templates/connections/createConnection.tsx
- libs/designer/src/lib/ui/templates/connections/workflowconnections.tsx
- libs/designer/src/lib/ui/templates/index.tsx
- libs/designer/src/lib/ui/templates/styles.less
- libs/designer/src/lib/ui/templates/templateoverview.tsx
Updated current connections grid component to also view grouped data when it has multiple workflows to create
> feat(templates): Adding grouped connections for accelerators

- libs/designer-ui/src/lib/authentication/index.tsx
- libs/designer-ui/src/lib/code/index.tsx
- libs/designer-ui/src/lib/combobox/index.tsx
- libs/designer-ui/src/lib/editor/string/index.tsx
- libs/designer-ui/src/lib/html/index.tsx
- libs/designer-ui/src/lib/recurrence/index.tsx
- libs/designer-ui/src/lib/schemaeditor/index.tsx
fixes #5682 
##Pending
Dictionary editor, Query Builder and Array editor
> fix(designer): Calling on change only when editor value has changed

- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
If an action has it's inputs location set to the action root, the retry policy was being loaded into the action root when it should be in the "inputs".
I have moved the setting logic of the retry policy to after the location swap so it will always be set in the correct location.
Fixes https://github.com/Azure/LogicAppsUX/issues/5824
> fix(Designer): Fixed retry policy serialization location issue

- .azure-pipelines/1esmain.yml
- .azure-pipelines/templates/build.yml
- .azure-pipelines/templates/package.yml
- .azure-pipelines/templates/setup.yml
This pull request includes significant updates to the Azure Pipelines configuration for the LogicAppsUX project. The changes primarily focus on updating repository references, adding new parameters and variables, and switching from npm to pnpm for build and package steps.
* Updated the repository reference from `MicroBuildTemplate` to `LogicAppsUX` and changed the service connection endpoint accordingly in `.azure-pipelines/1esmain.yml`.
* Added a new parameter `enableSigning` with a default value of `True` and updated the `publishVersion` default value to `4.85.3` in `.azure-pipelines/1esmain.yml`.
* Added a new variable `working_directory` with the value `'.'` in `.azure-pipelines/1esmain.yml`.
* Updated the `extends` section to use templates from `LogicAppsUX` and commented out the …
> feat(vscode): Update build and release pipeline

- libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
- libs/designer/src/lib/core/state/templates/templateSlice.ts
- libs/designer/src/lib/core/templates/utils/helper.ts
- libs/designer/src/lib/ui/templates/basics/multiworkflow.tsx
- libs/designer/src/lib/ui/templates/basics/singleworkflow.tsx
> fix(templates): Adding error information in basics tab for multi workflows

- apps/docs/docs/intro.md
- apps/vs-code-designer/vitest.config.ts
- libs/chatbot/vitest.config.ts
- libs/data-mapper-v2/vitest.config.ts
- libs/data-mapper/vitest.config.ts
- libs/designer-ui/vitest.config.ts
- libs/designer/vitest.config.ts
- libs/logic-apps-shared/vitest.config.ts
- libs/vscode-extension/vitest.config.ts
- package.json
- pnpm-lock.yaml
- vitest.workspace.js
unable to run tests in VSCode extension with new version
> Feat(all): Vitest upgrade and extension configuration

- libs/logic-apps-shared/src/designer-client-services/lib/base/experimentation.ts
- libs/logic-apps-shared/src/designer-client-services/lib/experimentation.ts
> fix(Designer): Remove type from experimentation

- libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/search.ts
Custom triggers now show in search
> fix(Designer): Custom connector triggers now show in search (#5885)

- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/designer/src/lib/core/utils/loops.ts
- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/validation.ts
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
Adding the check for dataverse connector when adding encoding for path parameters
> fix(designer): Hack for dataverse connector incorrect metadata in swagger

- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/usePanelTabs.tsx
Cherry picking into hotfix branch
> fix(templates): Moving isMultiworkflow log to the end (#5922)

- libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
This pull request includes changes to the `libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts` file to enhance error handling and import necessary utilities. The most important changes include adding the `isObject` import and improving the error handling logic in the `updateCallbackUrlInInputs` function.
Enhancements to error handling:
* Added `isObject` utility to the import list.
* Enhanced error handling in the `updateCallbackUrlInInputs` function to create an `Error` object if the error is an object.
> fix(designer): Log error object in callback url

- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/designer/src/lib/core/utils/loops.ts
- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/core/utils/validation.ts
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/formInputs/legacyManagedIdentityPicker.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/search.ts
Cherry-pick of the following:
- https://github.com/Azure/LogicAppsUX/pull/5897
- https://github.com/Azure/LogicAppsUX/pull/5885
- https://github.com/Azure/LogicAppsUX/pull/5911
> fix(vscode): Fix custom connectors, managed identity creation and dataverse connector swagger

- apps/vs-code-designer/src/README.md
Cherry-pick of the following:
- https://github.com/Azure/LogicAppsUX/pull/5933
> docs(vscode): Add Logic Apps (Standard – Hybrid) announcement to vscode readme 

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
- apps/vs-code-react/src/app/designer/servicesHelper.ts
Updated API Management api version for VSCode and standalone.
Portal has already been updated in the portal-side code and does not need any changes.
> feat(VSCode): Updated apim api version for vscode and standalone

- apps/vs-code-designer/src/app/utils/credentials.ts
This pull request includes changes to the `apps/vs-code-designer/src/app/utils/credentials.ts` file to improve the handling of account session credentials. The most important changes include modifying the type of `currentLoggedInSessions` to an array and updating the logic to handle multiple sessions.
Improvements to session handling:
* Changed the type of `currentLoggedInSessions` from `any` to `any[]` to ensure it is treated as an array.
*  Updated the condition to check if `currentLoggedInSessions` has more than one session before calling `getCredentialsForSessions`.
* Modified the `getCredentialsForSessions` function to accept `sessions` as an array of `any`.
Fixes: https://github.com/Azure/logicapps/issues/991
> fix(vscode): Add validation for sessions in azure account

- apps/Standalone/src/dataMapperV1/components/DevToolbox.tsx
- libs/data-mapper-v2/src/core/state/Store.ts
- libs/data-mapper-v2/src/mapHandling/MapDefinitionDeserializer.ts
- libs/data-mapper-v2/src/mapHandling/MapDefinitionSerializer.ts
- libs/data-mapper-v2/src/mapHandling/__test__/MapDefinitionDeserializer.spec.ts
- libs/data-mapper-v2/src/mapHandling/__test__/MapDefinitionSerializer.spec.ts
- libs/data-mapper-v2/src/utils/DataMap.Utils.ts
Could not deserialize functions with two functions below a loop
Issue with deserializing functions where two functions are the same
> fix(Data Mapper): Serialization/Deserialization fixes

- downloadTemplates.js
- libs/designer/src/lib/ui/templates/cards/templateCard.less
Updating template release branch
> chore(Templates): Update Template Release Version

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx
- libs/designer/src/lib/core/index.ts
- libs/designer/src/lib/core/state/designerView/designerViewSlice.ts
Fixes https://github.com/Azure/LogicAppsUX/issues/5770
> fix(designer): Remove Persisting Action Menu Showing When Switching Views

- libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
Was previously running into some issues with deserializing negatory simple query builder
> fix(designer): Properly paring Negatory Simple Query Builder 

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
Added a null catch in the createConnection component
> fix(Designer): Added a null catch in the createConnection component

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
- libs/designer-ui/src/lib/tokenpicker/nl2fExpressionAssistant.tsx
Fixes https://github.com/Azure/LogicAppsUX/issues/5985 in standalone
> fix(designer): Don't use shouldConvertToConsumption in Code View save

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
- libs/designer-ui/src/lib/querybuilder/Group.tsx
- libs/designer-ui/src/lib/querybuilder/index.tsx
- libs/designer-ui/src/lib/tokenpicker/nl2fExpressionAssistant.tsx
Cherry picks of:
https://github.com/Azure/LogicAppsUX/pull/6011
https://github.com/Azure/LogicAppsUX/pull/6009
https://github.com/Azure/LogicAppsUX/pull/5986
> fix(designer): Cherry pick PRs

- libs/designer-ui/src/lib/colorizer/colorizer.less
- libs/designer/src/lib/core/actions/bjsworkflow/monitoring.ts
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/monitoringTab/__tests__/__snapshots__/inputsPanel.spec.tsx.snap
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/monitoringTab/__tests__/__snapshots__/outputsPanel.spec.tsx.snap
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/monitoringTab/__tests__/inputsPanel.spec.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/monitoringTab/__tests__/outputsPanel.spec.tsx
This pull request includes several updates to the `designer-ui` and `designer` libraries, focusing on improving the UI styling, refining parameter binding logic, and adding tests for the `OutputsPanel` component.
* Added `overflow: hidden` to `.msla-colorizer-json-body` and moved the `max-height` property to a different block to ensure consistent styling. 
* Modified the `getParametersToBind` function to accept an additional `isInputs` boolean parameter, allowing differentiation between input and output bindings. Updated calls to this function accordingly.
* Added comprehensive tests for the `OutputsPanel` component, covering various states such as loading, error, and different types of outputs.
* Added comprehensive tests for the `InputsPanel` component, covering various states such as …
> fix(designer): Display correct outputs from query type actions

- libs/designer-ui/src/lib/arrayeditor/collapsedarray.tsx
- libs/designer-ui/src/lib/arrayeditor/expandedcomplexarray.tsx
- libs/designer-ui/src/lib/arrayeditor/expandedsimplearray.tsx
- libs/designer-ui/src/lib/authentication/AADOAuth/AADOAuth.tsx
- libs/designer-ui/src/lib/authentication/AADOAuth/AADOAuthCredentials.tsx
- libs/designer-ui/src/lib/authentication/AuthenticationProperty.tsx
- libs/designer-ui/src/lib/authentication/BasicAuth.tsx
- libs/designer-ui/src/lib/authentication/CertificateAuth.tsx
- libs/designer-ui/src/lib/authentication/CollapsedAuthentication.tsx
- libs/designer-ui/src/lib/authentication/MSIAuth/MSIAuth.tsx
- libs/designer-ui/src/lib/authentication/MSIAuth/MSIAuthDefault.tsx
- libs/designer-ui/src/lib/authentication/RawAuth.tsx
- libs/designer-ui/src/lib/dictionary/collapsedDictionary.tsx
- libs/designer-ui/src/lib/dictionary/expandeddictionary.tsx
- libs/designer-ui/src/lib/editor/base/index.tsx
- libs/designer-ui/src/lib/editor/base/plugins/Paste.tsx
- libs/designer-ui/src/lib/editor/base/utils/keyvalueitem.ts
- libs/designer-ui/src/lib/querybuilder/Group.tsx
- libs/designer-ui/src/lib/querybuilder/Row.tsx
- libs/designer-ui/src/lib/querybuilder/SimpleQueryBuilder.tsx
- libs/designer-ui/src/lib/querybuilder/index.tsx
- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
Fixes https://github.com/Azure/LogicAppsUX/issues/5948 on deserialization
Fixes https://github.com/Azure/LogicAppsUX/issues/5890 on serialization
> fix(designer): Fixing Some Non-string type Dictionary Serialization/Deserialization

- libs/designer-ui/src/lib/monitoring/requestpanel/__test__/__snapshots__/request.spec.tsx.snap
- libs/designer-ui/src/lib/monitoring/requestpanel/__test__/__snapshots__/requestpanel.spec.tsx.snap
- libs/designer-ui/src/lib/monitoring/values/__test__/__snapshots__/values.spec.tsx.snap
- libs/designer-ui/src/lib/monitoring/values/__test__/keyvaluepairs.spec.tsx
- libs/designer-ui/src/lib/monitoring/values/keyvaluepairs.tsx
Cherry picking Eric's key/value crash PR: https://github.com/Azure/LogicAppsUX/pull/6121
> fix(designer): Prevent crashing when having object in key/value (#6121)

- apps/vs-code-designer/package.json
- libs/chatbot/package.json
- libs/data-mapper-v2/package.json
- libs/data-mapper/package.json
- libs/designer-ui/package.json
- libs/designer/package.json
- libs/logic-apps-shared/package.json
- libs/vscode-extension/package.json
- package.json
- pnpm-lock.yaml
- turbo.json
https://github.com/user-attachments/assets/fc3891fa-fca5-4db4-ae3c-6e3adec48389
> chore: Update Turborepo to latest version

- libs/data-mapper-v2/package.json
- libs/data-mapper-v2/src/components/common/reactflow/edges/useEdgePath.ts
- libs/data-mapper-v2/src/components/schema/tree/SchemaTreeNode.tsx
- libs/data-mapper-v2/src/components/schema/tree/SchemaTreeNodeHandle.tsx
- libs/data-mapper-v2/src/components/schema/useSchema.ts
- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
- pnpm-lock.yaml
> feat(Data Mapper): Move edge path logic to useInternal Reactflow state

- apps/vs-code-designer/src/assets/UnitTestTemplates/TestClassFile
Updated the test class file to use the new constructs for unit test.
> feat(vscode): Updated Test Class file with new template for unit testing

- libs/designer/src/lib/ui/templates/connections/connector.tsx
> feat(Templates): Hover text for connectors

- apps/vs-code-designer/src/app/commands/workflows/unitTest/createUnitTest.ts
- apps/vs-code-designer/src/assets/UnitTestTemplates/TestClassFile
Updated sample file and renaming
> feat(vscode): Updated Test Class file and replacement methods

- apps/vs-code-designer/src/package.json
IaC is in public preview
IaC and Logic App Workspaces are now GA
> feat(vscode): Removed preview tag for workspace and IaC

- apps/vs-code-designer/src/app/commands/dataMapper/DataMapperExt.ts
- apps/vs-code-designer/src/app/commands/dataMapper/dataMapper.ts
- apps/vs-code-designer/src/extensionVariables.ts
- libs/data-mapper-v2/src/mapHandling/MapDefinitionDeserializer.ts
- libs/data-mapper-v2/src/mapHandling/__test__/MapDefinitionDeserializer.spec.ts
- libs/designer/src/lib/ui/templates/connections/connector.tsx
Handle error scenarios
1. Backend cannot process LML because of a syntax error (for example user edits LML and adds syntax error)
2. LML error that backend does not handle; invalid source node, invalid target node, invalid loop source node, invalid loop source node, invalid conditional node; there may be a few that we don't cover here, but I will add telemetry to see if this actually ends up catching many errors for users
> Feat(DM): deserialization error handling

- one-loc-build.yml
> chore: Remove automatic branch deletion for Localization

- libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/usePanelTabs.tsx
- libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/summaryTab.tsx
- libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/workflowTab.tsx
- libs/designer/src/lib/ui/templates/cards/templateCard.tsx
telemetry for templates is not getting logged. We will handle the logging for Trace level explicitly in the portal.
> fix(templates): Changing logentry level to Trace from Verbose for templates telemetry

- Localize/loc/cs/strings.json.lcl
- Localize/loc/de/strings.json.lcl
- Localize/loc/es/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/hu/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/it/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241220152457959 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241220152457959 to main

- Localize/loc/pt-PT/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241220182507637 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241220182507637 to main

- Localize/loc/de/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241220212419847 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241220212419847 to main

- Localize/loc/hu/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241221062309749 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241221062309749 to main

- Localize/loc/cs/strings.json.lcl
- Localize/loc/es/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241221092435017 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241221092435017 to main

- Localize/loc/sv/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241221152346645 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241221152346645 to main

- Localize/loc/ja/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241222182313306 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241222182313306 to main

- Localize/loc/nl/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241223032248297 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241223032248297 to main

- Localize/loc/it/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241223152521773 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20241223152521773 to main

- libs/designer-ui/src/lib/panel/recommendationpanel/operationGroupDetails/index.tsx
Actions within the connector browse view are now sorted alphabetically.
> fix(Designer): Sorted connector browse actions alphabetically

- Localize/loc/cs/strings.json.lcl
- Localize/loc/de/strings.json.lcl
- Localize/loc/es/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/hu/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250107062524510 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250107062524510 to main

- Localize/loc/id/strings.json.lcl
- Localize/loc/it/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250107182448320 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250107182448320 to main

- Localize/loc/cs/strings.json.lcl
- Localize/loc/de/strings.json.lcl
- Localize/loc/es/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/hu/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/it/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250108032328964 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250108032328964 to main

- Localize/loc/cs/strings.json.lcl
- Localize/loc/es/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/hu/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250108062716434 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250108062716434 to main

- Localize/loc/de/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250108092533977 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250108092533977 to main

- Localize/loc/id/strings.json.lcl
- Localize/loc/it/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250108154117691 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250108154117691 to main

- Localize/loc/sv/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250108212442445 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250108212442445 to main

- Localize/loc/hu/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250109032518443 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250109032518443 to main

- libs/data-mapper-v2/src/components/canvas/useReactflowStates.ts
- libs/data-mapper-v2/src/components/schema/styles.ts
- libs/data-mapper-v2/src/ui/hooks/useAutoLayout.ts
- libs/data-mapper-v2/src/utils/ReactFlow.Util.ts
> fix(Data Mapper): Fix circles cutting off

- Localize/loc/cs/strings.json.lcl
- Localize/loc/de/strings.json.lcl
- Localize/loc/es/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/hu/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/it/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250111032510598 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250111032510598 to main

- libs/data-mapper-v2/src/mapHandling/MapDefinitionSerializer.ts
- libs/data-mapper-v2/src/mapHandling/__test__/MapDefinitionSerializer.spec.ts
https://msazure.visualstudio.com/One/_workitems/edit/30772188
> Fix(Data Mapper): bracket serialization bug

- apps/Standalone/src/dataMapperV1/app/DataMapperStandaloneDesignerV2.tsx
- apps/vs-code-designer/src/app/commands/dataMapper/DataMapperPanel.ts
- apps/vs-code-designer/src/extensionVariables.ts
- apps/vs-code-react/src/app/dataMapper/services/dataMapperFileService.ts
- libs/data-mapper-v2/src/components/commandBar/EditorCommandBar.tsx
- libs/data-mapper-v2/src/core/services/dataMapperFileService/dataMapperFileService.ts
- libs/vscode-extension/src/lib/models/dataMapper.ts
- libs/vscode-extension/src/lib/models/extensioncommand.ts
> feat(Data Mapper): Add notification to vscode from DM

- apps/vs-code-designer/src/app/commands/workflows/unitTest/saveBlankUnitTest.ts
- apps/vs-code-designer/src/app/utils/codeful/saveBlankUnitTest.test.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
[work item 1: [Frontend] [VS Code Extension]:  Process JSON Data - Operation Parameters](https://msazure.visualstudio.com/One/_workitems/edit/30496877)
[work item 2: [Frontend] [VS Code Extension]:  Process JSON Data - Operation Info](https://msazure.visualstudio.com/One/_workitems/edit/30496897)
Currently, there is no functionality to process and transform JSON outputs from Logic App workflows into a structured format for unit test generation. This limits the ability to create reusable and accurate test cases.  
1. **Output Parameter Transformation:**
- Added a `parseUnitTestOutputs` method to process raw JSON outputs.
- Transforms raw output parameters by cleaning keys and filtering fields based on predefined rules (e.g., `type`, `title`, `format`, `description`).
2. **Key Cleaning and …
> feat(vscode): Add JSON Parsing for Blank Unit Test Generation for Logic App Workflows

- e2e/designer/errorsPanel.spec.ts
- e2e/designer/workflowParametersPanel.spec.ts
Added E2E test over the Errors panel
> test(Designer): Errors panel E2E test

- e2e/templates/app.spec.ts
- e2e/templates/utils/GoToTemplate.ts
> test(Templates): Template Lists Page e2e test 

- e2e/templates/templateFilters.spec.ts
> test(Templates): Template Filters e2e test

- apps/docs/docs/Development/Testing.md
- apps/vs-code-designer/src/app/commands/dataMapper/extensionConfig.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/main.ts
- apps/vs-code-designer/src/package.json
Simplify 'open existing' menu https://msazure.visualstudio.com/One/_workitems/edit/29241644
> Feat(Data Mapper): Changed VSCode entry menu

- e2e/designer/editors/condition.spec.ts
- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
Any scope node added will always show as loading due to a regression
Setting initial Data as null, so Reacy Query accurately reflects the data loading state in isLoading
I've added a simple base case test that will show the condition scope action card which should alert if this comes up again
> fix(designer): Scope Nodes Permanently Loading

- libs/data-mapper-v2/src/components/mapChecker/MapCheckerItem.tsx
- libs/data-mapper-v2/src/components/mapChecker/styles.tsx
- libs/data-mapper-v2/src/components/schema/tree/SchemaTree.tsx
- libs/data-mapper-v2/src/components/schema/useSchema.ts
> fix(Data Mapper): Add subtitle for error/warning cards

- .github/ISSUE_TEMPLATE/data_mapper.yml
> meta(Data Mapper): Update Data Mapper issue template

- libs/designer/src/lib/ui/CustomNodes/GraphContainerNode.tsx
- libs/designer/src/lib/ui/CustomNodes/SubgraphCardNode.tsx
- https://github.com/Azure/LogicAppsUX/issues/6484
E2E Tests have been implemented in this PR https://github.com/Azure/LogicAppsUX/pull/6444 to make sure that that behavior is not happening anymore
> fix(designer): Correctly add inactive class for subgraph cards 

- libs/designer/src/lib/core/graphlayout/elklayout.ts
This is removing telemetry start and end event of our layout algorithm, since that is causing tremendous amounts of logs in our portal and causing telemtry throttling. This is not much used currently since we already have the error logs if layout fails.
Existing automated tests should verify nothing breaks after removing the telemetry code and I have verified also in our test page there are no issues in loading the logicapps designer.
> chore(designer): Removing telemetry logging of elklayout

- apps/vs-code-designer/src/app/utils/codeless/__test__/parameterizer.test.ts
- apps/vs-code-designer/src/app/utils/codeless/parameterizer.ts
- apps/vs-code-designer/src/constants.ts
- https://github.com/Azure/LogicAppsUX/pull/6480
- Updated existing test cases to use a generic subscription test ID and added a new test case to verify the parameterization of connection references for custom connectors.
> fix(vscode): Update connection parameterization for custom connectors

- libs/data-mapper-v2/src/components/functionConfigurationMenu/inputTab/inputTab.tsx
> fix(Data Mapper): Remove the intermediary list drag effect + refactor to remove additional component

- apps/vs-code-designer/src/app/utils/codeless/__test__/parameterizer.test.ts
- apps/vs-code-designer/src/app/utils/codeless/parameterizer.ts
- apps/vs-code-designer/src/constants.ts
- https://github.com/Azure/LogicAppsUX/pull/6480
- Updated existing test cases to use a generic subscription test ID and added a new test case to verify the parameterization of connection references for custom connectors.
> fix(vscode): Update connection parameterization for custom connector

- libs/designer-ui/src/lib/editor/base/utils/initialConfig.ts
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnectionWrapper.tsx
- https://github.com/Azure/LogicAppsUX/pull/6425
- https://github.com/Azure/LogicAppsUX/pull/6370
> fix(designer): Custom connection cache and error thrown on extended text node

- libs/data-mapper-v2/src/components/codeView/styles.ts
- libs/data-mapper-v2/src/components/mapChecker/styles.tsx
- libs/data-mapper-v2/src/components/schema/tree/styles.ts
> fix(Data Mapper): Update overflow for node and error panel

- libs/data-mapper-v2/src/components/codeView/styles.ts
- libs/data-mapper-v2/src/components/mapChecker/styles.tsx
- libs/data-mapper-v2/src/components/schema/tree/styles.ts
* add wrap and padding
* overflow wrap
* overflow wrap for error panel
> fix(Data Mapper): Update overflow for node and error panel (#6509)

- libs/data-mapper-v2/src/components/mapChecker/MapCheckerItem.tsx
- libs/data-mapper-v2/src/components/mapChecker/MapCheckerPanel.tsx
> fix(Data Mapper): Filter empty/null messages

- libs/designer-ui/src/lib/editor/base/utils/initialConfig.ts
cherry pick of https://github.com/Azure/LogicAppsUX/pull/6370
> fix(designer): Error Being thrown On Extended Text Node

- downloadTemplates.js
> chore(templates): Updating templates release branch

- apps/vs-code-designer/src/assets/UnitTestTemplates/TestClassFile
Unit test (mstest) template file uses old OperationMock/ActionMock contract, which has since been modified
Update callback signature and ActionMock constructor usage
N/A
N/A
> feat(vscode): Update unit testing template file per new OperationMock

- apps/vs-code-designer/src/app/commands/workflows/unitTest/createUnitTest.ts
Currently, we only check if a project exists in a workspace.
Now we will use the ConvertToWorkspace function to determine whether the project is in a workspace before proceeding and the function will help the user create a workspace.
> feat(vscode): Added workspace requirement for unit test

- __mocks__/runs/LoopsPager/SuccessRun.json
- __mocks__/workflows/LoopsPager.json
- apps/Standalone/src/designer/app/LocalDesigner/LogicAppSelector/LogicAppSelector.tsx
- e2e/designer/monitoringView/loopsPager.spec.ts
- e2e/designer/monitoringView/monitoringView.spec.ts
- libs/designer/src/lib/ui/CustomNodes/GraphContainerNode.tsx
- libs/designer/src/lib/ui/CustomNodes/SubgraphCardNode.tsx
- libs/designer/src/lib/ui/common/LoopsPager/LoopsPager.tsx
- https://github.com/Azure/LogicAppsUX/pull/6548
> fix(designer): Loop pager visibility in do-until action

- Localize/loc/cs/strings.json.lcl
- Localize/loc/de/strings.json.lcl
- Localize/loc/es/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/hu/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/it/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250206062721989 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250206062721989 to main

- Localize/loc/cs/strings.json.lcl
- Localize/loc/it/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250206122544283 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250206122544283 to main

- Localize/loc/de/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250206152719774 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250206152719774 to main

- Localize/loc/es/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250206212247591 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250206212247591 to main

- package.json
> chore(designer): Fix the main branch package version

- Localize/loc/ko/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250207032245183 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250207032245183 to main

- apps/Standalone/src/dataMapperV1/components/DevToolbox.tsx
- apps/Standalone/src/dataMapperV1/mapDefinitions/X12Definition.ts
- apps/Standalone/src/dataMapperV1/mapDefinitions/index.ts
- apps/Standalone/src/dataMapperV1/schemas/index.ts
- apps/Standalone/src/dataMapperV1/schemas/x12.json
- apps/vs-code-designer/package.json
- apps/vs-code-designer/src/app/commands/dataMapper/DataMapperExt.ts
- apps/vs-code-designer/src/app/commands/dataMapper/DataMapperPanel.ts
- libs/data-mapper-v2/src/__mocks__/schemas/X12Schema.json
- libs/data-mapper-v2/src/__mocks__/schemas/adjacentLoopTest.json
- libs/data-mapper-v2/src/__mocks__/schemas/index.ts
- libs/data-mapper-v2/src/components/canvas/ReactFlow.tsx
- libs/data-mapper-v2/src/components/mapChecker/MapCheckerItem.tsx
- libs/data-mapper-v2/src/components/mapChecker/MapCheckerPanel.tsx
- libs/data-mapper-v2/src/mapHandling/MapDefinitionDeserializer.ts
- libs/data-mapper-v2/src/mapHandling/MapDefinitionSerializer.ts
- libs/data-mapper-v2/src/mapHandling/__test__/MapDefinitionDeserializer.spec.ts
- libs/data-mapper-v2/src/mapHandling/__test__/MapDefinitionSerializer.spec.ts
- libs/data-mapper-v2/src/models/Connection.ts
- libs/data-mapper-v2/src/models/Function.ts
- libs/data-mapper-v2/src/utils/Schema.Utils.ts
- libs/data-mapper/package.json
- libs/data-mapper/src/lib/mapDefinitions/__test__/MapDefinitionE2e.spec.ts
- libs/data-mapper/src/lib/utils/MapDefinition.Utils.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/guid.ts
- libs/logic-apps-shared/src/utils/src/lib/models/dataMap.ts
- pnpm-lock.yaml
see attached PRs
https://github.com/Azure/LogicAppsUX/pull/6527
https://github.com/Azure/LogicAppsUX/pull/6520
https://github.com/Azure/LogicAppsUX/pull/6571
https://github.com/Azure/LogicAppsUX/pull/6556
https://github.com/Azure/LogicAppsUX/pull/6552
> Fix(Data Mapper): serialization and error message fix

- e2e/designer/fixtures/real-api.ts
- e2e/designer/real-api/monitoring/NestedLoops/nestedLoops.spec.ts
- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
- libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
- Fixed issue where nested loops would not be iteratable.
- Issue is from the following PR: https://github.com/Azure/LogicAppsUX/pull/6458
- We have reverted and fixed the loading issue mentioned in the PR above
- Also fixed an issue where nested nodes would not change data when iterating backwards through loops.
> [!IMPORTANT]
> **TESTS**: Added E2E tests over issue scenarios
> **RISK**: Low risk Carlos and I have both tested all loop scenarios 
> [!NOTE]
> Cherry-pick from https://github.com/Azure/LogicAppsUX/pull/6624
> fix(Designer): Fixed nested loop monitoring view issues (#6624)

- apps/vs-code-designer/src/README.md
Adding the cloud to local feature (Create workflow from a package exported from portal) in the readme file.
N/A
N/A
Readme.MD is the only file impacted - no functionality change.
N/A
N/A
> docs(vscode): Add Cloud to Local feature announcement

- downloadTemplates.js
Just updating release branch for templates for new release
> chore(templates): Updating templates repo for new release

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/LogicAppSelectionSetting/AzureConsumptionLogicAppSelector.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/LogicAppSelectionSetting/AzureStandardLogicAppSelector.tsx
The dropdown for Logic App selection wasn't sorted
The dropdown for Logic App selection is now sorted in consumption and standard
N/A this is just for standalone app
> chore(standalone): Add sorting and fix valid resource regex

- libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
This change adds designer support for the ParsedocumentWithMetadata action
non-breaking change
> feat(designer): Support parsedocumentwithmetadat in standard

- apps/vs-code-designer/src/app/commands/initProjectForVSCode/DotnetInitVSCodeStep.ts
- apps/vs-code-designer/src/app/commands/initProjectForVSCode/InitVSCodeStepBase.ts
- apps/vs-code-designer/src/app/commands/initProjectForVSCode/ScriptInitVSCodeStep.ts
With workspaces, the tasks.json files are created with the incorrect cwd after a project is converted to nuget.
tasks.json file has the correct cwd after it is converted to nuget.
> fix(vscode): Fix nuget debug issue introduced with workspace

- apps/Standalone/src/dataMapperV1/mapDefinitions/FullTranscriptMapDefinition.ts
- libs/data-mapper-v2/src/mapHandling/MapDefinitionDeserializer.ts
- libs/data-mapper-v2/src/mapHandling/MapDefinitionSerializer.ts
- libs/data-mapper-v2/src/mapHandling/__test__/MapDefinitionDeserializerHelpers.spec.ts
- libs/data-mapper-v2/src/models/Function.ts
- libs/data-mapper-v2/src/utils/Connection.Utils.ts
- libs/data-mapper-v2/src/utils/DataMap.Utils.ts
- libs/data-mapper-v2/src/utils/Function.Utils.ts
- libs/data-mapper-v2/test-setup.ts
- confusing format of Direct Access in the Function config menu
- fixed Direct Access display value
- fixed undefined node in serialization
> Fix(Data Mapper): Able to load maps with combination of 'Direct Access' and 'Index' functions

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/formInputs/tenantPicker.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/common/azure.ts
- https://github.com/Azure/LogicAppsUX/pull/6733
> fix(designer): Add display name for tenants as optional

- apps/vs-code-designer/src/app/commands/dataMapper/DataMapperPanel.ts
- apps/vs-code-react/src/app/dataMapper/appV2.tsx
- apps/vs-code-react/src/app/services/Logger.ts
- apps/vs-code-react/src/state/DataMapSliceV2.ts
- apps/vs-code-react/src/webviewCommunication.tsx
- libs/data-mapper-v2/src/utils/Schema.Utils.ts
- libs/vscode-extension/src/lib/models/dataMapper.ts
added collection of schema type, schema name, DM version to extension logs and map name
> feat(Data Mapper): added telemetry values for DM

- e2e/templates/createWorkflowPanel.spec.ts
> Fixing failing test case

- apps/vs-code-designer/src/app/commands/createCodeless/createCodelessSteps/ScriptSteps/ScriptWorkflowNameStep.ts
- apps/vs-code-designer/src/app/commands/createCodeless/createCodelessSteps/WorkflowNameStepBase.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/SetLogicAppNameStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/SetWorkspaceName.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/setMethodName.ts
- apps/vs-code-designer/src/app/commands/initProjectForVSCode/DotnetInitVSCodeStep.ts
- apps/vs-code-designer/src/app/commands/initProjectForVSCode/InitVSCodeStepBase.ts
- apps/vs-code-designer/src/app/commands/initProjectForVSCode/ScriptInitVSCodeStep.ts
- apps/vs-code-designer/src/app/commands/workflows/useSQLStorage.ts
- apps/vs-code-designer/src/app/utils/__test__/workspace.test.ts
- apps/vs-code-designer/src/app/utils/binaries.ts
- apps/vs-code-designer/src/app/utils/verifyIsProject.ts
- apps/vs-code-designer/src/app/utils/vsCodeConfig/verifyInitForVSCode.ts
- apps/vs-code-designer/src/app/utils/workspace.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/test-setup.ts
Cherry-pick of the following PR's
- https://github.com/Azure/LogicAppsUX/pull/6673
- https://github.com/Azure/LogicAppsUX/pull/6690
- https://github.com/Azure/LogicAppsUX/pull/6698
- https://github.com/Azure/LogicAppsUX/pull/6706
- https://github.com/Azure/LogicAppsUX/pull/6720
- https://github.com/Azure/LogicAppsUX/pull/6739
> fix(vscode): Fix workspaces experience behavior

- libs/data-mapper-v2/src/core/state/DataMapSlice.ts
See ADO issue https://msazure.visualstudio.com/One/_workitems/edit/31738472
this is code left over from our old way of structuring connections
> Fix(Data Mapper): removed old code that affects connection deletion

- apps/vs-code-designer/src/app/commands/dataMapper/DataMapperPanel.ts
- apps/vs-code-designer/src/app/commands/dataMapper/extensionConfig.ts
users had to manually create the folders needed for custom code in the Data Mapper, multiple levels deep
creates these folders as soon as user starts data mapper
https://github.com/user-attachments/assets/aa880215-53ef-40ab-ad64-66b384b21cdc
> Feat(Data Mapper): creates folders needed for DM custom code feature

- libs/designer/src/lib/ui/styles.less
Modified our XYFlow import to have correct pathing.
Was breaking over in AI Foundry from the `~`, confirmed no effect on our projects.
> fix(Designer): Modified xyflow css import

- libs/designer/src/lib/core/actions/bjsworkflow/connections.ts
> fix(designer): Fix typo in connection configuration model

- apps/vs-code-designer/src/app/commands/createCodeless/createCodeless.ts
- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/app/utils/__test__/workspace.test.ts
- apps/vs-code-designer/src/app/utils/verifyIsProject.ts
- apps/vs-code-designer/src/app/utils/workspace.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/package.json
- Current behavior loops back to open project and users can't create projects
- Now the behavior redirects to workspace creation within the project creation
https://github.com/user-attachments/assets/49fd0a07-a9c8-4d4c-89f8-4a9697c1b65e
> fix(vscode): Fix project creation and redirect to workspace creation

- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/app/utils/__test__/workspace.test.ts
- apps/vs-code-designer/src/app/utils/verifyIsProject.ts
- apps/vs-code-designer/src/app/utils/workspace.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/package.json
Cherry pick of the following PR:
- https://github.com/Azure/LogicAppsUX/pull/6839
> fix(vscode): Fix project creation and redirect to workspace creation 

- libs/designer/src/lib/core/index.ts
Exported `validateParameters` + `validateConnections` actions from templates store
> feat(Templates): Exported `validateParameters` + `validateConnections` actions from templates store

- libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
> fix(designer): Change input for Agent

- libs/designer/src/lib/core/actions/bjsworkflow/connections.ts
- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- Current model configuration was set up to have a behavior similar to Service Provider connections
- Now agent connections model configuration is setup to what backend expects to have. 
This is not a breaking change
> fix(designer): Update agent connection model configuration

- libs/designer/src/lib/core/actions/bjsworkflow/connections.ts
- libs/designer/src/lib/ui/panel/connectionsPanel/connectionsPanel.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/selectConnection/selectConnection.tsx
* fix(designer): Skip auto create connection for oauth in designer and for multi auth
* Reusing function
> fix(designer): Skip auto create connection for oauth in designer and for multi auth (#6861)

- libs/logic-apps-shared/src/designer-client-services/lib/base/template.ts
CHerry pick of only template changes
> fix(templates): Getting templates service changes to load from storage account

- libs/designer/src/lib/ui/panel/templatePanel/panel.less
- libs/designer/src/lib/ui/templates/cards/templateCard.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/base/template.ts
> fix(templates): Fixing incorrect operation ids in connector icons

- apps/vs-code-designer/src/app/utils/verifyIsProject.ts
- https://github.com/Azure/LogicAppsUX/pull/6881
> fix(vscode): Update validation to allow having the csharp file inside the workflow folder

- apps/vs-code-designer/src/app/utils/verifyIsProject.ts
Cherry-pick of the following PR: 
- https://github.com/Azure/LogicAppsUX/pull/6881
> fix(vscode): Update validation to allow having the csharp file inside the workflow folder 

- libs/designer/src/lib/core/queries/runs.ts
- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/consumption/run.ts
- libs/logic-apps-shared/src/designer-client-services/lib/run.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
- Getting agent actions does not support the nextLink behavior, it just fetches the first chunk
- Getting agent actions now supports the nextLink behavior for tools with bigger actions within
> feat(designer): Implement next link for agent actions repetitions

- libs/designer/src/lib/core/queries/runs.ts
- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
> fix(vscode): Update properties for agent actions response

- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/channelsTab/ChannelContent.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/channelsTab/index.tsx
> fix(designer): Show default channel if enabled after closing/re-opening panel

- libs/designer/src/lib/common/constants.ts
- libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/channelsTab/index.tsx
> feat(designer): Serialize channels for Agentic workflows

- libs/chatbot/src/lib/ui/ChatbotUi.tsx
- libs/designer-ui/src/lib/chatbot/chatbot.less
- libs/designer-ui/src/lib/chatbot/components/chatBubble.tsx
- libs/designer-ui/src/lib/chatbot/components/conversationItem.ts
- libs/designer-ui/src/lib/chatbot/components/conversationMessage.tsx
- libs/designer-ui/src/lib/panel/panelResizer.tsx
- libs/designer/src/lib/ui/Designer.tsx
- libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
https://github.com/user-attachments/assets/2e962876-e005-4d79-bf18-42f0ab14ef59
> feat(designer): Add resizer to agent chat and remove footer

- libs/designer-ui/src/lib/agentinstruction/agentinstruction.less
- libs/designer-ui/src/lib/agentinstruction/util.ts
1. Fix warning showing of unable to parse agent instruction on initialization
2. Fix placeholder being wrong location on system instruction editor
> fix(designer): Couple of cosmetic changes on Agent

- libs/designer/src/lib/ui/connections/edge.tsx
Fixed bug with edge arrow markers sometimes disappearing.  (Was an issue with names having special characters)
> fix(Designer): Fixed issue with arrow visibility

- libs/designer-ui/src/lib/editor/initializevariable/__test__/__snapshots__/VariableEditor.spec.tsx.snap
- libs/designer-ui/src/lib/editor/initializevariable/index.tsx
- libs/designer-ui/src/lib/editor/initializevariable/variableEditor.less
- libs/designer-ui/src/lib/editor/initializevariable/variableEditor.tsx
- libs/designer-ui/src/lib/workflowparameters/workflowparameter.tsx
In the  initialize variables component, moved some elements around for better spacing
Same behavior in both agents and basic variables
> fix(Designer): Restructured the initialize variables component UX

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
- libs/logic-apps-shared/src/utils/src/lib/helpers/connections.ts
- package.json
> feat(Designer): Cert based multi-auth

- libs/chatbot/src/lib/ui/ChatbotUi.tsx
> fix(designer): Fix close button default value for assistant chat

- libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
- libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
- libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
> fix(designer): Fix run history crash with channels setup

- libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
- libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
- libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
- New behavior now doesn't load the data from the general run api call, and it just considers the data from the agentic api call.
- Added memoization for the selector and avoid infinite renderization in chat
> fix(designer): Memoize selectors and fix run data from agent

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/HttpClient.ts
- libs/designer/src/lib/core/queries/runs.ts
- libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
- libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/consumption/run.ts
- libs/logic-apps-shared/src/designer-client-services/lib/run.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
> feat(designer): Wire up input channel with chat

- libs/designer-ui/src/lib/chatbot/chatbot.less
- libs/designer-ui/src/lib/chatbot/components/chatBubble.tsx
- libs/designer-ui/src/lib/chatbot/components/conversationItem.ts
- libs/designer-ui/src/lib/chatbot/components/conversationMessage.tsx
- libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
- libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
> fix(designer): Update messages styles in chat

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
- libs/designer/src/lib/ui/panel/recommendation/hooks.ts
- libs/designer/src/lib/ui/panel/recommendation/operationGroupDetailView.tsx
- libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
- libs/logic-apps-shared/src/designer-client-services/index.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/experimentation.ts
- libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
- libs/logic-apps-shared/src/designer-client-services/lib/experimentationFlags.ts
- libs/logic-apps-shared/src/utils/src/lib/mocks/connectorsSearchResultsMock.ts
Allow experimentation Flags on Designer
Filter parsedocumentwithmetadata operation from search/connector view
> feat(designer): Experimental Flags + Parse Document Functionality

- libs/designer/src/lib/core/index.ts
Exported 3 templates actions for use in AI Foundry
> feat(Templates): Exported 3 templates actions

- libs/designer/src/lib/core/index.ts
- libs/designer/src/lib/ui/panel/templatePanel/panel.less
- libs/designer/src/lib/ui/templates/templateDisplay.tsx
Cherry-pick of the following PRs:
- https://github.com/Azure/LogicAppsUX/pull/7034
- https://github.com/Azure/LogicAppsUX/pull/6893
> feat(Templates): Markdown template description + exports

- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
- libs/designer/src/lib/core/utils/designerLayoutHelpers/index.ts
- libs/designer/src/lib/ui/CanvasFinder.tsx
- libs/designer/src/lib/ui/Designer.tsx
- libs/logic-apps-shared/src/utils/src/lib/helpers/hooks.ts
- libs/logic-apps-shared/src/utils/src/lib/models/graphics.ts
- libs/logic-apps-shared/src/utils/src/lib/models/index.ts
Before:
https://github.com/user-attachments/assets/1363072f-7fb1-48af-be67-d37d697a4215
After: 
https://github.com/user-attachments/assets/caee57ab-917e-42e3-bbfb-cb6c2ebbbef2
> fix(deigner): Position nodes at top of designer on start instead of middle

- libs/designer/src/lib/ui/settings/validation/validation.ts
https://github.com/user-attachments/assets/eca44890-ecd6-425d-8e72-5a3e2c2f02ae
fixes #6975
> fix(designer): Fix issue where retry policy error wouldn't disappear when retry policy changed

- libs/designer-ui/src/lib/agentinstruction/agentinstruction.less
- libs/designer-ui/src/lib/editor/initializevariable/index.tsx
- libs/designer-ui/src/lib/editor/initializevariable/styles.ts
- libs/designer-ui/src/lib/label/label.less
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/channelsTab/ChannelContent.tsx
> fix(designer): Agent workflow fixes

- apps/vs-code-designer/src/app/commands/dotnet/validateDotNetIsLatest.ts
- apps/vs-code-designer/src/app/commands/funcCoreTools/validateFuncCoreToolsIsLatest.ts
- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
- apps/vs-code-designer/src/app/utils/binaries.ts
- apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
- apps/vs-code-designer/src/app/utils/funcCoreTools/funcVersion.ts
- apps/vs-code-designer/src/package.json
- Current behavior expects user to update function core tools and dotnet binaries manually through the experience
- New behavior auto updates function core tools and dotnet dependencies
- Removed await on error window message, therefore doesn't wait for user to close it
> feat(vscode): Automatically update function core tools and dotnet binaries

- libs/designer-ui/src/lib/agentinstruction/util.ts
> fix(designer): Do not serialize user messages if empty

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
- Current behavior doesn't support stateful operatations in agentic workflows
- This new change enables agentic workflows to add operations that are supported in stateful workflows
> fix(designer): Update value in services to support stateful in agentic

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/utils/connectors/connections.ts
- Current behavior shows connection error for agent operation when a new agentic workflow gets created
-  New behavior will not show the error when loading fresh agent actions
> feat(designer): Add logic to not validate freshly created agent workflow

- apps/vs-code-designer/src/app/commands/dataMapper/DataMapperExt.ts
- apps/vs-code-designer/src/constants.ts
- libs/designer/src/lib/core/utils/connectors/connections.ts
Fixes #6692 
- Data map name was not throwing validation error when we try to add spaces and any special characters apart from allows special characters.
- Now data map name input has validation
> fix(vscode): Add validation for data map name

- libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
- libs/designer/src/lib/core/state/templates/templateSlice.ts
- libs/designer/src/lib/ui/templates/basics/resource.tsx
Added template trigger description validation.
Now adds an error to state if a trigger description is required and not provided.
Also shows validation message under input component.
> feat(Templates): Added template trigger description validation

- libs/designer-ui/src/lib/templates/templatesPanelFooter.tsx
- libs/designer/src/lib/core/configuretemplate/ConfigureTemplateWizard.tsx
- libs/designer/src/lib/ui/configuretemplate/connections/connectionslist.tsx
- libs/designer/src/lib/ui/configuretemplate/parameters/customizeParameter.tsx
- libs/designer/src/lib/ui/configuretemplate/parameters/parameterslist.tsx
- libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
- libs/designer/src/lib/ui/configuretemplate/tabs/publishTab.tsx
- libs/designer/src/lib/ui/configuretemplate/templateprofile/manifestform.tsx
- libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
- libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
- libs/designer/src/lib/ui/panel/templatePanel/panel.less
- libs/designer/src/lib/ui/templates/styles.less
UI improvements listed below
1. Footer to be sticking on the bottom disregarding the content size ![image](https://github.com/user-attachments/assets/2194cb88-bc09-42b3-bda5-f17189b3da67)
2. toaster to be hiding on panel open 
3. parameters to be showing ellipse 
4. associated workfows to be as a section of details
> feat(Templates): Custom Templates UI Enhancements

- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/SetWorkspaceSettings.ts
- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/app/commands/workflows/unitTest/__test__/saveBlankUnitTest.test.ts
- apps/vs-code-designer/src/app/commands/workflows/unitTest/createUnitTest.ts
- apps/vs-code-designer/src/app/commands/workflows/unitTest/saveBlankUnitTest.ts
- apps/vs-code-designer/src/app/utils/__test__/UnitTesting/unitTestUtils.test.ts
- apps/vs-code-designer/src/app/utils/unitTests.ts
- apps/vs-code-designer/src/assets/UnitTestTemplates/TestBlankClassFile
- apps/vs-code-designer/src/assets/UnitTestTemplates/TestClassFile
- apps/vs-code-designer/src/assets/UnitTestTemplates/TestClassFileWithoutActions
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/package.json
Cherry-pick of the following PR's:
- https://github.com/Azure/LogicAppsUX/pull/7059
- https://github.com/Azure/LogicAppsUX/pull/7073
> fix(vscode): Unit test fixes 

- apps/vs-code-designer/src/package.json
- libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
- Current command titles have a mix of uppercase and lowercase letters
- Commands titles now are standardized
> fix(vscode): Standardize commands titles

- apps/vs-code-designer/src/README.md
- https://github.com/Azure/LogicAppsUX/pull/7082
> docs(vscode): Update Readme - unit test announcement 

- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
> fix(designer): Update messages strings for operation deserializer

- libs/designer/src/lib/ui/panel/recommendation/actionSpotlight.tsx
Removing it from AI spotlight/ Favorites
> fix(designer): Remove agent in non-agent flow

- downloadTemplates.js
- libs/designer-ui/src/lib/card/subgraphCard/index.tsx
- libs/designer-ui/src/lib/card/subgraphCard/subgraphCard.less
- libs/designer/src/lib/ui/panel/recommendation/actionSpotlight.tsx
Small cosmetic change on Agent Conditions
Update templates
Cherry pick of https://github.com/Azure/LogicAppsUX/pull/7104
> fix(designer): Cosmetic Change on Agent Conditions/ Update Templates

- apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
- libs/designer/src/lib/core/configuretemplate/utils/queries.ts
- libs/designer/src/lib/core/state/templates/panelSlice.ts
- libs/designer/src/lib/core/state/templates/tabSlice.ts
- libs/designer/src/lib/core/state/templates/templateOptionsSlice.ts
- libs/designer/src/lib/core/state/templates/workflowSlice.ts
- libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/usePanelTabs.tsx
- libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/base/templateresource.ts
- libs/logic-apps-shared/src/designer-client-services/lib/templateresource.ts
This deals with the deserialization aspect of the templates load in initializing the stores and panels correctly with current incomplete template data
This has only been tested in standalone manually
> feat(templates): Loading existing template and its workflows data on wizard load

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/LogicAppSelectionSetting/AzureStandardLogicAppSelector.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Utilities/HybridAppUtilities.ts
- apps/vs-code-designer/src/app/commands/deploy/hybridLogicApp/cleanResources.ts
- apps/vs-code-designer/src/app/commands/deploy/hybridLogicApp/index.ts
- apps/vs-code-designer/src/app/utils/codeless/hybridLogicApp/connectedEnvironment.ts
- apps/vs-code-designer/src/app/utils/codeless/hybridLogicApp/hybridApp.ts
- apps/vs-code-designer/src/constants.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/connector.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/hybrid.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/operationmanifest.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/search.ts
cherry pick of https://github.com/Azure/LogicAppsUX/pull/7132
> fix(designer): Move Hybrid Api versions to a single location in Libraries

- apps/vs-code-designer/src/package.json
- apps/vs-code-react/package.json
- libs/chatbot/package.json
- libs/data-mapper-v2/package.json
- libs/data-mapper/package.json
- libs/designer-ui/package.json
- libs/designer/package.json
- libs/logic-apps-shared/package.json
- libs/vscode-extension/package.json
- package.json
Hotfix branch taken from before the increment done in prod build, so manually updating
> fix(designer): Increment package version to the correct minor version

- libs/designer/src/lib/core/actions/bjsworkflow/delete.ts
Removes the pin of any deleted node, so there isn't a lingering unloaded pinned panel
> fix(designer): Remove Pin on Deleting Node

- libs/designer-ui/src/lib/tokenpicker/tokenpickersection/agentparameter/CreateAgentParameter.tsx
> fix(designer): Refactor and remove unsupported types from Agent parameter creation

- apps/Standalone/public/authredirect.html
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/OAuthService.ts
Added `authredirect.html` file to fix local / standalone oauth for testing.
> fix(Designer): Fixed standalone oauth for testing

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Models/Workflow.ts
- libs/designer-ui/src/lib/constants.ts
- libs/designer-ui/src/lib/dropdown/index.tsx
- libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
- libs/designer/src/lib/common/utilities/Utils.ts
- libs/designer/src/lib/core/state/connection/connectionSelector.ts
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/useCognitiveService.ts
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/base/cognitiveService.ts
- libs/logic-apps-shared/src/designer-client-services/lib/cognitiveService.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
- libs/logic-apps-shared/src/utils/src/lib/models/connector.ts
https://www.loom.com/share/dc289456b2d2448aa02d3dd26222a071?sid=9e02a7b8-7801-46f9-9ff5-22b32f8f63ea
> fix(designer): Dropdown items for deployment names

- libs/logic-apps-shared/src/designer-client-services/lib/base/connection.ts
- libs/logic-apps-shared/src/designer-client-services/lib/httpClient.ts
- https://github.com/Azure/LogicAppsUX/pull/7153
> fix(designer): Add skip batch to HttpRequestOptions

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/openAIConnector.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/formInputs/universalConnectionParameter.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentLoopConnector.ts
https://www.loom.com/share/53a447c71d3f4e28a604d01108c2ae94?sid=812e3c53-ac36-4a1d-949d-568688be5aa2
> fix(designer): Add MSI support for Agent connections

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/openAIConnector.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/formInputs/universalConnectionParameter.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
- libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentLoopConnector.ts
> fix(designer): Cherry-pick for MSI and cognitive service resourceId

- libs/designer-ui/src/lib/searchabledropdown/__test__/searchabledropdown.spec.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/useCognitiveService.ts
cherry pick of https://github.com/Azure/LogicAppsUX/pull/7170
> fix(designer): Prevent error for undefined cognitiveServiceAccountId

- libs/designer/src/lib/ui/panel/recommendation/actionSpotlight.tsx
- libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
Changing some filtering logic within agent tools
> fix(designer): Update Agent Tool Filtering

- libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
https://github.com/user-attachments/assets/84a241c4-6ba2-46b2-bc64-fa76194336c7
> feat(designer): Update 'maximumTokenCount' and 'messageCountLimit' settings as required

- libs/designer/src/lib/core/utils/validation.ts
Changing JSON validation to avoid validating if starts with token
Fixes https://github.com/Azure/LogicAppsUX/issues/6650
> fix(designer): Update expression JSON validation

- apps/vs-code-designer/src/app/commands/__test__/pickCustomCodeNetHostProcess.test.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/CreateNewProjectInternal.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppFilesStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/initLogicAppCodeProjectVScode/InitCodeProject.ts
- apps/vs-code-designer/src/app/commands/debugLogicApp.ts
- apps/vs-code-designer/src/app/commands/pickCustomCodeNetHostProcess.ts
- apps/vs-code-designer/src/app/commands/pickFuncProcess.ts
- apps/vs-code-designer/src/app/commands/registerCommands.ts
- apps/vs-code-designer/src/app/utils/__test__/customCodeUtils.test.ts
- apps/vs-code-designer/src/app/utils/azurite/activateAzurite.ts
- apps/vs-code-designer/src/app/utils/customCodeUtils.ts
- apps/vs-code-designer/src/constants.ts
- apps/vs-code-designer/src/main.ts
- apps/vs-code-designer/src/package.json
Cherry-picked of the following PR:
- https://github.com/Azure/LogicAppsUX/pull/7131
> feat(vscode): New debug config provider for logic app project with custom code

- libs/designer/src/lib/core/templates/utils/queries.ts
- libs/designer/src/lib/ui/templates/review/ResourceDisplay.tsx
Fixed the `useSubscriptions` import in the `ResourceDisplay` component.
Added an extra query key to template queries to prevent overlap with other queries.
> fix(Templates): Fixed query issue in Templates

- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/ExtractPackageStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/ProcessPackageStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/cloudToLocal.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/cloudToLocalHelper.ts
- https://github.com/Azure/LogicAppsUX/pull/7191
> fix(vscode): Fix for Create Workspace from Package to properly create a workspace on deployment

- libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
This reverts commit 498eeb6858a832049fc24653c51e8eee26ca4d45.
> feat(designer): Revert - Update 'maximumTokenCount' and 'messageCountLimit' settings as required

- apps/Standalone/public/subscriptionIds.json
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
- libs/designer/src/lib/core/state/global.ts
- libs/designer/src/lib/core/state/workflow/workflowSlice.ts
revert of https://github.com/Azure/LogicAppsUX/pull/7105
> fix(designer): Revert of Reset id replacements when reset designer dirty state

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/openAIConnector.tsx
> fix(designer): Use the correct service for List Subscriptions

- libs/chatbot/src/lib/ui/styles.less
- Scrollbar is not visible in all OS and browsers and themes
- Scrollbar is visible in all OS and browsers and themes
Not a breaking chang
> fix(designer): Update chat scrollbar styles

- apps/vs-code-designer/src/app/commands/funcCoreTools/validateFuncCoreToolsIsLatest.ts
- apps/vs-code-designer/src/app/commands/nodeJs/validateNodeJsIsLatest.ts
- apps/vs-code-designer/src/app/utils/__test__/binaries.test.ts
- apps/vs-code-designer/src/app/utils/binaries.ts
- apps/vs-code-designer/src/app/utils/nodeJs/nodeJsVersion.ts
- apps/vs-code-designer/src/constants.ts
- https://github.com/Azure/LogicAppsUX/pull/7228
> fix(vscode): Add fallback for function core tools installation 

- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
Gets the default authentication session from vscode-azext-azureauth which corresponds to a different tenant than the one configured for logic app when the user has multiple tenants configured in VS code.
Use tenantId from local.settings.json to get auth token
> fix(vscode): Add tenant ID to get auth token on generate IaC scripts

- libs/designer-ui/src/lib/settings/settingsection/settingslider.tsx
- libs/designer-ui/src/lib/settings/settingsection/settingtoggle.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
> fix(designer): Update string and channels condition

- libs/designer-ui/src/lib/settings/settingsection/settingslider.tsx
- libs/designer-ui/src/lib/settings/settingsection/settingtoggle.tsx
- libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
* a11y changes
* mark experimental
* update channels condition
> fix(designer): Update string and channels condition (#7245)

- apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
Logic App must be selected in order to generate deployment scripts. 
Generate deployment scripts will work even if logic app is not selected. If there are multiple logic apps there will be prompting for one.
> fix(vscode): Fixed error when generating deployment scripts

- apps/vs-code-designer/src/app/utils/__test__/unitTestUtils.test.ts
- apps/vs-code-designer/src/app/utils/unitTests.ts
Logic App name is correctly sanitized for namespace but not for using.
Updated so that logic app name is correctly sanitized for both namespace and using.
> fix(vscode): Unit Test Sanitize Logic App name 

- .github/copilot-instructions.md
Just a starting point we can iterate one
> chore: Add Copilot Instructions

- apps/vs-code-react/src/app/designer/services/customConnectionParameterEditorService.ts
- apps/vs-code-react/src/app/designer/servicesHelper.ts
- apps/vs-code-react/src/app/services/Logger.ts
- libs/vscode-extension/src/lib/services/__test__/httpClient.spec.ts
- libs/vscode-extension/src/lib/services/httpClient.ts
- https://github.com/Azure/LogicAppsUX/pull/7311
> fix(vscode): Initialize custom connection parameter editor service 

- libs/designer-ui/src/lib/editor/initializevariable/__test__/util.spec.tsx
- libs/designer-ui/src/lib/editor/initializevariable/index.tsx
- libs/designer-ui/src/lib/editor/initializevariable/util.ts
- libs/designer-ui/src/lib/tokenpicker/index.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/stringFunctions.spec.ts
- libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
cherry picks of:
https://github.com/Azure/LogicAppsUX/commit/9670901e34c3a37211eb866942c9adadd88c7a18
https://github.com/Azure/LogicAppsUX/commit/99a48e30f4a573c8388eb6a76234f85d6bb28854
> fix(Designer): Variable/Hybrid Cherry picks

- apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
- libs/designer/src/lib/ui/configuretemplate/workflows/selectWorkflows.tsx
- libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
This fixes https://github.com/Azure/LogicAppsUX/issues/7334
https://github.com/user-attachments/assets/c8f38c2a-05b4-484e-af64-a6f5e8fc30b8
> fix(Templates): Select all for workflows table not working

- libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
- https://github.com/Azure/LogicAppsUX/pull/7375
> fix(vscode): Add noAuth to run trigger (#7375)

- apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
- libs/designer/src/lib/core/configuretemplate/utils/queries.ts
- libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/usePanelTabs.tsx
- libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
- libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
- libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
1. fixes #7372 
2. Added code to update template manifest whenever workflows are replaced from panel.
3. Removing unidentified properties in template parameters while fetching parameters from workflow.
4. Fixing summary tab to have correct values in template profile.
> fix(templates): Fixing saving template manifest when workflows change

- libs/designer/src/lib/ui/configuretemplate/parameters/customizeParameter.tsx
- libs/designer/src/lib/ui/configuretemplate/parameters/parameterslist.tsx
- libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
UI Fixes to align with https://github.com/Azure/LogicAppsUX/issues/7368, https://github.com/Azure/LogicAppsUX/issues/7365
> fix(Templates): Fix Parameter Grid & Panel with associated workflow display

- libs/designer/src/lib/ui/templates/cards/templateCard.less
- libs/designer/src/lib/ui/templates/filters/templatesearchfilters.tsx
- libs/designer/src/lib/ui/templates/gallery/templatesfullgalleryview.tsx
cherry-picking https://github.com/Azure/LogicAppsUX/pull/7413
> fix(Templates): Tab navigation broken UI + Template card css overlapping issue

- apps/vs-code-designer/src/app/utils/unitTests.ts
make all triggers mockable
Cherry-pick into release branch
> fix(vscode): Bypass isMockable check for trigger mocks (#7419)

- apps/vs-code-designer/package.json
- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/LogicAppHostingPlanStep.ts
- apps/vs-code-designer/src/app/tree/subscriptionTree/SubscriptionTreeItem.ts
- apps/vs-code-designer/src/constants.ts
- pnpm-lock.yaml
ARM API update broke our ability to list regions for subscriptions
The vscode-azuretools library has an update for this, but updating the library has other side-effects
Manually copied over these changes for now, and after this we need to update those libraries
- **Users**: users now able to see all locations for their subscriptions
- **System**:
> Temporary fix of GeoLocation API version in VSCode until we can update vscode-azuretools

- apps/vs-code-designer/package.json
- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/LogicAppHostingPlanStep.ts
- apps/vs-code-designer/src/app/tree/subscriptionTree/SubscriptionTreeItem.ts
- apps/vs-code-designer/src/constants.ts
- pnpm-lock.yaml
…e vscode-azuretools (#7434)
* experimenting with api-version
* updated lockfile
* update for hosting plan
* removed unused code
ARM API update broke our ability to list regions for subscriptions
The vscode-azuretools library has an update for this, but updating the library has other side-effects
Manually copied over these changes for now, and after this we need to update those libraries
- **Users**: users now able to see all locations for their subscriptions
- **Developers**: NA
> feat(VSCode): Temporary fix of GeoLocation API version in VSCode until we can update vscode-azuretools

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/ca11y.yml
- .github/ISSUE_TEMPLATE/data_mapper.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/templates.yml
This PR improves all GitHub issue templates to provide better structure, consistency, and context gathering for more effective issue triage and resolution. The changes standardize fields across templates and add severity/priority indicators to help maintainers prioritize work.
- **Users**: Clearer issue templates will help users provide better information when reporting bugs or requesting features, leading to faster resolution times
- **Developers**: Standardized severity levels and structured formats will improve triage efficiency and help identify critical issues faster
- **System**: No runtime impact - only affects GitHub issue creation flow
There is no way to test this without it being in main branch
Manual testing performed:
- Previewed each template in GitHub's issue creation …
> chore: Improve issue templates for better triage and consistency

- apps/vs-code-designer/src/app/commands/buildCustomCodeFunctionsProject.ts
- apps/vs-code-designer/src/app/commands/pickCustomCodeNetHostProcess.ts
The custom code debugger builds functions projects prior to launching logic app. Edited logic to ensure build is awaited properly. Fix attach to custom code net host child process (check children of children)
- **Users**: Fixes debugger launch errors for long-running builds and edge case where .net host child process can't be found
- **System**: 
- Andrew Eldridge (andrew-eldridge)
- Brian Lam (lambrianmsft)
> fix(vscode): fix build custom code project task

- apps/vs-code-designer/src/app/utils/codeless/__test__/parameterizer.test.ts
- apps/vs-code-designer/src/app/utils/codeless/parameterizer.ts
* fixed apim connector param check
* added another test
* fixed parameter ref check
---------
- [ x] Low - Minor changes, limited scope
IFixes incorrect evaluation of parameterizes apim connections.
- **Users**: 
- **System**: 
- [ x] Unit tests added/updated
> fix(vscode): Apim connector parameterization check fix (#7310) 

- libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
- libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
- libs/designer/src/lib/core/configuretemplate/utils/queries.ts
- libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/usePanelTabs.tsx
- libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
- libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
- libs/designer/src/lib/ui/configuretemplate/templateprofile/connectors.tsx
- libs/designer/src/lib/ui/templates/connections/connector.tsx
- Updating workflow data with ManageData so workflow name is disabled after workflow is created first time.
- Updating workflow manifest in case of single workflow scenario when template data is changed
- Fixing accelarator template not loading issue
- **Users**: Publishing of single workflow templates
- **Developers**: Moved save handler to actions for better structuring
- **System**: no significant changes
@preetriti1
> fix(Templates): Workflow tab, Template save, Accelarator loading issue

- libs/logic-apps-shared/src/designer-client-services/lib/base/templateresource.ts
This is a cherry pick of #7455
> fix(templates): Doing case insensitive check for filtering out workflow artifacts while adding workflows in template (#7455)

- .github/workflows/base-coverage.yml
- .github/workflows/coverage-report.yml
- .github/workflows/production-build.yml
Reverts Azure/LogicAppsUX#7462
> Revert "chore: remove obsolete GitHub workflow files"

- libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
- libs/designer/src/lib/core/templates/utils/parametershelper.ts
Case sensitive lookups were causing issues in getting data from custom templates. This change adds case insensitive lookups to resolve the issue and improve the user experience
- **Users**: Dynamic data to show up in template parameters
- **Developers**: Always lookup case insensitively from non UI data to avoid such issues
- **System**: No such impact
@divyaswarnkar 
NA
> fix(templates): Adding case insensitive lookups while using data from custom template

- libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
- libs/designer/src/lib/core/templates/utils/parametershelper.ts
> fix(templates): Adding case insensitive lookups while using data from custom template (#7474)

- libs/chatbot/package.json
- libs/designer-ui/package.json
- libs/designer/package.json
- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
- libs/logic-apps-shared/package.json
- libs/logic-apps-shared/src/utils/src/lib/helpers/connections.ts
- libs/vscode-extension/package.json
- package.json
Updating package version numbers for private deployment
- **Users**: No impact
- **Developers**: No impact
- **System**: Version number adjusted for private deployment
- Testing not needed
@rllyy97
> chore(Designer): Updated version number for private deployment

- apps/vs-code-designer/package.json
- apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/LogicAppHostingPlanStep.ts
- apps/vs-code-designer/src/app/tree/subscriptionTree/SubscriptionTreeItem.ts
- apps/vs-code-designer/src/constants.ts
- pnpm-lock.yaml
…an update vscode-azuretools (#7434)"
This reverts commit d88c94008c655e1bbf431ceb02aa7333c13dfb81.
found an side effect of this PR, and found another way to fix the bug, so reverting
- **Users**: resolves side-effect issue for users related to the fix, partner team is already rolling out a different fix for the bug
- **System**:
> Revert "Temporary fix of GeoLocation API version in VSCode

- Localize/loc/es/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/hu/strings.json.lcl
- Localize/loc/it/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250612201934658 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250612201934658 to main

- Localize/loc/cs/strings.json.lcl
- Localize/loc/de/strings.json.lcl
- Localize/loc/es/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/hu/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/it/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250613051754989 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250613051754989 to main

- Localize/loc/cs/strings.json.lcl
- Localize/loc/de/strings.json.lcl
- Localize/loc/es/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/hu/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/it/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250613111833633 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250613111833633 to main

- Localize/loc/cs/strings.json.lcl
- Localize/loc/de/strings.json.lcl
- Localize/loc/es/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/hu/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/it/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250613142111613 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250613142111613 to main

- Localize/loc/es/strings.json.lcl
- Localize/loc/hu/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250614052812074 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250614052812074 to main

- Localize/loc/de/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250614172123169 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250614172123169 to main

- Localize/loc/cs/strings.json.lcl
- Localize/loc/de/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250615021951779 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250615021951779 to main

- Localize/loc/de/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250614231919539 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250614231919539 to main

- Localize/loc/pl/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250615171835094 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250615171835094 to main

- Localize/loc/pl/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250615201915220 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250615201915220 to main

- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250616051821487 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250616051821487 to main

- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250616081853219 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250616081853219 to main

- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250616111805863 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250616111805863 to main

- Localize/loc/de/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250619051906219 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250619051906219 to main

- Localize/loc/de/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250619112250089 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250619112250089 to main

- Localize/loc/cs/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250620112043948 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250620112043948 to main

- Localize/loc/cs/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250620051749353 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250620051749353 to main

- libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
- libs/designer/src/lib/core/state/templates/panelSlice.ts
- libs/designer/src/lib/core/state/templates/tabSlice.ts
- libs/designer/src/lib/core/state/templates/templateSlice.ts
- libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/usePanelTabs.tsx
- libs/logic-apps-shared/src/designer-client-services/lib/base/templateresource.ts
- libs/logic-apps-shared/src/designer-client-services/lib/templateresource.ts
Refactoring current template changes methods to support Add and Update workflows scenarios. Also updated the rollback scenarios and no more deleting existing workflows.
This is needed for supporting add/update scenarios reducing the erroneous paths.
- **Users**: Users will be able to see correct values in created/updated time and existing parameter metadata won't be wiped off, reducing the erroneous scenarios
- **Developers**: Better refactoring and usage of methods
- **System**:NA
@bonica-ayala @divyaswarnkar @Elaina-Lee 
just method changes so NA
> feat(templates): Refactoring methods to handle rollback and saving for add/edit

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx
- libs/designer-ui/src/lib/styles/connectionContainer.ts
- libs/designer/src/lib/core/state/panel/panelSlice.ts
- libs/designer/src/lib/core/state/panel/panelTypes.ts
- libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/allConnections.less
- libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/allConnections.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/allConnectionsEmptyState.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/connectionEntry.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/connectorConnectionsCard.tsx
- libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/nodeLinkButton.tsx
- Connection panel now remembers which connectors were expanded / collapsed between opens
- Improved action button visibility
- Fixed icon styling issue
- Moved empty state to its own component
- Added connections button to standalone command bar
- **Users**: Connection panel remembers state between opens/closes
- **Developers**: Easier testing in standalone
@rllyy97
> feat(Designer): ConnectionsPanel improvements

- Localize/loc/cs/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250620081824465 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250620081824465 to main

- apps/vs-code-designer/src/app/commands/__test__/pickCustomCodeNetHostProcess.test.ts
- apps/vs-code-designer/src/app/commands/createCodeful/CodefulWorkflowCreateStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/NewCodeProjectTypeStep.ts
- apps/vs-code-designer/src/app/commands/createWorkflow/createWorkflow.ts
- apps/vs-code-designer/src/app/commands/initProjectForVSCode/InitVSCodeStepBase.ts
- apps/vs-code-designer/src/app/commands/pickCustomCodeNetHostProcess.ts
- apps/vs-code-designer/src/app/commands/pickFuncProcess.ts
- apps/vs-code-designer/src/constants.ts
- libs/vscode-extension/src/lib/models/project.ts
Cherry-pick of the following PR - https://github.com/Azure/LogicAppsUX/pull/7571
Updated to newest version of Codeful sdk for integrate payload
Added changes to launch.json configuration to allow debugging of codeful workflows
edited debug command to find func processes
- **Users**: Users get latest codeful sdk and codeful debugging
- **Developers**: NA
@DanielleCogs
Fixes #7565
> fix(vscode): Upgrade Codeful SDK to 1.127.21.3-preview and enhance workflow debugging support in VS Code Designer 

- apps/vs-code-designer/src/app/commands/createNewProject/createProjectSteps/ProjectCreateStepBase.ts
Missing codeful flag in telemetry so we can add alerting and monitoring
- **Users**: none
- **Developers**: able to gather better data on who is creating codeful workflows 
- **System**:
> Added telemetry for when codeful workflow is created in a new project

- Localize/loc/de/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/hu/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250702112029863 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250702112029863 to main

- apps/vs-code-designer/src/app/commands/deploy/deploy.ts
Cherry-pick of the following PR: https://github.com/Azure/LogicAppsUX/pull/7664
> fix(vscode): Always upload app settings during Logic App deployment 

- Localize/loc/ko/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250702051922065 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250702051922065 to main

- Localize/loc/es/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250702172024802 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250702172024802 to main

- Localize/loc/cs/strings.json.lcl
- Localize/loc/it/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250702232808048 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250702232808048 to main

- Localize/loc/sv/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250703021848214 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250703021848214 to main

- Localize/loc/fr/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250703141930799 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250703141930799 to main

- Localize/loc/id/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250703231905624 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250703231905624 to main

- libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
This PR hides behavior that was implemented in a recent timeline component feature.
Now in non-agent flows the behavior will be as it was before the timeline component.
- **Users**: Fixed issue with nested loops not having data
- **System**: 
@ccastrotrejo 
No visual changes
> fix(Designer): Fixed nested loop issue stemming from timeline component changes

- Localize/loc/de/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250709051925011 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250709051925011 to main

- Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250710022123545 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250710022123545 to main

- Localize/loc/es/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250709231920728 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250709231920728 to main

- libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
We're creating a duplicate tenantId connection parameter on connection creation. We create a customer tenantPicker, but we don't filter the parameter out, so it ends up rendering twice (one custom, one normal parameter).
Fixes https://github.com/Azure/LogicAppsUX/issues/7396
- **Users**: Users should no longer see duplicate tenant Ids on connection creation
- **Developers**: Changed the parameter visibility to false so that we don't render more than a single tenantId
- **System**: No System impact
@DanielleCogs tagging as original issue owner
> fix(designer): Duplicate tenantID parameter on Connection Creation

- libs/designer/src/lib/core/mcp/utils/serializer.ts
Fixing mutation of connections.json.
this is needed for successful save
- **Users**: Successful creation of mcp server
- **Developers**: Method bug fix
@Elaina-Lee @Eric-B-Wu 
NA
> fix(mcp): Fixing serialization of connections.json

- libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
This PR restores and updates the Mcp Wizard button and layout styles that were previously overwritten. This ensures visual consistency following the latest design review and addresses regressions introduced in a recent update.
- **Users**: Mcp Wizard visual appearance is corrected (ex: alignment, icon, colors)
- **Developers**:  No API or logic change, style files only
- **System**: No impact on dependencies or performance
@preetriti1, @Eric-B-Wu
> fix(Mcp): Restore and update Mcp Wizard button and layout styles as per design review

- apps/vs-code-designer/src/app/commands/createCodeful/CodefulWorkflowCreateStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppFilesStep.ts
- apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/initLogicAppCodeProjectVScode/InitCodeProject.ts
- apps/vs-code-designer/src/app/commands/debugLogicApp.ts
- apps/vs-code-designer/src/app/commands/pickCustomCodeNetHostProcess.ts
- apps/vs-code-designer/src/app/commands/pickFuncProcess.ts
- apps/vs-code-designer/src/package.json
* fix issue where custom code debugger attaches to wrong process
* run start debug task for codeful projects
* fix tests
see related PR
- **Users**: 
- **System**:
> Cherry-pick commit to fix debug select process for custom code into release

- Localize/loc/de/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250716111931964 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250716111931964 to main

- Localize/loc/pt-BR/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250716053634506 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250716053634506 to main

- Localize/loc/pl/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250717021915775 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250717021915775 to main

- libs/logic-apps-shared/src/designer-client-services/lib/base/__test__/connector.spec.ts
The pagination logic was recently updated to preserve original data when subsequent page requests fail, but
lacked test coverage. These tests ensure the error handling works correctly for various failure scenarios
(network errors, invalid responses, partial failures) and verify that users receive partial data rather than
losing everything when pagination fails.
Adding a test to 
- **Users**: No changes on User
- **Developers**: Adding a test file on our connector service
- **System**: 
@eric-b-wu
> test(designer): Adding test to fetching next page on dynamic data 

- apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/NewCodeProjectTypeStep.ts
Codeful feature is not ready for release yet
- **Users**: cannot yet make codeful workflows
- **System**:
> Removed codeful step for v5.130 release

- libs/designer/src/lib/core/state/selectors/actionMetadataSelector.ts
- libs/designer/src/lib/ui/mcp/connections/connectionselection.tsx
- libs/designer/src/lib/ui/mcp/parameters/EditOperation.tsx
- libs/designer/src/lib/ui/mcp/parameters/ParameterEditor.tsx
Added combobox and file picker editor to support dynamic content in parameters
This is needed for users to fill in correct values
- **Users**: Users will be able to choose from their dynamic content both in lists and folder picker
- **Developers**: New format of adding more editors.
@Eric-B-Wu @Elaina-Lee
> feat(mcp): Add dynamic combobox and file picker editors for parameter values in designer UI

- libs/designer-ui/src/lib/editor/models/parameter.ts
- libs/designer/src/lib/core/actions/bjsworkflow/add.ts
- libs/designer/src/lib/core/actions/bjsworkflow/connections.ts
- libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
- libs/designer/src/lib/core/mcp/utils/hooks.ts
- libs/designer/src/lib/core/mcp/utils/serializer.ts
- libs/designer/src/lib/core/state/mcp/store.ts
- libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
- libs/designer/src/lib/core/utils/parameters/helper.ts
- libs/designer/src/lib/ui/mcp/connectors/ListConnectors.tsx
- libs/designer/src/lib/ui/mcp/operations/ListOperations.tsx
- libs/designer/src/lib/ui/mcp/panel/connector/usePanelTabs.tsx
- libs/designer/src/lib/ui/mcp/panel/operation/EditOperationPanel.tsx
- libs/designer/src/lib/ui/mcp/parameters/EditOperation.tsx
- libs/designer/src/lib/ui/mcp/parameters/ParameterEditor.tsx
- libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Added transforming swagger schema before adding it to trigger inputs.
This is needed for LLM to correctly identify the properties.
Also added a fix in dynamic inputs loading where incorrect input schema was being used and there was null ref exception.
This is needed for loading the dynamic inputs correctly.
- **Users**: Users able to create correct input schema in trigger inputs
- **Developers**: API changes, moved designer store specific data as direct function arguments instead of reading from store.
- **System**: No changes
@Elaina-Lee 
NA
> fix(mcp): Fixing serialization with transforming the swagger schema and dynamic inputs null ref fix

- Localize/loc/cs/strings.json.lcl
- Localize/loc/de/strings.json.lcl
- Localize/loc/es/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/hu/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/it/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250730022337357 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250730022337357 to main

- Localize/loc/de/strings.json.lcl
- Localize/loc/es/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250730141906626 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250730141906626 to main

- Localize/loc/fr/strings.json.lcl
- Localize/loc/it/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250730172124270 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250730172124270 to main

- .azure-pipelines/1esmain.yml
- .azure-pipelines/release.yml
<\!-- Select based on potential impact -->
Updates the Azure DevOps environment name from `AzCodeDeploy` to `VSCodeDeployLAUX` in both the main and release pipeline configurations to align with the new Azure DevOps environment naming convention.
- **Developers**: No API changes or new patterns
- **System**: Updates deployment environment configuration for Azure pipelines
@ccastrotrejo
> ci(vscode): Azure DevOps environment name to VSCodeDeployLAUX

- Localize/loc/cs/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250801111917547 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250801111917547 to main

- Localize/loc/id/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250801142408574 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250801142408574 to main

- Localize/loc/de/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250801210211804 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250801210211804 to main

- Localize/loc/sv/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250802022510143 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250802022510143 to main

- .azure-pipelines/templates/package.yml
This PR updates the Azure pipeline script to use PowerShell instead of a bash script with jq for JSON manipulation. The previous implementation used a bash command that was not cross-platform compatible and could fail on Windows agents.
- **Developers**: More reliable CI/CD pipeline execution across different agent types
- **System**: Improved cross-platform compatibility for Azure pipeline builds, particularly when using Windows agents
> fix(ci): update Azure pipeline script to use PowerShell for cross-platform JSON manipulation

- apps/Standalone/src/mcp/app/McpStandard.tsx
- libs/designer/src/lib/core/actions/bjsworkflow/mcp.ts
- libs/designer/src/lib/ui/mcp/operations/ListOperations.tsx
- libs/designer/src/lib/ui/mcp/panel/operation/EditOperationPanel.tsx
- libs/designer/src/lib/ui/mcp/wizard/styles.ts
Description column will have ellipsis for overflowing text. Telemetry has additional details as needed.
- **Users**: Description field will be truncated.
- **Developers**: none
- **System**: none
@bonica-ayala @kewear
> fix(Mcp): Bug bash fixes + telemetry clean up

- libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/handoffTab/HandoffToolEntry.tsx
Changing a handoff description now flags dirty-state properly.
- **Users**: Users can now only change a handoff description and save.
@rllyy97, found by @edwardyhe
> fix(Designer): Fixed handoff description dirty state issue

- Localize/loc/cs/strings.json.lcl
- Localize/loc/de/strings.json.lcl
- Localize/loc/es/strings.json.lcl
- Localize/loc/fr/strings.json.lcl
- Localize/loc/hu/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/it/strings.json.lcl
- Localize/loc/ja/strings.json.lcl
- Localize/loc/ko/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/pl/strings.json.lcl
- Localize/loc/pt-BR/strings.json.lcl
- Localize/loc/pt-PT/strings.json.lcl
- Localize/loc/ru/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
- Localize/loc/tr/strings.json.lcl
- Localize/loc/zh-Hans/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250813021911252 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250813021911252 to main

- Localize/loc/fr/strings.json.lcl
- Localize/loc/id/strings.json.lcl
- Localize/loc/it/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250813231940304 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250813231940304 to main

- Localize/loc/hu/strings.json.lcl
- Localize/loc/nl/strings.json.lcl
- Localize/loc/sv/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250814021934565 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250814021934565 to main

- Localize/loc/pl/strings.json.lcl
- Localize/loc/zh-Hant/strings.json.lcl
LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250814051925835 to main with localized lcls
> LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250814051925835 to main

- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
Reverting validate api call pending fix from validate partial.
- **Users**:  Most users
- **Developers**:  NA
- **System**:  NA
> fix(vscode): revert validate API call due to issues with pending validate partial implementation

- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
- [x ] fix - Bug fix
- [ x] Low - Minor changes, limited scope
Adds additional logic to prevent showing error messages for invalid validation calls with undefined error codes.
- **Users**:  Most
- **Developers**:  NA
- [ x] Manual testing completed
> fix(vscode): Add additional conditional to show validate error message

- libs/logic-apps-shared/src/designer-client-services/lib/base/manifests/a2arequest.ts
Update parameter names for a2a trigger from name to agentName and description to agentDescription
- **Users**: Fixes a validation error for when saving an a2a trigger with name or description
- **Developers**: no dev changes
- **System**: no system changes
@eric-b-wu
> fix(Designer): Update a2a trigger property names

- apps/Standalone/src/clonetostandard/app/clonetostandard.tsx
- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
- libs/designer/src/lib/core/clonetostandard/clonedataprovider.tsx
- libs/designer/src/lib/core/state/clonetostandard/cloneslice.ts
- libs/designer/src/lib/core/state/clonetostandard/resourceslice.ts
- libs/designer/src/lib/ui/clonetostandard/resourcepicker.tsx
- libs/designer/src/lib/ui/clonetostandard/wizard/clonewizard.tsx
Passed on API calls (validation, clone) from standalone; using this, handles error message storign in store and the capability to display by catching errors within clone wizard.
- **Users**: page will demonstrate a behvaior passed on from api
- **Developers**: Api connection with the state
- **System**: none
> feat(Clone): Api connection using states with validation and error handling

- libs/designer-ui/src/lib/searchabledropdownWithAddAll/index.tsx
- libs/designer/src/lib/ui/settings/settingsection.tsx
For Agent loop, move the description under Advanced parameters instead of the top
- **Users**: Users will see description under the label now
- **Developers**: None
> fix(designer): Move description under advanced parameters

- libs/designer-ui/src/lib/searchabledropdownWithAddAll/index.tsx
- libs/designer/src/lib/ui/settings/settingsection.tsx
For Agent loop, move the description under Advanced parameters instead of the top
- **Users**: Users will see description under the label now
- **Developers**: None
> fix(designer): Move description under advanced parameters (#8176)

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
Right now the easy auth call just fails silently, going to add a try catch and handle it accordingly
- **Users**: None
- **Developers**: If this enables better debugging or error recovery, mention "Improved error handling for easier debugging.
> fix(designer): Add try catch for Easy Auth call

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
Right now the easy auth call just fails silently, going to add a try catch and handle it accordingly
- **Users**: None
- **Developers**: If this enables better debugging or error recovery, mention "Improved error handling for easier debugging.
> fix(designer): [Cherry-pick] Add try catch for Easy Auth call (#8178)

- apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
Cherry-pick of #8099 
Fixes an issue where data being passed to the validatePartial API route would not pick up data recently saved in the same designer session.
This addresses https://github.com/Azure/LogicAppsUX/issues/7968
- **Users**:  Most
- **Developers**:  NA
- **System**:  NA
> fix(vscode): Changed validate call on workflow save to use saved data instead of panel metadata

- e2e/designer/real-api/connections/connectionAuth.spec.ts
Added E2E test to verify auth type switching + params
- **Users**: N/A
- **System**: Improved testing around auth type parameters
@rllyy97
N/A
> chore(Designer): Added E2E test to verify auth type switching + params

- libs/designer/src/lib/core/DesignerProvider.tsx
- libs/designer/src/lib/core/templates/TemplatesDesignerProvider.tsx
For a private deployment to prevent foundry repo from crashing
- **Users**: These are temporary changes to a private deployment so users will not be affected
- **Developers**: No dev changes
- **System**: No System changes
> fix(designer): Remove fluentui/azure-themes from designer repo

- CHANGELOG.md
- Added release notes for version 5.185.5.
- Generated from changes between v5.165.9 and hotfix/v5.185 (c2b31a85a).
- Auto-generated by changelog workflow.
- **Users**: Documentation-only change; no runtime impact.
- **Developers**: Provides consolidated release notes for 5.185.5.
- **System**: None.
- Documentation-only change; no additional testing required.
- n/a
- n/a
> docs: update changelog for release 

- CHANGELOG.md
This PR updates the main CHANGELOG.md file to document two recent releases:
- Version 5.185.7 (2025-10-07): Includes VS Code extension bundle path parsing improvements
- Version 5.185.6 (2025-10-02): Includes multiple VS Code and Designer features and bug fixes
This update ensures users and developers have visibility into recent changes, features, and fixes across the Logic Apps UX repository.
- **Users**: No direct impact on users, documentation only. However, users can now reference the changelog to understand recent features and bug fixes.
- **Developers**: Improved visibility into recent changes across v5.185.6 and v5.185.7, including VS Code extension improvements, Designer features, and bug fixes.
- **System**: No system changes. Documentation only.
- **Tested in**: Documentation …
> docs(vscode): update main changelog with v5.185.7 and v5.185.6 releases

- apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerV2.tsx
Fixed issue with `onRunSelected` being reference before it's initialization.
- **Users**: N/A
- **Developers**: Fixes crash in standalone
@rllyy97, @takyyon 
N/A
> fix(Standalone): Fixed standalone `onRunSelected` variable reference issue
